### ISSUE TITLE
FeatReq: Mark rows as no-expand

### ISSUE THREAD

**Issue by JamaicanRumCream** [fooplugins/FooTable#100]
My CSS isn't so great, but I need to be able to mark rows as non-expandable. For example, I have a table that has multiple "pseudo-header" rows, or rows for demarking different groups inside the data. The table can not be sortable, but these intermediate header rows should not be expandable when some of their cells are hidden. I have not been able to find out how to do this. 
For example see http://www.scca-susq.com/results/2013/13-07-07pm-axresults.html

I am trying to collapse the table to only show column 1 (place), name, and total time. Example screenshot:
![screen shot 2013-07-15 at 1 38 50 pm](https://f.cloud.github.com/assets/5015041/799469/8d9f7ebc-ed75-11e2-94ad-4e3cf17ac419.png)

**Comment by bradvin** [comment]
Cool feature request, and a great example to add to the demos.
I am busy working on the V2 branch at the moment, so I will see if I can add this quite soon

**Comment by JamaicanRumCream** [comment]
Is this implemented yet? I was test driving v2 today and don't see a simple way to mark non-expand. If I change the TD or TH cells I can approximate it (looks like TH cells now don't expand), but then I am getting a "footable-last-column" item that sticks out over the end at phone size where only 3 columns are displayed. My psuedo-header cells have a colspan=5 attribute. If I make all the cells of this header row be TH then it seems like they don't respect the data-hide="phone" attribute I set in the thead section- they all are displayed and don't hide.
![screen shot 2013-09-04 at 3 39 10 pm](https://f.cloud.github.com/assets/5015041/1083461/bb390982-1599-11e3-8bcf-ce609be13fea.png)

``` html
<tbody>
                  <tr class="CarClassHeader">
                    <th colspan="5" align="left"><a name="ss"></a>ss - 'Super Stock' - Total Entries: 1  Trophies: 1</th>
                    <td  >Times</td>
                    <td  ></td>
                    <td  ></td>
                    <td  ></td>
                    <td  > Total</td>
                    <td  > Diff. </td>
                  </tr>
```

**Comment by bradvin** [comment]
@JamaicanRumCream check out the data-attributes demo where I do something similar. I added class="footable-disabled" onto the TR and then footable leave it alone

**Comment by JamaicanRumCream** [comment]
OK I got it to work, but there is something else that goes on with my table then. See #133.
