### ISSUE TITLE
Filter specific columns

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#101]
Is there a way to filter only on a specific column? I have this setup to display issue statues and if someone types in open I want it to filter all the cases that haven't been resolved yet. The closed field has the text open in it but the subject field could also contain open so I don't want those results to show in the filter. 

Any help would be appreciated! Thanks

**Comment by bradvin** [comment]
this is a cool feature to add - I will try to add this

**Comment by chibani** [comment]
Any news about a column specific filtering ?

**Comment by bradvin** [comment]
@chibani at the moment this can be done by overridding the option filter.filterFunction

You could then write a small function to only look at the data you are interested in

**Comment by chibani** [comment]
Thx, I'll give it a try ;)

**Comment by yarhouse** [comment]
I'm curious to know if anyone has devised a solution to this request on their own. I've attempted to create 2 select elements to filter only from specified columns, but I'm having no good luck with it. I'd be interested in anyones unofficial column filtering while we await the awesome (possible) future enhancement

**Comment by chibani** [comment]
I did it.
I've been able to override the filterFunction (providing it as a parameter to footable).
This way I could enhance the fonctionnalities.
For example, I've add a "data-filter-columns" that is a jQuery selector so I could add some classes to my tds and target them when filtering.

There's still one problem with code (or maybe it's footable... not sure) : I can't filter using 2 columns at the same time.
For example, filtering my users by age and then by city will only filter them by city (age will be skipped).

Here's my code : 

```
filterFunction: function(index){
    var $t = $(this),
          $table = $t.parents('table:first'),
          filter = $table.data('current-filter').toUpperCase();

          var $f = $('.footable-filter:focus');//actives filters
          var $td = $t.find('td'); //the table cells

          //Filtering the td list
          if($f.data('filter-columns')){
              $td = $td.filter(  $f.data('filter-columns') );
          }

          //Search for text in td's class
          if($f.data('filter-class') === true){
              return  $td.hasClass( $table.data('current-filter') );
          }else{
              var text = $td.text();
          }

             // filtering on data-value, not innerText    
          if (!$table.data('filter-text-only')) {
              $t.find('td[data-value]').each(function () {
                  text += $(this).data('value');
              });
          }

          //Split ? (allow to search different elements, like postcode : "75010,78180" will find both Paris 10th, and Montigny le Bretonneux)          
          if($f.data('filter-split') === true){
              var filters = filter.split(',');

              for(var i in filters){
                  if(text.toUpperCase().indexOf(filters[i]) >= 0)
                      return true;
              }

              return false;
          }else{
              return text.toUpperCase().indexOf(filter) >= 0;
          }


      }
```

**Comment by drmcclelland** [comment]
I really love the extensibility of FooTable!  I followed an approach similar to @chibani in order to enable two new data- attributes (`data-filter-text-only` and `data-filter-ignore`) at the TH level:

```
$('#myDataTable').footable({
    addRowToggle: false,
    filter: {
        filterFunction: function (index) {
            var $t = $(this),
                $table = $t.parents('table:first'),
                filter = $table.data('current-filter').toUpperCase(),
                tableFilterTextOnly = $table.data('filter-text-only');

            var text;
            $t.find('td').each(function () {
                var $td = $(this);
                var $th = $table.find('th').eq($td.index());

                if (!$th.data('filter-ignore')) {
                    text += $td.text();

                    if (!tableFilterTextOnly) {
                        if (!$th.data('filter-text-only')) {
                            text += $td.data('value');
                        }
                    }
                }
            });

            return text.toUpperCase().indexOf(filter) >= 0;
        }
    }
});
```

**Comment by aathar** [comment]
@chibani  @drmcclelland thanks for the code... I am trying to implement that on my page. But having difficulties. Here is my scenario

I am first Populating footable. Then filtering the list by  Drop downlist 

function filterByDepartment() {

```
        $('#myTable').footable().bind('footable_filtering', function (e) {
            var selected = $('#<%=ddlDepartments.ClientID %>').find(':selected').text();
            if (selected == 'Select All') {
                selected = "";
            }
            if (selected && selected.length > 0) {
                e.filter += (e.filter && e.filter.length > 0) ? ' ' + selected : selected;
                e.clear = !e.filter;
            }
        });
```

But It filters in the whole table. So for example I have a department Name : "IT"... it would get all the records having "it" anywhere in them like editor etc.

How do I implement your code so that filter is applied only on the "Department" column and not on whole table.

2) I have a input "Search" too... i want to keep search functionality. So If a user types in a search criteria in the input box, then it should filter the complete table. But if the search takes place from a drop down list (as mentioned earlier), it should only look into the specified column.

Please Help !!!

Thanks
Athar

**Comment by ghost** [comment]
I had to do something similar I believe and the easiest way was to set a data-value attrubute on the item you have listed for IT. Then your select list should show IT as the option text but the value it would insert into the filter and search for would be Information Technology (the same as the data attribute).

**Comment by rajaveernapu** [comment]
Hi All, 

I also facing the same issue, can some one provide the solution for
I am not able to filter on single column

```
 $('#myDataTable').footable({
    addRowToggle: false,
    filter: {
        filterFunction: function (index) {
            var $t = $(this),
                $table = $t.parents('table:first'),
                filter = $table.data('current-filter').toUpperCase(),
                tableFilterTextOnly = $table.data('filter-text-only');

            var text;
            $t.find('td').each(function () {
                var $td = $(this);
                var $th = $table.find('th').eq($td.index());

                if (!$th.data('filter-ignore')) {
                    text += $td.text();

                    if (!tableFilterTextOnly) {
                        if (!$th.data('filter-text-only')) {
                            text += $td.data('value');
                        }
                    }
                }
            });

            return text.toUpperCase().indexOf(filter) >= 0;
        }
    }
});
```

I have a th with data-filter-ignore for all the columns except my filter column.

Can some one provide us the working example please.

Thanks
Rajasekhar

**Comment by mtdukes** [comment]
Any word on whether a data-filter-ignore attribute will become official? That would be a great feature.

**Comment by mattgreenwd** [comment]
Was having an issue with this today.

The easiest way I found is to add a class name to your cell and then change the footable.filter.js to only search that for text within that class.

Ex.

```
        filterFunction: function(index) {
            var $t = $(this),
                $table = $t.parents('table:first'),
                filter = $table.data('current-filter').toUpperCase(),

                //changed the search below so it only looks within ".name" classes
                text = $t.find('.name').text();
```

**Comment by jleavers** [comment]
Similar to @aathar I also have a search input as well as a dropdown to filter on a particular column. Thanks @aschreiner85 for the suggestion to use the data-value attribute in conjunction with the option value. I also changed the function to use .val instead of .text:

```
 $(function () {
    $('table').footable().bind('footable_filtering', function (e) {
      // change .text() to .val()
      var selected = $('.filter-status').find(':selected').val();
```

**Comment by svdev22** [comment]
I have a table where I need to filter it based on the multiple values in the single column. How can we implement this using foo tables.

@chibani, I tried your code but it is not working. Can you help me in implementing the same in my web page.

**Comment by chibani** [comment]
Hi, my code is 2 years old... It's possible that FooTable has changed a lot since then :/
Unfortunately, I don't use FooTable anymore, and I didn't upgrade my code.

**Comment by svdev22** [comment]
ok.. But I don't think we have that functionality in the FooTable even by now.

**Comment by chibani** [comment]
@vsrikanth22 May you should look at this : http://fooplugins.github.io/FooTable/docs/examples/component/filtering.html
