### ISSUE TITLE
Pass column id/class to data-hidden divs?

### ISSUE THREAD

**Issue by yarhouse** [fooplugins/FooTable#102]
First of all, this is the best table plugin I have ever used. Fairly easy to use, and simple enough to style to my liking. Thank you very much for this.

I'm not sure if this already is possible, so please pardon my asking; Is there any way to pass a cells #id or .class into the <div> for each column?

**Comment by bradvin** [comment]
thanks for the great comment :)

Let me understand your question correctly:

You want the ids and classes of the table cells to be copied to the detail row's divs?

**Comment by yarhouse** [comment]
Yes, thats correct. A class or id called in a cell that is "style='display:none;'" would be passed to the corresponding div located in "footable-row-detail-inner". That would be amazingly helpful in styling the information located in the dropdown. I've run into the specific issue of where I could really use a divider like < hr / > or border-top to separate the dropdown information into chunks.
