### ISSUE TITLE
Ignore a row

### ISSUE THREAD

**Issue by helgatheviking** [fooplugins/FooTable#103]
Is there a way to exclude a row from the FooTable collapsing magic?  For example, I've got a bottom row (I could make this in <tfoot> if that would help) that spans all the columns and needs to always be visible.

**Comment by bradvin** [comment]
this is similar to https://github.com/bradvin/FooTable/issues/100

I am currently working on supporting these types of rows and will hopefully have a working demo out in the next day

**Comment by helgatheviking** [comment]
Cool!  For the time being, I got around this by creating an empty first column, and putting `display: none !important;` on it. Since this column doesn't have the `data-hide` attribute, the bottom spanning row stays visible, but the column doesn't take up any space since I'm not displaying it.

**Comment by bradvin** [comment]
if you add <code>class="footable-disabled"</code> to the row then FooTable will ignore it.

check out the data-attributes demo where this is used

**Comment by maxshuty** [comment]
@bradvin Has `footable-disabled` been deprecated or replaced with something else in newer versions?
Thanks

**Comment by zebwoy** [comment]
> @bradvin Has `footable-disabled` been deprecated or replaced with something else in newer versions? Thanks

I needed help on this exact problem. when I am applying footable-disabled class to the row which i want to be excluded from footable, it's not working.
