### ISSUE TITLE
Branch V2 not hiding the details row correctly when resizing and having an unused breakpoint

### ISSUE THREAD

**Issue by jes-carr** [fooplugins/FooTable#107]
Steps to reproduce:

Make breakpoints b1 and b2, but only use the b1 in the table headers.
- Go to b1 and open the detail row (footable-row-detail-cell) with the hidden details
- resize to b2 size: controls disappear, but the detail row stays there
- resize to pass the b2 size and the details row gets hidden correctly

An obvious solution is to comment breakpoints if you don't use them, but I think it can be easy to forget to do it, so it would be nice if the script fixes that for us

**Comment by jes-carr** [comment]
also just noticed something: my breakpoints are named phone,tablet,desktop,largeDesktop. If I change their names (in HTML and JS) to anything else, the details row don't show/hide correctly when resizing...

**Comment by bradvin** [comment]
@jesucarr thanks for reporting these - i will follow up and fix asap

**Comment by bradvin** [comment]
@jesucarr I managed to reproduce your unused breakpoint issue and fixed that (will commit shortly)

but I cannot repro your second problem with the custom breakpoint names. Do you have an example in jsfiddle or codepen?

**Comment by jes-carr** [comment]
Sorry as mentioned in the other thread my code is in a private area, and I'm using an old version because otherwise my ajax break. Maybe it only happens in that older version and that's why you can't reproduce it?
