### ISSUE TITLE
Set all row to "expand" mode at mobile size?

### ISSUE THREAD

**Issue by alexisletrotteur** [fooplugins/FooTable#109]
Thought #96 would cover that, but now that I second read it was only about the first row... Is it possible to expand all row at mobile size?

**Comment by TolMera** [comment]
I would also find this really useful, can't seem to implement it myself (not very good at Javascript).

**Comment by bradvin** [comment]
@alexisletrotteur @TolMera I have added 2 new triggers that allow you to expand/collapse all rows.

check out the new demo : https://github.com/bradvin/FooTable/blob/V2/demos/expand-collapse-all.htm

You can simply call

``` javascript
$('table').trigger('footable_expand_all');
```
