### ISSUE TITLE
Document jQuery version requirements

### ISSUE THREAD

**Issue by rocketeerbkw** [fooplugins/FooTable#11]
I witnessed a problem using this plugin with Drupal 7 because it comes with jQuery 1.4.4 and this plugin failed due to the second parameter of $.Event() only being added in jQuery 1.6.

It's possible to use jQuery Update module in Drupal to bump up the jQuery version and get this plugin to work, but it took a bit to figure which version is the minimum requirement.

So I can speak that at least jQuery 1.6 is needed but I haven't extensively tested everything yet.

**Comment by bradvin** [comment]
I will add a check on init for jQuery 1.6, and if it's less then I will through an exception

**Comment by tinacious** [comment]
I was using jQuery 1.6.2 and it didn't work. I changed it to 1.8.2 which was included in the demo and it works now.

**Comment by bradvin** [comment]
I have just committed some changes that make footable work with jQuery 1.4.4
The demo demo-sorting-filtering.htm now references 1.4.4 and works just fine :)
