### ISSUE TITLE
Add Dynamic row with JQuery

### ISSUE THREAD

**Issue by sunnysetia** [fooplugins/FooTable#111]
I am adding dynamic rows with jquery and footable is not working. 
I have added this line.
 $('#mytableid tbody tr').footable();

Column hiding is working fine but it is not expanding rest of the columns. 
If I try with below line then 
 $('#mytableid').footable() then nothing is working.

Please tell me solution....

**Comment by bradvin** [comment]
$('#mytableid tbody tr').footable(); is not correct, you need to init footable on the table not the table rows.

$('#mytableid').footable(); is correct.

What errors do you get when doing the 2nd call? Have you set the table headers to hide on the different breakpoints?

**Comment by anneramey** [comment]
I think I'm having a similar problem, but I'm not referencing my rows. When I add a row to my table using jquery, My columns are removed and readded correctly on resizing, but the expand feature doesn't work on the added row(s). A snippet of the code from where the row is actually added is:

var mytable = $('#'+divTag);
mytable.append(row);
mytable.footable({toggleSelector : ' > tbody > tr > .expand'});
//set up delete on click
deleteTableRow(mytable);

Note that if I don't specify the expand and delete classes (defined in the table head and correctly added to all the initially existing rows), they don't get added. I specified them when I create the row to be added, and I can correctly click on the delete icon to remove the row, but the expand doesn't work. What have I missed?

Thanks

**Comment by bradvin** [comment]
@anneramey @sunnysetia please get the latest code and check out the add-remove demo where rows are dynamically added and removed after footable is initialized
