### ISSUE TITLE
Breakpoint clarification

### ISSUE THREAD

**Issue by pattan** [fooplugins/FooTable#113]
It took me a while to understand how the breakpoint used in footables. In a responsive or media-query context to we talk about viewport or device width.

So as I understand it, breakpoint is the **table** width, not the viewport or device width. (But it can be by the use of the function 'calculateWidthAndHeightOverride')

Or am I completely wrong here?

**Comment by bradvin** [comment]
@pattan the breakpoints in footable did start out as the device width, but it soon became apparent that was not going to work for the masses, so it changed to look at the table width.

But yes, you can override it using that function you mention
