### ISSUE TITLE
Anyway to remove the detail view on row-click?

### ISSUE THREAD

**Issue by xziler8** [fooplugins/FooTable#115]
only have 5 columns, none to hide -- want to remove the click event per row to show the detailed view....haven't found any reference as such...

thanks
AG

**Comment by bradvin** [comment]
@xziler8  good point - it does not make sense to bind the click event if no breakpoint will fire. Same goes for the resize event - if no breakpoints are found in the table, then it should do nothing.

I have made a fix for this and will commit soon after some further testing.

thanks

**Comment by xziler8** [comment]
Thanks -- will github notify when commit is made?

On Wed, Aug 7, 2013 at 1:57 AM, bradvin notifications@github.com wrote:

> @xziler8 https://github.com/xziler8 good point - it does not make sense
> to bind the click event if no breakpoint will fire. Same goes for the
> resize event - if no breakpoints are found in the table, then it should do
> nothing.
> 
> I have made a fix for this and will commit soon after some further testing.
> 
> thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/115#issuecomment-22231283
> .

## 

Thanks,

Alan

**Comment by bradvin** [comment]
@xziler8 it will if you watch the footable repo

**Comment by xziler8** [comment]
I am watching but cannot discern if this particular fix has been committed.

A

**Comment by bradvin** [comment]
@xziler8 this fix was committed a while ago. I now check if there are any columns with breakpoints before I bind the toggle action : https://github.com/bradvin/FooTable/blob/V2/js/footable.js#L410

**Comment by xziler8** [comment]
thanks Brad.

also on [http://fooplugins.com/footable-demos/] the "Demo's" subheads
should not be possessive... just pluralized.

A

On Fri, Sep 13, 2013 at 1:40 AM, bradvin notifications@github.com wrote:

> @xziler8 https://github.com/xziler8 this fix was committed a while ago.
> I now check if there are any columns with breakpoints before I bind the
> toggle action :
> https://github.com/bradvin/FooTable/blob/V2/js/footable.js#L410
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/115#issuecomment-24374342
> .

## 

Thanks,

Alan

**Comment by bradvin** [comment]
@xziler8  thanks the spellings have been fixed :) https://github.com/bradvin/FooTable/commit/c11b9c1bea6a06f08dfb423e6f78207a5c56b8f2
