### ISSUE TITLE
Sorting prevents cell click function

### ISSUE THREAD

**Issue by anneramey** [fooplugins/FooTable#116]
I'm defining my table like this:
//apply fooTable to the table with a custom toggleSelector to overwrite the default selector on the entire row.
tableItems.footable({toggleSelector : ' > tbody > tr > .expand'});
//set up delete on click
deleteTableRow(tableItems);

And when the table first loads everything is fine. There is a column that contains a red checkbox (font-awesome). When the user clicks on that, the row is deleted. But once I do a sort on any column, the delete stops working. The delete function is no longer called on click of that check-mark in the column with the delete class. The cells still have the delete class, but clicking on them no longer calls the desired function. It's as if the sorting nullifies my on click function. Am I doing something wrong?

Note that the expand feature is still working only on the items with the class expand, like it should.

**Comment by anneramey** [comment]
I see this on the demo versions, but it's not happening with the version I downloaded from here. I suppose it's something that's been fixed in a current copy?

**Comment by bradvin** [comment]
Sorry for the slow response - make sure you are using .on to bind your delete events at a table level. The sorting extension shuffles the table rows around which may cause your elements to loose their attached bindings. Binding to the table using .on will safe guard against this:

``` javascript
$('table').footable().on('click', '.row-delete', function(e) {
    e.preventDefault();
    //do your delete here
});
```

I am putting together a new demo showing how to add and remove data from an existing table. Going through this demo has also shown me that this is not so straight forward as I had hoped, so I am making quite a few changes to the code to make this as simple as possible

**Comment by anneramey** [comment]
Thank you! That fixes the click issue I was having. I await the demo on how to add and remove rows with bated breath. I found deletion pretty straight forward, but adding quite complex. Thanks again.

**Comment by bradvin** [comment]
@anneramey a lot of changes and fixes and demos have been updated. 

Check out the demos here : http://fooplugins.com/footable-demos/
There is a demo called add / remove rows which uses the new API that is built in now
