### ISSUE TITLE
Question/Issue pertaining to Plugin Development. 

### ISSUE THREAD

**Issue by 6eDesign** [fooplugins/FooTable#117]
@bradvin , 

Thanks for footable!  I wanted to bring something to your attention and also I have a question.  First, you might want to fix the plugin template file as it throws errors when included - I was able to get around this by using the sortable plugin file as a template instead.  

Next, my question: is there a hook or method by which I can tell FooTable to rebuild the columns on the table and/or invoke the subroutines which naturally occur when the window is re-sized? I have created a 'column-picker' plugin that allows you to choose to include extra columns on a custom desktop breakpoint.  Interestingly, the first column chosen pops right up into view.  Subsequently added columns, however, require re-sizing the browser window in order to appear.  I have tried invoking the ft.resize() function and the ft.createOrUpdateDetailRow() function but I am doing so without having completely read your code.. 

That's when I realized that you're a real person and might be able to answer this question without me banging my head on the desk too much.  So.. any suggestion? 

Thanks, 
Jon

**Comment by bradvin** [comment]
@6eDesign you can force a "redraw" by triggering a custom event:

$(".footable").trigger("footable_resize");

Thanks for letting me know about the plugin template file - I have not updated that file in a while

**Comment by 6eDesign** [comment]
Hey @bravdin

Thanks for getting back to me so quick.  I actually had browsed through the issues and seen the $(".footable").trigger("footable_resize") trick but it does not seem to be working for me.  

Other than changing the data-hide attribute of the 'th' element and changing the the hide attribute for the appropriate breakpoint inside of the ft.columns object - what might I be missing? 

Thanks again.

**Comment by bradvin** [comment]
ah - I think I know why it appears to do nothing - I have some checks in place to stop resizing from happening unnecessarily. The "state" of the FooTable is not changed, so you need to make it think it has changed. You can do that by clearing the breakpoint data value on the table first:

$(".footable").data(''breakpoint", "");

and then triggering the event

**Comment by 6eDesign** [comment]
@bradvin - thanks again for the help.  

Here's my function for showing columns, maybe you will be able to see where I am going wrong.. I apologize... I know this isn't stackoverflow.. 

```
    var showColumn = function(elem,cols) { 
      // retrieve cols Index for column to be shown: (stored in DOM)
      colsIndex = elem.getAttribute('data-colsIndex'); 
      // create ref to actual dom th dom element
      var th = table.getElementsByTagName('thead')[0].getElementsByTagName('th')[colsIndex]; 

      cols[colsIndex].hide.desktop = false; 

      // update data-hide attribute which used to be: 'phone,tablet,desktop'
      th.setAttribute('data-hide','phone,tablet'); 

      // attempt fix ala Bravdin
      $(".footable").data("breakpoint", "");
      $(".footable").trigger("footable_resize");

      return cols; 
    }
```

It is behaving the same as before, the first column to be run through this function shows fine.. subsequent calls only seem to work after a resize of the window.

**Comment by 6eDesign** [comment]
I have been able to invoke the resize() event by disabling this line in footable.js: 
            // This (if) statement is here purely to make sure events aren't raised twice as mobile safari seems to do
            if (!pinfo || ((pinfo && pinfo.width && pinfo.width != info.width) || (pinfo && pinfo.height && pinfo.height != info.height))) {

A bit hackish, for sure but it does get the job done even without these lines: 
      $(".footable").data("breakpoint", "");
      $(".footable").trigger("footable_resize");

I'm still completely open to suggestions but could not seem to get the "footable_resize" event to work.

**Comment by bradvin** [comment]
@6eDesign I think I will add a redraw function that forces a redraw no matter what.

And then you can trigger the redraw:

$(".footable").trigger("footable_redraw");

I will make the change, test and commit as soon as possible

**Comment by 6eDesign** [comment]
@bradvin 

Thanks.  That would be great.  Would a "footable_redraw" function work equivalently to the ft.resize() function? (that's what I am currently using after disabling that previously mentioned if statment and it's working well thus far).  

If you want, you can check out the work I'm doing - I will make the column picker aspect available as a FooTable plugin once we have this redraw business worked out. :)  Here's a link to the repo: https://github.com/6eDesign/JSONTable (it's a combination of the column picker plugin, your FooTable, and a function I wrote for parsing any generic JSON into a table with a number of settings and a hook for customizing output. 

It's pretty fast - it uses (mostly) native DOM creation methods, so that helps.  It's still a baby but I'd love to hear what you think.

**Comment by bradvin** [comment]
@6eDesign the redraw would work exactly like the resize works now with your changes (sort of)

I had a look at your jsontable repo - nice work - do you have an online demo at all?

**Comment by 6eDesign** [comment]
Thank you, much appreciated.  There's an example.html file in the repository but I will get something online soon and get you a link.

**Comment by 6eDesign** [comment]
@bradvin 

I will probably build this out a bit better, but here's an online example: 
http://6edesign.github.io/JSONTable/

Don't forget to right click on the column headings/play with the column picker.

**Comment by bradvin** [comment]
wow - looks really cool - I love the column selector/hider - I would love that to become an extension in footable - submit a pull request to the V2 branch when you can

**Comment by 6eDesign** [comment]
@bradvin - Thanks!  I thought the JSON loader might be something of general use to the community.  I appreciate your kind words.

**Comment by 6eDesign** [comment]
@bradvin I am still working to make JSONTable cooler and incorporate as many options and configurations as possible.  I am currently working on the filtering aspect and ran into a question for you: is there a way to use the filter plugin to filter only one specific column while ignoring the rest?

**Comment by rajaveernapu** [comment]
@bradvin  is there a way to filter the data on specific columns? 

@6eDesign Have you written any extention for the specific column text filter?
