### ISSUE TITLE
Expanding not working if sorting clicked (phone)

### ISSUE THREAD

**Issue by tinacious** [fooplugins/FooTable#12]
Hi there, I'm trying to implement your plugin but unfortunately I've come across an issue. When clicking to sort, that works fine, but if I click to expand a collapsed area after already clicking to sort, the area won't expand. If I refresh and click to expand without clicking to sort, it's fine, but as soon as I click to sort, if I want to expand I need to refresh and expand without sorting. 

![phone-sort-expand](https://f.cloud.github.com/assets/1856992/44111/ab0dd81a-56ab-11e2-816e-f48a14002d94.png)

My HTML looks like this. 

``` html
<thead>
    <tr>
        <th data-hide="phone,tablet">
            Program Code
        </th>
        <th data-class="expand">
            Program Name
        </th>
        <th data-hide="phone,tablet" data-type="numeric">
            Academic Terms
        </th>
        <th data-hide="phone">
            CO-OP Terms</br> in Program
        </th>
         <th>
            Total Fees </br>
            For First Two Academic Terms
        </th>
    </tr>
</thead>
```

The table looks like this expanded:

![expanded](https://f.cloud.github.com/assets/1856992/44117/3784489c-56ac-11e2-8a55-d421b69439ba.png)

The Chrome Inspector console shows no errors. In Chrome Inspector, upon clicking, when it works I notice classes being added. When it doesn't work, I notice that no classes are added. Also if the window is resized from large to small, clicking on the plus doesn't work either unless I refresh it ahead of time.

Have I done something incorrectly?

The full project can be seen [here](https://github.com/tinacious/fee-guide).

Please let me know at your earliest convenience. Thank you.

**Comment by tinacious** [comment]
### Update

At this moment in time, using the files from [this demo](http://themergency.com/footable-demo/demo-sorting.htm) you provided works. Unfortunately the package off the website is not up to date, and the JS files on Github's master branch are not working either. There are at least 2 instances of `footable.js` dated 15 November floating around and one of them works. The 18 November one does not. Also I had to change `footable.sortable.js` too. Too many variables to pinpoint what the issue is exactly but I got it working finally.

[This](https://github.com/tinacious/fee-guide/blob/ff25a68eb5786d5def4a1a7f4fde4c6ceb43421a/js/footable.js) is the working `footable.js` I used and [this](https://github.com/tinacious/fee-guide/blob/ff25a68eb5786d5def4a1a7f4fde4c6ceb43421a/js/footable.sortable.js) is the working `footable.sortable.js` I used.

**Comment by tinacious** [comment]
This is a great tool you developed. I love it. I forked it and created a new branch `working-responsive-sortable` in which i changed `footable.js` and `footable.sortable.js` to older the versions I found on [this demo](http://themergency.com/footable-demo/demo-sorting.htm) at this time. These were the versions that worked for my use case. You can view the fork [here](https://github.com/tinacious/FooTable). 

Thanks for taking the time to develop such a great tool. It is very useful.

**Comment by bradvin** [comment]
Thanks Tina - there was a bug introduced somewhere along the line where the sorted columns no longer expanded. I have fixed the bug in my latest commit https://github.com/bradvin/FooTable/commit/f7d01c6afef17881a83b17fc65d07e744d0fbe93

Please could you test your code again using the latest code
