### ISSUE TITLE
What would cause FooTable mobile query not to Expand?

### ISSUE THREAD

**Issue by lenichols** [fooplugins/FooTable#121]
Footable-Toggle was working just fine. Now suddenly I can not toggle the dropdown expansion view of the hidden columns. What could cause this?

**Comment by bradvin** [comment]
Does this happen in one of the demos? Or one of your pages? Do you have a jsfiddle or codepen of it?

**Comment by pahuja12** [comment]
Hey! I am facing a similar problem on touch devices.
