### ISSUE TITLE
Only activate/show column if tablet or phone?

### ISSUE THREAD

**Issue by flickster** [fooplugins/FooTable#122]
I know this question goes in the opposite direction of FooTable; but am wondering if it would work (can't figure it out in my head at the moment so any help is appreciated!) or if anyone could suggest an alternative solution?

i.e. on a full desktop, the content of a particular column would not show.  However, when the viewport is tablet/phone, the '+' control sign appears, and upon clicking  (or touching on the iPad eqv) this hidden column is shown.

Thank you in advance :)

p/s: My starting position is that I was using a Tooltip to show content but was informed that this tooltip worked on every device but the mobile safari browser.  

Now thinking of alternative solutions.

**Comment by bradvin** [comment]
@flickster I think I know what you are after, but that is not currently a feature of footable. There are numerous events you can hook into to accomplish your specific customization. If there are more requests for this feature then we might add it in a future release
