### ISSUE TITLE
Working demo?

### ISSUE THREAD

**Issue by yazinsai** [fooplugins/FooTable#124]
I've been having a hard time figuring out which files I need for a working demo (just the core, no sorting or anythign extra). I checked out the demo site you have on [Themergency](http://themergency.com/footable/) but it uses the old version from Nov '12 and the filenames have all changed.

Could you please tell me which `.js` and `.css` files I need to get the barebones version of this working?

Thanks!

**Comment by bradvin** [comment]
The new demo URL will be http://fooplugins.com/footable-demos/

Check out the getting started demo : http://fooplugins.com/footable/demos/getting-started.htm

Then check out the setup tab on that page for full instructions

**Comment by yazinsai** [comment]
Awesome, thanks @bradvin ! :+1:
