### ISSUE TITLE
About external link to sort table and filter

### ISSUE THREAD

**Issue by nirajaryal** [fooplugins/FooTable#125]
Hello :)
First of all, I would like to thank you for this awesome plugin! Thank you so much :)

The thing is, I would really like an external link to sort the table. Some function like, 

<code>$('a').click(function(){
$('.demo-table').sort(indexOfColumn,'asc');
});
</code>

Or is there anyway that I could use it?

Could you help me with this?

And I really hope you could add the column specific filter enhancement soon. Really hoping for positive response.

**Comment by bradvin** [comment]
@nirajaryal  this is now available in the latest changes. Check out the sorting demo where it uses the new sorting API
