### ISSUE TITLE
Footable won`t work in opera mobile

### ISSUE THREAD

**Issue by izorgor** [fooplugins/FooTable#126]
Hi, 

for some reason footable plugin have issue with opera mobile. When I`m testing in opera mobile emulator, some of the tables load properly and other not. I double checked html and both tables have the same.

Despite the fact that in emulator some tables work, on real mobile device (opera browser) non of them won`t work.

**Comment by bradvin** [comment]
thanks for letting me know - I will install the emulator and test it out the demos

**Comment by bradvin** [comment]
I installed the emulator and ran through every demo http://fooplugins.com/footable/demos/index.htm
And they all worked 100%

Please could you double check this for me on your side

**Comment by bradvin** [comment]
@izorgor also - what device did you launch in the emulator? I tested with samsung galaxy S3

**Comment by izorgor** [comment]
Maybe my theme or plugin have conflict, I`m not sure. I tested on S3 as well. 

I also tested on real S3 device and here is the thing:

Opera classic have that issue
Regular Opera doesn`t 
Firefox is ok
and Chrome is ok

I have also issue in emulator, you can check it here: http://bit.ly/12q1jdO

It`s kinda strange because some of the tables load footable and some are not. 

If it`s work for you then my issue is caused by some other script.

Best.
