### ISSUE TITLE
data-ignore seems to make columns immune to hiding

### ISSUE THREAD

**Issue by DonGissel** [fooplugins/FooTable#127]
I just upgraded footable a few minor versions, and in today's build, a curious problem appears:

```
<th data-hide="phone">Derp</th>
```

... works just fine, and hides when it's supposed to. However:

```
<th data-hide="phone" data-ignore="1">Derp</th>
```

... does NOT seem to work. The column should hide, and just be excluded from the detail row, but it doesn't disappear at all.

**Comment by bradvin** [comment]
I cannot reproduce this with the latest code. Also - you must use 

data-ignore="true"

instead of "1"

**Comment by DonGissel** [comment]
Here's a stripped-down version of the table that causes me grief:

```
<table class="table table-striped">
    <thead>
        <tr>
            <th>Invoice no.</th>
            <th>Date</th>
            <th>Amount</th>
            <th>CUR</th>
            <th data-hide="phone" data-ignore="true">Type</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><a href="#">2107052244</a></td>
            <td>02/15/2011</td>
            <td data-value="20000000">&euro;20,000,000.00</td>
            <td>EUR</td>
            <td>Standard invoice</td>
        </tr>
    </tbody>
</table>

<script>
    $('table').footable({
        delay: 50,
        breakpoints: {
            tablet: 800,
            phone: 480
        }
    });
</script>
```

I'm using the newest version of the script, and this one table is the only one not working.

**Comment by bradvin** [comment]
@murderfacemurderfacemurderface thanks for the sample code - I see why it is not firing the breakpoint now. I was checking if the column also had an ignore on it (which was incorrect).

I have fixed the code and will commit shortly

**Comment by DonGissel** [comment]
Awesome! Thanks for the quick fix. :-)

**Comment by bradvin** [comment]
@murderfacemurderfacemurderface code is updated and commited
