### ISSUE TITLE
After the row is added via AJAX "detail row" should be re-inited

### ISSUE THREAD

**Issue by thehappycoder** [fooplugins/FooTable#128]
I am not sure if it's a bug or a feature but it would be nice to have.
1. New row is created
2. Old one is removed from DOM
3. The details row, however, stays from the last row. And if the ajax call was made after the details had been opened, the detail row stays visible (with old data).

Maybe somehow it is possible to determine that the detail row needs to be re-inited.

I am using footable-2.0 and doing jQuery('.footable').trigger('footable_initialize') after ajax call is complete.

**Comment by bradvin** [comment]
@thehappycoder the FooTable API has changed a bit in V2 - try calling the redraw method instead of triggering the event. Here is an example:

$('table').data('footable').redraw();

The redraw should force the detail to be redrawn again. If not then that is a bug, but I just had a look at the code and it should do what you are expecting.

**Comment by thehappycoder** [comment]
jQuery('.footable').data('footable').redraw() didn't help. After refreshing page I see that the data has changed (I have updated_at datetime hidden in detail row).

**Comment by thehappycoder** [comment]
I forgot to mention that the added row is added right after (in DOM tree) the one that gets deleted at step 2.

**Comment by bradvin** [comment]
@thehappycoder how are you removing the row from the table? There is a method you can call to remove a row from the table and it removes the detail row too (if it exists)

check out the demo : http://fooplugins.com/footable-demos/?url=http://fooplugins.com/footable/demos/add-delete-row.htm

**Comment by bradvin** [comment]
@thehappycoder please let me know if this is now fixed in the latest code so I can close this issue - thanks
