### ISSUE TITLE
add-delete-row example

### ISSUE THREAD

**Issue by DustyCarr** [fooplugins/FooTable#129]
The demo works great on desktop, but I can't delete any rows on the phone (tested on iPhone 5 and galaxy S3). Tap the X and nothing happens?

**Comment by bradvin** [comment]
thanks for letting me know i will check it out

**Comment by bradvin** [comment]
@DustyCarr turns out to be a css issue - I had to make the buttons display inline block and give them a width and then it works, as ios thinks they are empty links.

**Comment by bradvin** [comment]
this has been fixed now in the latest code
