### ISSUE TITLE
Issues with multiple footables on the same page

### ISSUE THREAD

**Issue by jlars62** [fooplugins/FooTable#132]
I'm sorry if I have missed something in some documentation, but there seems to be an issue with V2 of footables. I have been using v.5, according to the footable.js header, and just switched over to v2. However, on pages where I have more than one footable, it's as if the second table overwrites the first table. 

Examples, if I click a th element of the first table, it tries to sort the second table. When I enter text into the input filter of the first table, it filters the second table. 

I have double-checked my html for any syntax errors, multiple ids, etc, and as far as I can tell it is clean. I also created a simple standalone page and it had the same issue.

This wasn't happening with v.5, am I missing something or is this a bug?

Thanks alot! Footables is a great plugin!

**Comment by bradvin** [comment]
@jlars62 This was a bug in V2 - we have just fixed it so it should be fine now - check out the new demo called multiple-showcases.htm 

Let me know if this update fixes your problem and we will tag this as a new release

**Comment by jlars62** [comment]
@bradvin Awesome thanks!

**Comment by michaelGregoire** [comment]
Thanks for squashing this bug so quickly!
