### ISSUE TITLE
Auto Select Column with a Checkbox / Checkboxes or Other Methods

### ISSUE THREAD

**Issue by ingenuitor** [fooplugins/FooTable#134]
Hello, I have been playing around with FooTables vs Data-tables and whereas Data-tables has been around forever, FooTables seems to be easier to use, yet missing some vitals. Here is one that is a must http://tetzfiles.com/temp/datatables/
I'm missing something in the documentation or I just can't find a way to to use check-boxes workout using custom scripting, which I'm trying to get away from. Let me know your your thoughts and keep up the great work.

**Comment by bradvin** [comment]
thanks - this is a great candidate for an addon for FooTable - if you could contribute this code back to the project that would be great :)

**Comment by ingenuitor** [comment]
Not sure of the logic for this one yet, hence the question and sample URL, perhaps my presentation was bad, sorry for the confusion.

**Comment by ingenuitor** [comment]
I guess I have to revert back to DataTables, can't function without this feature. Will keep my eyes on FooTable for the future. Seems cleaner than DT, but missing vital functions. Thanks again.

**Comment by kondloa** [comment]
Hi. I would like to know if this functionality is available now. I want to use JQuery to get rows on all pages and change the flag. The below example only affects the current page.

$(".footable tbody tr:not(.footable-filtered) input:checkbox").prop("checked", this.checked);
