### ISSUE TITLE
pagination bootstrap 3

### ISSUE THREAD

**Issue by lalocespedes** [fooplugins/FooTable#136]
pagination class not working with bootstrap 3, its shows twice paginate. help please

**Comment by flex86** [comment]
``` html
<table class="table table-striped" data-page-navigation=".pagination">
....
<tfoot>
    <tr>
        <td colspan="5">
            <div class="paging">
                <ul class="pagination"></ul>
            </div>
        </td>
    </tr>
</tfoot>
```

Works for me

**Comment by bradvin** [comment]
@lalocespedes are you using the WP plugin?

@flex86 thanks for confirming it works - I want to update all the demo/docs to V3 soonish

**Comment by scicco** [comment]
hi all, i think the example documentation page is not updated:
http://fooplugins.com/footable/demos/paging.htm#docs

i mean:

```
<tfoot class="hide-if-no-paging">
    <tr>
        <td colspan="5">
            <div class="pagination pagination-centered"></div>
        </td>
    </tr>
</tfoot>
```

while only

```
<tfoot>
    <tr>
        <td colspan="5">
             <div class="paging">
                <ul class="pagination"></ul>
             </div>
        </td>
    </tr>
</tfoot>
```

works for me (ul tag with the needed class inside div)

**Comment by ThemeMetro** [comment]
But what about "pagination-centered" its still not working

**Comment by ThemeMetro** [comment]
Sorry got it working code for me

```
<tfoot class="hide-if-no-paging">
    <tr>
        <td colspan="7" class="text-center">
            <ul class="pagination pagination-centered">

            </ul>
        </td>
    </tr>
</tfoot>
```

**Comment by flex86** [comment]
FYI: There is no 'pagination-centered' class in Bootstrap v3. You can just leave it out and surround the ul with an element which uses the class="text-center"; just like you did.

**Comment by felipecocar** [comment]
TY flex, wrapped it around a <div> and it works fine now. :)

**Comment by ghost** [comment]
The above is also working for me, however, in the "phone" view the pagination disappears complete. Any ideas?

**Comment by suseeindaran** [comment]
First column in the table should be visible. You should not use data-hide property in the first column of your table.
