### ISSUE TITLE
Incompatible with Post Backs

### ISSUE THREAD

**Issue by ThomasBowen** [fooplugins/FooTable#137]
It seems that whenever I display a Bootstrap modal on the same page as a Footable table, the Footbale table breaks, and no longer works until I refresh the page.

It doesn't seem to be throwing errors though.

UPDATE: In fact I think the problem in general is that Post-backs seem to break it, not just modals.

**Comment by bradvin** [comment]
@FallenBlade post-backs as in asp.net post backs?

**Comment by ThomasBowen** [comment]
@bradvin yes, ASP .Net post backs.

**Comment by ThomasBowen** [comment]
@bradvin Have you experienced this before? Has anyone got a solution to allow FooTable to work with asp.net post backs?

**Comment by bradvin** [comment]
@FallenBlade I have not had this before. I am not sure how an ASP.NET postback will affect the footable js. On postback, the footable init code will be called again surely?

**Comment by ThomasBowen** [comment]
@bradvin it seems like the table has the "footable-loaded" class added to it after the post back. But could it be a left over from before? Is there a way of reinitialising Footbale, even if "footable-loaded" is already on the table?

**Comment by bradvin** [comment]
@FallenBlade yes, you can "reset" the footable first. Check out the reset demo https://github.com/bradvin/FooTable/blob/V2/demos/reset.htm that has an example of this.

Are you using an ajax update panel on your page at all? It is very strange that the table has that class still after a post pack. Perhaps you have runat="server" on your table? If so, make sure enableviewstate is false for the table

**Comment by ThomasBowen** [comment]
@bradvin the table is runat="server", I've just added "enableviewstate = false".

I've tried to add a reset method, however I'm getting a JavaScript error of "Cannot call method 'reset' of undefined".

**Comment by steveush** [comment]
Solution found by @FallenBlade, closing issue.

**Comment by ThomasBowen** [comment]
@steveush a solution was never found, in the end we removed FooTable from our project.

**Comment by tiagomsimao** [comment]
I had this issue a couple years ago and I forget the solution when I try to use it inside a ajax.updatepanel today.
But I found it .. so the solution is to call/create the footable all time that occurs a postback. 

In html header (script):

```
 function pageLoad(sender, args) {
    $(function () {
        $('.footable').footable();
    });
    if (args.get_isPartialLoad()) {
        $('.footable').footable();
    }
}
```

You have to call/create the footable in pageload and in partialload.

sorry for my English.

Cheers
