### ISSUE TITLE
Pagination hiding

### ISSUE THREAD

**Issue by xziler8** [fooplugins/FooTable#139]
When including the class "hide-if-no-paging" on the &lt;tfoot&gt; and having one page of data, the &lt;tfoot&gt; is NOT hiding as desired.

**Comment by bradvin** [comment]
@xziler8 i just tested this in the showcase demo by setting the page size to 15 and the tfoot was hidden. Perhaps it's your setup. Do you have a url I can check, or even better, can you reproduce the issue in a jsfiddle or codepen?

**Comment by xziler8** [comment]
added the pagination.js file and this code

```
        <tfoot>
          <tr>
            <td colspan="5">
              <div class="pagination pagination-centered
```

hide-if-no-paging"></div>
                </td>
              </tr>
            </tfoot>

looked at the .js file -- saw no reference to handling the
class="hide-if-no-paging"
saw the code where info.pages.length === 1 ... adding class="no-paging"

```
        if (info.pages.length === 1) {
            //we only have a single page
            $(ft.table).addClass('no-paging');
        } else {
            $(ft.table).removeClass('no-paging');
        }
```

not sure how the 2 classes relate... is it possible my versions are
mismatched?

A

On Tue, Sep 24, 2013 at 4:09 PM, bradvin notifications@github.com wrote:

> @xziler8 https://github.com/xziler8 i just tested this in the showcase
> demo by setting the page size to 15 and the tfoot was hidden. Perhaps it's
> your setup. Do you have a url I can check, or even better, can you
> reproduce the issue in a jsfiddle or codepen?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/139#issuecomment-25038130
> .

## 

Thanks,

Alan

**Comment by bradvin** [comment]
@xziler8 - this CSS does the hiding:

.footable.no-paging .hide-if-no-paging {
  display: none;
}

try putting the class on the tfoot itself : <tfoot class="hide-if-no-paging"> I think the pagination class is overriding my CSS rule above.

**Comment by xziler8** [comment]
cannot find your CSS (above)-- where is it at?

Alan

On Wed, Sep 25, 2013 at 1:22 AM, bradvin notifications@github.com wrote:

> @xziler8 https://github.com/xziler8 - this CSS does the hiding:
> 
> .footable.no-paging .hide-if-no-paging {
> display: none;
> }
> 
> try putting the class on the tfoot itself :
> I think the pagination class is overriding my CSS rule above.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/139#issuecomment-25062635
> .

## 

Thanks,

Alan

**Comment by xziler8** [comment]
Sould there be a footable.paging.css file?

Alan

On Wed, Sep 25, 2013 at 10:01 AM, Alan Gochin alan@gochin.com wrote:

> cannot find your CSS (above)-- where is it at?
> 
> Alan
> 
> On Wed, Sep 25, 2013 at 1:22 AM, bradvin notifications@github.com wrote:
> 
> > @xziler8 https://github.com/xziler8 - this CSS does the hiding:
> > 
> > .footable.no-paging .hide-if-no-paging {
> > display: none;
> > }
> > 
> > try putting the class on the tfoot itself :
> > I think the pagination class is overriding my CSS rule above.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/139#issuecomment-25062635
> > .
> 
> ## 
> 
> Thanks,
> 
> Alan

## 

Thanks,

Alan

**Comment by bradvin** [comment]
https://github.com/bradvin/FooTable/blob/V2/css/footable.core.css#L152

which is generated from the less:

https://github.com/bradvin/FooTable/blob/V2/less/footable.core.less#L225

I originally had separate files per add-on, but they were so small it just didn't make sense. And then support for themes meant even more files, so I chose to keep it simple
