### ISSUE TITLE
table zebra broken

### ISSUE THREAD

**Issue by havvg** [fooplugins/FooTable#14]
When applying FooTable on a table having a zebra (using `:nth-child`), the zebra breaks, as FooTable adds additional `<tr>` elements.

**Comment by bradvin** [comment]
unfortunately, the way the css nth-child selector works, it will always "break" the zebra stripes when you expand a detail row. One way around this is with some jquery:

$('table').footable().find('> tbody > tr:not(.footable-row-detail):nth-child(even)').addClass('zebra');

**Comment by jserrao** [comment]
Yeah nth child is kinda weird, but this worked for me FWIW.

**Comment by boulox** [comment]
Does anyone manage to make it work with the bootstrap markup.  The tweak above can't make it here
