### ISSUE TITLE
A Table within another Table in data-hide ="all"

### ISSUE THREAD

**Issue by iamYANNNN** [fooplugins/FooTable#140]
Hi, I would like to ask if is it possible to have a footable within the hiding portion of another footable currently? I've tried but was unable to sort the columns and the responsive element was not working.

**Comment by bradvin** [comment]
Do you have a online demo on jsfiddle or codepen?

**Comment by iamYANNNN** [comment]
Am currently having problems reproducing the issue in jsfiddle. However, i am able to reproduce it externally by doing an edit of the demo - multiple-showcases. It is done by adding another column, placing data-hide="all" and copying one of the tables into the respective td which is hidden. The main table was able to sort but the table within it wasnt responsive and also unable to sort.

Just downloaded and used the latest codes but still had this problem.
