### ISSUE TITLE
Colspan is not handled properly

### ISSUE THREAD

**Issue by malayhm** [fooplugins/FooTable#141]
<table class="footable toggle-arrow phon">
        <thead>
          <tr role="row">
            <th>Id</th>
            <th>Type</th>
            <th data-hide="phone">Instances</th>
          </tr>
        </thead>
        <tbody>
<tr><td colspan="3">No Data Available. </td></tr></tbody>
      </table>

In mobile view thead has only two columns but body expands to three. 

There is no way to handle colspan here.

**Comment by bradvin** [comment]
Could you put up a demo on jsfiddle or codepen so that I can see the issue you are talking about?

**Comment by ricardozea** [comment]
I'm having a similar issue but I created a new issue since I'm not 100% sure they are exactly the same.

Check this issue: https://github.com/bradvin/FooTable/issues/160
