### ISSUE TITLE
Problem with filtering and expanding a row

### ISSUE THREAD

**Issue by victorbueno** [fooplugins/FooTable#142]
When you filter the results and expand a row, a new row with non-filtered data is added below the expanded one.

**Comment by bradvin** [comment]
@victorbueno thanks for pointing this out - I managed to reproduce the issue. I will work on a fix

**Comment by bradvin** [comment]
@victorbueno this should be sorted in the latest commit https://github.com/bradvin/FooTable/commit/0d803160d692cd9f043ba0e38b522c9723502b04
