### ISSUE TITLE
Bootstrap 3 compat

### ISSUE THREAD

**Issue by markc** [fooplugins/FooTable#143]
Is anyone working on BS3 compatibility?

**Comment by bradvin** [comment]
@markc not at the moment - just no time - but you are more than welcome to submit a pull request :)

**Comment by markc** [comment]
Okay I can try but I'm not really familiar enough with FooTable to best know how to integrate these changes. For instance the DIV wrapper for the pager has a class called "pagination" whereas BS3 uses that classname on the UL itself so both the example demo page(s) and footable.pagination.js needs changing, so that means the current demos will fall over. I guess I could work in a "bootstrap3" branch and "go wild" with changes (I'm not interested in backwards compatibility with BS2). In fact I'd like to make the entire demos rely on BS3 (breadcrumbs and tabs too).

**Comment by bradvin** [comment]
I have wanted to make a BS3 theme for a while now. If you create a BS3 branch please let me know and I can work on it with you

**Comment by markc** [comment]
Finally got a first cut at a Bootstrap 3 version of showcase.htm. It's obviously a WIP so may or may not work at any point in time...

https://github.com/markc/FooTable/tree/bs3/bs3
http://goldcoast.org/footable/bs3/

**Comment by bradvin** [comment]
@markc that is looking great! Nice work
I have merged your changes to a bs3 branch so I can also work on it - I love your demo

**Comment by markc** [comment]
Another update where I split up 3 demos and docs. The demo examples in bs3/lib/htm/ can nearly be dropped into another project as long as the right JS/CSS is wrapped around them and the doc examples in bs3/lib/md/ are in Markdown format and work on Github as well, but links in the docs themselves only work from within the README.md so bouncing back to README.md is required to continue reading other docs. They work as expected on the live site because the AJAX requests are relative to the index.html. Next I'll add the AJAX demo, following the same pattern, and then look into some PHP based server-side code to provide dynamic content.

https://github.com/markc/FooTable/tree/bs3/bs3

**Comment by markc** [comment]
Thanks for the last merge. The examples and docs split up is just a suggestion and makes it easier for me to focus on each step. I've added the start of an editable plugin (from Horton) and a server side PHP script (from datatables.net) but I've come to a full stop in how to "port" the horton based editable plugin and there is a lot of work to add full server side sorting and filtering. The inline editing and server side features are the main things I need so for now I'll have to continue with Horton because at least the editable plugin works within the Horton context so I can mainly re-focus on the PHP server side. If you or anyone gets a chance to look at the editable plugin and get the basics to work then I'll be happy to continue with this branch.

**Comment by hamerw** [comment]
The only problem I came across was the pagination links when using the add-on pagination plugin. It was an easy fix..
instead of, as per the documentation: `<div class="pagination pagination-centered"></div>`
switch to: `<ul class="pagination pagination-centered"></ul>`

The paginate.js actually looks for a `<ul>`  first so it was and easy test and worked.

**Comment by timtailor** [comment]
Thanks @hamerw 

I'm glad i found this after googling for quite a while why my footable pagination doesn't work :( 
Unfortunately the documentation still seems to be not up-to-date (inspite of issue #136)

**Comment by lenamtl** [comment]
+1

**Comment by bradvin** [comment]
FooTable V3 is coming...

**Comment by kedano** [comment]
Is it in a dev branch?

—
Kenneth Dahlstrøm
