### ISSUE TITLE
Question: How to Disable Toggle & Always Show

### ISSUE THREAD

**Issue by Hilmon** [fooplugins/FooTable#144]
Not really an issue but I'd like to always show the hidden columns in the "footable-row-detail" by default and turn off the toggle function altogether. Is this possible with limited js experience?? ...

**Comment by bradvin** [comment]
perhaps footable is not what you need then. I would just output the HTML in the layout that you need it. If nothing is needed to be toggled, then why load footable in the first place

**Comment by Hilmon** [comment]
The responsive behaviour and html output is exactly what I'm looking for... I just don't want to hide the secondary content...

**Comment by bradvin** [comment]
@Hilmon so you want to remove the toggle button and force the detail rows to display on smaller devices?

**Comment by Hilmon** [comment]
Yes, exactly!... I've had a good look thru footable.js ... but as I said, my js skills are just not there yet. Thanks for taking the time to respond by the way ... it's very much appreciated.
