### ISSUE TITLE
data-page-size not respected 

### ISSUE THREAD

**Issue by bwyss** [fooplugins/FooTable#145]
On page load my table is empty, then on a click event I am dynamically adding data to a table. When the table is loaded with records the data-page-size is not respected until I click on the header, then the table is reduced to 5 records. 
I am using $('#myTable').append(html); to load the data into the table.

**Comment by bradvin** [comment]
@bwyss you need to force footable to redraw:

$('#myTable').append(html).trigger('footable_redraw');

**Comment by ABIDImedali** [comment]
html not defined :/

**Comment by hilariogoes-cci** [comment]
Instead of html call this.html
So your line will be:
$('#myTable').append(this.html).trigger('footable_redraw');

**Comment by Shubhamnandwana18** [comment]
Hi @bwyss @steveush ,
I am trying to change page-size using an event, also tried to reinitialize table as given by @bradvin but still there are only 10 rows showing in the table although the number of entries is more than that. Pasting my code for reference, I would be pleased if someone could help.
I am using 
* FooTable - Awesome Responsive Tables
 * Version : 2.0.3
HTML (buttons)
====
<button type="button" data-page-size="10">10</button>
										<button type="button" data-page-size="20">20</button>
										<button type="button" data-page-size="50">50</button>
										<button type="button" data-page-size="100">100</button>

js
===
$('[data-page-size]').on('click', function(e){
						e.preventDefault();
						var newSize = $(this).data('pageSize');
						$("#fooTable").attr("data-page-size",newSize);
						console.log($("#fooTable").attr("data-page-size"));
						$('#fooTable').append(this.html).trigger('footable_redraw');
					});
console.log prints the correct value which is clicked.
Please reply ASAP.
Thanks
