### ISSUE TITLE
Use data attribute to disable moving column into the "detail-inner" div.

### ISSUE THREAD

**Issue by bgallagh3r** [fooplugins/FooTable#15]
Love to see another attribute flag to disable footable from adding a column to the details div when it shrinks, it's not really a great option in my opinion since all data in the table should be relevant, but for instance we have form buttons in the last column of a table to allow the user to edit/delete an entry, that may not be needed in mobile.

**Comment by steveush** [comment]
Hi bgallagh3r,

You should be able to achieve this by using the attribute data-ignore="true". FooTable should ignore the column when creating the detail view.

Thanks
Steve

**Comment by bgallagh3r** [comment]
Thanks, the documentation isn't really clear on the data-attributes that 
can/should be used with footables, thanks for the heads up.

steveush wrote:

**Comment by steveush** [comment]
No problem, I'll add in some more details on all the data- attributes available in the plugin and there specific functions, I just took a look at the readme now and it seems like I didn't go into much/any detail the first time through ;)

**Comment by steveush** [comment]
Apologies for the long delay, I ran into some hardware issues and have just put together a new PC, but on the bright side I have also just updated the README.md to include some more info on the supported data- attributes and there usage.

Thanks
Steve
