### ISSUE TITLE
Multiple Tables

### ISSUE THREAD

**Issue by DustyCarr** [fooplugins/FooTable#150]
When I add more than one FooTable to a page, the last table remains sortable but the other tables won't sort. Any idea what could be causing this?

Thanks,
Dusty Carr

**Comment by bradvin** [comment]
@DustyCarr not sure what the cause could be - check out the multiple-showcases.htm demo - that has 2 tables with sorting on it. If you can reproduce the issue on jsfiddle or codepen that would be really helpful thanks

**Comment by DustyCarr** [comment]
Upgrading to the latest release solved this issue. Thanks!
