### ISSUE TITLE
Footable + data-binding frameworks (angular)

### ISSUE THREAD

**Issue by dtheodor** [fooplugins/FooTable#151]
Hi,

I am trying to make Footable work with AngularJS. When table cell values are bound to a model (the `$scope` in Angular), I am having issues when table cells are moved to detail rows and back.

The particular problem I think lies with how Footable creates a detail row:  the columns are hidden (`display:none`), and the html of the table cell is _copied_ to the newly created detail row (seen at https://github.com/bradvin/FooTable/blob/V2/js/footable.js#L729). This does not work at all with data-binding, as Angular still binds to the element in the hidden column.

There are two ways around this:
1. A framework specific solution: pick up the `'footable_row_detail_updated'` event, then do framework specific stuff to get the data-binding up and running in the newly created element.
2. A framework agnostic solution: instead of re-creating the cell's content, [**move**](http://api.jquery.com/append/) the element to the detail row. When the table is expanded again and the detail row is destroyed, move the element back to the previously hidden column.

I think solution 2 is the way to go as it would make Footable more friendly to frameworks. However I am not sure if it would break any other functionality. It would also require to build a proper mechanism to 'restore' hidden columns, right now as far as I can tell the whole table is just redrawn.

Is there interest or comments for something like this? I'd be willing to attempt a pull request.

**Comment by bradvin** [comment]
@dtheodor This is definitely something I am interested in. I want FooTable to work with most, if not all, frameworks. Seeing as AngularJS has such a big following, I would like FooTable to work with it out of the box. 

I agree with you : # 2 seems a better choice. If you would be willing to branch and work on this, I will help out where I can, although my AngularJS experience is very limited

thanks!

**Comment by zurie** [comment]
Now that angular 1.2.x is out, this is the perfect time to do this.  I would like to see this request started.

**Comment by angleman** [comment]
:+1:

**Comment by bradvin** [comment]
we have started the V3 rewrite and this is going to be a top priority - please be patient, as we are rewriting the plugin from the ground up

**Comment by ewagnerdesign** [comment]
Couldn't get footable to work in my Angular app.  Found that adding a timeout fixes the problem!

setTimeout(function(){  
                $('table').footable({
                    breakpoints: {
                        phone:480,
                        tablet:680
                    }
                });
            }, 5000);

**Comment by pisakec** [comment]
ewagnerdesign, it works ...thanks

**Comment by dafinley** [comment]
I created a FooTable AngularJS V3 plugin/directive in case you wanted to check it out http://dafinley.github.io/FooTable/#/
