### ISSUE TITLE
Pagination question

### ISSUE THREAD

**Issue by DustyCarr** [fooplugins/FooTable#152]
Is there currently a way to limit the number of pagination links? If not, is this something you would consider building in to the next release? BTW, I love FooTable! 

Thanks

**Comment by xziler8** [comment]
Or simply show only the 2 page links before and after with a .... until the
last or first page.

A

On Mon, Oct 14, 2013 at 4:34 PM, DustyCarr notifications@github.com wrote:

> Is there currently a way to limit the number of pagination links? If no,t
> is this something you would consider building in to the next release? BTW,
> I love FooTable!
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/152
> .

## 

Thanks,

Alan

**Comment by bradvin** [comment]
@DustyCarr this has been asked for quite a bit. I think I will add an option to the pagination add-on to limit the number of pages shown

**Comment by xziler8** [comment]
Once page limit is implemented will it behave like so...

<<   |   <   |   7   |   8   |   9   |   10   |   11   |   >   |   >>

??

**Comment by felleuch** [comment]
waiting  this enhancement .... :-)

**Comment by syedaliaziz** [comment]
+10 for page limit

please implement this - it's pretty much standard is pagging controls.

Thanks.

**Comment by steveush** [comment]
Hi,

I have checked in a limiter for the paging controls. Check out the paging.htm demo to see it working.

Thanks
Steve
