### ISSUE TITLE
Sorting strings case-sensitive

### ISSUE THREAD

**Issue by bfj05021** [fooplugins/FooTable#153]
The sorting feature of FooTable is case-sensitive. Example:

Strings = {michael, Steve, Richard, john, thomas} would be sorted in the following way:

{ Richard, Steve, john, michael, thomas} where it should be 
{ john, michael, Richard, Steve, thomas}.

**Comment by JeganGitHub** [comment]
We have found the same issue and fixed it as

sorters: {
            alpha: function (a, b) {
                var aLower = a.toLowerCase();
                var bLower = b.toLowerCase();
                if (aLower === bLower) return 0;
                if (aLower < bLower) return -1;
                return 1;
            },
            numeric: function (a, b) {
                return a - b;
            }
        },

**Comment by steveush** [comment]
Hi,

I've added @JeganGitHub's suggestion as the default alpha sorter now, thanks Jegan :) This should no longer be an issue that requires a custom sorter.

Thanks
Steve
