### ISSUE TITLE
+ and - sign not visible in latest version

### ISSUE THREAD

**Issue by Allmedialab** [fooplugins/FooTable#154]
Hi,

Thanks! I love your plugin!

I downloaded the latest version and instead of the + and  - signs I see Chinese signs.

This is in the demo's.  But unfortunately also in my design.

How do I get the + and - back for the mobile view for opening and closing the hidden  tables!?

David

**Comment by bradvin** [comment]
hey David,

What browser are you using?

**Comment by Allmedialab** [comment]
Hi Bradvin,

I'm using all browsers for testing.

Can you please point me out where the links are for plus.png or minus.png!? 

Even the search function in my IDE can't find them.

Then I can fix the problem my self.

Thanks! David

**Comment by bradvin** [comment]
@Allmedialab there are no images for the plus and minus - they are in a font now as of V2

**Comment by Allmedialab** [comment]
Yes I discovered that, I was confused because both PNG's are in the demo in the img folder.

Found it! 

I downloaded the ZIP again and now it works perfect! 

Thanks! David
