### ISSUE TITLE
Performanse in more data

### ISSUE THREAD

**Issue by carlinchisart** [fooplugins/FooTable#155]
Hi all, 

I use footable is a gread solution!!, my question is i have one table with mora that  1500 item so 1500 rows, i construct the table with php, but with footable, i have problem in load the table and the browser is brokend. so i have one problem with performance of the publing, this is the url 

http://developer.hombresolo.com/inventario/administracionproductos/administrar_productos

is posible problem with jquery 2.0? or bootstrap 3?? 

Thanks

**Comment by ZainShaikh** [comment]
Any update on this?
