### ISSUE TITLE
Pagination div outside the table

### ISSUE THREAD

**Issue by celiovasconcelos** [fooplugins/FooTable#159]
According the doc i can have the pagination div outside the table http://fooplugins.com/footable/demos/paging.htm#docs
The doc says the pagination is binded through the data-page-navigation attribute.
I couldn't set it up.
Is this a bug?

**Comment by steveush** [comment]
Hi,

I've checked in a fix for this issue. It was performing a check that needed a tweak that was causing it to exit early and not create the pagination control if it was outside of a table.

Thanks
Steve
