### ISSUE TITLE
Filtering: Any way to hide duplicates within a given column?

### ISSUE THREAD

**Issue by xziler8** [fooplugins/FooTable#161]

**Comment by mspanish** [comment]
You could use something like lodash or underscore to find the dups, then use a jQuery hide() function to hide those rows. If you need a code example post back, would just take me a few mins to make an example.

**Comment by xziler8** [comment]
Thanks Stacey -- please elaborate in a JS fiddle...

:)

On Thu, Nov 7, 2013 at 4:36 PM, Stacey Reiman notifications@github.comwrote:

> You could use something like lodash or underscore to find the dups, then
> use a jQuery hide() function to hide those rows. If you need a code example
> post back, would just take me a few mins to make an example.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/161#issuecomment-28008843
> .

## 

Thanks,

Alan

**Comment by mspanish** [comment]
ah I was just going to search for my repo where I do something similar, may not have time for a riddle right now :)  I'll try to post back later today...

**Comment by steveush** [comment]
Hi,

This is currently not possible with the out of the box solution, this will require a custom one implemented on your side to depending on your situation.

Thanks
Steve
