### ISSUE TITLE
Showing only on Phone

### ISSUE THREAD

**Issue by notflip** [fooplugins/FooTable#164]
Hi, is it possible to SHOW a certain row only on phone? 

Thank you!

**Comment by notflip** [comment]
Solved it by adding an breakpoint set on infinite,

``` javascript
breakpoints: {
   infinite: 9999
}
```

**Comment by steveush** [comment]
Hi,

There is a default breakpoint called desktop which is added to the breakpoints. You could use this in the data-hide attribute the same way you use tablet or phone. So data-hide="desktop,tablet" should show the column only on a phone.

Thanks
Steve
