### ISSUE TITLE
FooTable Customized Breakpoints Not Working

### ISSUE THREAD

**Issue by khloukrada** [fooplugins/FooTable#165]
In the document, it says "To change the breakpoints simply pass in a breakpoints option when initializing FooTable:".

$('.footable').footable({
    breakpoints: {
        tiny: 100,
        medium: 555,
        big: 2048
    }
});

But it's not working when I apply the customized breakpoints on the data-hide attribute.

**Comment by apaleslimghost** [comment]
Bear in mind that the breakpoints are for the width of the _table_, not the viewport like media queries. To use the viewport width, pass the following option:

``` javascript
calculateWidthOverride: function() {
  return {width: $(window).width()};
}
```

**Comment by khloukrada** [comment]
Many thanks. I got it now.

**Comment by bradvin** [comment]
@quarterto thanks for posting this solution

**Comment by asier-laukoa** [comment]
Where do I have to pass this option?

Just like this?

<code>
$('.footable').footable({
calculateWidthOverride: function() {
    return {width: $(window).width()};
},
breakpoints: {
    tiny: 100,
    medium: 555,
    big: 2048
}
});
</code>

Thanks a lot!

**Comment by apaleslimghost** [comment]
@asier-laukoa yep, that should work.

**Comment by juanserrats** [comment]
@quarterto Thanks! You=idol, me=grateful.

**Comment by ghost** [comment]
$('.footable').footable({ calculateWidthOverride: function() { return {width: $(window).width()}; }, breakpoints: { tiny: 100, medium: 555, big: 2048 } }); 
workd just in html type, can anyone help me out ?
