### ISSUE TITLE
Is there a programatic way to detach and reattach pagination for table printing?

### ISSUE THREAD

**Issue by xziler8** [fooplugins/FooTable#166]

**Comment by steveush** [comment]
Hi,

Sorry there is not. Your best bet is to include a little CSS rule to hide the pagination when printing as per this [SO link](http://stackoverflow.com/questions/12218189/hide-html-div-when-printing-page).

So something like this should work assuming the default pagination class is being used.

``` HTML
<style type="text/css" media="print">
.pagination { display: none; }
</style>
```

Thanks
Steve
