### ISSUE TITLE
Retrieve row id from footable_row_expanded event

### ISSUE THREAD

**Issue by hugsbrugs** [fooplugins/FooTable#168]
Hi,

I've added 

```
<tr id="my_id">
```

I need to retrieve row id inside footable_row_expanded event but as I see it's the hole footable witch is the clicked element and not a particular row.

Could you give me a way of doing this since I'm instanciating elements inside hidden rows based on row's id

thanks

Hugo

**Comment by steveush** [comment]
Hi,

You can use the e.ft.row property of the footable_row_expanded event object to get whatever you may need.

``` javascript
$('.footable').bind('footable_row_expanded', function(e){
  var id = $(e.ft.row).attr('id');
});
```

**Comment by hugsbrugs** [comment]
Many Thanks !

EDIT : 
it doesn't work, I get an undefined id and when doing : 

```
var id = $(e.ft.row).attr('id');
alert(JSON.stringify($(e.ft.row)));
```

I get {} as answer for the object $(e.ft.row) 

Still no luck !

EDIT 2 : 
I found my tr id this way : 

```
var trID = $('.footable-detail-show').attr('id');
```

**Comment by XanderT** [comment]
I realize this is an old post. But I am strugling with the same issue.
None of the above examples gives me more than "undefined"

$('#CustOrderTab').bind('footable_row_expanded', function(e){
  var id = $(e).attr('id');
  console.log('Row click: ' + id + ' | ' + JSON.stringify(id));
});

any other ideas :) ?
