### ISSUE TITLE
pagination (group/minimize page numbers) - page limit required

### ISSUE THREAD

**Issue by syedaliaziz** [fooplugins/FooTable#170]
First of all thanks for the awesome FooTable. :)

I am using pagination, but the is an issue (no page limit):

![pagging too much page numbers](https://f.cloud.github.com/assets/5800988/1652466/97047efa-5b14-11e3-9218-6bd8d7ad27a4.png)
- I have too much data for a record and after pagination the view is like this (attached above), what i want here is to show these page like

<<   <   1   2   3   4   5   ...   >   >>

and when i click "..." it show the next 5 pages from 6 all the way through 10 (it's pretty much standard in most pagging controls).

Please help me in this regards, how can i achieve this. Many Thanks!

**Comment by syedaliaziz** [comment]
![sample pagination limit](https://f.cloud.github.com/assets/5800988/1654310/0e185776-5b49-11e3-8baa-123b451092b0.jpg)

just like the above sample.

Kindly look into this - it's a really important feature. :)

**Comment by xziler8** [comment]
better yet --- show First and Last icon, prev and next icons within, then
show 5 pages with  "..." before or after the 5 pages as necessary. So when
on page 5 show,

<<       <       ... 3        4       5       6       7 ...        >


Thanks

A

On Mon, Dec 2, 2013 at 6:59 AM, Syed Ali Aziz notifications@github.comwrote:

> [image: sample pagination limit]https://f.cloud.github.com/assets/5800988/1654310/0e185776-5b49-11e3-8baa-123b451092b0.jpg
> 
> just like the above sample.
> 
> Kindly look into this - it's a really important feature. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/170#issuecomment-29612340
> .

## 

Thanks,

Alan

**Comment by syedaliaziz** [comment]
:+1: 

@bradvin please consider this request - request/issue of such is already opened..

**Comment by syedaliaziz** [comment]
@bradvin  please respond?  Its important!!

**Comment by syedaliaziz** [comment]
@xziler8  have you found any means to do it?

**Comment by syedaliaziz** [comment]
@steveush  @bradvin  please respond?  Its important!!

**Comment by bradvin** [comment]
@syedaliaziz if you need it so badly then submit a pull request and I will include it. Both steve and I have been very busy on other projects and have not had time to make changes to FooTable in a while. This is a free library. You do not pay for it, so you cannot demand that we make changes when it suits you

**Comment by steveush** [comment]
I've checked in some changes to the pagination plugin which allows these features. Check the demo paging.htm to see it. Basically a new option called limitNavigation which you can set to the number of pages you want displayed in the pagination navigation control.

Thanks
Steve
