### ISSUE TITLE
Form Drop Select paging not working - Demo

### ISSUE THREAD

**Issue by starboy-zz** [fooplugins/FooTable#171]
When FooTable is downloaded there is a page in its directory called paging.htm (see: FooTable-2/demos/paging.htm). That page has a form drop select to allow users to select/adjust the paging size of the table but the problem is that it does not work.

How to get the form drop select paging to work?

**Comment by steveush** [comment]
Hi,

I have checked in a fix for this issue. There was a small bug in the paging addon where it cached it's options and never reset them when reiniting.

Thanks
Steve
