### ISSUE TITLE
Feature request:  fixed column headers

### ISSUE THREAD

**Issue by drmcclelland** [fooplugins/FooTable#174]
A nice feature for FooTable would be to have built-in support for fixed column headers so as the user scrolls down a long page they don't lose track of what columns they are looking at.  In order to have "fixed" or "sticky" column headers, I am using StickyTableHeaders (https://github.com/jmosbech/StickyTableHeaders) after FooTable has initialized.  It works great, the only thing you have to keep in mind is that the background-color of the <thead> needs to be set to something like #fff so it doesn't look transparent.  Also, in my case I'm using a Bootstrap 3 navbar, so I have to take the height of that into account:

```
    // Enable the sticky table headers after the call to .footable();
    var offset = $('.navbar').height();
    $('#myDataTable').stickyTableHeaders({ fixedOffset: offset });
```

**Comment by imjoeybrennan** [comment]
+1

**Comment by steveush** [comment]
Hi,

I'll flag this as an enhancement however due to limited time to spend on this project I'm not sure when we can get around to implementing it.

Thanks
Steve

**Comment by cristianoisaac** [comment]
+1! This is exactly what I need. Don't need the StickyTableHeader, but I need a header that doesn't overflow and I don't like the PAGINATION when using mobile. Just need a FIXED header with the FooTable.

**Comment by ShujaatKagathra** [comment]
- 1 !
  We are using FooTable along with stickyTableHeaders and it works great from http://tablesorter.com, yet it will become much more flexible if stickyTableheaders is integrated into Footable

Thanks !

**Comment by cjaacks** [comment]
I used successfully http://mkoryak.github.io/floatThead/ with FooTable for that, works fine. (The script must be loaded before FooTable).

**Comment by rails-hub** [comment]
+1

**Comment by ShujaatKagathra** [comment]
Thankyou Carlos Augusto Jaacks
floatThread is nice plugin to use with footable !
