### ISSUE TITLE
Arrange footable-row-detail on TOP of row-details-show

### ISSUE THREAD

**Issue by imjoeybrennan** [fooplugins/FooTable#175]
Does anyone know how to rearrange/flip the rows so the footable-row-details are on top and the row-details-show is on bottom as seen in this screenshot below. 
![screen shot 2013-12-12 at 10 25 59 am](https://f.cloud.github.com/assets/1739106/1734701/3df9f68a-634a-11e3-90c9-9527ff17f8b8.png)

It would be awesome if this option was added. My idea is to create a mobile table layout similar to Yahoo's Fantasy  Football app design as seen below. The footable-row-details would become the main information which would be fixed and the details would be the row-details-show would would scroll horizontally. 
![yahoofantasyfootball](https://f.cloud.github.com/assets/1739106/1734767/4671bd06-634b-11e3-9835-dff62240c0c0.png)

Please let me know if anyone can help do this row flip! Would be a great option for the plugin.

**Comment by steveush** [comment]
Hi,

At present there is no option to flip the detail rows, there is a lot of logic that relies on it being below the normal row. I'll flag this as an enhancement however due to limited time to spend on this project I'm not sure when we can get around to implementing it.

Thanks
Steve
