### ISSUE TITLE
Disable Toggle functionality so both rows are always visible.

### ISSUE THREAD

**Issue by imjoeybrennan** [fooplugins/FooTable#176]
Is there a way to disable the toggle-visibility button and have both of the rows of details visible? I feel like this would be a great option for this plugin because if vertical space wasn't an issue, then it would be easier if users didn't have to hit a button to see all the details.

Let me know if you can help!

**Comment by steveush** [comment]
Hi,

At present there is no option to disable the toggling of rows, I'll flag this as an enhancement however due to limited time to spend on this project I'm not sure when we can get around to implementing it.

Thanks
Steve

**Comment by pavelbeliaev** [comment]
Hi,

That would be cool. 
After a review of several plugins that liked most. It allows you to selectively move columns in `footable-row-detail` depending on the width of the screen. But the need to click every time that is not what I want. Is there an elegant way to get around and make `footable-row-detail` visible by default?

Thanks.

**Comment by diegocanal** [comment]
Hi,
One more vote for this. Either having the option to "disable the toggle-visibility button and have both of the rows of details visible", as @imjoeybrennan proposed, OR simply having an option to set all the toggles expanded by default (having the possibility to collapse them)  OR adding a new data attribute to selectively expand by default some of the toggles.

Thanks for such a great plugin!
Diego
