### ISSUE TITLE
Duplicate element id when expanding row

### ISSUE THREAD

**Issue by hugsbrugs** [fooplugins/FooTable#177]
Hi,

I'm using footable to be able to modify a bunch a data using x-editable plugin.

One of my columns looks like : 

```
<td id='td_deg_coul_<?= $DID ?>'><span class='deg_coul' id='deg_coul_<?=$DID?>' data-type="select2" data-title='Update Color' data-value='Red'></span></td>
```

As I get lots of datas, I would be able to instantiate x-editable elements based on their id (so only the current expanded row would have its elements updatable).
The problem is that footable makes a copy of my element so I have 2 elements with same id in DOM which is not cool !

I can't find where in footable.js the copy is made. I'd like to just add a prefix to the copied element id so it would be unique and I could instanciate it correctly.

Thanks for any suggestions.

**Comment by bradvin** [comment]
A lot of people have this same issue. The fact that we clone the contents of the cell cause a lot of issues when you do anything slightly complex. 

These are my thoughts on this enhancement so far:
1. Determine if a cell contains any elements. If it is plain text, then simply clone as before and do nothing else.
2. create a placeholder div with a unique id
3. Wrap the cell elements in a container div and add a data attribute which is the placeholder id above
4. Move the container div created above to the new row
5. Insert the placeholder div into the cell

@steveush what do you think?

**Comment by judebowman** [comment]
I have the same issue.  My solution may not be the best (and I would love to hear what others think is a better approach), but I added a data- attribute to the editable control (span in my case) and on the "on success event handler" i call code that looks like this:

publicProperties.ProcessNumberExpectedChange = function (control, newValue) {
        var partyId = control.data('partyid');
        $("[data-partyid='" + partyId + "']").each(function () {
            $(this).text(newValue);  
        });
    }

**Comment by guymaness2** [comment]
I am having this same issue. Has it been addressed yet? Perhaps you could pull off something like storing the original element's parent node name and index in a custom attribute of the clone, then blow away the original when the clone is created. Then, if the screen is expanded again, pull the needed original info from the clone, recreate the original and blow away the clone. I like the idea of cloning, keeping the same id and info, as it keeps a .NET GridView working well. Just need to find a way to only have one of them on the page at a time.
