### ISSUE TITLE
Pagination page size change only triggering on sort.

### ISSUE THREAD

**Issue by ultraflash** [fooplugins/FooTable#178]
I used the recent fixes and commits for the addition of a combo box to change pagination size however, the size change only seems to happen when I click on a column header to sort the table. 

Is it possible to have the new page size change as soon as the option is selected in the combo box or to add a button to do it?

Is this correct or have I screwed something up and it isn't changing properly?

**Comment by wesleyem** [comment]
In the docs for FooTable this is kind of touched on. If you force the table to be redrawn after you change the page size it will make the changes, however, if you are using paging this will break it.

```
$('.do_something').click(function(e) {
    e.preventDefault();
    $('.footable').trigger('footable_redraw'); //force a redraw
});
```
