### ISSUE TITLE
ajax updated data insert at top of table not the end

### ISSUE THREAD

**Issue by imanviii** [fooplugins/FooTable#179]
Hi all
Recently i saw ajax demo at (http://fooplugins.com/footable-demos/) and have a question to ask.
Is there any way to insert new data at the top of table instead of the end?
in this way the users could see new data without going to the last page of table.

**Comment by xziler8** [comment]
should be able to use .insertBefore JS.

A

On Thu, Dec 26, 2013 at 1:02 PM, imax36581 notifications@github.com wrote:

> Hi all
> Recently i saw ajax demo at (http://fooplugins.com/footable-demos/) and
> have a question to ask.
> Is there any way to insert new data at the top of table instead of the end?
> in this way the users could see new data without going to the last page of
> table.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/179
> .

## 

Thanks,

Alan
