### ISSUE TITLE
Redraw function is cleaning my table.

### ISSUE THREAD

**Issue by lusabo** [fooplugins/FooTable#180]
I have a table like this:

&lt;table id="modality" class="table table-hover footable"&gt;
    &lt;thead&gt;
        &lt;tr&gt;
            &lt;th width="40%"&gt;Modality&lt;/th&gt;
            &lt;th width="30%"&gt;A&lt;/th&gt;
            &lt;th width="30%"&gt;B&lt;/th&gt;
        &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;&lt;/tbody&gt;
&lt;/table>

And the script is:

$(function(e) {

```
var footable = $('#modality').footable().data('footable');

$.ajax({
    url : 'api/modality',
    dataType : 'json',
    success : function(result) {
        $.each(result, function(idx, obj) {
            var row = '<tr>';
            $.each(obj, function(key, value) {
                if (key != 'id') {
                    row += '<td>' + value + '</td>';
                }
            });
            row += '<td>Edit</td>';
            row += '<td>Remove</td>';
            row += '</tr>';
            footable.appendRow(row);
        });
        footable.redraw();
    }
});
```

});

The JSON returned by ajax call is:

[ {
  "id" : 30,
  "name" : "Corrida"
}, {
  "id" : 31,
  "name" : "Mountain Bike"
} ]

I have the same situation in another page and works well! :(

**Comment by lusabo** [comment]
When I change &lt;th&gt; to &lt;td&gt; on thead area it works well.

**Comment by theoarena** [comment]
That's happening here too. Changing th to td works but it stops the sorting feature!! I dont know what to do

**Comment by theoarena** [comment]
I reloaded the table using $('.footable').footable() rather than footable.redraw(); and it worked for me!

**Comment by bradvin** [comment]
please put up and example of this code on jsfiddle or codepen so I can see what is going on

**Comment by theoarena** [comment]
I can't get this working right now, but here it is http://jsfiddle.net/theoarena/vfk8z/1/

**Comment by bradvin** [comment]
@lusabo @theoarena I managed to reproduce the issue and fixed it in commit : https://github.com/bradvin/FooTable/commit/8f6adfec5c102de89ef162fe1b931cedb00fca72

**Comment by theoarena** [comment]
Thanks man! it's working now

2014/1/4 bradvin notifications@github.com

**Comment by lusabo** [comment]
Thanks @bradvin! Here it's working too.
