### ISSUE TITLE
add min version for footable core

### ISSUE THREAD

**Issue by SiteSplat** [fooplugins/FooTable#182]
Is there a way you could include the min version for the core? Or could you suggest a tool that will not break the plugin?
Thanks!

**Comment by bradvin** [comment]
@SiteSplat I am not sure I follow you. Are you talking about a min jquery version? Or a min version of the core for the add-ons?

**Comment by SiteSplat** [comment]
Hi I meant the footable.js file. I noticed there is no min version included and I'm afraid about the outcome of using a online tool to minify it myself.
Thanks!

**Comment by bradvin** [comment]
@SiteSplat oh haha! check out the dist folder for the minified versions https://github.com/bradvin/FooTable/tree/V2/dist
