### ISSUE TITLE
Different background color for odd and even rows

### ISSUE THREAD

**Issue by goten4** [fooplugins/FooTable#183]
Hello,

Thanks for this great plugin !
I wonder how to manage different background color for odd and even rows ...
If I specify odd or even class on each &lt;tr&gt;, it will be mixed up after sorting the table.
If I use nth-child(odd/even) CSS pseudo class, it will fail on responsive because of the creation of new row ...
Do you have an idea on how to do that ?

Thanks

**Comment by bradvin** [comment]
@goten4 check out the striping add on : https://github.com/bradvin/FooTable/blob/V2/js/footable.striping.js

That adds classes to the table rows that you can then style in your CSS

**Comment by goten4** [comment]
Hi,
It works, thank you very much :)
