### ISSUE TITLE
Iphone & Ipad Mini Performance

### ISSUE THREAD

**Issue by MartyBJones** [fooplugins/FooTable#187]
Let me start by saying that this pluggin is awesome!  I am using it in a responsive website and it works great on a normal pc browser.  I am for some reason having very long render times when loading a page with a table on my Iphone with ios7.  The table only has 50 rows in it but it is taking around 26 seconds to load!

If I comment out $('.footable').footable(); and reload the page then it loads instantly so I am pretty sure the time is being spent updating the table.

Also, I am using footable with bootstrap 3.

Here is a snippet of the table:

<table id="sample-table-1" class="table footable table-striped table-bordered table-hover toggle-circle">
<thead>
  <tr>
      <th>Test</th>
      <th>Test2</th>
      <th data-hide="phone">One</th>
      <th data-hide="phone">Two</th>
      <th data-hide="phone,tablet">Three</th>
      <th data-hide="phone,tablet">Four</th>
      <th data-hide="phone,tablet">Five</th>
      <th data-hide="phone,tablet">Six</th>
      <th data-hide="phone,tablet">Seven</th>
      <th data-hide="phone,tablet">Eight</th>
      <th data-hide="phone,tablet">Nine</th>
      <th data-hide="phone,tablet">Ten</th>
      <th data-hide="phone,tablet">Eleven</th>
  </tr>
</thead>
<tbody>
<tr>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
</tr>   
</tbody>
</table>

Any Ideas?

**Comment by MartyBJones** [comment]
I did some more testing and it ended up being a boostrap theme css file that was causing the issue when the table is updated.   I took off the "table-striped" attribute off of the table and the performance was much better.

**Comment by bradvin** [comment]
@MartyBJones thanks for letting me know what the cause was. Interesting that that could cause such bad performance. I need to reproduce this and see where things are getting degraded.

**Comment by MartyBJones** [comment]
I can send you a test case if you need it.

**Comment by bradvin** [comment]
@MartyBJones that would be very helpful thanks

**Comment by MartyBJones** [comment]
I will whip something up and send it to you.  I have another question, I
would like to combine several column values into the column that receives
the expander icon instead of pushing the values into the sub section.  How
hard do you think this would be?

Basically I want to show a few column values appended with <br/> so that
the user can see a few items in the table that are the most important that
will not fit in a phone environment.  I don't want them to have to expand
each row to see the most important data.

Hopefully this makes sense.

Thanks,

Marty
