### ISSUE TITLE
Table Footers

### ISSUE THREAD

**Issue by smockensturm** [fooplugins/FooTable#188]
I have a rather pressing need to include table footers in my FooTables. You know... a footer to hold sub-totals and grand totals and what not. (Bonus: there are several such tables on a page.)

A workaround might include some way to exclude entire rows (not columns) from sorting.

Any plans for supporting table footers? Or a workaround in the interim?

This is a great tool, by the way. Thank you.

**Comment by bradvin** [comment]
sorry for the extremely late response on this. I have tried adding a footer using a tfoot and that is ignored in the paging and the "collapsing" so that might work for you
