### ISSUE TITLE
Prevent Row from Toggling Hidden Rows

### ISSUE THREAD

**Issue by johndugan** [fooplugins/FooTable#189]
Is there a way to prevent the entire `<tr>` from toggling the hidden row and use only the footable-toggle `<span>`?

**Comment by bradvin** [comment]
@johndugan try using this HTML 

```
<tr class="footable-disabled">
```

as seen in this demo https://github.com/bradvin/FooTable/blob/V2/demos/data-attributes.htm

**Comment by ghost** [comment]
Hi Bradvin,

Thank you for great plugin.

I have test the code. But it is still expanding the hidden column details when we clicked on the table row.

As I understood, Johndugan want to expand hidden columns when clicked on the span with "Plus Sign" as attached image. So if we clicked on anywhere else in the row, the data of the hidden columns will not expand.

![screenshot from 2014-02-26 15 27 51](https://f.cloud.github.com/assets/6231803/2269536/6431494e-9edb-11e3-9ae3-6bbd340c2357.png)

Thanks.

**Comment by johndugan** [comment]
@ddulitha that is correct - this is my intention just as your picture illustrates.

@bradvin perhaps a new option could be created when calling the plugin to relegate the toggle functionality only to the toggle button?

The ability in my specific design to toggle hidden cells by clicking anywhere on the row is a bit confusing. I have a fairly "loud" toggle button. In the adjacent table cells are links. When a user _mistakenly_ clicks just outside of the link container and hits the table row, which then toggles the hidden cells, they question the functionality of the link (which they thought they clicked).

Love the plugin.

Regards,

john

**Comment by bradvin** [comment]
@johndugan there is an option called _toggleSelector_ which by default is set to

```
toggleSelector: ' > tbody > tr:not(.footable-row-detail)'
```

You can maybe use that together with

```
toggleHTMLElement: '<span />'
```

And add a class to that span which you can then target in the selector?

**Comment by GraphicShaun** [comment]
Look for the line that reads:
`'togleSelector: ' > tbody > tr:not(.footable-row-detail)',`

On my download, that was on line 36 of 'footable.js'

Change that value to: `' > tbody > tr > td > span.footable-toggle'` and I was able to accomplish expanding the row only via the toggle icon.

**Comment by jrswenson** [comment]
@GraphicShaun I did what you suggest and it changes the behavior like you suggest.  Thanks!

FYI: I was able to achieve the same thing with out changing the JS file by doing: 

$('.footable').footable({ toggleSelector: " > tbody > tr > td > span.footable-toggle" });

I got this method from the "Getting Started" demo.  In that demo, it describes how to change the breakpoints option.  I figured that would be the way to override any of the options.  @bradvin, could you confirm that is the correct way? (or suggested way?)

**Comment by efkan** [comment]
Hello,
@GraphicShaun, I'll use your option thank you. It's useful. 
@bradvin I think this information should be added on the Footable documantation.

Because if you should work on a desktop computer with a lot of columns, you might want to work with tables at row level.
So, you need @GraphicShaun's option. Or maybe a full column that has toggle icon. 

I'm using like that simply;

```
*when click a row mark as selected row*

/* Footable style */
.selected {
    background-color: #F9FBA2 !important;
}
.selected:hover {
    background-color: #F5F973 !important;
}
/* end of footable style */

$('.footable').footable();
$('.table tbody').on('click', 'tr', function(){ 
    var row = $(this);
    /* Mark as selected if the row is not a detail row */
    if(!row.hasClass('footable-row-detail')) {
        row.toggleClass('selected');
        row.attr("clickedat", new Date().valueOf());
    }
});

/* Put a delete button */
$("#rowDel").on("click", function() {   
        $('#footable>tbody>tr.selected').remove();
        $('#footable').trigger('footable_redraw')
}
```

And I've added 'new' and 'edit' buttons to. It became a very useful table for huge screens :)

Thanks guys, espically @bradvin...

I have a table contains 19 columns! 
I've used Footable together Bootstrap. `class="table table-hover footable"`
And this is an example;

![adsiz](https://cloud.githubusercontent.com/assets/6974198/5695160/7c85b258-999b-11e4-90d8-944ae44dcabc.png)

I can select multiple rows the below table, I can use filter for 19 columns, I can delete multiple rows and If I want I can see the details using Toggle Icon.

![image](https://cloud.githubusercontent.com/assets/6974198/5695178/51614eb4-999d-11e4-9070-f9e469130dab.png)

**Comment by GaryStanton** [comment]
FYI - In V3 of FooTables, the toggle target appears to have changed in the code.
I couldn't figure out how to override this without amending the actual JS (boooo!) but around line 1590 I found the _onToggle function and the following line:
`if ($(e.target).is('tr,td,.footable-toggle')){`

Change the target to update which elements trigger the toggling of the data, so for my needs I updated to:
`if ($(e.target).is('.footable-toggle')){`
and only the first column containing the plus symbol triggers the toggle.
