### ISSUE TITLE
How To Use Custom Expand/Collapse Icons

### ISSUE THREAD

**Issue by MartyBJones** [fooplugins/FooTable#190]
I would like to use bootstrap glyphicons or fontawesome icons for the expand and collapse icons.  How can I go about doing this?

**Comment by bradvin** [comment]
@MartyBJones you would need to edit the core footable css file and replace all the font-specific code with your font-awesome or similar CSS. The file to look at is : https://github.com/bradvin/FooTable/blob/V2/css/footable.core.css

**Comment by aboutaaron** [comment]
It'd be nice if you could just specify the class used for sorting. That way, rather than edit the core.css file, you could just include your preferred fonts and initialize footable with the correct classes.
