### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by MartyBJones** [fooplugins/FooTable#193]
Is there a way you can tell if footable has hidden any columns through an api call?  I want to programatically show or hide a "button" in the table header to allow users who have hidden columns to display a popup for sorting "all" available columns.  If the table fits in the viewport then I don't want to show the user the button.

The problem is I need to know if footable has "hidden" anything or not.

Any help would be appreciated.

Thanks

**Comment by bradvin** [comment]
@MartyBJones there are a few ways to check for this. You can either bind to an event (preferred) or check for the 'breakpoint' class on the table. To bind to the event, check out the code in this demo: https://github.com/bradvin/FooTable/blob/V2/demos/event-interception.htm

or you can do something like this:

```
$('#mytable').footable().bind({
            'footable_breakpoint': function (e) {
                        //do something here
            }
});



```
