### ISSUE TITLE
Not cloned data in rows, just copied, text inputs errors.

### ISSUE THREAD

**Issue by frogleon** [fooplugins/FooTable#194]
I need in some project put text inputs in rows but, in landscape/portrait mode it shows different data values, this is because, the node is copied not cloned, so i made some changes to this in "createDetail" function, maybe in other version you can include this as a feature.

element.append($('< div class="' + classes.detailInnerRow + '" >').append($('< div class="' + classes.detailInnerName + '">').html(groups[group].data[j].name+separator)).
append($('< div class="' + classes.detailInnerValue + '">').append(groups[group].data[j].display)));

also in "createOrUpdateDetailRow"  i changed "values.push", from this:
$.trim($(this).html())
to this:
$(this).find('p').clone()

I  put, the "p" tag, inside "td" for all rows, but, maybe can be solved with a data attribute to switch between both: clone, or copy.

**Comment by bradvin** [comment]
@frogleon thanks for the code - this is defintely something I want to change in the next version of FooTable.

I think I am going to start a dev branch and work on this

**Comment by minroo** [comment]
Thanks for the awesome FooTable. Made few changes and added the documentation to make it work for form Input fields. I believe it will also handle the dynamic column data
https://github.com/bradvin/FooTable/pull/285

**Comment by kyleshevlin** [comment]
Has this issue been solved? Is there an option I am missing? Some of my table cells had links in them, but V3 seems to be stripping an html I had inside my original `td`. This was working fine in V2. Haven't found anything in the docs yet.
