### ISSUE TITLE
Filtering for multiple tables on same page

### ISSUE THREAD

**Issue by Flankerator** [fooplugins/FooTable#196]
Great plugin guys, thanks for the hard work!

I've given it a go and tried to find a similar issue that could have been posted over here, also checked the documentation but to no avail.

I'm having multiple tables nested under tabs in WordPress (using the Footable WP plugin by the way ver 0.3.1), I can't get the filtering function to work on all tables, in fact, it does on the first table only. The filtering text area does show on all tables but actually works on the first table only when you type in something. Any help would be appreciated. 

I've posted the same @ WordPress.org in the plugin support section.

**Comment by bradvin** [comment]
@Flankerator pls post the url to your page so I can check it out

**Comment by Flankerator** [comment]
Thanks for the quick reply Brad!
Unfortunately, the site I'm working on (sa-sim.com) is a work in progress currently (viewable by admins only) and I do not have permission to turn it on until it's 100% finished, but I can provide you with any sort of code if you tell me what you need to see.

**Comment by Flankerator** [comment]
Debug Information on the plugin settings page below. Maybe this will help?

Javascript:

/\* FooTable init code */

var $FOOTABLE = $FOOTABLE || {};
(function( $FOOTABLE, $, undefined ) {

```
jQuery.fn.attrAppendWithComma=function(a,b){var c;return this.each(function(){c=$(this),void 0!==c.attr(a)&&""!=c.attr(a)?c.attr(a,c.attr(a)+","+b):c.attr(a,b)})};jQuery.fn.footableAttr=function(a,b){return this.each(function(){var c=$(this);c.data("auto-columns")!==!1&&(c.find("thead th:gt("+a+")").attrAppendWithComma("data-hide","tablet"),c.find("thead th:gt("+b+")").attrAppendWithComma("data-hide","phone"))})},jQuery.fn.footableFilter=function(a){return this.each(function(){var b=$(this);b.data("filter")||b.data("filter")===!1||b.data("filter-text-only","true").before('<div class="footable-filter-container"><input placeholder="'+a+'" style="float:left" type="text" class="footable-filter" /></div>')})},jQuery.fn.footablePager=function(){return this.each(function(){var a=$(this);if(a.data("page")!==!1){var b=$('<tfoot class="hide-if-no-paging"><tr><td><div class="pagination pagination-centered"></div></td></tr></tfoot>');b.find("td").attr("colspan",a.find("thead th").length),a.find("tbody:last").after(b)}})};

$FOOTABLE.init = function() {
    $(".footable, .footable-demo")
        .footableAttr(3,1)
        .footableFilter("search")
        .footablePager()
        .footable( { breakpoints: { phone: 320, tablet: 768 } });

};
```

}( $FOOTABLE, jQuery ));

jQuery(function($) {
    $FOOTABLE.init();
});

Settings:

Array
(
    [selector] => .footable
    [enable_filtering] => on
    [enable_pagination] => on
    [breakpoint_tablet] => 768
    [breakpoint_phone] => 320
    [columns_tablet] => 4
    [columns_phone] => 2
    [theme] => metro
    [custom_css] => 
    [custom_js_before] => 
    [custom_js_after] => 
    [enable_debug] => on
)

**Comment by bradvin** [comment]
@Flankerator thanks for posting that info - there seems to be a bug in the jquery code I added to the WP version to auto-add a filter textbox to the footable. That code is unique to the WP plugin so I will need to update it there

**Comment by Flankerator** [comment]
Hey Brad,  FYI- I have also tried the Footable jquery plugin  thinking that the issue was affecting the WP version of the plugin only...well I ended up with the same issue again and since people are not reporting it, I started suspecting a conflict with the WP tabs plugin as I'm calling Footable within the tabs.

On another hand, I saw the demo of the multiple Footable working fine, so that MUST be something related either to the tabs plugin or the bug you detected. Waiting for your update with my finger crossed. Any thoughts, let me know please. Thanks again.

**Comment by adaptifyDesigns** [comment]
Hi, I am also unable to use footable twice on the same page when nesting the tables inside of tabs. 

I am using [Responsive Tabs](https://github.com/jellekralt/Responsive-Tabs) js, with a separate table in each tab. Only the first table is selected by footable.

I am also developing on Wordpress, using the jQuery plugin (not the WP plugin). Using jQuery 1.10.2

Any progress on this issue?

Thanks!

**Comment by Flankerator** [comment]
Hello,
I'm still waiting for an update as well. WP-wise, it is still v0.3.1. I hope this great plugin wil get some love soon.

**Comment by ghost** [comment]
Hi Brad,
I experience the same problem as Flankerator.
I see you haven't updated the WP plugin in over two years.
Is there any chance that you could help me out with the filtering problem, or update the WP plugin (in the near future) or at least give me some hint on where to look ?
Thanks.
Great work BTW.
