### ISSUE TITLE
No thead tag

### ISSUE THREAD

**Issue by bkehren** [fooplugins/FooTable#197]
New to the FooTable project and so far enjoying it.  Wonder what I might need to modify to make this work with a table structure that does not have the < th > tags in a < thead > tag.

**Comment by bradvin** [comment]
@bkehren there may be too much to change to get that working. One of the features I want to add is the ability to define the columns in options rather than reading them from the thead - that could work for you, but that will be a while still, unless someone does a pull request :)

**Comment by bkehren** [comment]
Thanks @bradvin.  I am working with a standard asp.net gridview and found there is way to toggle the  < th > tags to be rendered in a < thead >.  Take a look at this Stackoverflow article: http://stackoverflow.com/questions/309101/how-do-i-get-gridview-to-render-thead
