### ISSUE TITLE
On select some of the content does not show up 

### ISSUE THREAD

**Issue by justawebbie** [fooplugins/FooTable#198]
I am using the example and just replaced and deleted a few things but the select option does not work for me except on one selection.  I am learning this and working on this for a student project.  If I select Occupational endorsements nothing shows up in the filtered table but if I select Post-baccalurate licensures one thing does show up which is correct. Please let me know what I did wrong in this html.

http://www.uaf.edu/catalog/catalog_13-14/majors-test-occ.html

**Comment by bradvin** [comment]
@justawebbie the values you are using in your filter select are not matching up to the data-value's in the table column for the degree type. For example, change the value of the licensure option to be "5" rather than "licensure". Or make sure the data-value values in the columns are "licensure"

**Comment by justawebbie** [comment]
I tried changing what I thought you were suggesting and it still does not work for me. I am still not getting what I expect but an empty page. Thank you for trying to help out even if I evidently do not understand it seems.
