### ISSUE TITLE
The sorting arrow is misplaced in latest Firefox (Windows)

### ISSUE THREAD

**Issue by cocinerox** [fooplugins/FooTable#2]
Could you check it? Thanks.
BTW superb effort!

**Comment by bradvin** [comment]
thanks for the heads up - i will look into now - probably just a css issue

**Comment by bradvin** [comment]
this has been fixed. I also made the arrow images into a sprite and added a new image for a "sortable" state so you can easily see which columns you are able to sort

**Comment by cocinerox** [comment]
Works as expected, thanks!
However, I'd suggest to replace Line 51 in footable.sortable.js with

``` javascript
if ($th.find('> span.'+cls.indicator).length == 0) {
    $('<span />').addClass(cls.indicator).appendTo($th);
}
```

to prevent displaying multiple indicators when `$('table').footable();` is called more than one time.

**Comment by fooplugins** [comment]
cool, thanks - I will add that check in, but why are you calling $('table').footable(); twice? That should only ever be called once for each page load.

**Comment by cocinerox** [comment]
When adding tables dinamically it's simpler to call it after each table.

**Comment by bradvin** [comment]
I added a check into the base footable js file, so if the table has already been initialized by footable it does not do it again

that should solve your problem
