### ISSUE TITLE
Default Hide Columns

### ISSUE THREAD

**Issue by sfunkho** [fooplugins/FooTable#20]
It would be nice to have a **th data-class="footable-default-hide"** option to hide the column when no breakpoints have been triggered, and to show the column when any breakpoints have been triggered.  Here's some proposed code to support such an option (I would just submit a pull request, but I'm new to git and now exactly sure how to do it).

This code would be just before the ft.raise() call in ft.resize()

``` javascript
/* deal with show/hide of footable-hide-default* columns
 * 
 * The options are:
 *  data-class="footable-hide-default"
 *      This will hide the column when no breakpoints have been triggered
 * 
 *  data-class="footable-hide-default-expand"
 *      Same as above; except, it adds the 'expand' class when column is shown
 */ 
$table.find('> thead > tr > th[data-class^=footable-hide-default]').each(function() {
    var data = ft.columns[$(this).index()];
    var count = data.index + 1;
    //get all the cells in the column
    var $column = $table.find('> tbody > tr > td:nth-child(' + count + ')').add(this);

    expand = false;
    if (data.className.indexOf('expand') >= 0) expand = true;  
    if ($table.attr('class').indexOf('breakpoint') < 0) {
        $column.removeClass('expand');
        $column.hide();
    }else{
        // expand only non-detail rows
        if (expand) $table.find('> tbody > tr:not(.footable-row-detail) > td:nth-child(' + count + ')').addClass('expand');
        $column.show();
    }
});
```

**Comment by steveush** [comment]
Hi sfunkho, could you try using **th data-hide="default"**, the below is from the updated documentation I'm currently writing:

_There is also a breakpoint called "default" which is the fallback breakpoint for when the current screen width is larger than any defined breakpoint. Looking at the built-in breakpoints (480, 1024), "default" will be the active breakpoint for any screen width larger than 1024 (tablet). This is useful if you have a column you want to hide on larger widths._

Thanks
Steve

**Comment by sfunkho** [comment]
Thanks for the tip.  Somehow I missed that when looking over the code.

**Comment by steveush** [comment]
No problem, there isn't really much documentation at the moment but I'm working on it I'm just learning Git's Markdown at the moment :) There is also another built-in breakpoint which can be useful called **"all"** and is pretty straight forward in it's use. You can always hide a column on any screen width by applying the **data-hide="all"** attribute to a column header.

**Comment by steveush** [comment]
Apologies for the long delay, I ran into some hardware issues and have just put together a new PC, but on the bright side I have also just updated the README.md to include some more info on the supported data- attributes and there usage.

Thanks
Steve
