### ISSUE TITLE
Pagination not working as shown

### ISSUE THREAD

**Issue by Terramune** [fooplugins/FooTable#201]
First off, I want to say how awesome fooTables really is. My only dilemma is with the pagination feature. I am using the footables within a gridview with 200+ records, so to better speed up loading times, i was wanting to use the pagination option. However since i cant fit a <div> inside the footer of the gridview without the pagination going to the last gridview page, i am currently stuck using it in a div beneath the gridview declaration.

The problem however is that instead of getting a nice pager like on the demo, i get a bulleted list for my pagination. Worst part is that it lists every page, and it doesnt allow me to set a limit. Does anyone know what I could be doing wrong with this functionality?

**Comment by bradvin** [comment]
@Terramune glad you like FooTable :) Do you have a link to your page online? Are you using bootstrap 3? I know there have been some styling issues when using BS3 and pagination together.

Also - are you using the latest release which includes the page limit option?

**Comment by Terramune** [comment]
The page is on a private test server for my client. Its not on the web until i get the kinks out. Since I'm not sure what bootstrap 3 is, I doubt I'm using it. And yes, I got the latest release. Ive attempted to set the page limit option to 5, but with no luck.

All i am doing is declaring your Js/css files, the script to call break points, and then i have a gridview with a div at the end for the pagination. At the moment, i currently have to style the UL and LI to remove the bullets, throw a border up around each page number, and change the list from vertical to horizontal. I am building this within an .aspx file if that makes a difference. If the source code would help, i can throw the code up here.

**Comment by bradvin** [comment]
@Terramune if you can put the source up on jsfiddle or codepen, that would be great

**Comment by Terramune** [comment]
@bradvin I hate to say, but im not familiar with those well enough to post my code on there. I did end up mocking up a CSS control myself( doesnt look quite as good, but i did find out its another CSS thats causing my error). Now what im trying to figure out what is happening is limiting the page amounts. I currently have this in the Pageinate.js file:
![image](https://f.cloud.github.com/assets/6817051/2327296/c467e2b6-a3ed-11e3-9b97-60393e865a93.png)

but when i run the program, and i do a breakpoint in the JS, this is what it shows:
![image](https://f.cloud.github.com/assets/6817051/2327308/f3655a80-a3ed-11e3-8a00-a0d87e045e83.png)

Would you have any idea as to what might cause limit navigation to reset to 0. Or can i declare a navigation limit when i do the script call for the footable?

**Comment by Terramune** [comment]
Wow ok so I feel like an idiot. One of my co-workers threw in a .js file that was causing this whole problem. Im sorry for taking up anyone's time.
