### ISSUE TITLE
Sort indicator in header not seen in IE7

### ISSUE THREAD

**Issue by asharani009** [fooplugins/FooTable#202]
Sorting indicator for ascending and descending is shown for Firefox, ie8 but do not shown in ie7. Please help, i need info ASAP

**Comment by bradvin** [comment]
you realize that IS7 ussage is less than 1% worldwide right : http://theie7countdown.com/

If you want to cater for IE7, then you will need to add some custom CSS similar to what is done here : https://github.com/FortAwesome/Font-Awesome/issues/38
