### ISSUE TITLE
IE8: 'w.footable.options' is null or not an object

### ISSUE THREAD

**Issue by drobbo** [fooplugins/FooTable#205]
Hi,

When I try to initialize footable in IE 8 I get the following error:
'w.footable.options' is null or not an object.

and when I do a console.log of 'w.footable', I get undefined.

My code is simple:

```
$(function(){
$('table').footable();
})
```

I haven't found this issue anywhere else and the examples on the website work, which is really strange.

Any ideas?

Kind regards,
Robbe

**Comment by bradvin** [comment]
@drobbo it must be something that was introduced in a recent update. We will look into it

**Comment by duby690** [comment]
@bradvin I have the same issue, have you found a solution?

**Comment by dibu-2008** [comment]
I have the same issue too
