### ISSUE TITLE
colspan in column header

### ISSUE THREAD

**Issue by surrealroad** [fooplugins/FooTable#21]
the first column (in the table's header) in my table has a colspan set to 3, which causes the other columns to sort incorrectly, i.e. trying to sort any column results in the 2nd column before it actually being sorted.

**Comment by steveush** [comment]
Hey surrealroad, could you paste a snippet of your table html so I can see your issue my side.

**Comment by surrealroad** [comment]
here's an excerpt:

http://pastebin.com/1qF2zntd

**Comment by steveush** [comment]
Hi surrealroad,

I've created a new branch called [Colspan](https://github.com/bradvin/FooTable/tree/Colspan) and have made the changes which I think handle the colspans correctly. However I am still testing and fixing any issues as I find them so any feedback is welcome.

There are a two new attributes available for use now, the first is **data-names** which will accept a comma separated list of names for use in the detail view, one per column _wrapped_ by the colspan.

The sorting plugin was also updated to handle colspans. The second new attribute is used to control which of the columns _wrapped_ by the colspan is used for sorting and is called **data-sort-match**. The value for this is the zero based index of the column within the colspan. So if you have 3 columns a value of 1 would always sort using the middle column (0, **1**, 2) no matter where this group was located within the table.

The **data-class** attribute will now be applied to all columns in the colspan.

To see these changes working on a table based on your pastebin example take a look at **issue21.htm** in the root and let me know if you find any issues.

Thanks
Steve

**Comment by surrealroad** [comment]
Thanks a lot Steve.

On Tue, Feb 5, 2013 at 8:18 PM, steveush notifications@github.com wrote:

> Hi surrealroad,
> 
> I've created a new branch called Colspanhttps://github.com/bradvin/FooTable/tree/Colspanand have made the changes which I think handle the colspans correctly.
> However I am still testing and fixing any issues as I find them so any
> feedback is welcome.
> 
> There are a two new attributes available for use now, the first is *
> data-names\* which will accept a comma separated list of names for use in
> the detail view, one per column _wrapped_ by the colspan.
> 
> The sorting plugin was also updated to handle colspans. The second new
> attribute is used to control which of the columns _wrapped_ by the
> colspan is used for sorting and is called _data-sort-match_. The value
> for this is the zero based index of the column within the colspan. So if
> you have 3 columns a value of 1 would always sort using the middle column
> (0, _1_, 2) no matter where this group was located within the table.
> 
> The _data-class_ attribute will now be applied to all columns in the
> colspan.
> 
> To see these changes working on a table based on your pastebin example
> take a look at _issue21.htm_ in the root and let me know if you find any
> issues.
> 
> Thanks
> Steve
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradvin/FooTable/issues/21#issuecomment-13149565.

## 

Sign up for the Synaesthesia beta: http://synaesthesia.surrealroad.com/beta

www.surrealroad.com

**Comment by steveush** [comment]
No problem, please take a look and let me know if you find any issues or have any suggestions. As it stands I think this will be moved across to the master if I can't find any problems while testing.

I would also just like to say sorry for the long delay for a response, I had some hardware issues and only got my new PC put together a few days ago.

Thanks
Steve

**Comment by steveush** [comment]
Merged into master.
