### ISSUE TITLE
data-hide not working while loading data via ajax

### ISSUE THREAD

**Issue by siddharthsrivastava** [fooplugins/FooTable#211]
I am using footable with AngularJS binding the rows with ng-repeat.

My table has 10 columns and I did data-hide = all for all except first 4 columns. Now, when I click submit I am using the following directive in the angularJS (borrowed from:http://stackoverflow.com/questions/20243339/footable-along-with-angular-js)

When the data is populated in the table for the first time, all the columns are shown. The columns are collapsed only when the orientation is changed on the phone. Then onwards it works fine.

app.directive('myDirective', function(){
  return function(scope, element)
  {

```
if(scope.$last && !$('.footable').hasClass('footable-loaded')) {
        $('.footable').footable();
}

var footableObject = $('.footable').data('footable');
if (footableObject  !== undefined) {
        footableObject.appendRow($(element));           
        footableObject.resize();    
}
```

  };})

**Comment by mchiarella** [comment]
I have the same problem with footable. In my case, the pagination only appears after the first table refresh with a search, for example.

**Comment by shantanubhadoria** [comment]
+1 for this, essentially data-hide fails to work when using angularjs ng-repeat in tr. It doesn't matter if you use a REST API or not so perhaps change of title for this bug is warranted?

**Comment by hozefask** [comment]
i am creating table in dynamically but responsive  purpose using footable.js. in mobile view its not working hide the data ,also plus and minus also not working...pls suggest me any one, with example also use jquery or java-script to craete dynamic table apply footable.js
