### ISSUE TITLE
Hi How i could delete all rows of Footable.

### ISSUE THREAD

**Issue by RuanBM** [fooplugins/FooTable#213]
I use ajax to fill a footable, but then I want to refresh this table, overwrite, but after using ajax my footable is filled with new data and previous data. The idea I have is to delete all rows of data before new data refresh using ajax. Someone could help me with that. thank you very much

**Comment by bradvin** [comment]
You could select all rows inside the tbody and remove them. This will remove all data rows and all detail rows.
