### ISSUE TITLE
Sorting icons are reversed

### ISSUE THREAD

**Issue by Zambonilli** [fooplugins/FooTable#214]
The sort icons being displayed are reverse of what the sort order is sorted as.  If you bind to footable_sorted the direction field is correct and the data is sorted correctly.  However, the up/down content displayed is the incorrect sort icon. You can reproduce by going to the sort documentation example.

**Comment by bradvin** [comment]
holy crap!

http://stackoverflow.com/questions/338166/which-direction-should-the-arrows-point-in-a-sorted-table

it seems this is quite a strange UX issue. The correct way:

ascending = up arrow
descending = down arrow

Tablesorter plugin is done as above.
The windows explorer sort icons are also done as above.

I cannot believe that no one else has noticed this :)

I will change FooTable to also follow this convention. Thanks for point this out @Zambonilli

**Comment by mvrhov** [comment]
Any chances of fixing this in V2?

**Comment by molequetu** [comment]
Any news from this??
