### ISSUE TITLE
remember row expand/collapse on reload

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#217]
Is it possible to keep the expanded rows expanded on a page reload? I have a page with tables that refreshes every 5 seconds, but I want that if the row is expanded or collapsed, it keeps it the same after the reload.

**Comment by bradvin** [comment]
This will have to be done using cookies. I am not sure this falls within the scope of footable, but perhaps an add-on that remembers state? I am open to suggestions...

**Comment by akf** [comment]
I have a suggestion! I had a similar request, except that the goal was for the user to be able to filter/sort/expand and then send a link to someone else so they could see the table in that state. So, I wrote a plugin to add state information to the URL and read it when initializing. Since there's interest, I've put it up on github: 

https://github.com/lucidmeetings/lucid_footable_plugins

It may be useful to others, or it may serve as an example. 

Obviously I was trying to make a reusable plugin, but the main goal was to get our use case working, so there may be some assumptions in there. I use this with the paginate, sort, and filter plugins and didn't test rigorously against any other configuration. YMMV, etc. 

You can see this thing in action on a rather unwieldy table here: 
https://features.icann.org/board-advice#advice-to-board_f=confusing&advice-to-board_d=false&advice-to-board_e=19

**Comment by bradvin** [comment]
@akf that is so awesome! If you want, send a pull request to add this to the FooTable repo. Be sure to update the readme with a link and cudos to yourself.

So happy to see people building on top of FooTable, and this is a really great add-on!

**Comment by bradvin** [comment]
@mitch2k please try the extension made by @akf and see if that solves your problem. It seems like it will do the job 100%

**Comment by akf** [comment]
Done! Thanks for FooTable, @bradvin. We're getting a lot of mileage out of it.

**Comment by bradvin** [comment]
@akf great to hear :) And thanks for your contributions - it is very much appreciated!

**Comment by emaad** [comment]
Hi @akf and @bradvin ,
The bookmarkable js code is no more working with latest JS. I have integrated the code but the code line "w.FooTable.plugins.register" is no more available in latest FT js. I also tried to use component for registering it but failed.

Can you guys please tell me how it need to be done in latest JS.

**Comment by akf** [comment]
Hi @emaad. I haven't made the switch to Footable V3, so I haven't looked into this at all. My understanding is that V3 is a complete rewrite, so I wouldn't expect the plugins for V2 to work with it or even be a good starting point, other than as a source of ideas.

**Comment by emaad** [comment]
Thanks for your quick response.
I have implemented a quick solution for it. May be someone else need it later on.

`<script type="text/javascript">

        var sPath = window.location.pathname;
        var sPage = sPath.substring(sPath.lastIndexOf('/') + 1);
        var cookieValue = getCookie(sPage);

        $(function () {




            $("#TableID").footable({
                //"expandFirst": true,
                "data-show-toggle": false,
            });

            var ft = FooTable.get('#TableID');

            ft.rows.all.forEach(function (row) {

                if (cookieValue != null) {
                    var arrIDs = cookieValue.split(",");
                    for (var i = 0; i < arrIDs.length; i++) {
                        if (arrIDs[i] == row.value.col2) {
                            row.expand();
                        }
                    }
                }
            });


            $("#TableID").on("expand.ft.row", function (e, ft, row) {
                cookieValue = getCookie(sPage);
                var ID = row.value.col2;

                if (cookieValue == null) {
                    setCookie(sPage, ID + ",", 1);
                }
                else {
                    setCookie(sPage, cookieValue + ID + ",", 1);
                }
            });
            $("#TableID").on("collapse.ft.row", function (e, ft, row) {
                cookieValue = getCookie(sPage);
                var ID = row.value.col2;

                if (cookieValue != null) {
                    var res = cookieValue.replace(ID + ",", "");
                    setCookie(sPage, res, 1);
                }

            });


        });

        function setCookie(name, value, days) {
            var expires = "";
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                expires = "; expires=" + date.toUTCString();
            }
            document.cookie = name + "=" + (value || "") + expires + "; path=/";
        }
        function getCookie(name) {
            var nameEQ = name + "=";
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') c = c.substring(1, c.length);
                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
            }
            return null;
        }
    </script>`

The code may need more amendments.

Happy Coding :)
