### ISSUE TITLE
Filtering with select option value

### ISSUE THREAD

**Issue by justawebbie** [fooplugins/FooTable#218]
I am not sure what I have done wrong exactly but 7 out of the 10 option values will filter the table which I have rechecked name, spelling etc. all is great.  The search works great. The page looks and works great. I just need help with the option values. What am I missing or not doing to make it work on all 10 of the option values for filtering?

Webpage: http://www.uaf.edu/catalog/catalog_13-14/majors-test8.html

**Comment by bradvin** [comment]
You are binding to the filtering event of footable, which I would not do in your case. Just bind to the change event of the select (which you are doing) and trigger the filter but rather use the val() of the select:

```
$('.filter-status').change(function (e) {
      e.preventDefault();
      $('table.demo').trigger('footable_filter', {filter: $('.filter-status').val()});
    });
```

**Comment by justawebbie** [comment]
So my script should look like this:

```
$(function () {
    $('.filter-status').change(function (e) {
        e.preventDefault();
        $('table.demo').trigger('footable_filter', {filter: $('.filter-status').val()});
    });

   $('.clear-filter').click(function (e) {
        e.preventDefault();
        $('.filter-status').val('');
        $('table.demo').trigger('footable_clear_filter');
    });
 });
```

**Comment by justawebbie** [comment]
Nope that is not it.  I have tried to redo the script but I seem to keep breaking the footable.  I need more classes on javascript. I am so sorry.

**Comment by bradvin** [comment]
your above code looks correct - is it live on your site?

**Comment by justawebbie** [comment]
I took it off because it caused the footable to loose all its css and structure.  I will add again for you to look at.

**Comment by justawebbie** [comment]
Hate to seem in a rush. I know you are a busy man and I appreciate the time you take to help me out.  Did you take a look at it again by chance? It just took away all the formatting when I used that javascript.

It is a mess now does not filter at all, Please help!

**Comment by bradvin** [comment]
oh, i did not realise you put the changes live. But it looks like you are not initializing footable at all anymore?

```
$(function () {
    $('.filter-status').change(function (e) {
        e.preventDefault();
        $('table.demo').trigger('footable_filter', {filter: $('.filter-status').val()});
    });

   $('.clear-filter').click(function (e) {
        e.preventDefault();
        $('.filter-status').val('');
        $('table.demo').trigger('footable_clear_filter');
    });

    $('table.demo').footable();  //this line is missing!!
 });
```

**Comment by justawebbie** [comment]
Ughh! I make some the dumbest mistakes.  Thank you that works great now!
