### ISSUE TITLE
Sorting does not work correctly for Alpha or Currency

### ISSUE THREAD

**Issue by ShawmutSteve** [fooplugins/FooTable#22]
Alpha sorting - seems to only be based on the first character.  In your demo (http://themergency.com/footable-demo/demo-sorting.htm), this problem is visible.  If you sort the 'Job Title' column, Aviation Tactical Readiness Officer should sort below Airline Transport Pilot.

Currency sorting - I tried to get this to work by following the example of data-value="1025" (without the currency $ symbol).  But it did not work correctly.  I also assigned a data-type="numeric" as a second attempt, but that also did not change the outcome.

**Comment by ShawmutSteve** [comment]
Ignore the Currency sorting issue - I found https://github.com/bradvin/FooTable/issues/4.  Adding  data-type="numeric"to the <th resolves the issue.

Alpha is the only remaining issue from this ticket.

**Comment by hcvitto** [comment]
same bug here. Here's my example
http://www.vitto.mt.it/app/table.php

**Comment by steveush** [comment]
Hey guys, I'm looking into this and may end up writing a better compare function, I would use the built in localeCompare function which is supported in all major browsers except that it seems to have some issues in Chrome:

Issue 459 - v8 - localeCompare implementation differs from other ...
http://code.google.com/p/v8/issues/detail?id=459

Issue 19254 - chromium - Javascript localeCompare is not locale ...
http://code.google.com/p/chromium/is...etail?id=19254

Issue 622 - v8 - localeCompare is not locale-dependent - Project ...
http://code.google.com/p/v8/issues/detail?id=622

**Comment by steveush** [comment]
I've made a change to the sortable plugin and changed the alpha sorting function a little. Please get the latest and your issue should be fixed :)

Thanks
Steve
