### ISSUE TITLE
How to use the Dropdownlist in row using footable 

### ISSUE THREAD

**Issue by AnbuselvanA** [fooplugins/FooTable#220]
Hi,

I am surprise to view this but I have a problem .while I am using Dropdownlist 
   <table class="footable">
            <thead>
                <tr>
                    <th data-class="expand">Name</th>
                    <th data-hide="phone,tablet">Choice</th>
                </tr>
            </thead>
            <tbody>
      <tr>
                    <td>Tom Cruise</td>
                    <td>
                        <asp:DropDownList ID="DropDownList1" AutoPostBack="true" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" runat="server">
                            <asp:ListItem Value="1" Text="Yes">/asp:ListItem
                            <asp:ListItem Value="2" Text="No">/asp:ListItem
                            <asp:ListItem Value="3" Text="Don't Need">/asp:ListItem
                        /asp:DropDownList
                    </td>
                </tr>  </tbody></table>

Desktop view working fine.while chossing the  option in dropdown I am updated db.but In mobile view the function not working..pls help.

**Comment by bradvin** [comment]
There is a limitation in the current version of FooTable whereby it clones the cell centents into the detail rows in a mobile view. This will cause issues with .NET because it will duplicate the control ID's.

We will be fixing this limitation in the next major release of FooTable, by moving the cell contents rather than cloning

**Comment by AnbuselvanA** [comment]
ok ,but I need temporary solutions to handle it now.

**Comment by bradvin** [comment]
there is no solution at this stage

**Comment by AnbuselvanA** [comment]
thank u i fixed. Traffic response.
