### ISSUE TITLE
Filtering by data attributes

### ISSUE THREAD

**Issue by capitaldeath** [fooplugins/FooTable#222]
Hello,

Firstly, thanks for your great plugin, it's really helpful in making tables responsive on my website. I'm wondering if it's possible to filter table rows by their data-attribute values. I have numerous rows with data-attributes like data-type="a", data-type="b", data-type="a b", data-type="c", etc, and I'd like to filter rows based on that, by clicking a button or selecting from a dropdown or similar methods. Is this possible?

Thank you,
Jack

**Comment by bradvin** [comment]
Hello Jack,

Yes, indeed this is possible. You will need to override the filterFunction : https://github.com/bradvin/FooTable/blob/V2/js/footable.filter.js#L12

To rather look at your data-attributes

**Comment by capitaldeath** [comment]
Hello @bradvin - thank you for getting back to me quickly.

I currently have this as my filterFunction:

``` javascript
 filterFunction: function(index) {
                var $t = $(this),
                    $table = $t.parents('table:first'),
                    filter = $table.data('current-filter').toUpperCase(),
                    text = $t.find('td').text();
                if (!$table.data('filter-text-only')) {
                    $t.find('tr[data-event-type]').each(function () {
                        text += $(this).data('event-type');
                    });
                }
                return text.toUpperCase().indexOf(filter) >= 0;
            }
```

(I'm trying to filter by the value of the data-event-type attribute)
However I haven't managed to get it to work. Do you have any ideas? :)

Thanks again,
Jack

**Comment by capitaldeath** [comment]
@bradvin - do you think this will be possible?

**Comment by bradvin** [comment]
@capitaldeath can you get this in a jsfiddle so I can see it in action?
