### ISSUE TITLE
Fixed height table

### ISSUE THREAD

**Issue by dschleup** [fooplugins/FooTable#224]
I am trying to create a sortable, paginated table using FooTable that is fixed height.  The primary reason I want the table to be fixed height is that I don't want the pagination controls to move when navigating to a last page that doesn't have the same number of rows as the data-page-size.  For example, if my data-page-size is set to 5 and I have 8 records to display in the table, when I navigate to page 2 (which will only have three rows), the paging control shifts up the equivalent of two rows since the entire table changes height.

If I simply assign a fixed height to the table in CSS (equal to the height of the table when displaying page 1), the table does stay the same height when navigating to page 2, but the three rows are stretched in height to fill the entire table height.  I'd like the rows to remain the same height as the rows on page 1 and then have blank "padding" below the three rows.

To achieve this, I can simply add two blank rows to my table when building it.  It looks great when navigating to page 2 - the table remains the same height and the pagination control stays in the same spot.  However, this causes a problem when sorting - since the rows actually exist in the table, they are sorted to the top of page when changing the sort on any column.  As far as I can tell, there is no equivalent of data-sort-ignore="true" at the row level, so there's no way to tell the sorter to ignore these rows.

Given that, I realized I could try to remove the rows just before sorting and then add them back in after sorting by intercepting the footable_sorting and footable_sorted events.  The javascript below achives that, however it creates an infinite loop since the appendRow method fires a redraw, which I believe then fires the footable_sorting event, which then removes the row, etc.  If I try to manually add the row without firing redraw, the row doesn't show.

Sooooooo.....my question is whether there is any way to fix the height of the table so that the pagination control remains in the same place?  Is there a way to achieve this already that I haven't found?  Or would it require something similar to the approach in the code below (that wouldn't create an infinite loop, of course)?

```
$(function () {
    $('#myTable').footable().bind({
        'footable_sorting': function (e) {
            removeBlankRows();
        },
        'footable_sorted': function (e) {
            addBlankRows();
        }
    });
});

function addBlankRows()
{
    var footable = $('table').data('footable');
    rowCount = $('.footable tbody tr:not(.footable-filtered)').length;
    pageSize = footable.pageInfo.pageSize;
    modulus = rowCount % pageSize;
    addRowCount = pageSize - modulus;

    var newRow = '<tr id="blank"><td></td><td></td><td></td><td></td><td></td></tr>';

    for (i = 0; i < addRowCount; i++) {
        footable.appendRow(newRow);
    }
}

function removeBlankRows()
{
    var footable = $('table').data('footable');

    rows = $('#blank');

    for (i = 0; i < rows.length; i++)
    {
        footable.removeRow(rows[i]);
    }
}
```

**Comment by dschleup** [comment]
Inadvertent close while scrolling on mobile.  My apologies.  Not trying to nudge anyone.

**Comment by bradvin** [comment]
@dschleup I am not sure this is the best way to achieve "fixed height" tables. It just seems like a hack to me to add blank rows.

The pagination control does not need to be in the table footer. It can live outside of the table markup, so that you can position it fixed to the bottom of a container.

But also remember that when the table "collapses" columns, FooTable appends rows, which will mess with your table height depending on if the user expands the rows or not.

**Comment by dschleup** [comment]
Thanks for the quick reply, @bradvin.  I agree that it is a bit of a hack to try to fix the height of the table by adding the padding rows.  I probably should have picked a better subject for this post as I don't actually want a "fixed height" table, but I want a table that is always the same size (that's probably a better way to phrase it).  I'm building a pretty fluid layout and, in general, I'm trying to avoid setting any sort of fixed heights or widths on anything.  By adding the padding rows, I could achieve a table that is always the same size (no matter what page you are on) without explicitly setting a height.

Also, you make an excellent point about the additional rows after collapsing columns (i was more worried about the non-collapsed state).  I've played around with your suggestion to remove the pagination control and have fixed its position underneath the table.  I have to set a min-height on the table - instead of a fixed height - to account for expanding/collapsing the rows when the columns collapse.  I think this will work for me and not affect the rest of my layout.

Thanks again for the help.
