### ISSUE TITLE
Footable-row-detail not hidden after page resized to fullscreen when footable.min.js (Version : 2.0.1.3) is used

### ISSUE THREAD

**Issue by lygutas** [fooplugins/FooTable#227]
If footable.js Version : 2.0.1.4 is used - everything works fine. 
Current Github repo contains 2.0.1.3 version of minified file and 2.0.1.4 version of full code javascript file.

Reproducing:
Include footable.min.js (2.0.1.3) file into html page
Resize browser window to phone resolution, some columns are hidden, [+] icon appears.
Click on [+] icon, hidden column data expands in additional detail row. 
Resize browser to fullscreen
=> hidden columns reappear, but additional detail row is still there. 

But if non-minified script v 2.0.1.4 is used - this issue does not appear.

**Comment by bradvin** [comment]
thanks for letting me know @lygutas 

I have built new min scripts and committed those. So the min files are now at 2.0.1.4
