### ISSUE TITLE
Table not resizing properly on mobile & Icons issue

### ISSUE THREAD

**Issue by felixyakubov91** [fooplugins/FooTable#229]
First of all thanks for developing this awesome table! 
I added footable to my wordpress page using scripts (following getting started) and everything is great but the table is not fully displayed in mobile...Im using http://quirktools.com/screenfly to check different screens. 
Also my sorting arrows are not working. 
http://www.agamy.co.il/jobs-table - my test page
Could you help me out?

**Comment by nikhilknoldus** [comment]
+1
