### ISSUE TITLE
Combining Filters

### ISSUE THREAD

**Issue by Chalkin** [fooplugins/FooTable#233]
Is there a way to combine the filters in Footable?

Example:

<code>

<table>
<thead>
<tr>
<th>Year</th>
<th>Type</th>
<th>Status</th>
<tr>
</thead>
<tbody>
<tr>
<td>2013</td>
<td>Income</td>
<td>Paid</td>
</tr>
<tr>
<td>2014</td>
<td>Income</td>
<td>Unpaid</td>
</tr>
<tr>
<td>2013</td>
<td>Expense</td>
<td>Paid</td>
</tr>
<tr>
<td>2013</td>
<td>Income</td>
<td>Unpaid</td>
</tr>
</tbody>
</table>

</code>

Filter: Year 2013 + Incomes
Filter: Type Income + Status Unpaid + Year 2013

**Comment by hereiam133** [comment]
This is exactly what I need as well

**Comment by kedano** [comment]
+1
