### ISSUE TITLE
Not an issue, I'd like to contribute, but i don't know how :(

### ISSUE THREAD

**Issue by joseluisillana** [fooplugins/FooTable#240]
Hello, I'm Jose.

Recently I was using this powerful responsive table.

I've made some changes to get pagination in server, and let the footable to manage the number of results by page, the total of pages, etc..

I think I can contribute uploading my changes to the repository, but I don't know how to do that. So I would ask bradvin, if you can help me. I really would like to contribute on this.

Congratulations, that's an amazing tool.

Thanks you

**Comment by bradvin** [comment]
Hi @joseluisillana 

Thanks for your interest in FooTable! I would love you to contribute your work back to the project. The easiest way to get started is to fork the repo (which I see you have done already).

Then make your changes and commit them back to your fork. 
Once you have commited them back to your fork, you can then submit a pull request : https://help.github.com/articles/creating-a-pull-request

I can then review and test your changes and then merge them back into my repo if it all looks good

let me know if you need any more guidance or help
