### ISSUE TITLE
Missing function to update a row

### ISSUE THREAD

**Issue by twigmac** [fooplugins/FooTable#241]
[In the docs](http://fooplugins.com/footable/demos/add-delete-row.htm#docs) is described how to add (to the end of the table) and how to remove a row. But FooTable is missing a function to update, respectively to replace a row.

I was looking for something like this.

`footable.replaceRow($("#oldRow"), "<tr>Fresh HTML</tr>");`

Have I overlooked something?

**Comment by yb11206** [comment]
also it would be nice to have function to retrieve row lets say by row index or row id...
so even if its the row is expanded it should be able to get the the row at once the mail and the details
