### ISSUE TITLE
Filter specific columns 2 

### ISSUE THREAD

**Issue by cafc3** [fooplugins/FooTable#242]
Hi,

I saw in this forum that this question (https://github.com/bradvin/FooTable/issues/101)
has already been posted and answered but I need some help to implement in my webpage the solution presented there.

I need to filter only by specific column and not in the all table (but keeping the generic search also), 

the code presented in #101 :

filterFunction: function(index){
    var $t = $(this),
          $table = $t.parents('table:first'),
          filter = $table.data('current-filter').toUpperCase();

```
      var $f = $('.footable-filter:focus');//actives filters
      var $td = $t.find('td'); //the table cells

      //Filtering the td list
      if($f.data('filter-columns')){
          $td = $td.filter(  $f.data('filter-columns') );
      }

      //Search for text in td's class
      if($f.data('filter-class') === true){
          return  $td.hasClass( $table.data('current-filter') );
      }else{
          var text = $td.text();
      }

         // filtering on data-value, not innerText    
      if (!$table.data('filter-text-only')) {
          $t.find('td[data-value]').each(function () {
              text += $(this).data('value');
          });
      }

      //Split ? (allow to search different elements, like postcode : "75010,78180" will find both Paris 10th, and Montigny le Bretonneux)          
      if($f.data('filter-split') === true){
          var filters = filter.split(',');

          for(var i in filters){
              if(text.toUpperCase().indexOf(filters[i]) >= 0)
                  return true;
          }

          return false;
      }else{
          return text.toUpperCase().indexOf(filter) >= 0;
      }


  }
```

but how I can call this in my webpage to filter only specific column instead of all table. Can anyone please help me,

thanks in advance,

cafc

**Comment by svdev22** [comment]
Even I have the same question..Can some one help ?

**Comment by svdev22** [comment]
I have a table where I need to filter it based on the multiple values in the single column. How can we implement this using foo tables.
