### ISSUE TITLE
Filter table data based on multiple sections of checkboxes

### ISSUE THREAD

**Issue by kedano** [fooplugins/FooTable#243]
Hi,

I have a table of data at the following url:
http://neted3.hiof.no/studier

What is the best way to hook up the checkboxes on the right side to filter data in the table? So far I've added the checkbox name attributes to each row as data-value and changed the selector for the data-value to look at the table row.

My JS code:
https://github.com/hiof/frontend/blob/next/app/assets/js/app.js#L194

As far as I understand I have to override the default filterFunction functionality so it filters on "ANY" of the values in the array from my form?

**Comment by ghost** [comment]
> My JS code:
> https://github.com/hiof/frontend/blob/next/app/assets/js/app.js#L194
> that's URL 404
