### ISSUE TITLE
Footable not working in css styles

### ISSUE THREAD

**Issue by AnbuselvanA** [fooplugins/FooTable#245]
i have status column in my table, those td have class as progress .
Desktop view working fine applied the class.

desktop view:
<td class="Progress" style="display: table-cell;">Progress</td>

but in Mobile view,class is not applied

<div class="" "detail-inner-datacell"="">Progress</div>

**Comment by Sherif-Ahmed** [comment]
+1 ... but in my project even desktop view ... the classes is not applied at all
