### ISSUE TITLE
Pagination not working with gridview control

### ISSUE THREAD

**Issue by Faisal-Saleem** [fooplugins/FooTable#248]
Hi,

First of all thank you for this wonderful Table, every thing is working fine except pagination, I am using this with an asp.net gridview control. how can i achieve this.

Thanks

**Comment by mazharqayyum** [comment]
Looks like I am in same boat :( Footable really makes GridView a lot better. I wonder if there is any way to tell footable ignore pager rows. As of this moment footable hides the gridview pager. I know about footable-disabled class but that doesn't seems to work.
