### ISSUE TITLE
Sort icons show incorrectly in column headers

### ISSUE THREAD

**Issue by efkan** [fooplugins/FooTable#251]
This is not important. Just I want to inform.

For instance:  "˄" sign value must be showing low to high order. 
                      Otherwise if the sign value is "˅" then column is ordered high to low.

**Comment by manijak** [comment]
Yes, I can confirm this issue. Please fix it or show us where we can do it, as it is very anoying :)

Edit: Easy fix: Open file footable.core.css and search for "\e013". Replace the 13 with 12. Then find "\e012" and replace the 12 with 13.

**Comment by efkan** [comment]
Thanx! :)
