### ISSUE TITLE
Formatting not displaying properly on mobile

### ISSUE THREAD

**Issue by bstenz** [fooplugins/FooTable#253]
I cannot figure how to get superscript to display when the table transitions to mobile. It looks like it strips out any formatting when it hits a breakpoint.

Additionally, if I try to add the formatting myself, it displays the </sup> tags.

Thanks in advance!

Desktop
![desktop](https://cloud.githubusercontent.com/assets/8258444/3690117/16d9842e-1346-11e4-8b44-fa19db2875dd.png)

Mobile
![mobile](https://cloud.githubusercontent.com/assets/8258444/3690121/1b06d812-1346-11e4-9453-8a9a159a5f80.png)

**Comment by tzd** [comment]
You can use "data-name" atribute to show superscript in detail row:

``` html
<th data-name="Voltage/Phase/Hz<sup>4</sup>">Voltage/Phase/Hz<sup>4</sup></th>
```

http://fooplugins.com/footable-demos/?url=http://fooplugins.com/footable/demos/data-attributes.htm
