### ISSUE TITLE
Nested footable

### ISSUE THREAD

**Issue by myratheesh** [fooplugins/FooTable#255]
Can we create nested foo table ?How?
Like jqgrid have property like subgrid.

**Comment by bradvin** [comment]
I do not think a nested footable will work, as the selectors target the thead inside the table and if there are multiple then it will probably break. Having said that, I have not tested if this statement is true or not

**Comment by myratheesh** [comment]
Okay..Thanks for  your kind information.. And Can you help me out any other plugin is there or not ? i am working on  MVC responsive website..  so grid should be responsive
