### ISSUE TITLE
Change Table height

### ISSUE THREAD

**Issue by NudeWeb** [fooplugins/FooTable#256]
Thanks for the great plugin

I have a table with just 1 row on the 2nd page. I'd like to set the height of the table so that either I end up with more than just 1 row on page 2 or better that I get all the data on a single page table. Can't see where I can vary the default table height

Could you tell me how to do that please.

**Comment by chrislaskey** [comment]
You can change how many items are on a page using the [`data-page-size` attribute](http://fooplugins.com/footable/demos/paging.htm#docs).

**Comment by NudeWeb** [comment]
Could you tell me how to remove the Search box for an individual table please?

Regards
Marc
