### ISSUE TITLE
Pagination don't work

### ISSUE THREAD

**Issue by luiito** [fooplugins/FooTable#257]
Hello,
I have a problem, the pagination don´t work. 
In this this link you can see: http://focir.cat/focir-web/ca/articles/

Can you help me?

Thank you

**Comment by bradvin** [comment]
The pagination seems to be fine on that page as far as functionality is concerned.
But there is a styling issue so it looks strange. You are going to have to tweak your css in order to get it looking 100% as your site's CSS is overriding the pagination styling.
