### ISSUE TITLE
Adapt CSS to simplify mobile text selection

### ISSUE THREAD

**Issue by andi1984** [fooplugins/FooTable#26]
Hi,

I don't want to add a bug report or something like this, but I think footable should (somehow) make the detail row a little bit more mobile friendly with regard to text selection.

It's really hard to hit & mark the text passages with font-size 14px inside a td. Especially on iOS, you have to make original marking rectangle smaller to fit the specific data-row.

I made it a bit simpler by adding a mobile-friendly height attribute of 40px to the single data-rows to make it simplier on touching the text which you want to copy.

I think some research and work has to be done on that topic, because, in contrast to the footable concept, it's not **THAT** user friendly. :smile:

**Comment by steveush** [comment]
Hi Andi,

I agree the detail row leaves much to be desired and is really just a simple data dump of the values to HTML with no real styling added to it. This however was done on purpose as we expected people to make use of the **createDetail** option which is really the function used to create the detail row HTML. They could then style their custom HTML as they liked with no interference from FooTable, that said I do see your point that the default detail row needs some tender love and care so I will look into making some default styles with explicit CSS classes so they can't interfere with anything that could be added later.

The below is the default **createDetail** function but it shows how you could override it and create pretty much whatever you like in the detail row, as you can see at the moment this is an extremely simple HTML structure with no classes applied but you could make it do whatever you like.

``` javascript
    $('table').footable({
      createDetail: function(element, data) {
        /// <summary>This function is used by FooTable to generate the detail view seen when expanding a collapsed row.</summary>
        /// <param name="element">This is the div that contains all the detail row information, anything could be added to it.</param>
        /// <param name="data">
        ///  This is an array of objects containing the cell information for the current row.
        ///  These objects look like the below:
        ///    obj = {
        ///      'name': String, // The name of the column
        ///      'value': Object, // The value parsed from the cell using the parsers. This could be a string, a number or whatever the parser outputs.
        ///      'display': String // This is the actual HTML from the cell, so if you have images etc you want moved this is the one to use and is the default value used.
        ///    }
        /// </param>

        for (var i = 0; i < data.length; i++) {
          element.append('<div><strong>' + data[i].name + '</strong> : ' + data[i].display + '</div>');
        }
      }
    });
```

Thanks
Steve

EDIT:

Just wanted to add that this is the reason for the explicit selectors and CSS classes in FooTable, as much as possible is now directly targeted to avoid any FooTable CSS styles and JS selectors cascading down to the detail row.

**Comment by andi1984** [comment]
Hi Steve,

thanks for your fast reply!

I already use these customization options. Sure, customization is (more or less) necessary all the time to fit personal needs, but at least in my opinion a plugin should provide a good starting point to work with. Don't understand me wrong, footable is :+1:, but if you have some :clock1: pls work on these styling issues to provide some minimal CSS which considers these problems with minimal effort possible.

I think I will provide some pull requests :smile: 

Thanks for your work and your feedback!

**Comment by steveush** [comment]
Hey Andi,

Yes, I agree with you and will add in some default styles so it's not so eye smacking with no customization. If you provide your CSS as a starting point I could work from there and add it in. I'm currently working in the Colspan branch and will make the modifications there before moving it across to the master branch.

Thanks
Steve
