### ISSUE TITLE
Not working with Bootstrap3

### ISSUE THREAD

**Issue by jayeshtharani** [fooplugins/FooTable#260]
Integrated Footable with Bootstrap Latest Version i.e V 3.0
But the sorting,paging and filtering are not working.
The table is showing all the records.
And in console window no error is being displayed.

Kindly help to resolve the issue.

Thanks in advance.

**Comment by neverfox** [comment]
It's working fine for me with Bootstrap 3. Can you post an jsfiddle or jsbin showing the problem?

**Comment by voltechs** [comment]
Everything works for me except for sorting, as it starts multiplying rows.
