### ISSUE TITLE
Data-Toggle when using <th> in <tbody> not working!

### ISSUE THREAD

**Issue by designspin** [fooplugins/FooTable#262]
The data toggle does not show if the first element in tbody tr is a th instead of a td

Is it possible to adjust something to make this work?

**Comment by bradvin** [comment]
ah yes, at the moment it only looks for td's 

https://github.com/bradvin/FooTable/blob/V2/js/footable.js#L387

this should probably move out into an option

**Comment by designspin** [comment]
Is this likely to be tackled anytime soon?
