### ISSUE TITLE
Zebra

### ISSUE THREAD

**Issue by X-Raym** [fooplugins/FooTable#263]
Feature Request : Zebra (with two or more colors), every certain number of rows.  and priority.

Exemple : Zebra color Grey every 10 rows priority one, and Zebra colors Yellow every tow rows priority 2

I cant developp if needed :)

thanks for listening, and thank you for your great plugin !

**Comment by X-Raym** [comment]
Oh, it appears simpler that I thought, with CSS only :)

http://dev.opera.com/articles/zebra-striping-tables-with-css3/

Consider as closed !

**Comment by X-Raym** [comment]
Oh, not closed, it breaks with collapsed rows =/
and i was already reported 

https://github.com/bradvin/FooTable/issues/14

EDIT : nevermind : metro theme is perfect :)

**Comment by bradvin** [comment]
Yes, CSS will not work because of the new rows that FooTable adds. This add-on was created for this exact purpose : https://github.com/bradvin/FooTable/blob/V2/js/footable.striping.js

**Comment by X-Raym** [comment]
Thanks !! :)
(footable is really incredible)
