### ISSUE TITLE
FooTable destroy method

### ISSUE THREAD

**Issue by johndugan** [fooplugins/FooTable#264]
Hi Folks,

Looking through the source, is there a way to destroy a footable instance? I am working to make a site ie8 compatible. There are a couple tables that I wish to remove footable from. What is the best way to do this?

**Comment by bradvin** [comment]
hey John, there is no destroy method in footable at the moment. I suppose the easiest way to do this is to remove all rows with class `.footable-row-detail` and then show all cells by doing something like `$('.footable').find('th,td').show();`

**Comment by johndugan** [comment]
Hi Brad,

Since I am conditionally loading different js for ie8. I just defined a variable ie8 = true. Then approached the issue the following way.

```
    if ( !ie8 ) {

        $('.footable--cart').footable({ // order/quote cart
            breakpoints: {
                phone: 479,
                tablet: 649
            }
        });

    }
```

It would still be cool to see a destroy method... though I don't exactly have a use case for it anymore :-). Thanks for the reply.
