### ISSUE TITLE
Very Urgent!! Expand Rows on Hover !!

### ISSUE THREAD

**Issue by Tapmeet** [fooplugins/FooTable#265]
My client have a website http://www.geldbank.be/ . They recently had a problem with issues regarding showing the content on their website. 

So basically the problem is we want to expand the row on mouse hover in desktop version. Example http://www.geldbank.be/persoonlijke-lening/ this page needs to expand rows on mouseover. I managed but i can't work this out, as i am just a beginner. 

My code:-
    jQuery('.footable tbody tr').hover(function() {
        jQuery(this).addClass('footable-detail-show');
        jQuery('.footable-row-detail').show();
    }, function() {
        jQuery(this).removeClass('footable-detail-show');
         jQuery('.footable-row-detail').hide();
    });

Its very urgent or else website will be down forever. Need to fix asap.

**Comment by bradvin** [comment]
rather use the `toggleDetail` method of FooTable to toggle the detail row:

```
var footable = $('table').data('footable');
//get the row we are wanting to toggle
var row = $(this).parents('tr:first');
footable.toggleDetail(row);
```

**Comment by Tapmeet** [comment]
http://www.geldbank.be/vergelijk-leningen/ .Please check this page. There is a spacing issue. Also the website inspector wants to display the row at the bottom as it is now but on hover.

Also when we click "+" Sign it opens the row at the bottom. If we check the code it generates on the click function. Is there a way to expand all rows on page load or make them hidden but visible through code?
