### ISSUE TITLE
Could you insert click row event with row id feedback?

### ISSUE THREAD

**Issue by breezeboy** [fooplugins/FooTable#267]
I use FooTable like BBS List, So I need click event (Now, if click row or icon, then expand the hide item), then feedback the row id, Could you help me or must to change the code ?Thank you.

**Comment by bradvin** [comment]
you can do this outside of FooTable. Just bind click events to your table rows and get the row id out manually

**Comment by breezeboy** [comment]
Thank you for your prompt reply.
But, How can I block the plug event? In Demo, click row or icon, then expand the hide item.

I just want to click icon then expand the hide information, click row then popup a new window with row id. How to do?

**Comment by bradvin** [comment]
You can try changing the toggleSelector option to `> tbody > tr .footable-toggle`

That should only bind the hide/show to that toggle icon. You can then bind to the row and do what you need

**Comment by breezeboy** [comment]
Thanks, I'll try it.

**Comment by breezeboy** [comment]
Hello, bradvin,
1. when I change as below:
   toggleSelector: ' > tbody > tr .footable-toggle',
   It' done. But row's cursor is hand when small window (row's cursor is normal when Max Window), It's not better.
2. when I bind click events, I can't find which css name is better for table rows.
   Could you help me to finish the simple questions.

I think it's a common require, Could you add this function (row click event) into FooTable with parameter switch.
Thanks again.
