### ISSUE TITLE
custom page navigation in footable

### ISSUE THREAD

**Issue by Sushil-Dhiver** [fooplugins/FooTable#269]
Hi Bradvin,

I have an issue where the user is on the 2nd or the 3rd page in footable and he navigates to another url and then does a back. what happens in this case is instead of the user going back to the page he was working he is taken to the first page in the footable. 

I am thinking of storing the page numbers in the querystring and navigating to the page in the table from the querystring value. 

is there any method that i can call to navigate to a particular page in footable? please help me with this.

Thanks in advance.
Sushil

**Comment by akf** [comment]
Sushil, check out the "bookmarkable" and "memory" plugins. I think either would address your issue. Bookmarkable uses a hash fragment on the URL; memory uses localStorage.

**Comment by Sushil-Dhiver** [comment]
thanks akf. 
but is there any way i can call a method from the footable plugin that can just navigate me to the said page?
the paging in footable is a client side paging and it just hides the rows and displays them according to their pages. footable internally triggers "footable_paging" and does the paging so is there any way i can trigger this event and just pass the page no I want to navigate to?

Can you also share the links of these plugins cuz i was not able to find them.

Thank you very much for your help.

**Comment by akf** [comment]
@Sushil-Dhiver, if you've downloaded the latest release (2.0.1.5) from this repo, there's a demo for the bookmarkable plugin in the release (look in the demos directory). It's not linked up on the fooplugins site. There isn't a demo (yet?) for the memory plugin.

The code itself is here: https://github.com/bradvin/FooTable/blob/V2/js/footable.bookmarkable.js

The relevant lines to what you're trying to do, if I understand correctly, are 98 and 111: 

This sets the "currentPage" value in the table's data (so you would pull the desired page from your query string and substitute it for q_page_num): 
 $(ft.table).data('currentPage', q_page_num); 

This triggers the paging event: 
$(ft.table).trigger('footable_setup_paging');

Hope this helps! 
- Amy

**Comment by Sushil-Dhiver** [comment]
Thank you very much Amy for your reply
.
I was able to do the paging using the following code.

var footableObject = $('.footable').data('footable');
footableObject.plugins[2].paginate(footableObject, currentPageNumber); 
// using plugins[2] since I have only added a total of 3 footable plugins, paging being the third in the reference list.

I know this is not neat but this serves my purpose.

I tried using the code you gave but was not able to make it work. I didn't add the bookmarkable plugin reference though since I don't think this code is anywhere related to the plugin. please correct me if I am wrong.

Thanks again for your help :+1: 
Sushil.

**Comment by nilpix** [comment]
Hi, @akf , with your code `$(ft.table).data('currentPage', q_page_num);`, you can _set_ the `currentPage`.
But is there any way to _get_ the `currentPage`?

For exemple, to use this number to write into field or text. I'm using angular and I would like to match to a `$scope` variable and use easyly.
Thanks in advance.

**Comment by akf** [comment]
Hi @nilp, `$(ft.table).data('currentPage');` should do it. See the jquery `data` function: 
https://api.jquery.com/data/

I haven't worked with angular, so I won't be much help with that.

**Comment by nilpix** [comment]
I tried but it seems that FooTable kills all things and doesn't detect `currentPage`. I'm currently using FooTable 2.0.3. It seems that `currentPage` doesn't exists or something like that and this is for FooTable, I think so.
I'm trying to make something to indicate to the user: 'page 1 of 50'.
Do you know if that could be an issue of the old version?
