### ISSUE TITLE
Pagination controls disappear on phone (with workaround)

### ISSUE THREAD

**Issue by Zeophlite** [fooplugins/FooTable#281]
# Issue

I have found using pagination and data-hide has an issue where the the pagination controls are hidden for certain devices.  For example:

```
      <table class='footable table'>
        <thead>
          <tr>
            <th data-toggle='true'>Name</th>
            <th data-hide='phone'>Blurb</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Some guy</td>
            <td>Some blurb</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td class='text-center' colspan='2'>
              <ul class='pagination'></ul>
            </td>
          </tr>
        </tfoot>
      </table>
```

When resized to a phone, the pagination controls are hidden.
# Workaround

```
        <tfoot>
          <tr class='footable-row-detail'>
            <td class='text-center' colspan='2'>
              <ul class='pagination'></ul>
            </td>
          </tr>
        </tfoot>
```

i.e. add `class='footable-row-detail'` to the `tr` in `tfoot`
# Cause

This selector picks up the row in the footer ( https://github.com/bradvin/FooTable/blob/V2/js/footable.js#L610 )

```
selector += ', > tfoot > tr:not(.' + cls.detail + ') > td:nth-child(' + count + ')';
```

Then `.footable-paginate` is added to that row ( https://github.com/bradvin/FooTable/blob/V2/js/footable.js#L618 )

```
if (data.hide[breakpointName] === false) $column.addClass('footable-visible').show();
```

**Comment by liquidvisual** [comment]
Just stumbled across this myself. Very very annoying. Thanks for the write up! 

Could the author please update this simple change into the core?

**Comment by equiman** [comment]
Wow thanks!!!

Just adding `class="footable-row-detail"` to `tr` solve my hiding footer problem on mobile devices. Now works like a charm.

Footer with Problem

``` html
    <tfoot>
        <tr class="footable-row-detail">
            <td colspan="6">
                <div class="text-center hide-if-no-paging">
                    <ul class="pagination"></ul>
                </div>
            </td>
        </tr>
    </tfoot>
```

Footer Fixed with `<tr class="footable-row-detail">`

``` html
    <tfoot>
        <tr class="footable-row-detail">
            <td colspan="6">
                <div class="text-center hide-if-no-paging">
                    <ul class="pagination"></ul>
                </div>
            </td>
        </tr>
    </tfoot>
```

I think it can be solved easily adding this info on documentation examples.
