### ISSUE TITLE
Data Attribute: data-class 

### ISSUE THREAD

**Issue by Clementtang** [fooplugins/FooTable#282]
Hi, the documentation describes the "data-class" data attribute is to "Use to specify a CSS class to apply to all cells in a column."

Therefore, I added data-class="text-center" to one of the th element, and then added the styles in css for the class text-center.

However, it doesn't take any effect, all of my td elements of that specific column still didn't apply any class, but all the other footable functions works.

Did I missed anything?

**Comment by steveush** [comment]
Hi, I've made a small change to the way FooTable handles things when there are no active breakpoints or hidden columns (basically it used to exit early under these conditions) so that the data-class attribute should work correctly now.

**Comment by Clementtang** [comment]
Thanks for fix :D
