### ISSUE TITLE
Can You Pass A Filter Through A Link From One Page To Another

### ISSUE THREAD

**Issue by tapnarts** [fooplugins/FooTable#283]
is it possible to some how pass a link to the page with the table that would contain a keyword to search?

For instance, instead of going to...
http://fooplugins.com/footable/demos/filtering.htm

Then needing to add the keyword, such as Suspended, to filter in the search. 

Could I pass it through a link on another page?
http://fooplugins.com/footable/demos/filtering.htm?filter=Suspended

**Comment by dcblogdev** [comment]
I've found a way to do this:

This select the value in the select menu

```
<select class="filter-status">
    <option></option>
    <option value="active" <?php if($_GET['filter'] == 'active'){ echo 'selected=selected';}?>>Active</option>
    <option value="disabled" <?php if($_GET['filter'] == 'disabled'){ echo 'selected=selected';}?>>Disabled</option>
    <option value="suspended" <?php if($_GET['filter'] == 'suspended'){ echo 'selected=selected';}?>>Suspended</option>
</select>
```

Then to apply that to the filter before the

```
$('.filter-status').change(function (e) {
```

Add:

```
$('table.demo').data('footable-filter').filter( $('#filter').val() );
```

**Comment by dcblogdev** [comment]
oh I renamed the .html to .php

**Comment by jeskill** [comment]
It would be great to have this feature as a plugin for Footable in Wordpress ...
