### ISSUE TITLE
Breakpoint Calculation and Classes Being Removed

### ISSUE THREAD

**Issue by cpoteet** [fooplugins/FooTable#284]
Two things:

1) The value for the breakpoints absolutely should be based on viewport by default. I wasted far too much time trying to figure out what was going on. All other media queries operate that way (at this point in time), and I suggest you go that route and allow someone to override with a element width.

2) I noticed classes would get dropped between custom breakpoints for some reason. I had my custom breakpoints:

```
   breakpoints: {
         small: 480,
         medium: 740
   },
```

But for some reason between the two, medium would drop and "phone" would come back. Then small would finally trigger. It was frustrating.

**Comment by cpoteet** [comment]
At the very least you should note how the breakpoint calculation happens in your documentation.

**Comment by tkent** [comment]
Just ran into the same confusion and was going to file an issue when I found this. It certainly seems like the wrong behavior.

**Comment by bradvin** [comment]
This is being addressed in V3 of FooTable - it was a bad design choice to change to the table width over the viewport width. V3 will have the default based on viewport width and an option to change it to table width. We are hoping to commit a V3 branch to the repo in the next 2 weeks
