### ISSUE TITLE
colspan isnt counted well when th is in tbody

### ISSUE THREAD

**Issue by mibocs** [fooplugins/FooTable#286]
Colspan of .footable-row-detail-cell row isnt calculated well when th is used in tbody cos this th wont be count into sum of colum.

for example:

`<tbody>`
 `<tr>`
    `<th>hhjjh</th>`
    `<td>ghghgh</td>`
   `<td>ghghgh</td>`
 `</tr>`
`</tbody>`

In this case colspan of .footable-row-detail-cell will be 2 instead of 3.

Fix:

`var colspan = $row.find('> td:visible').length;`

should be:

`var colspan = $row.find('> td:visible, > th:visible').length;`

**Comment by mibocs** [comment]
Why close?

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

Thanks

**Comment by mibocs** [comment]
But will the old issues be moved to the new branch? I mean can i/we expect that these will be fixed in v3?

**Comment by steveush** [comment]
V3 is a complete re-write, the old issues have no relevance to the new branch, it's a completely different code base.

**Comment by mibocs** [comment]
Yes but in my case there is no code, but this issue what i created could be checked on the new code base too to make sure it is working well.
