### ISSUE TITLE
data-class is not working without data-hide

### ISSUE THREAD

**Issue by SLemming** [fooplugins/FooTable#287]
I've got many producttables with the footable plugin working great but one is set by the editor without data-hide-Attribute because it only has two columns and none should be hidden.
And then data-class doesn't work and all other classes (footable-visible etc.) aren't set in the tbody. I generated a JSFiddle:
http://jsfiddle.net/xxemtkw9/2/

The first table has the result expected (class "head" ist set to all cells in a column), table two doesn't have.

I think data-class should work without data-hide. Can you please fix that? Is there a workaround for the problem?

**Comment by steveush** [comment]
Hi, I've made a small change to the way FooTable handles things when there are no active breakpoints or hidden columns (basically it used to exit early under these conditions) so that the data-class attribute should work correctly now.

**Comment by SLemming** [comment]
Thanks, it's working well.
