### ISSUE TITLE
Custom breakpoints do not override default

### ISSUE THREAD

**Issue by hpatoio** [fooplugins/FooTable#288]
I've defined my custom breakpoints:

``` javascript
$('#myFooTable').footable({
        breakpoints: {
          phoneP: 290,
          phoneL: 530,
          tabletP: 768,
          tabletL: 992
        }
});
```

But the default one (`phone` and `tablet`) are still set. So I've to specify them when I set the `data-hide` property.

I think my setup should overwrite the default values. Is this a bug ? Otherwise can you explain why you decided to make it works this way ?

Thanks

**Comment by Hydraner** [comment]
I'm facing the same issue. For me this behaves like a bug, since only one "breakpoint" is active at once. So if I'm defining a {mobile: 600} option, this will not be true below 480px

**Comment by Hydraner** [comment]
After some hours of crying, I found out a workaroung for this issue:
Before you call the plugin use

``` javascript
window.footable.options.breakpoints = {};
```

**Comment by bradvin** [comment]
the following line merges the options:

```
var o = $.extend(true, {}, w.footable.options, options); //merge user and default options
```

The default jQuery extend is merging the options together. Perhaps we check first if the breakpoints are being set and if so, set the defaults to {} as @Hydraner does above

@steveush what you reckon is the best route here? I think we will need to do this in V3

**Comment by hjzheng** [comment]
Yes, I  found the problem too.

``` javascript
    $(function () {
        $('.footable').footable(   
                   {
                       breakpoints: {
                            tiny: 480,
                            medium: 1024,
                            big: 1280
                       }
                   }
             ).bind({
                'footable_breakpoint' : function(e) {
                    console.log(e.breakpoint);      
                }
             });
      });
```

The output in console when I resize the brower:
![q -20141209104302](https://cloud.githubusercontent.com/assets/4166657/5351395/4f7d9304-7f90-11e4-8b52-556851dfa347.png)

**Comment by beefydog** [comment]
So, no solution to this?

**Comment by steveush** [comment]
V2 is not supported and V3 does not have the same issue. So the solution is upgrade to V3 if you're still on V2.
