### ISSUE TITLE
Updating Field Values in Detail Row

### ISSUE THREAD

**Issue by thomstark** [fooplugins/FooTable#292]
I submitted a paid support ticket for this issue, then realized that I submitted it to the WordPress plugin support forum, so my apologies. The support ticket I created included administrator login credentials to the dev site. 

Basically, updating data in a detail row seems to be hit or miss. I have text, select, and textarea fields in my detail row that become visible when you click the edit icon in the actions column. The edit icon then becomes a save icon. 

I can change the HTML in the detail row for displaying the values, but I cannot change the field values themselves on subsequent clicks of the edit button. For instance, I click edit, I change some text in a textarea field, then click save. The new value from the textarea will update the div for displaying that value in the detail row, but then when I click edit again, the value in the textarea is back to the original value. This is not a problem in the main TR, only in the detail row. 

Also, when the actions column is pushed to the detail row on tablets and mobiles, I cannot do a simple $('.icon-edit', context).addClass('icon-save').removeClass('icon-edit');

It works fine in when the actions column is in the main TR, but not when in the detail row.

**Comment by bradvin** [comment]
@thomstark I have just merged in some changes to cater for editable textboxes within FooTable.

Try it out and let me know if it works for you now.
