### ISSUE TITLE
How to disable striping

### ISSUE THREAD

**Issue by Clementtang** [fooplugins/FooTable#294]
I would like to activate only some of my tables to have them stripped, is there an attribute for me to disable it?

Thanks!

**Comment by bradvin** [comment]
check out https://github.com/bradvin/FooTable/blob/V2/js/footable.striping.js#L27

it seems if you add

```
data-striping="false"
```

onto the table element then striping will be ignored

**Comment by Clementtang** [comment]
Nice, thank you very much, and I guess the data attributes of the documents page need to be updated. :)

Thanks again!
