### ISSUE TITLE
Performance enhancement suggestion

### ISSUE THREAD

**Issue by ClubWebware** [fooplugins/FooTable#298]
We have a table where the THEAD consists of 2 TR-elements, where the 1st TR has some pagination controls en the 2nd TR has the column headers.

One of the pagination controls in the 1st TR is a select list with the total number of pages.
When the dataset is really large, the number of pages may be large as well. And that turned out to be a  real problem for FooTable.

We had a table where the pages select list in the 1st TR had over 4.000 option elements, and it took FooTable an incredibale amount of time to handle the table. 
The entire webpage became unresponsive (hanging) while FooTable was trying to do what it is supposed to do.

We managed to solve this issue with a small change to the FooTable code:

In the ft.addRowToggle function, we changed:

```
                var selector = '> tbody > tr:not(.' + cls.detail + ',.' + cls.disabled + ') > td:nth-child(' + (parseInt(col.index, 10) + 1) + '),' +
                                        '> tbody > tr:not(.' + cls.detail + ',.' + cls.disabled + ') > th:nth-child(' + (parseInt(col.index, 10) + 1) + ')';
                $table.find(selector).not('.' + cls.detailCell).prepend($(opt.toggleHTMLElement).addClass(cls.toggle));
```

into:

```
                var _oTBody = $table.find('> tbody');
                var selector = '> tr:not(.' + cls.detail + ',.' + cls.disabled + ') > td:nth-child(' + (parseInt(col.index, 10) + 1) + '),' +
                                        '> tr:not(.' + cls.detail + ',.' + cls.disabled + ') > th:nth-child(' + (parseInt(col.index, 10) + 1) + ')';
                _oTBody.find(selector).not('.' + cls.detailCell).prepend($(opt.toggleHTMLElement).addClass(cls.toggle));
```

And it's working like a charm now.

Maybe someone can apply this code change to the base product?

**Comment by M3lkior** [comment]
Hello,

I have the same issue to report, do you plan to merge this code ?

Thanks in advance.

**Comment by liquidvisual** [comment]
Merge please!

**Comment by neuropass** [comment]
megrge!!! Same issue: https://github.com/fooplugins/FooTable/issues/334

**Comment by SiteSplat** [comment]
Definitely needs some refactoring. Its terribly slow at handling many rows and tables this is really the purpose of the plugin. Could you look into the performance part?

**Comment by chalchis** [comment]
I think it could be solved if smash to go down the scroll load more items by ajax

**Comment by yb11206** [comment]
i am having performance issues even with 10 rows of data
if i have input boxes in the table td any solution please...

**Comment by bradvin** [comment]
@neuropass I will gladly merge if you submit a pull request. We have stopped working on the V2 branch completely and are now working on the V3 branch which is a complete rewrite.

The main goal of the V3 branch was to handle a LOT of data. Our initial tests using V3 can handle 10000 rows of data - I would suggest having a look at that branch, but it is still in active development and will likely change quite a bit before it is officially released

**Comment by SiteSplat** [comment]
@bradvin  I didnt know there was v3. I cant find the link on github.

**Comment by bradvin** [comment]
https://github.com/fooplugins/FooTable/tree/V3

**Comment by neuropass** [comment]
That's great thank-you! I just looked into the files and the dist version is 140+kb. :-/ Say I wanted to use footable core only just to allows the table to collapse etc like the v 2, which is the correct JS file I need to use? Is it /js/FooTable.js ?

Thanks!
