### ISSUE TITLE
Autogenrated markup

### ISSUE THREAD

**Issue by matteo-hertel** [fooplugins/FooTable#299]
Hello, 

is there a way to change the auto generated markup of the hidden td and th?
I went through the documentation but there's no reference to that.

Cheers

**Comment by bradvin** [comment]
I think you are looking for the createDetail option

**Comment by matteo-hertel** [comment]
Thanks mate, I saw on the source code that that's the option I'm looking for!

https://github.com/bradvin/FooTable/blob/V2/js/footable.js line 54
