### ISSUE TITLE
Columns visibility based on priority rather than break points.

### ISSUE THREAD

**Issue by brendanheywood** [fooplugins/FooTable#3]
Love it! Heaps better than the other plugins I've been looking into. 

But there is one thing which I'd prefer to see which is removing columns based on priority rather than set break points. eg:

``` html
<table>
 <tr>
 <th data-priority="1">First Name
 <th data-priority="1">Last Name
 <th data-priority="2">Age
 <th data-priority="3">Home town
 <th data-priority="3">Fav color
</tr>
<tr>
<td>....

```

To be more concise you could assume that if no priority is specified then it is the highest priority.

There are no break points specified at all. On resize it just checks if the table overflows it's containers width and if so then it removes a single lowest priority visibile column, and then checks if the table fits. If not then remove another one. If that priority level runs out then go down to the next priority level. ie If you run it on a table with no priority levels then it will just progressively remove to rightmost columns until it fits.

Pros:
- less or zero config
- will work with td's that may have wildly varying data sizes
- will work when nested inside a container which isn't the width of the device which happens quite often

Cons:
- maybe a small bit of reflow performance

**Comment by brendanheywood** [comment]
Oh and the most important pro is that is work better on more devices that don't neatly fit into the 'mobile' or 'tablet' ranges.

**Comment by bradvin** [comment]
Hey Brendan,

That is a very cool idea, and an awesome idea for a future add-on to FooTable

thanks
