### ISSUE TITLE
A way to delere phone & tablet breakpoints ?

### ISSUE THREAD

**Issue by M3lkior** [fooplugins/FooTable#301]
Hi,

I'm using Footable (great job, by the way !) with Bootstrap table and i want to create Bootstrap breakpoints to use with the plugin like this :

<pre>
      breakpoints : {
                  xs : 767
                  sm : 992,
                  md : 1199
              },
</pre>

Use : 

```
<thead>
           <tr>
             <th>Nom</th>
             <th data-hide="xs">Département</th>
             <th data-hide="xs, md"><abbr title="CP">Code Postal</abbr></th>
           </tr>
         </thead>
         <tbody>
```

Problem : phone and tablet breakpoint are considers by the plugin and redrawn the table.
I would like to only set my customs breakpoints in data-hide attrs without use phone and tablet breakpoints in data-hide.

Is it possible ?

**Comment by liquidvisual** [comment]
+1

**Comment by bradvin** [comment]
please check out the V3 branch

**Comment by liquidvisual** [comment]
Thanks Bradvin. Is V3 stable?

**Comment by bradvin** [comment]
We think it is more stable than the current version. It is a complete rewrite from the ground up, so we want more people to test it before it becomes officially released. Please let us know what you think

**Comment by liquidvisual** [comment]
Awesome! I'll give a whirl then. Cheers for the tip.

**Comment by M3lkior** [comment]
Thanks Bradvin.

Uses of plugins remains unchanged ?

And about this issue ? https://github.com/fooplugins/FooTable/issues/315

The best way to force people using this new rewrite version is to make V3 Branch the current version to use ;)

**Comment by Haixing-Hu** [comment]
Hi, I have fixed this issue and created a pull request.

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

Thanks
