### ISSUE TITLE
Multiple checkboxes with values that filter result

### ISSUE THREAD

**Issue by kedano** [fooplugins/FooTable#303]
Is there a way to recreate something similar to the checkboxes on the left of this page to filter data in a footable table?
http://www.finn.no/finn/car/used/result?carmodelmake=0%2F2999&sort=0

I guess what I'm asking for is the same functionality described in #138

**Comment by kedano** [comment]
I solved this with a edited version of the following answer on stackoverflow:
http://stackoverflow.com/a/24253543/996068

It does a regex search for your values on the table. My working code is live here:
http://www.hiof.no/studier

And the code in my repo:
https://github.com/hiof/frontend/blob/master/app/assets/js/components/_component_study.js#L85

#138

**Comment by kartheekgj** [comment]
couldnot find the repo code 
how to perform multiple textbox or checkbox searches using footable?

**Comment by kedano** [comment]
I've refactored the code abit. 

The regex filter is available here:

https://github.com/hiof/frontend/blob/master/app/assets/js/components/__helper.js#L422

The filter is used in this plugin:

https://github.com/hiof/course-catalogue/blob/develop/app/assets/js/course-catalogue.js

—
Kenneth Dahlstrøm

**Comment by kartheekgj** [comment]
Thanks for the link
