### ISSUE TITLE
filtring after refresh?

### ISSUE THREAD

**Issue by mekeke79** [fooplugins/FooTable#307]
Hi, 
I made page with refreshing div every 1minute.
Filter form is outside the div.
Sorting works fine but, when refreshing heppen new content is with all data.

Is any way to keep filtering beetwen refreshing ?

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this specific issue in V3 you would simply need to store the current page/filter/sort values and supply them as options when the page is reloaded. I would simply use localStorage for these values but how you decide to implement it is up to you.

Thanks
