### ISSUE TITLE
Children of td not clickable

### ISSUE THREAD

**Issue by robme** [fooplugins/FooTable#309]
My table cells have their content inside divs. In the div which becomes the only row on mobile, which gets the toggler:

``` html
<td class="footable-visible footable-last-column footable-first-column">
  <span class="footable-toggle"></span>
  <div>Title</div>
  <div>Content</div>
</td>
```

If you click on the toggler (the plus sign) then it toggles the details, and also if you click on any part of the td (e.g. in the margins of the divs). But if you click on any of the text in the divs then nothing happens. It has the pointer cursor but never toggles anything. It's not good from a usability point of view.

**Comment by ldeck** [comment]
Yes, how might this be fixed?
