### ISSUE TITLE
Add ARIA roles when sorting tables

### ISSUE THREAD

**Issue by edmelly** [fooplugins/FooTable#31]
I'm making the switch from DataTables, and one thing that plugin handles very well is accessibility. Specifically, adding ARIA roles to the table where needed. e.g., when a column is sortable the `aria-sort` attribute is added and the `aria-label` amended to reflect that:

(`aria-sort="ascending" aria-label="Title: activate to sort column descending"`).

Is a similar implementation on the cards for FooTable?

**Comment by steveush** [comment]
Hi edmelly,

Apologies for the late response I haven't had a PC this last week due to my new motherboard having a fault and being sent back for testing :( Anyway this seems like a simple addition and I'll keep it in mind for the next round of updates I do.

Thanks
Steve
