### ISSUE TITLE
Sortable dates: Different format using custom attribute

### ISSUE THREAD

**Issue by X-Raym** [fooplugins/FooTable#316]
Hi!
I highly needed a way to have sortable dates in HTML table.
I know your plugin is able to do it, but we have to convert the dates to unix format first. This is not a very flexible way to use it, and there is no way to make the process automatic, even with other softwares. I just cannot do it, there is too many of them in my table.
I saw than a jquery plugin sorttable, has a very clever way to manage different date format, using some kind of "keys". Look at this demo below:
http://www.kryogenix.org/code/browser/sorttable/#dates
Do you think a similar system could developped for footable ? it would be very nice!

Thanks for listening!

**Comment by bradvin** [comment]
@X-Raym, 
thanks for the link. @steveush can see how easy this is to add to V3 branch

**Comment by steveush** [comment]
@X-Raym and @bradvin this is already possible using what is in FooTable at present. Sorttable is just using numeric sorting and the "key" is a date provided in a format where newer dates are numerically larger allowing it to sort by them, the same thing we do ourselves by using a dates tick value. The same can be achieved using the data-value attribute specifying the "key" and then marking the column as numeric using the data-type attribute.

``` html
<table class="footable">
  <thead>
    <tr>
      <td data-type="numeric">My Date</td>
    </tr>
  <thead>
  <tbody>
    <tr>
      <td data-value="201503150947">10 March 2015, 09:47 AM</td>
    </tr>
  </tbody>
</table>
```

**Comment by X-Raym** [comment]
Oh nice! This is fare more handy to tranpose than unix time!
Do you think it would be possible to write the 'date format' on the column header, so that we dont have to convert the date as data attribute? For example, if I tell the header 'yyyy-mm-dd', then it would be able to parse the column value itself without having to write data attribute for each cell ?
Thanks for your support and for your great work on FooTable!

**Comment by steveush** [comment]
At present we do not support date formats simply due to the complexity of handling dates in JavaScript and the bloat it would add to the plugin for a single feature. You should however be able to make a custom column format by providing just a parser and sorter via the options (NOTE: The name of the parser and sorter can be anything but they must be the same for both options, in this case I called it "custom"):

``` javascript
$('table').footable({
  parsers: {
    alpha: window.footable.options.parsers.alpha, // default alpha & numeric parsers
    numeric: window.footable.options.parsers.numeric,
    custom: function(cell){
      // Here you are passed the TD cell element and must return the parsed value for the cell.
      // You will need to use whatever method you like to retrieve the cell's actual value.
      // So for something like YYYY-MM-dd you could do:
      var str = $(cell).text(),
        parts = str.split('-'),
        YYYY = parseInt(parts[0]),
        MM = parseInt(parts[1]),
        dd = parseInt(parts[2]);
      // When making the new date remember months are indexed from 0 so minus 1.
      return new Date(YYYY, MM-1, dd);
    }
  },
  sorters: {
    alpha: window.footable.options.sorters.alpha, // default alpha & numeric sorters
    numeric: window.footable.options.sorters.numeric,
    custom: function(a, b){
      // here you are passed two values from the column and you must return a comparison of the two.
      if (a === b) return 1;
      if (a < b) return -1;
      return 1;
    }
  }
});
```

Once you have those two working you can simply specify your column type as "custom" as it is in this case using the data-type attribute.

``` html
<table>
  <thead>
    <tr>
      <td data-type="custom">My Date</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>2015-03-10</td>
    </tr>
  </tbody>
</table>
```

Please note I haven't tested the above but it should get you pointed in the right direction to accomplish what you are asking for.

**Comment by X-Raym** [comment]
You are right, no need to be included!
Sharing script snippet like that is a perfect solution :)

Thanks for your time on this! I will test it asap, and make it work if if doesn't already! Cheers! :)

**Comment by HopeLyn** [comment]
@steveush Thx for your advice! It successfully solved my problem.

**Comment by SuizideFF** [comment]
Is there a parser sorter for the following formats:
dd/mm/yyyy
dd/mm/yy

**Comment by kaiwech** [comment]
Hello,

i am using footable V 3.1.5 and i have a problem with date sorting.

I am getting row data via ajax in JSON format and i want to use the solution like

<table class="footable">
  <thead>
    <tr>
      <td data-type="numeric">My Date</td>
    </tr>
  <thead>
  <tbody>
    <tr>
      <td data-value="201503150947">10 March 2015, 09:47 AM</td>
    </tr>
  </tbody>
</table>


How can i put the data-value="201503150947" in JSON .

My column definition looks like this
  ....
  {"name":"lastEditDate","title":"Letzte Änderung","type":"numerics", "style":{"width":80,"maxWidth":150}},
  ....

and the rows are defined with

.....
$ticketObj[$i]->creationDate           = $ticket['creationDate'];
....

Please, can someone help.

Sorry, but my english is very bad ;-)

Thanks !
