### ISSUE TITLE
V3 - JsDoc Online ?

### ISSUE THREAD

**Issue by M3lkior** [fooplugins/FooTable#317]
Hello bradvin,

It is possible to publish your JsDoc to access online ?

I start to try your V3 and it seems really good (and thanks for the JsDoc ! ;)). 

For the ajax functionnality, i'm using Spring MVC Pageable Structure for JsonResponse wich contains this json properties : 
- totalElements
- totalPages
- content ( = row)
- ...

It is possible to make FooTable.ResponseData  more flexible so that it can adapt to another json structure ?

Congratz for your rewrite job !

**Comment by lenamtl** [comment]
Hi, where can I download the v3?

**Comment by M3lkior** [comment]
In the Github V3 branch :

https://github.com/fooplugins/FooTable/archive/V3.zip

The jsDoc is in docs directory

**Comment by steveush** [comment]
Hey @M3lkior, sorry I think I'm missing something here, do you want the JsDoc template that I made to create the docs available to you? Or are you simply wanting the already generated docs published somewhere online?

As for your second issue regarding the FooTable.ResponseData object, there was a little mistake in the docs when I took a look at them, the properties available on the object should be as below:

``` javascript
{
  paging: {
    total: -1 // Specifies the total number of rows on the server not the amount being shown
  },
  rows: [] // An array of JSON objects containing the data for the rows to be displayed. If you have paging enabled this should be whatever the number of rows specified to be displayed.
}
```

With this in mind you can massage your response from Spring MVC into one that FooTable can interpret by doing something like the below pseudo code.

``` javascript
$('table').footable({
    ... // Any other options
    columns: ..., // You must define your columns so FooTable knows how to read your JSON row data
    ajaxEnabled: true,
    ajax: function (requestData) {
        // Do what you need to do with the FooTable.RequestData to initiate an ajax call to the server
        return $.ajax({
            type: 'GET',
            dataType: 'JSON',
            url: 'http://your-endpoint.com',
            data: requestData
        }).then(function(response){
            // On success massage the server response into one that FooTable can recognize (The FooTable.ResponseData object)
            return {
                paging: {
                    total: response.totalElements
                },
                rows: response.content
            };
        });
    }
});
```

The ajax option requires you to provide a jQuery.Deferred object for it to work correctly, due to that the above chaining method using THEN also becomes available to you to massage your response from the server in any way you like before handing it over to FooTable. When rewriting FooTable I thought this the best approach as it cuts down on a lot of unnecessary code in FooTable to handle multiple response types and what is required to get it to work is fairly small and can change a lot depending on your data source.

**Comment by M3lkior** [comment]
Thanks for yours answers @steveush ,

For the jsDoc, i'm just wanting the already generated docs published somewhere online:)
By the way, good job for your template, i think i will reuse it for my owns projects ;)

I will do the test for my second issue, thanks a lot :)

I developed two plugins in Footable V2 for serverside paging and sorting based on Handlebars templates and Spring MVC Pageable Structure (ie. the server-side response feeds the plugins options like totalPages, pageNumber, etc and do a server-side call when sorting/changing page). I think i will do the same for Footable V3 if you are interested

**Comment by steveush** [comment]
@M3lkior thanks for the compliments on the template, the only reason I haven't made it publicly available is that it was built on a BETA version of JsDoc that doesn't require Java to be installed and I made a few modifications to it so it's not exactly standard :) I have been meaning to go back and update the template to a newer more stable version of JsDoc and fix/update the documentation with examples like the above however I am focused on 2 other projects and have not had the time to get back and finish it up. This is the reason the V3 version is not the main branch at the moment, lack of documentation and testing.

If you find any issues please log them with V3 in the name so I can take a look as it has been tested but not as much as I would like.

As for the plugins feel free to make and document them and we can link to your repo from our docs once they get done :) Just understand that the V3 branch is new and there will be changes to the way components work if a bug is discovered or a new feature is implemented that requires it etc. so you would need to update them accordingly.

**Comment by steveush** [comment]
@M3lkior also forgot to mention, the JsDocs that are generated now are not hosted anywhere as they will be hosted using Git Pages once the V3 branch becomes the main branch.

**Comment by steveush** [comment]
@M3lkior put the breaks on! I believe I was looking at an old version of the ResponseData object when I responded to your previous reply. Apologies for the confusion, the documentation is correct and the ResponseData object looks like the below:

``` javascript
{
  totalRows: -1, // Specifies the total number of rows on the server not the amount being shown
  rows: [] // An array of JSON objects containing the data for the rows to be displayed. If you have paging enabled this should be whatever the number of rows specified to be displayed.
}
```

Which means the ajax options would change to look like the below:

``` javascript
$('table').footable({
    ... // Any other options
    columns: ..., // You must define your columns so FooTable knows how to read your JSON row data
    ajaxEnabled: true,
    ajax: function (requestData) {
        // Do what you need to do with the FooTable.RequestData to initiate an ajax call to the server
        return $.ajax({
            type: 'GET',
            dataType: 'JSON',
            url: 'http://your-endpoint.com',
            data: requestData
        }).then(function(response){
            // On success massage the server response into one that FooTable can recognize (The FooTable.ResponseData object)
            return {
                totalRows: response.totalElements,
                rows: response.content
            };
        });
    }
});
```

Again, sorry for the confusion, I was looking at an earlier version of V3 before I had flattened the objects.

**Comment by steveush** [comment]
@M3lkior I was thinking about your plugin and you can wrap up the Ajax functionality quite neatly without creating an actual FooTable addon by doing something like the below:

``` javascript
function SpringMVCAjax(url){
    return function(requestData){
        return $.ajax({
            type: 'GET',
            dataType: 'JSON',
            url: url,
            data: { // Here massage the requestData object into one your server can understand
                page: requestData.currentPage,
                ...
            }
        }).then(function(response){
            // On success massage the server response into one that FooTable can understand (The FooTable.ResponseData object)
            return {
                totalRows: response.totalElements,
                rows: response.content
            };
        });
    };
}
```

And then to use it:

``` javascript
$('table').footable({
    ... // Any other options
    columns: ..., // You must define your columns so FooTable knows how to read your JSON row data
    ajaxEnabled: true,
    ajax: SpringMVCAjax('http://your-endpoint.com')
});
```

**Comment by M3lkior** [comment]
Thanks @steveush.

The idea is to generate paging elements with serverside url to call to display next/previous pages. It is possible with your rewrite ?
Same idea for sorting : send indications about sort options to serverside when we are clicking on columns.

Here is a sample of my plugin code in Footable V2, working with Handlebars : 

```

        //do server-side call whith paging params
        p.doServerCall = function(ft, pageNumber, ajaxCallback){
            $table = $(ft.table),
            ft.pageInfo.currentPage = pageNumber;
            $table.data('currentPage', pageNumber);

            $.ajax({
                url : ft.options.serverSide.url,
                dataType: "json",
                data : ft.pageInfo.requestParams()


            }).done(function(data, textStatus, jqXHR){
                //update paging results informations, from server-side
                $table.data("totalElements", data.totalElements)
                    .data("totalPages", data.totalPages);
                ft.pageInfo.totalElements = data.totalElements; 
                ft.pageInfo.totalPages = data.totalPages;
                ft.pageInfo.totalPages.newPage = data.number;

                if($.isFunction(ajaxCallback)){
                    ajaxCallback(data);
                }



                ft.raise('footable_serverside_called');
            });
        };

        //fill page thanks to handlebars template
        p.fillPage = function (ft, tbody, datas, buildTable) {
                var _html = fwk.ui.handlebars.getHtml(ft.pageInfo.handlebarsTemplateSelector, datas.content); //rebuild footable thanks to handlebars template with new set of datas

                if($(_html).find(ft.options.bodySelector).length > 0){
                    tbody.html($(_html).find(ft.options.bodySelector).html())
                        .trigger("footable_redraw"); //replace table body content with new set of results
                }else{
                    throw new Error("Unable to find table body when retrieving handlebars template");
                }
            ft.raise('footable_page_filled');
        };
    }
```

**requestParams function** build a query string for server-side with paging and sorting options like this : 

<pre>jsonSpringData?labelReal=lille&departmentLabel=nord&size=10&page=3&sort=population,DESC</pre>

size, page and sort params are filled thansk to **requestParams function** when user interacts with Footable Paging/sorting plugin

**Comment by steveush** [comment]
@M3lkior it is possible to handle the sort and paging, it is one of the main reasons for the rewrite. The ajax function is called every time a user performs paging, sorting or filtering, so in effect it replaces your p.doServerCall. The FooTable.RequestData object contains all the properties at the time the ajax function is called. If you wanted you could break it down like the below:

``` javascript
ajax: function (requestData) {
    if (requestData.filterQuery && requestData.filterColumns){
        // You need to filter the rows using the supplied query and columns
    }
    if (requestData.sortColumn && requestData.sortDirection){
        // You need to sort the rows by the supplied column and direction
    }
    if (requestData.currentPage && requestData.pageSize){
        // You need to reduce the rows using the supplied page size and number
    }
}
```

But the above is only showing the basic idea, you should handle those properties on the server side. Looking at what you provided above you could use the below:

``` javascript
function doServerCall(url){
    return function(requestData){
        return $.ajax({
            type: 'GET',
            dataType: 'JSON',
            url: url,
            data: { // This will append params onto the url, example: page=1&size=10&sort=column_name,DESC
                page: requestData.currentPage,
                size: requestData.pageSize,
                sort: requestData.sortColumn+(requestData.sortDirection ? ','+requestData.sortDirection : '')
            }
        }).then(function(response){
            // On success massage the server response into one that FooTable can understand (The FooTable.ResponseData object)
            return {
                totalRows: response.totalElements,
                rows: response.content
            };
        });
    };
}
```

And then use it like I mentioned previously:

``` javascript
$('table').footable({
    //... // Any other options
    //columns: ..., // You must define your columns so FooTable knows how to read your JSON row data
    ajaxEnabled: true,
    ajax: doServerCall('http://your-endpoint.com')
});
```

That should handle your paging and sorting, unfortunately your previous example doesn't handle filtering so I can't provide a way to do that however you should be able to implement it without too much of a problem as the properties (filterQuery and filterColumns) are already supplied on the RequestData object, you simply need to update the doServerCall function above and your server side code to handle them.

Unfortunately as for mustache/handlebars support I will need to dig a little deeper to see how I could implement addons for them and so can't give you an answer at the moment however I have some ideas that I will try.

**Comment by M3lkior** [comment]
Thanks @steveush.

I will follow your plugin development  with a big interest.

Maybe, if i have time, contribute for template engines development ;)

**Comment by M3lkior** [comment]
Hello @steveush ,

Finally, i'm interested about your JsDoc3 template . Are you always willing to provide me ? :p
