### ISSUE TITLE
Desktop hides 

### ISSUE THREAD

**Issue by manking109** [fooplugins/FooTable#320]
When I use 
`<th data-hide="tablet,phone" >`

The data-hide also hides on desktop.

How do I stop that?

**Comment by Tenbrink** [comment]
the data-hide attribute works with breakpoints, it has no device detection. You can define your own breakpoints as seen in http://fooplugins.com/footable/demos/getting-started.htm#docs

**Comment by cathrin-will** [comment]
I would have thought the breakpoints work from window width not the table width?

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this specific issue in V3 you can specify whether to use the table or the viewport to calculate breakpoints which I believe would resolve this issue.

Thanks
