### ISSUE TITLE
Footable sorting issue

### ISSUE THREAD

**Issue by Nicole18** [fooplugins/FooTable#321]
Hi,

I'm using footable with a huge amount of data. 
I saw that is an issue for pagination/sorting because it waits to load all data and after that apply the sorting and the paging - Because of this I had to create my custom paging and sorting to retrieve only the first 50 records and after that call the server for the rest. Now I'm trying to add in the header arrows for the sorting but even that I apply the css class to the th the arrows are not showing up, footable is overwrite it. Do you have any solution for this?

Thanks,
Nic

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

Thanks
