### ISSUE TITLE
getting row when expanded using jQ

### ISSUE THREAD

**Issue by yb11206** [fooplugins/FooTable#323]
this plugin is a good one but ran into a problem when we added input boxes to the tr but then want to save the data to server if its expanded then the data will be divided into two rows and plus the new data from detail row will not be set onto the input boxes when trying to get the value on the input boxes

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this specific issue please take a look at the V3 editing example.

Thanks
