### ISSUE TITLE
Question about detail-name

### ISSUE THREAD

**Issue by lenamtl** [fooplugins/FooTable#325]
Hi,
I'm using a Bootstrap 3 responsive template.
The problem I'm having is the detail-name for example "Not Mandatory"
it having one character two long so it display on 2 lines.
"NotMadatory" will display on one line

So I'm wondering where can I change the settings to allow the space for one extra character, 
where is this  set?

By the way when using bootstrap.css we also need some of the classes from footable.core.css
because it's was not displaying the detail- information correctly without it and also not display the icons.

Thanks

**Comment by steveush** [comment]
Hi,

The detail row header width is simply set using CSS, I suggest using the web inspector in your browser of choice so you can see exactly how it is setup and so you can override what you need to. In V3 this is set using the below CSS class:

``` css
table.footable-details>tbody>tr>th:nth-child(1) {
    min-width: 40px;
    width: 120px;
}
```

Thanks
