### ISSUE TITLE
[V2] How to appendRow (insert before)

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#331]
Hi,
Is there a way/method that appendRow (add row) insert at first the row instead of last row?
Thanks.

**Comment by fejimene** [comment]
Hi @claudchan, have you found a way to properly do that?

**Comment by claudchan** [comment]
Not really but only change at the source js instead. Find append change into prepend.

**Comment by claudchan** [comment]
Also this not works well if having paging on. If you are at some page, click add row, I have to set trigger back to 1st page.

To solve this I have to disable the paging instead and at scroll to first row.

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

Thanks
