### ISSUE TITLE
How to start over/reset when after sort?

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#332]
Hi,
Anyway I could reset/start over the rows after make a sort?
I have an issue when I add a new row (appendRow) after sorted, that row seems to be in other page.

Same question asked before from: 
https://github.com/fooplugins/FooTable/issues/16#issuecomment-58480478

Thanks.

**Comment by steveush** [comment]
Hi,

In V3 this has been addressed and you can use the below to reset sorting to the initial state:

``` javascript
FooTable.get('#table').use(FooTable.Sorting).reset();
```

Thanks
