### ISSUE TITLE
hide-if-no-paging with external paging element

### ISSUE THREAD

**Issue by M3lkior** [fooplugins/FooTable#335]
**hide-if-no-paging** doesn't work when using an external DOM Element thanks to **pageNavigation** paging option

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this specific issue in V3 the paging is simply not displayed if there are no more records to display. There is no longer an option to create an external paging element, instead you can simply hide the default paging elements and then make calls to the plugin API to perform paging using what ever elements you want.

Thanks
