### ISSUE TITLE
Issue with initial table size rendering on safari mobile (IOS).

### ISSUE THREAD

**Issue by spotvader** [fooplugins/FooTable#34]
I am using the footable plugin on two tables that are on separate tabs using jQuery UI tabs.  The tables are working properly and resizing based on the viewport on a regular PC-based browser, but the initial state is not working (scaling down) on the mobile device.  I have to toggle the tabs back and forth about 5 times and THEN the tables resizes as it should.  Any ideas what may cause this?

I am using the following:

jquery 1.7.2
jquery-ui 1.8.16
footable-0.1
footable.sortable-0.1
jquery.ba-bbq

NOTE:  I have seen the other post about multiple tabs and have attempted to apply that fix, but it did not work for me.  I suspect that the jquery.ba-bbq may be the culprit?

**Comment by ghost** [comment]
I'm having this issue as well only I'm seeing it in chrome and ff. I'm using it with bootstrap and using their tabs. I'm also populating the table from my own ajax call to retrieve data before creating the table.

I have a project going live next week with this so any suggestions would be appreciated!

**Comment by bradvin** [comment]
When the one table is hidden, footable sees the width as 0 and the mobile breakpoint fires.
What you need to do is hook into the tab change event and raise the footable resize event on the table.

this demo : https://github.com/bradvin/FooTable/blob/master/demo-with-bootstrap.htm

shows how to get around this issue

**Comment by ghost** [comment]
Thanks so much! For some reason the .trigger method didn't work so I just called it in a timeout javascript function and that took care of it. Really appreciate the quick turnaround!
