### ISSUE TITLE
Filter attribute is needed for <td> 

### ISSUE THREAD

**Issue by efkan** [fooplugins/FooTable#340]
If I reckon without Footable have been developed for mobile applications;
Sometimes when setting a filter for a table we have to add new a hidden column to filter property. For instance if we need to filter Driving License 'yes' records we cannot use 'yes' text to filter. We should add a new hidden field like `[Drv.Lic.Filter]` then we might set this field as `dl-yes` if driving license yes of the record. Then we can use the select\option tags' values to filter the table. 

However, it could be an option as `data-value` within the `<td>` tag like `<td data-value="dl-yes>"` to apply the filter.

```
<label>Driving License</label> 
<select id="dl-select-filter" class="form-control">
    <option></option>
    <option value="dl-yes">Evet</option>
    <option value="dl-no">Hayır</option>
</select>   
<label>Car</label> 
<select id="car-select-filter" class="form-control">
    <option></option>
    <option value="car-yes">Evet</option>
    <option value="car-no">Hayır</option>
</select>   
```

```
[Name]      [Age]   [Drv.License]   [Car]   |   [hidden dl] [hidden car]
Alice       20          yes         yes     |       dl-yes      car-yes
Burton      28          yes         no      |       dl-yes      car-no
Jack        18          no          yes     |       dl-no       car-yes
```

**Comment by steveush** [comment]
Hi,

In V3 you can specify the `data-filter-value` attribute along with `data-value` and `data-sort-value` so you can specify a different value for each if you really wanted to. The default fallback value is `data-value` or simply the `.text()` value of the cell.

Thanks
