### ISSUE TITLE
Cannot change pageSize dynamically if there is a sorted column

### ISSUE THREAD

**Issue by efkan** [fooplugins/FooTable#343]
Hello,

I use select/option controls to change Footable `pageSize` property dynamically. Unless there is a sorted column, it works perfectly. 
However, if there is a sorted column of Footable and `trigger('footable_redraw')` is called it doesn't work and throws the following error;

`Uncaught TypeError: Cannot read property 'sort' of undefined`

**Comment by efkan** [comment]
It was my fault. 
I had defined a variable like `var $ft = $(".footable")` and had tried triggering the same variable. So, I used `$(".footable").trigger('footable_redraw')` instead of `$ft.trigger('foorable_redraw')` and it works...

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this issue specifically please take a look at the [V3 change page size example](http://fooplugins.github.io/FooTable/docs/examples/advanced/change-pagesize.html).

Thanks
