### ISSUE TITLE
row toggling not working 

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#344]
At the beginning  I would like to start writing by saying thank you for the amazing footable tool and I appreciate it. I am a new in the programming so if I am missing anything I give you my deep apologies.

I am using footable and it is working find, however, it will not work until I do a lot of manual resizing of the window.

the code deployed on http://v1.development.s-sharif.divshot.io

all my work is here https://github.com/yasser-kfupm/footableDemo

:)
Thanks in advanced for the help...

**Comment by yasser-kfupm** [comment]
this is my table code 



         <table id="too" class="table footable table-hover table-condensed toggle-circle-filled" >



             <thead >

             <tr>
                 <th  data-hide="phone,tablet">#</th>

                 <th data-toggle="true" >FLT Arr</th>

                 <th  >AET</th>

                 <th data-hide="phone,tablet" >N.TIME</th>

                 <th data-hide="phone,tablet" >A/C</th>

                 <th  data-hide="phone">APU</th>

                 <th >FLT det</th>

                 <th >DET</th>

                 <th data-hide="phone,tablet" >SPOT</th>

                 <th  data-hide="phone,tablet" >REMARKS AET</th>
                 <th  data-hide="phone,tablet" >REMARKS DET</th>

                 <th data-hide="phone">F.CALL</th>

                 <th data-hide="phone,tablet">F.ST</th>

                 <th data-hide="phone">FINAL</th>

                 <th data-hide="phone,tablet">TIME</th>

                 <th data-hide="phone,tablet" >CROW</th>



             </tr>
             </thead>

**Comment by ghost** [comment]
if found the solution .... 

```
    $('.footable').trigger('footable_redraw'); 
    $('.footable').trigger('footable_resize');
```

... I hope some one will found this information helpful
