### ISSUE TITLE
Breakpoints are not honoring TABLE width

### ISSUE THREAD

**Issue by JohnTendik** [fooplugins/FooTable#347]
I have a website with a sidebar, and the content area is around 700px when the page is max size (around 1600px on my pc). Footables checks the page size which is >1200px and then sets the breakpoint value to lg. This is not good because my table has <700px available space. This causes the table to be broken because it tries to show all the columns(lg) when it only have available space for (sm)

Is this an issue only I'm experiencing or am I doing something wrong that's causing this issue? 

PS: I'm using v3.

**Comment by bradvin** [comment]
check out http://fooplugins.github.io/FooTable/docs/getting-started.html#useParentWidth

either use a data attrib:

`<table data-use-parent-width="true">`

or as options:

`jQuery(function($){
    $('.table').footable({
        "useParentWidth": true
    });
});`
