### ISSUE TITLE
How to define multiple row toggler icon columns

### ISSUE THREAD

**Issue by seven-plus** [fooplugins/FooTable#349]
Firstly, I'm loving this plugin, thank you!

My first column is my `data-toggle` row toggler but under a certain breakpoint I have to hide this column but when this happens the row no longer displays any row toggler icon.

To try to address this I added `data-toggle` to multiple columns hoping that when the first column is hidden then the second column (that has the `data-toggle` attr) would display the toggler icon but it didn't work.

Any ideas of how I can fix this please?

Thanks.

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this issue it has been addressed in V3 so you simply specify whether you want the toggle to appear in the first or last column that is visible. See http://fooplugins.github.io/FooTable/docs/examples/basic/row-toggle.html

Thanks
