### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by tburd** [fooplugins/FooTable#35]
First of all, thank you @bradvin for this awesome work!

I would appreciate some help with the filtering code...
I have a table where one of the columns displays item's CATEGORIES, and for some reason I would like to filter the table dynamically according to these categories.

I have tried to change the <input id="filter"> value dynamically, but table is refreshed only after keyup events.

Any tips?

**Comment by tburd** [comment]
I solved this using:

```
$('#filter').val(category).keyup();
```

But is there any other option to filter the table and also sort any given row dynamically?
Thanks

**Comment by bradvin** [comment]
that is a good point, and it would be nice to filter and sort the table programmatically rather than forcing events to fire.

**Comment by Neener54** [comment]
You can accomplish this somewhat with https://github.com/rbayliss/Dropdown-Table-Filter.  It creates dropdowns.  I'm certain it wouldn't take much work to modify this for your situation.

**Comment by phalancs** [comment]
This is exactly what i am looking for, but when I implement the Dropdown-Table-Filter it does not filter but trigger the sort. Hmm. Anyone got this sorted?
