### ISSUE TITLE
Footable heavy data problem

### ISSUE THREAD

**Issue by wasimikukwa** [fooplugins/FooTable#350]
Hi,

I have setup footable in my application with asp.net GridView. It's successfully done and running also fine.
but problem is that when my data comes more then 10,000 rows then page hangs. but whenever I remove footable and set only simple asp.net GridView  then page shows data successfully. But whenever I setup Footable CSS and JS Scripts then I get problem. I get problem after set the paging means sorting goes perfect.

please help for it.......
I am waiting for your reply....

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

Thanks
