### ISSUE TITLE
Sortable

### ISSUE THREAD

**Issue by mikhailrepka** [fooplugins/FooTable#351]
Could you add possible to make draggable/sortable for TRs, with callbacks, for live manual sortable elements.
Thank you

**Comment by neotropic2023** [comment]
It does work with jQuery sortable, but has some weird visuals when doing so. Also think sorting and paginate would not work too well together depending on how many fields there are.

**Comment by steveush** [comment]
Ye, sorry, this is not something I think I will implement as part of the base plugin. If someone does implement this themselves I would gladly look it over and merge it into the plugin if it worked well with all the default components.
