### ISSUE TITLE
Table getting unresponsive when loading on small screen

### ISSUE THREAD

**Issue by nikhilknoldus** [fooplugins/FooTable#353]
I have applied the code for "th" in table:
data-hide="phone"

now where i have written this(for 3 columns), its working fine. but only when i manuall drag my browser window to less size, when i directly open it in mobile all columns are visible and messy.
So table getting unresponsive when loading on mobile(obviously) screen.

Any help thanks a lot !!

**Comment by steveush** [comment]
Hi,

I this has been resolved in one of the last updates for V3.

Thanks
