### ISSUE TITLE
Filtering issue with full email address

### ISSUE THREAD

**Issue by ksrchen** [fooplugins/FooTable#354]
Filtering fail with full email address.  As soon as user type something dot something, grid reports no match.  For example, type n.com where there are many email addresses with similar to .....n.com in the table.

**Comment by steveush** [comment]
Hi,

In V3 can make use of the [connectors](http://fooplugins.github.io/FooTable/docs/components/filtering.html#connectors) option. The issue is that by default +.-_ are all replaced with spaces when filtering.

Thanks
