### ISSUE TITLE
Is V3 support Paging on Server-Side?

### ISSUE THREAD

**Issue by THTTT** [fooplugins/FooTable#358]
Hi,
Great plugin - thanks for that!

I got problem with Paging on server-side, and i lookup some issues such as   V3 - JsDoc Online ? #317 .

I can't understand why FooTable use javascript do paging still now , a big data (100,0000+) should't be load to the page  .

My idea is to create a table, including the thead, then I tbody and tfoot should use ajax to get, such as:

<pre>
current-page: 100,
current-page-rows:[
    {id:1,name:'thttt'},
    ...
],//as long as page-size, e.g.10
total-page:100000
</pre>

then FooTable init tfoot like this:

<pre>
Frist-Page,Pre-Page,...,97,98,99,100,101,102,103,...,Next-Page,Last-Page
</pre>

then fill current-page-rows in tbody.

Please help for it, thanks.
I am waiting for your reply.

**Comment by steveush** [comment]
Hi,

The original version of V3 which didn't make it to release was implemented so each click of the pager would execute an ajax request for more data providing the server with the requested page number, sort column and direction and any filters applied. This proved too complicated for the majority of our test users to implement as they then had to create a custom endpoint on their server, in whatever language they might use, to handle these requests, including the sorting and filtering values as they are required to get accurate paging. Due to this and to simplify the plugin for the majority of users we opted to switch it to an all client side approach. If we have more requests for this I'll see if I can create a separate component that adds this functionality back in.

Thanks

**Comment by bucketpress** [comment]
This is very much needed as it doesn't just solve the large dataset issue. 
It also solves the problem when multiple channels (web, mobileapp, etc) can alter the db records. a serverside solution that makes an ajax call on every pager-click, search-execution, filter-execution, add-action, delete-action, edit-action will make sure that the user is looking at the most updated records/list each time.

**Comment by ghost** [comment]
I hope in v3 can support footable page server-side!

**Comment by totoprayogo1916** [comment]
+1

**Comment by mazharqayyum** [comment]
+1

**Comment by tilegg** [comment]
I'd really like to see this feature too...
Can i switch to said original-version to use this feature?

**Comment by jeffconklin** [comment]
+1

**Comment by unxs0** [comment]
+1

**Comment by alko89** [comment]
+1
and filtering

**Comment by astaphobia** [comment]
+1

**Comment by Marcovecchio** [comment]
I use DataTables now, but I really want to replace it with FooTable, and I need this feature.

Did you guys consider doing it in a way similar to what DataTables do?

By the way, is it possible to send a number of records to FooTable, and change the number of recods paging sees? I mean, send 10 records, and tell the paging there are 100000 records? This is a basic pre-requisite to implement server-side paging.

**Comment by zhengbowu** [comment]
+1

**Comment by vsuta** [comment]
+1 server side

**Comment by DaveEOS** [comment]
Thanks for a great project. May I recommend that if server side pagination isn't going to be supported, that the links referring to pagination on the ajax loading topic of the documentation be removed. It is misleading and/or confusing. Better still, call out server-side pagination is not supported and all rows needs to be delivered in the first pass.

Given that one of the selling points of FooTable is its responsiveness, though, it seems like a kind of important feature. Like a critical one. I don't know how it is expected to run on a mobile device with more than a couple of thousand rows.

But, it's open source. Right guys?

**Comment by bucketpress** [comment]
@DaveEOS 

Are you referring to this: http://fooplugins.github.io/FooTable/docs/examples/advanced/ajax.html

The 'paging component' referred in this doc isn't for serverside. And it is well written and not misleading. It simply tells us that we can load our data from a server source as opposed to getting data the from DOM. And it tells developers that table paging will work effectively even when loading data via ajax. The info is relevant and without it mentioned in this doc, some developers might not realise that.

**Comment by dosource** [comment]
+1 server side

**Comment by fexra** [comment]
+1 I can't believe what I just read when I read the original response. Server-side is an necessity or no serious applications can be build using FooTables. I got really excited when I found this project and it looks very promising but as long as there is server side option it's a no go :/

**Comment by linakirsanova** [comment]
+1

**Comment by sdwru** [comment]
+1 

I was going to switch from datatables until I found out that Foo doesn't do this.  All my datatables use server side.  It's not just useful for large tables.  I use it for small ones as well to keep everything the same.  Once you create the first one it is not more complicated than client side.  You just need the server side script like what is available for datatables.  That script could be easily modifed to work with Foo.  It's just using Pdo and making standard MySQL queries.  If the Foo implementation is exactly the same as Datatables then it would be plug and play.
