### ISSUE TITLE
ERROR: No columns supplied...

### ISSUE THREAD

**Issue by marasi** [fooplugins/FooTable#359]
HI. I have this code below that return this error in Chrome: [FooTable: unhandled error thrown during initialization. Error: No columns supplied.(…)].

What am I doing wrong?

``` javascript
<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="plugins/footable/css/footable.bootstrap.min.css">

<table class="table footable">
<thead>
  <tr>
    <th data-toggle='true'>UP</th>
    <th data-hide='phone'>Nome</th>
    <th>Telefone</th>
    <th>E-mail</th>
    <th>Data</th>
    <th>Update</th>
    <th>Corretor</th>
    <th></th>
  </tr>
</thead>
<tbody>
...
</tbody>
</table>

<script src="plugins/jQuery/jQuery-2.1.4.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="plugins/footable/js/footable.min.js"></script>

<script>
$(document).ready(function(e) {
    $('.footable').footable();
});
</script>
```

**Comment by dafinley** [comment]
One of your th need data-breakpoint.  You have to have at least one...the last one with zero content would work.  <th data-breakpoint="xs"></th>

**Comment by mikeres0** [comment]
I'm also getting this error. I've specified the breakpoints when I initialise the plugin.

What tags need to be added to the HTML mark up? I have added data-hide="phone,tablet" to a number of my columns. 

$(document).ready(function(){
        $('.data-table').footable({
            breakpoints: {
                phone: 480,
                tablet: 800
            }
        });
    });

**Comment by dafinley** [comment]
I haven't  messed with the custom breakpoints..I would just use the bootstrap data-breakpoints on the th column like the example

``` html
<th data-breakpoints="xs">ID</th>
<th>First Name</th>
<th>Last Name</th>
<th data-breakpoints="xs">Job Title</th>
<th data-breakpoints="xs sm">Started</th>
<th data-breakpoints="xs sm md">DOB</th>
```

http://fooplugins.github.io/FooTable/docs/getting-started.html

**Comment by mikeres0** [comment]
Thanks for you reply. I got this working by changing the breakpoints again.

**Comment by SuheylZ** [comment]
I'm also getting this error and it seems that at least one break point is necessary. Why is it a requirement for using footable?

**Comment by ubongofaidas** [comment]
i'm getting this error in * FooTable v3
* @version 3.1.5
jQuery.Deferred exception: Cannot use 'in' operator to search for 'length' in {"rows":[[1,1,"jeremia","jeremia","Mathayo","Mathayo","Mahenda","Mahenda","1994-03-25","1994-03-25","programmer","programmer"],[2,2,"Ernest","Ernest","Mathias","Mathias","Mahenda","Mahenda","1989-03-23","1989-03-23","Mechanical Engneer","Mechanical Engneer"],[3,3,"joseph","joseph","Mathayo","Mathayo","baluya","baluya","1985-03-21","1985-03-21","Electrical Engineer","Electrical Engineer"],[4,4,"Salum","Salum","Abdalah","Abdalah","Khaji","Khaji","1985-03-20","1985-03-20","Mhasibu","Mhasibu"],[5,5,"Claudianus","Claudianus","David","David","Kunze","Kunze","1993-03-23","1993-03-23","Electrical Engneer","Electrical Engneer"],[6,6,"Barnaba","Barnaba","Obey","Obey","Ndalima","Ndalima","1994-11-20","1994-11-20","System Analyst","System Analyst"]]} TypeError: Cannot use 'in' operator to search for 'length' in {"rows":[[1,1,"jeremia","jeremia","Mathayo","Mathayo","Mahenda","Mahenda","1994-03-25","1994-03-25","programmer","programmer"],[2,2,"Ernest","Ernest","Mathias","Mathias","Mahenda","Mahenda","1989-03-23","1989-03-23","Mechanical Engneer","Mechanical Engneer"],[3,3,"joseph","joseph","Mathayo","Mathayo","baluya","baluya","1985-03-21","1985-03-21","Electrical Engineer","Electrical Engineer"],[4,4,"Salum","Salum","Abdalah","Abdalah","Khaji","Khaji","1985-03-20","1985-03-20","Mhasibu","Mhasibu"],[5,5,"Claudianus","Claudianus","David","David","Kunze","Kunze","1993-03-23","1993-03-23","Electrical Engneer","Electrical Engneer"],[6,6,"Barnaba","Barnaba","Obey","Obey","Ndalima","Ndalima","1994-11-20","1994-11-20","System Analyst","System Analyst"]]}
    at isArrayLike (http://localhost/mtaa-system/assets/vendor/jquery-3.3.1.min.js:489:33)
    at Function.map (http://localhost/mtaa-system/assets/vendor/jquery-3.3.1.min.js:440:8)
    at c.parseFinalize (http://localhost/mtaa-system/assets/vendor/footable/js/footable.min.js:9:2668)
    at Object.<anonymous> (http://localhost/mtaa-system/assets/vendor/footable/js/footable.min.js:9:2445)
    at mightThrow (http://localhost/mtaa-system/assets/vendor/jquery-3.3.1.min.js:3534:29)
    at process (http://localhost/mtaa-system/assets/vendor/jquery-3.3.1.min.js:3602:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.3.1.min.js:3818
process @ jquery-3.3.1.min.js:3606
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
add @ jquery-3.3.1.min.js:3327
(anonymous) @ jquery-3.3.1.min.js:3660
Deferred @ jquery-3.3.1.min.js:3751
then @ jquery-3.3.1.min.js:3645
(anonymous) @ footable.min.js:formatted:1390
Deferred @ jquery-3.3.1.min.js:3751
parse @ footable.min.js:formatted:1388
(anonymous) @ footable.min.js:formatted:1408
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
add @ jquery-3.3.1.min.js:3327
(anonymous) @ jquery-3.3.1.min.js:3660
Deferred @ jquery-3.3.1.min.js:3751
then @ jquery-3.3.1.min.js:3645
preinit @ footable.min.js:formatted:1407
(anonymous) @ footable.min.js:formatted:932
Deferred @ jquery-3.3.1.min.js:3751
_execute @ footable.min.js:formatted:930
(anonymous) @ footable.min.js:formatted:940
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
add @ jquery-3.3.1.min.js:3327
(anonymous) @ jquery-3.3.1.min.js:3660
Deferred @ jquery-3.3.1.min.js:3751
then @ jquery-3.3.1.min.js:3645
_execute @ footable.min.js:formatted:939
(anonymous) @ footable.min.js:formatted:940
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
fire @ jquery-3.3.1.min.js:3406
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
deferred.<computed> @ jquery-3.3.1.min.js:3736
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
fire @ jquery-3.3.1.min.js:3406
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
mightThrow @ jquery-3.3.1.min.js:3593
process @ jquery-3.3.1.min.js:3602
(anonymous) @ jquery-3.3.1.min.js:3632
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
fire @ jquery-3.3.1.min.js:3406
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
mightThrow @ jquery-3.3.1.min.js:3593
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
add @ jquery-3.3.1.min.js:3327
(anonymous) @ jquery-3.3.1.min.js:3660
Deferred @ jquery-3.3.1.min.js:3751
then @ jquery-3.3.1.min.js:3645
(anonymous) @ footable.min.js:formatted:1296
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
add @ jquery-3.3.1.min.js:3327
(anonymous) @ jquery-3.3.1.min.js:3660
Deferred @ jquery-3.3.1.min.js:3751
then @ jquery-3.3.1.min.js:3645
preinit @ footable.min.js:formatted:1295
(anonymous) @ footable.min.js:formatted:932
Deferred @ jquery-3.3.1.min.js:3751
_execute @ footable.min.js:formatted:930
(anonymous) @ footable.min.js:formatted:940
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
fire @ jquery-3.3.1.min.js:3406
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
deferred.<computed> @ jquery-3.3.1.min.js:3736
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
fire @ jquery-3.3.1.min.js:3406
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
mightThrow @ jquery-3.3.1.min.js:3593
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
add @ jquery-3.3.1.min.js:3327
(anonymous) @ jquery-3.3.1.min.js:3660
Deferred @ jquery-3.3.1.min.js:3751
then @ jquery-3.3.1.min.js:3645
preinit @ footable.min.js:formatted:1124
(anonymous) @ footable.min.js:formatted:932
Deferred @ jquery-3.3.1.min.js:3751
_execute @ footable.min.js:formatted:930
execute @ footable.min.js:formatted:921
(anonymous) @ footable.min.js:formatted:824
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
add @ jquery-3.3.1.min.js:3327
(anonymous) @ jquery-3.3.1.min.js:3660
Deferred @ jquery-3.3.1.min.js:3751
then @ jquery-3.3.1.min.js:3645
_preinit @ footable.min.js:formatted:817
(anonymous) @ footable.min.js:formatted:3032
(anonymous) @ footable.min.js:formatted:313
_construct @ footable.min.js:formatted:804
(anonymous) @ footable.min.js:formatted:3028
(anonymous) @ footable.min.js:formatted:313
construct @ footable.min.js:formatted:800
k @ footable.min.js:formatted:330
b.init @ footable.min.js:formatted:40
(anonymous) @ citizen.js:5
mightThrow @ jquery-3.3.1.min.js:3534
process @ jquery-3.3.1.min.js:3602
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:3640
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
fire @ jquery-3.3.1.min.js:3406
fire @ jquery-3.3.1.min.js:3268
fireWith @ jquery-3.3.1.min.js:3398
ready @ jquery-3.3.1.min.js:3878
completed @ jquery-3.3.1.min.js:3888
