### ISSUE TITLE
Last column button type disappears when we resize it

### ISSUE THREAD

**Issue by JeganGitHub** [fooplugins/FooTable#360]
If the last column is a type of button then when we resize it from small size to larger size button disappears! You can duplicate this in chrome browser with the demo example given for Add Remove rows. In the debugger change the link anchor to button, resize it to smaller size and resize back to larger size, button will disappear.

http://fooplugins.com/footable-demos/

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this issue specifically please take a look at the [editor example](http://fooplugins.github.io/FooTable/docs/examples/component/editing.html) to see how it is handled in V3.

Thanks
