### ISSUE TITLE
Error: No rows supplied

### ISSUE THREAD

**Issue by smartmeta** [fooplugins/FooTable#365]
I tried the [Single Header](http://fooplugins.github.io/FooTable/docs/examples/basic/single-header.html) example and get 

`"FooTable: unhandled error thrown during initialization." Error: No rows supplied.
Stack-Trace:
complete@http://test.imby.cms.bybn.de/footable/js/footable.js:2914:16
F.Rows<.parse/<@http://test.imby.cms.bybn.de/footable/js/footable.js:2930:6
.Deferred@http://test.imby.cms.bybn.de/imperia/js/dist/jquery.js:3286:4
F.Rows<.parse@http://test.imby.cms.bybn.de/footable/js/footable.js:2907:1
F.Rows<.preinit/<@http://test.imby.cms.bybn.de/footable/js/footable.js:2952:12 ...`

Code:

```
<link href="/footable/css/footable.standalone.css" rel="stylesheet" type="text/css" />
<script src="/footable/js/footable.js" type="text/javascript">
</script><script type="text/javascript">
var jq=jQuery.noConflict();
jq(document).ready(function($){
    var body = $( 'body' );
    jq('.footable').footable({
    "breakpoints": {
        "phone": 480,
        "tablet": 1024,
        "x-small": 480,
        "small": 768,
        "medium": 992,
        "large": 1200,
        "x-large": 1400
    }
   });
});
</script>
```

```
   <table class="footable">
    <thead>
        <tr>
            <th data-breakpoints="xs">ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th data-breakpoints="xs">Job Title</th>
            <th data-breakpoints="xs sm">Started On</th>
            <th data-breakpoints="xs sm md" data-title="DOB">Date of Birth</th>
        </tr>
    </thead>
    <tbody>
        <tr data-expanded="true">
            <td>1</td>
            <td>Dennise</td>
            <td>Fuhrman</td>
            <td>High School History Teacher</td>
            <td>November 8th 2011</td>
            <td>July 25th 1960</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Elodia</td>
            <td>Weisz</td>
            <td>Wallpaperer Helper</td>
            <td>October 15th 2010</td>
            <td>March 30th 1982</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Raeann</td>
            <td>Haner</td>
            <td>Internal Medicine Nurse Practitioner</td>
            <td>November 28th 2013</td>
            <td>February 26th 1966</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Junie</td>
            <td>Landa</td>
            <td>Offbearer</td>
            <td>October 31st 2010</td>
            <td>March 29th 1966</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Solomon</td>
            <td>Bittinger</td>
            <td>Roller Skater</td>
            <td>December 29th 2011</td>
            <td>September 22nd 1964</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Bar</td>
            <td>Lewis</td>
            <td>Clown</td>
            <td>November 12th 2012</td>
            <td>August 4th 1991</td>
        </tr>
        <tr>
            <td>7</td>
            <td>Usha</td>
            <td>Leak</td>
            <td>Ships Electronic Warfare Officer</td>
            <td>August 14th 2012</td>
            <td>November 20th 1979</td>
        </tr>
        <tr>
            <td>8</td>
            <td>Lorriane</td>
            <td>Cooke</td>
            <td>Technical Services Librarian</td>
            <td>September 21st 2010</td>
            <td>April 7th 1969</td>
        </tr>
    </tbody>
  </table>
```

I'm using the js and css from FooTable-3/releases/footable-standalone.v3.0.1.zip

My Browser is: Firefox ESR 38.2.1

How can I get the example running? What's wrong?

**Comment by mavnorthwind** [comment]
I think the problem is that you're using breakpoints "xs", "sm" and "md" in your table header but define completely different breakpoint names in your js code.

**Comment by smartmeta** [comment]
Thanks @mavnorthwind. I changed it to

```
"breakpoints": {
        "phone": 480,
        "tablet": 1024,
        "x-small": 480,
        "xs": 480,
        "small": 768,
        "medium": 992,
        "sm": 992,
        "large": 1200,
        "md": 1200,
        "x-large": 1400
    }
```

but the error is the same: 

"FooTable: unhandled error thrown during initialization." Error: No rows supplied. Stack-Trace: complete@http://test.imby.cms.bybn.de/footable/js/footable.js:2914:16 F.Rows<.parse/<@http://test.imby.cms.bybn.de/footable/js/footable.js:2930:6 .Deferred@http://test.imby.cms.bybn.de/imperia/js/dist/jquery.js:3286:4 F.Rows<.parse@http://test.imby.cms.bybn.de/footable/js/footable.js:2907:1 F.Rows<.preinit/<@http://test.imby.cms.bybn.de/footable/js/footable.js:2952:

**Comment by blindMoe** [comment]
Note that this can also happen if either of the following are true:
1. The `<tbody>` tag is not present but the `<thead>` tag is.
2. The `<tbody>` contains no rows ( happens when programmatically adding rows with php / c# / javascript ... )

**Comment by Luis-Palacios** [comment]
did you find a workaround this?

**Comment by blindMoe** [comment]
LRPalacios,

I updated my comment above as it appears that github removed the code that I had in there making my comment unreadable.  Basically you need to ensure that you have the proper table sections included and if you won't have a tbody and thead then simply do not show the table.  I don't think it is the best thing to have to do but it works.  Hopefully one day the plugin will be smart enough to simply check for the existence of the elements it is working with before attempting to do so.

**Comment by steveush** [comment]
Hi,

In v3.0.6 the "No rows supplied error" was removed as per issue #409 . v3 will initialize on an empty table now but you will need to reinitialize it once more rows are added. @blindMoe this error was only ever thrown when the table could find no rows to work with i.e. the `<tbody>` element and the `rows: []` option were both empty, so @smartmeta it would seem your table was being seen as empty pre v3.0.6.

Thanks

**Comment by Luis-Palacios** [comment]
Ok, thanks it is working now
