### ISSUE TITLE
Footable v3.0.1 dropbox filtering

### ISSUE THREAD

**Issue by cortix** [fooplugins/FooTable#367]
Hi,

How can I filter using with dropbox in latest version of Footable (v3.0.1) like that

http://fooplugins.com/footable/demos/filtering.htm

in this example there is status dropbox and you can able to filter dropbox's options..but this one is older version...In latest version, How can I use dropbox?

**Comment by rdbrazil** [comment]
I am trying to migrate from 2 to 3, however I was using this feature too. It would be great to have it on v3.

**Comment by ahaubold** [comment]
Thank you very much for this great plugin! V3 is really fast for huge lists with the pagination enabled.

I'm looking for the same feature. I'm trying to filter a list with different dropdown fields at the same time and would like to use the result set for further operations. (e.g. get the ids of all persons within the age of 18 and 20 which are male; with a click on a button "send email" or "export csv" I would like to transmit the results array to another action.)

**Comment by steveush** [comment]
Hi,

I've created an example showing how to do this. you can find it under the advanced examples [here](http://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html).

Thanks

**Comment by ahaubold** [comment]
Great!

Thanks alot.
