### ISSUE TITLE
Issues with rowspan?

### ISSUE THREAD

**Issue by dhanlon** [fooplugins/FooTable#37]
I have a table with the first column displaying a grouping value. Rather than repeat that value for each row in the group, I set rowspan on the cell in the first row so that the grouping value is only displayed once.

I tried to use footable on this and make the 2nd column of the table be expandable.

What happens is that when the table collapses, the expand icon is always added to the 2nd cell in each row, which corresponds to the 2nd column in the table for rows that contain the grouped value, and the 3rd column for all other rows. In addition the collapsed table displays an additional column in the 2nd and subsequent rows of each row in the group. This extra column juts out from the rest of the collapsed table.

I can forego the rowspan and repeat the grouping value in each row, but that detracts from the look of the table when it displays in full.

Here is a simple example:

<table class="footable">
        <thead>
            <tr>
                <th>Group</th>
                <th data-class="expand">Name</th>
                <th data-hide="phone,tablet">Type</th>
                <th data-hide="phone,tablet">Percentage</th>
                <th data-hide="phone,tablet">Active</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan="2">Group Value 1</td>   
                <td>John Doeperson</td><td>Primary</td><td>50.00 %</td><td>False</td>
            </tr>   
            <tr>
                <td>Jane DoePerson</td><td>Primary</td><td>50.00 %</td><td>False</td>
            </tr>   
            <tr>
                <td rowspan="1">Group Value 2</td>   
                <td>John Doeperson</td><td>Primary</td><td>100.00 %</td><td>False</td>
            </tr>   
        </tbody>
        </table>

Thanks

**Comment by steveush** [comment]
Hi dhanlon,

Currently FooTable has no support for rowspans but it is something I could look into for a future update however this would probably only happen after paging support is released.

Thanks
Steve

**Comment by Anke** [comment]
:-)

**Comment by roguemonkey** [comment]
I'd like to also "vote" on this issue, if possible. Rowspan in the headers would make some layouts a lot nicer to look at, but unfortunately, it doesn't work.

**Comment by MarFan** [comment]
+1 on working with rowspan

**Comment by yacobell** [comment]
Agreed, would be very helpful!

**Comment by kmindi** [comment]
:+1: Is anyone already working on this?

**Comment by SLemming** [comment]
Hi,

I would like a solution in the footable plugin (really great plugin btw), but since there isn't one yet, I decided to script a solution on my own. It's only working on table headers now, but perhaps you can change it to your own needs.

Just set rowspan to the upper row like this:

``` html
<thead>
    <tr class="footable-group-row">
        <th class="head" rowspan="2">Stahlsorten</th>
        <th class="head" rowspan="2">Normbezeichnung</th>
        <th colspan="2" class="left" data-group="Oberflächenveredelungen">Oberflächenveredelungen</th>
    </tr>

    <tr>
        <th class="head" data-class="head">Stahlsorten</th>
        <th class="head" data-toggle="true" data-class="head">Normbezeichnung</th>
        <th data-hide="phone" data-group="Oberflächenveredelungen">ZE</th>
        <th data-hide="phone" data-group="Oberflächenveredelungen">Z</th>
    </tr>
</thead>
```

And then hide the other cells via JS.

``` javascript
$table.on('footable_breakpoint', function(data) {
                // rowspan: hide other headers
                $table.find('th[rowspan]').each(function() {
                    var $th = $(this),
                        index = $th.index(),
                        rowspan = $th.attr('rowspan');

                    // get all cells in the next rows (dependend on the rowspan-value) and hide them
                    $th.parent('tr').nextAll('tr:lt(' + rowspan + ')')
                        .find('th:eq(' + index + ')').hide();
                });
            })
            .footable();
```

I used the breakpoint event because with it I can detect display changes on the element.

It's not a perfect solution and maybe it's not working in all cases, but I hope I can help someone.

**Comment by ClubWebware** [comment]
+1 on working with rowspan

**Comment by newcoder23** [comment]
adsfasdafasd

**Comment by ehsan6sha** [comment]
+1 on adding this feature

**Comment by kmindi** [comment]
@steveush was this fixed/implemented?

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

As for if this has been implemented in V3, no it has not. V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

Thanks
