### ISSUE TITLE
cell (td) and row (tr) classes are removed

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#370]
Version 3.0.1, jQuery v1.11.3, Bootstrap v3.3.5

Hello,
thanks for this plugin first.

In docs > Cell options > classes > static examples I found as example

```
To supply this option simply use the standard class attribute.
<td class="class1 class2">...</td>
```

So, I've added classes to my TDs of a table with id="bootstrap-3-variables"
Calling FooTable (plus bootstraped CSS):

```
(function($){
 $(document).ready(function(){
  $("#bootstrap-3-variables").footable();
 });
})(jQuery);
```

All TD-classes are removed from table. 

```
<td style="display: table-cell;">Thing</td>
```

Checked without JS where they are present.

Same behavior with class attributes in TR tags

**Comment by ghost** [comment]
Sorry, it's FooTable version 3.0.1. not 2.0.3! I have corrected this above.

**Comment by dave-buzzy** [comment]
As above, classes are being stripped from cells (using v3.03) - any further news on this?

**Comment by steveush** [comment]
Hi, I've just tested the code now and I was using `.split(/\S+/g)` instead of `.match(/\S+/g)` which was removing all classes. I've patched this locally and will push a new release in a bit.

**Comment by dave-buzzy** [comment]
Thanks @steveush!
