### ISSUE TITLE
Define Columns for each footable

### ISSUE THREAD

**Issue by bwolfe16** [fooplugins/FooTable#377]
Love the plugin!

I know in the footable settings you can specify how many columns should be shown at what breakpoints.  However, one of my tables I would ideally like to show 4 columns, while the other Id like to show only 2.  this is not achievable through any settings or css I can find out there, would you have any suggestions?

Thank you!

**Comment by steveush** [comment]
Hi,

I think you're using the old V2 of the plugin. Please take a look at the V3 version and my explanation below.

The breakpoints are simply a generic value to use across all tables. I suggest taking a look at the [column breakpoints option in the documentation](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-breakpoints) as how you specify which columns are shown/hidden is completely separate to setting up the [table breakpoints](http://fooplugins.github.io/FooTable/docs/getting-started.html#breakpoints).

Thanks
