### ISSUE TITLE
Sorting of column with all cells with the same value causes some rows to rearrange

### ISSUE THREAD

**Issue by sahild57** [fooplugins/FooTable#378]
I have a table where it lists users and one of the columns is an indicator whether they are members or not. A simple Y and N value. If all of the members are set to Y and I sort on that column 3 rows will cycle their positions. Row 1 moves to Row 2, Row 2 moves to Row 19, Row 19 moves to Row 1. Repeatedly clicking the sort will cause these 3 rows to cycle around following this pattern.
I assume if all of the rows have the same value for the column the rows wouldn't move. How do I stop this behavior?

**Comment by steveush** [comment]
Hi,

Apologies but I honestly couldn't say why you are seeing this behavior. Under the hood the sorting simply uses the browsers built in Array.sort function. It's not a custom implementation, it's native to the browser.

Thanks
