### ISSUE TITLE
V2: Html input fields lost

### ISSUE THREAD

**Issue by JimBacon** [fooplugins/FooTable#379]
See http://jsfiddle.net/JimBacon/5f8ecLwm/10/

In the Fiddle, make the result pane narrow to hide the price. Open the details row to view the price. Make the result pane wide again. The price input vanishes.

This is caused by createOrUpdateDetailRow() being called before toggleInput() in redraw(). createOrUpdateDetailRow() calls empty() on the details before toggleInput() gets a chance to move the inputs back in to the main row.

I hope to submit a patch soon.

**Comment by steveush** [comment]
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this issue specifically please have a look at the HTML column type in V3.

Thanks
