### ISSUE TITLE
[V3 Question] Any ways to dynamically add or delete row?

### ISSUE THREAD

**Issue by rui-gu** [fooplugins/FooTable#381]
Hi, 

Having been trying get add/delete row to work for the last two days without any success. V2 seems to have these functions but I can't find them in V3. Can anyone point me to the right direction please?  

Thanks

R

**Comment by steveush** [comment]
Hi,

Not at present, but I will be adding in some editing features that will allow for this functionality in the near future, I have the majority of the changes implemented already in my local version but they need to be finished and tested.

Thanks

**Comment by akribopo** [comment]
Any update on this?

**Comment by nullbio** [comment]
I'd love this feature too :)

**Comment by jeffconklin** [comment]
Same here.

**Comment by nullbio** [comment]
Unfortunately I can't use this product for a project I was hoping to use it on, due to the fact that it doesn't let you update the table dynamically by sending it a new data stream. You can initialize the table with a JSON data stream, but unfortunately there's no way to reinit the table with a new data stream. It needs the ability to take the new stream, compare the data in the table against the data in the new response, and dynamically update the table without changing your page position and redrawing everything. I'd love to see this get added in the future some time, because this seems to be the best table software out there (minus that ability) :)

**Comment by nextglory** [comment]
The next dynamic loading of a live stream will add more pages, just like the infinite scroll do, this feature would be great. Is there a way to reload more data in current V3 version?

**Comment by nullbio** [comment]
I never did find a way around it, I digged through the API and as far as I
can tell, there is no provision for it. I ended up deleting the table from
DOM and redrawing it, which is a really gross solution because it resets
the pages and filtering and stuff, but my table was not for any live
systems and only for a local database so it didn't affect me too greatly,
but if it was for a live system I think I'd have to find an alternative
table software unfortunately. Which is a shame, because it does everything
else so amazingly :(

**Comment by nextglory** [comment]
You can refer to the pagination plugin and create a new component :), but this is a huge task...

**Comment by nextglory** [comment]
You don't necessarily need to delete the table from the dom, just call:
var newData = $.get(".................");
$("#youtable").footable(newData);

This will recreate the table based on the new data...

**Comment by leonardofarias** [comment]
Hello , I have no idea what I have to do to solve my problem :

I am using a model that provides footable .

When I go to a page of my application, for example , parameterView.html load a controller called ParameterCtrl ( routes) and in my page I load another controller called FootableCtrl :

(function () {
    'use strict';

```
angular.module('app.table.footable',[])
        .controller('FootableCtrl', function ($scope, $filter, $http, $templateCache) {

            $scope.teste = function(){
                $('.footable').trigger('footable_initialize');
            }

            $scope.clearFilter = function () {
                $('.filter-status').val('');
                $('.footable').trigger('footable_clear_filter');
            };

            $scope.filteringEventHandler = function (e) {
                var selected = $('.filter-status').find(':selected').text();
                if (selected && selected.length > 0) {
                    e.filter += (e.filter && e.filter.length > 0) ? ' ' + selected : selected;
                    e.clear = !e.filter;
                }
            };

            $scope.filterByStatus = function () {
                $('.footable').trigger('footable_filter', {
                    filter: $('#filter').val()
                });
            };

            $scope.filter = {
                status: null
            };
        });
```

})();

To load the layout Footable, i put in my ng-repeat a filter that calls the function teste(). It works well when i refreshes the page, resizes the page or adds a row. My problem is when i removes a row. Look the controller ParameterCtrl:

 $scope.remove = function(parameter) {
        var parameterExcluded = angular.copy(parameter);
        parameterExcluded.status = Status.EXCLUDED;

```
    SweetAlert.swal({
        title: "Tem certeza que deseja remover?",
        text: parameterExcluded.name,
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "remover",
        cancelButtonText: "cancelar",
        closeOnConfirm: true,
        closeOnCancel: true
        }, function (isConfirm) {
            if(isConfirm){
             ParameterService.save(parameterExcluded, function(response) {
                if (response.success) {
                    $scope.parameterList.splice($scope.parameterList.indexOf(parameter),1);
                    $('.footable').footable($scope.parameterList);
                    $('.footable').trigger('footable_redraw');
                    toaster.pop('success', 'Sucesso', response.data.message); 
                } else {
                    toaster.pop('error', 'Erro', response.error.message);
                }
            }); 
        }
    });             
};
```

All lines below disappear. I remove the row with function splice and I set new table footable with:

$('footable').footable($scope.parameterList);

Adding a row:
![image](https://cloud.githubusercontent.com/assets/9506102/14151517/a07c0936-f684-11e5-8a7e-e6488e85ab6c.png)

Removing the row:

![image](https://cloud.githubusercontent.com/assets/9506102/14151486/7d30d95c-f684-11e5-8efe-31776b36111e.png)

When i refresh the lines back. 

My page parameterView.html:

![image](https://cloud.githubusercontent.com/assets/9506102/14152020/4de59482-f687-11e5-8208-bbd2444c452b.png)

Thanks for attention

**Comment by steveush** [comment]
Hi all,

I've added a new editing component which does half the work of providing an editor for the table. Basically it handles the table functions and UI while you would need to create the editor UI and logic. You can see an example of how to implement it [here](http://fooplugins.github.io/FooTable/docs/examples/component/editing.html).

Thanks

**Comment by jamesarm97** [comment]
Is there any way or plans to add a prepentRow or insertRow type of function? I would like to load some data from a database into the table, then monitor for new records in the database but insert or add them to the beginning of the existing footable so that the old data scrolls down.

**Comment by steveush** [comment]
@jamesarm97 at present there are no plans to add in these type of functions, the reason being that sorting is applied after a row is added so it most likely won't end up where you expect. If you don't have sorting enabled at all then it might be a bit different however in your situation I would enable sorting on a hidden DB ID column and then simply reverse sort the column.
