### ISSUE TITLE
unexpected override on footable icons

### ISSUE THREAD

**Issue by sturze** [fooplugins/FooTable#384]
Hi guys! 

my footable site is also offline available (cached via appcache) on mobile devices and somehow (just in cached version) my search-icon shows up as a kiss-icon! and after entering text its something like a golf-hole-icon

i also use fontawesome, but i cant find these images in their library, and i also have no idea how i can prevent this behavour, because its only on mobile devices (ios, cant test others...) OFFLINE (flymode) so hard to troubleshoot....any ideas?

where does footable get their images from? 

![img_2085](https://cloud.githubusercontent.com/assets/5389555/11715902/2b97c406-9f46-11e5-8944-233cc6d614ef.PNG)
![img_2084](https://cloud.githubusercontent.com/assets/5389555/11715906/313a38da-9f46-11e5-921e-322a932f3bea.PNG)

**Comment by steveush** [comment]
Hi, this is actually an issue with iOS overriding glyphs in the private unicode area and using them to serve emoji. I'm looking into using svg icons instead of the usual font icons so iOS can have the entire private unicode area to play in seeing as it doesn't like to share.

**Comment by sturze** [comment]
aaahhh... now i know where i've seen them before :laughing: 
can't i just define the symbol via class instead of unicode?

**Comment by steveush** [comment]
Not 100% sure what you mean by define it by class, the icons are created using the CSS `:before` pseudo selector and `content` property which is applied in the same way FontAwesome or Glyphicons does. One thing to try but I don't think will work is forcing the `font-family` to FontAwesome for the `.fooicon` class using the `!important` declaration. When I get a chance I'll test out a few different ways to try get around this but seeing as it is done on an OS/browser level I'm not sure it can be worked around, hence my interest in using SVG icons.

**Comment by steveush** [comment]
Just ran across this SO thread about the same issue http://stackoverflow.com/questions/8208126/prevent-emoji-characters-from-showing and the solution there seems simple enough. My iPad doesn't seem to replicate the problem which is strange so I'm updating the OS now to the latest hoping it will break it so I can test out that solution. One thing though is that this SO solution seems like it is only for HTML special characters, not necessarily icon fonts.

**Comment by sturze** [comment]
``` css
fooicon-search:before{content:"\e003\U0000FE0E"}
```

seems to just add "\U000FE0E" after the lips... :-/

**Comment by steveush** [comment]
lol I thought it might :smile:

**Comment by sturze** [comment]
``` css
.fooicon {
font-family: FontAwesome !important;
}
```

seems just to force NOT to show the search-icon :laughing: 

on firefox the icon now is also gone... 

the search-icon only shows up with this fontfamily:

``` css
font-family: "Glyphicons Halflings";
```

**Comment by sturze** [comment]
YUP!!!!! Got it!

``` css
.fooicon {
font-family: "Glyphicons Halflings"; !important;
}
```

forcing this font-family done the trick! no kisses! no golf-holes!

**Comment by steveush** [comment]
Ah, apologies, when you mentioned using Font Awesome I assumed you were using the standalone version. The bootstrap version does indeed use the Glyphicons font that comes bundled in it. I'll add the important declarations for the next update.

**Comment by sturze** [comment]
i just found that one semicolon between the fontfamily and the !important in my post... :see_no_evil: 
it seems it is not even necessary to force! i just tested...

``` css
.fooicon {
font-family: "Glyphicons Halflings";
}
```

all good, too....

**Comment by steveush** [comment]
Hmm, well what you just posted above is what is in the source file at the moment, so it shouldn't make any difference without the `!important` declaration. I'll do some more testing once my iPad is updated and see what I find.
