### ISSUE TITLE
Links in table columns are being removed

### ISSUE THREAD

**Issue by scottlucas58** [fooplugins/FooTable#386]
Is there a way to protect a column? A tag attribute, etc.?

If I have this in a table: 
<td class="text-center"><a href="/UrlHere/"><i class="fa fa-play-circle fa-2x"></i></a></td>

The resulting table after .footable() is called is <td></td>

P.S. This worked fine in V2.

**Comment by steveush** [comment]
Hi, add `data-type="html"` to the column.

**Comment by scottlucas58** [comment]
Sweet! Thank you.
