### ISSUE TITLE
Sophisticated table colspan and rowspan

### ISSUE THREAD

**Issue by kiberkun** [fooplugins/FooTable#387]
How to deal with such a table ?

<table align="center" cellpadding="1" cellspacing="1" class="bx-table" width="100%">
    <thead>
        <tr class="light">
            <th colspan="3" data-class="expand">Наименование показателя</th>
            <th data-hide="phone,tablet">Значение показателя</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="3">Колесная формула</td>
            <td>1х3х3</td>
        </tr>
        <tr>
            <td colspan="2" rowspan="5">Двигатель</td>
            <td>Марка</td>
            <td>Cummins</td>
        </tr>
        <tr>
            <td>Модель</td>
            <td>6BT5.9-215</td>
        </tr>
        <tr>
            <td>Номинальная мощность (кВт/л.с.)</td>
            <td>60 кВт (215 л. с.)</td>
        </tr>
        <tr>
            <td>Номинальная скорость вращения, об/мин.</td>
            <td>2200</td>
        </tr>
        <tr>
            <td>Объем цилиндра двигателя, л.</td>
            <td>5,9</td>
        </tr>
        <tr>
            <td colspan="2" rowspan="5">Рабочая характеристика</td>
            <td>Максимальный дорожный просвет, мм</td>
            <td>430</td>
        </tr>
        <tr>
            <td>Минимальный радиус поворота</td>
            <td>7,8</td>
        </tr>
        <tr>
            <td>Шарнирно-поворотное устройство (L/R)</td>
            <td>25</td>
        </tr>
        <tr>
            <td>Поворот переднего моста (L/R)</td>
            <td>45&deg;</td>
        </tr>
        <tr>
            <td>Максимальная сила сцепления KN</td>
            <td>115</td>
        </tr>
        <tr>
            <td rowspan="6">Передняя передача</td>
            <td colspan="2">1-я скорость, км/ч</td>
            <td>5</td>
        </tr>
        <tr>
            <td colspan="2">2-я скорость, км/ч</td>
            <td>8</td>
        </tr>
        <tr>
            <td colspan="2">3-я скорость, км/ч</td>
            <td>11</td>
        </tr>
        <tr>
            <td colspan="2">4-я скорость, км/ч</td>
            <td>19</td>
        </tr>
        <tr>
            <td colspan="2">5-я скорость, км/ч</td>
            <td>23</td>
        </tr>
        <tr>
            <td colspan="2">6-я скорость, км/ч</td>
            <td>38</td>
        </tr>
        <tr>
            <td colspan="3">Максимальная скорость обратного хода, км/ч</td>
            <td>23</td>
        </tr>
        <tr>
            <td rowspan="5">Отвал</td>
            <td colspan="2">Угол резания отвала</td>
            <td>26°-70°</td>
        </tr>
        <tr>
            <td colspan="2">Длина*высота, мм</td>
            <td>4270*610</td>
        </tr>
        <tr>
            <td colspan="2">Максимальная высота подъема, мм</td>
            <td>450</td>
        </tr>
        <tr>
            <td colspan="2">Максимальная глубина захвата, мм</td>
            <td>500</td>
        </tr>
        <tr>
            <td colspan="2">Угол поворота</td>
            <td>360°</td>
        </tr>
        <tr>
            <td rowspan="2">Объем</td>
            <td colspan="2">Топливный бак, л</td>
            <td>290</td>
        </tr>
        <tr>
            <td colspan="2">Гидравлический бак топлива, л</td>
            <td>110</td>
        </tr>
        <tr>
            <td colspan="3">Габаритные размеры (длина * ширина * высота), мм</td>
            <td>9642*2610*3440</td>
        </tr>
        <tr>
            <td colspan="3">Эксплуатационная масса, кг</td>
            <td>17500</td>
        </tr>
        <tr>
            <td colspan="3">Производственный стандарт</td>
            <td>ISO9001:2000</td>
        </tr>
    </tbody>
</table>

**Comment by steveush** [comment]
Hi,

Unfortunately this is not what FooTable was designed to do. V3 was designed to fill the gap between having to roll your own plugin for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

Thanks
