### ISSUE TITLE
Calling it at the bottom of the page - not in the Head tag

### ISSUE THREAD

**Issue by codivist** [fooplugins/FooTable#39]
does FooTable not work if it's not called in the head tag?  I'm calling all my jquery stuff just before the close of my body tag, then call .footable() in 

``` javascript
$(document).ready(function(){
   $('table').footable();
});
```

I'm not getting any errors, but no columns that are designated to get hidden are hiding.  Neither tablet or phone.  
I'm using jQuery 1.7.2 and Bootstrap 2.2.1

**Comment by steveush** [comment]
Hi codivist,

It shouldn't make a difference where it is placed as it is called within the jQuery.ready callback which only fires once everything is loaded. I have just tested now on a dummy page moving all script tags and the ready call to the bottom of the body and everything seems to work correctly. I'm not sure what might be causing your issue, do you have a demo page I could look at? Or a fiddle?

Thanks
Steve

**Comment by codivist** [comment]
I'm currently working on it locally but here is a fiddle of what I'm doing
http://jsfiddle.net/ysJ7x/1/
The Stage1, Stage2, and Stage 3 columns should be the ones hiding.

A side note too, I'll be adding sorting to it, but I just wanted to make sure everything was working before I add that in.

**Comment by codivist** [comment]
I was able to make this work by removing the "footable-loaded" and "default" classes from the table.  Those class names are in some of the demos, so not sure why its making this one not work.

One thing I have noticed since taking those off is everything is hidden at once, instead of Stage 3, then Stage 2, etc. It's either all of none.

btw, thanks for your hard work on this.
