### ISSUE TITLE
Version tags for 3.x

### ISSUE THREAD

**Issue by anorm** [fooplugins/FooTable#391]
I'm pulling in footable via composer which require tags in the repo for the released versions. Is there a reason why the 3.0.x versions don't have tags? Can it be added?

**Comment by jeffconklin** [comment]
Was wondering (just about) the same thing.

**Comment by steveush** [comment]
Hey,

Apologies I actually forgot to tag the releases. I have since added tags for the 3.0.6 release and will continue to add them going forward.

Thanks
