### ISSUE TITLE
Boostrap Tooltips disabled on paging

### ISSUE THREAD

**Issue by marwan2** [fooplugins/FooTable#394]
If you have a table with pagination then after navigate to other pages, the boostrap tooltip become disabled.

I have fixed it by trigger jquery tooltip script each time I paginate by the event of footable 

$('.table_datalist').footable({
                "paging": {"enabled": true,"limit":10,"position":'left'},
                "sorting": {"enabled": true},
                "filtering": {"enabled": true,'delay':1},
            }).on('after.ft.paging', function(e) {
                $('[data-toggle="tooltip"]').tooltip();
            });

**Comment by steveush** [comment]
Hi,

I'll be closing this as it's not really an issue with the plugin. This is more on the implementation side of things and the way you resolved it is the way I would have recommended it to be done. The reason why I say it's on the implementation side of things is that the content of the cells of a table could be anything, so it doesn't make sense for FooTable to call the tooltip code every time. So if you do use tooltips in your cell contents, like you do, hook into the various events as you have done and simply trigger what you need to.

Thanks
