### ISSUE TITLE
Cell contents are not HTML escaped

### ISSUE THREAD

**Issue by sarahsehr** [fooplugins/FooTable#395]
Text that is HTML escaped on page load (correctly escaped when Footable not instantiated yet), is not longer HTML escaped after Footable is instantiated.

I fixed this on my local copy by modifying the following line in Cell $create:
`.append(this.format(this.value));`
to be 
`.append(this.format($('<div/>').text(this.value)));`

**Comment by steveush** [comment]
Hi,

This should be fixed in 3.1.4.

Thanks
