### ISSUE TITLE
Footable Removes HTML from Columns

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#396]
Hello,

I raised a question within the Footable support area (http://docs.fooplugins.com/support/topic/footable-removed-formatting/) but have not received any recent answers. Figured I would bring it here to see if anyone else has had the same issue and have a fix.

Many of my tables contain HTML within certain columns. This may include a link for more information, some type of label or icon to denote something special, or whatever I may need for that design/page within my system.

When I instantiate Footables on that table, the HTML stripped out from all the tbody cells. The HTML with the thead cell are not removed.

This is very frustrating, and has not allowed us to switch from V2 to V3. 

As Steve mentioned in the forum, there is a way to get around this, but I do not know what it may be.

Any thoughts on how, in V3, we can "save" the state / contents of the cell and ensure that the HTML is not removed?

Thanks.

**Comment by jeffconklin** [comment]
It looks like there is already a solution for this that has been noted on the FT docs page: 

fooplugins.github.io/FooTable/docs/getting-started.html   Column options->Type

There is a column type of "html". This does not work in the version that I had downloaded last year (3.0.1). Once I upgraded to 3.0.4, it is working properly.

I have tested this within my app and it seems to work Ok.

**Comment by rodmtl** [comment]
Thanks, @jeffconklin you save me a lot of time!
