### ISSUE TITLE
Toggle-data on responsive breakpoints

### ISSUE THREAD

**Issue by justinmz** [fooplugins/FooTable#397]
Is there a way to change the data toggle column on the responsive breakpoints or specify a toggle data column according to the breakpoints.
At the moment I have the first column toggling which is the default behavior, but this get's hidden on my first breakpoint. 
The toggling still works but with the first column hidden you can't see the caret and this obviously means that it isn't apparent that the user is able to show more information.
Any assistance or suggestions would be appreciated.

Thanks
Justin

**Comment by sccake03** [comment]
can you provide a jsfiddle example?

**Comment by steveush** [comment]
Hi,

This seems like V2 issue which is no longer supported. In V3 you simply specify the toggle should be displayed in either the first or last column and the plugin will move it as required even if the original column is hidden.

Thanks
