### ISSUE TITLE
footable pagiantion not rendering properly

### ISSUE THREAD

**Issue by krupaharan** [fooplugins/FooTable#399]
Currently am working on footable(jQuery plugin) to implement pagination and filter table functionality . But now facing some issues with pagination , pagination doesn't render properly . Even though my table has many rows, it shows only one page in the pagination section initially , but once after I search something in the search box(above table) , my pagination section shows all pages.

JS ,

`$(function() {
  $('table').footable();
});`  
HTML,

`
Search:<input id="filter" type="text" />
    <table data-filter="#filter" data-page-size = "3">
    <tr>.... //updating table data dynamically 
    </tr>
   <tfoot>
   <ul id="pagination" class="footable-nav"><span>Pages:</span></ul>
    </tfoot>   
</table>
`

After further investigation, got below error in the developer tools(F12).

**> Unable to get property 'pageSize' of undefined or null reference.** (in footable paginate js file)

When I run the above code , i could see table with three rows(data-page-size=3) and pagination section shows only one page with prev and next . but once after the search has been made(in search box), pagination works fine.

I suspect pagination section gets refreshed automatically when I search something in the search box , so it shows all pages after the search has been made . But I don't know how to address this issue.

**Comment by sccake03** [comment]
1) try putting  data-page-navigation="#pagination" in your table.
2) put 'footable' class in the table 'class="footable'
3) change ur JS like this:

 $(document).ready(function () {
    $('.footable').footable();
});

hope it helps :D

**Comment by steveush** [comment]
Apologies, this seems like a V2 issue which is not supported. Please take a look at the V3 examples and documentation, they are fairly thorough.
