### ISSUE TITLE
footable filters not working properly

### ISSUE THREAD

**Issue by krupaharan** [fooplugins/FooTable#400]
Am currently working on footable and facing difficulties in filters . Here is my sample code ,

`Search:<input id="filter" type="text" />
    <table data-filter="#filter">
       <thead>
        <tr>
          <th> First Name </th>
          <th> Last Name </th>
          <th> Designation </th>
          <th> DOB </th>
          <th> Satus </th>
        </tr>
      </thead>
      <tbody>
      <tr>
      <td> Krupa </td>
      <td> Haran </td>
      <td> Analyst </td>
      <td> 26 feb 1992 </td>
      <td> Single </td>
      </tr>
      <tr>
      <td> Manoj </td>
      <td> Kumar </td>
      <td> Analyst </td>
      <td> 16 Mar 1992 </td>
      <td> Single </td>
      </tr>
      </tbody>    
    </table>`

And my JS,

`$(function() {
      $('table').footable();
    });`

If I search using search box , sometimes I end up with below output,
![image](https://cloud.githubusercontent.com/assets/17051626/12824796/f8ad8024-cb98-11e5-8adc-a11a187c6396.png)

**Comment by sccake03** [comment]
add` "footable" class in the table (class="footable")
then change the $('table') to $('.footable')
hope it works :D

**Comment by steveush** [comment]
Apologies, this seems like a V2 issue which is not supported. Please take a look at the V3 examples and documentation, they are fairly thorough.
