### ISSUE TITLE
data-hide="all" not working until resize

### ISSUE THREAD

**Issue by johnowenx** [fooplugins/FooTable#401]
Hi,
It's most likely my code but my data-hide is not working until a i resize the page. The same thing can be seen across browsers, tablets and phones. When I  resize the page the data-hide suddenly jumps into effect and works 

Any ideas what could be causing this? Sorry for the lack of code formatting. 

`<table class="footable table table-stripped toggle-arrow-tiny" data-page-size="10">
                           <thead>
                                                                    <tr>
                                                                        <th data-toggle="true">Staff Member</th>
                                                                        <th>Date</th>
                                                                        <th>Expiration Date</th>
                                                                        <th data-hide="all">Results</th>
                                                                    </tr>
                                                                </thead>`

**Comment by kartikparnami** [comment]
This issue is reproducible for me too. Can someone please have a look?

**Comment by steveush** [comment]
Apologies, this seems like a V2 issue which is not supported. Please take a look at the V3 examples and documentation, they are fairly thorough.
