### ISSUE TITLE
Any ideas to support AJAX loading with Filtering and paging and sorting support

### ISSUE THREAD

**Issue by killermoon** [fooplugins/FooTable#402]
hi,

Do you have any ideas how to support Ajax loading with filtering, sorting and paging (on server side) to avoid full reload every time we request something? 

Thanks in advance.

**Comment by steveush** [comment]
Hi,

This was actually how one of the first BETA versions of V3 worked, every click of sort/filter/page was sent to the server with the relevant params and then the results were simply dumped back into the table. After giving it out to BETA testers it proved to difficult for them to implement (sighs) so we ended up going with the current model of give me everything and let the JS handle it. We wanted to go with a solution that was easy to implement for the majority and this was what we landed on. While I agree it is not the best solution it is fairly optimized and can handle quite comfortably up to a 100,000 rows of data, it all comes down to the end user's machine, most notably their CPU and RAM limits. Unfortunately it would require quite a bit of customization to re-implement the server side paging/sorting/filtering but I will keep it in mind for the future and possibly look at creating a component that adds this functionality back in.

Thanks
