### ISSUE TITLE
Example Table From Website Doesn't Display Correctly

### ISSUE THREAD

**Issue by tdale** [fooplugins/FooTable#403]
Whether I am using Chrome, FireFox or Safari, the example table from http://fooplugins.github.io/FooTable/ displays in three columns (First Name, Last Name, Status), regardless of the browser window width.  The toggle + is visible and functional at all times.  I had two of my colleagues pull up the same link, and they both see 7 columns at the wider browser widths.  Why would I be seeing a different number of columns on the example page?  I have cleared my cache in all three browsers, rebooted my computer, but still have this problem. I am on a MacBook Pro (Retina, 15-inch, Mid 2015) running OX X El Capitan Version 10.11.2.  We are currently using version FooTable 2 which still works fine for me, but for whatever reason version 3 is not working for me even on your own website.

**Comment by steveush** [comment]
Hi,

I think this may have to do with your retina display. FooTable takes into account pixel density when figuring out actual viewport width. Could you try adding the below after you have included FooTable in the page but before you initialize the plugin and let me know if it resolves your issue:

``` javascript
FooTable.Breakpoints.extend('getViewportWidth', function(){
    return Math.max(document.documentElement.clientWidth, window.innerWidth, 0);
});
```

Thanks

**Comment by steveush** [comment]
Hi,

I've pushed a new version (3.0.6) and have changed the way the viewport is calculated which should resolve your issue while maintaining previous functionality.

Thanks

**Comment by tdale** [comment]
I haven't tried things out locally yet, but now I can see all the columns on the example table on the Footable site, something that wasn't working for me before.  Appears to be working great.  Thanks so much!
