### ISSUE TITLE
Sorting freeze on EDGE

### ISSUE THREAD

**Issue by itajackass** [fooplugins/FooTable#405]
Clicking several times (4,5+ times) different column header for sorting, with browser EDGE, the table "freeze". i can't do anything...i need to refresh page or clicking (if present) a link to # outside the table to un-freeze the sorting of table...problem appears also in demo pages. please fix that.

**Comment by steveush** [comment]
Hi,

I'm unable to replicate this behavior using our demo pages, I have opened the [showcase](http://fooplugins.github.io/FooTable/docs/examples/component/showcase.html) example in EDGE and clicked multiple times (10+) across all columns as well on just a single column and do not experience any freezing. You can see a screencast of it here http://recordit.co/quFILETqfE.

Thanks
