### ISSUE TITLE
Add pagination function before show content

### ISSUE THREAD

**Issue by nuryfv** [fooplugins/FooTable#406]
I'm trying to add a function to replace some information in column, but only works in the first page when loads, if i change to other page (with pagination) the content of column is not affected, i would like to add some function in the event of click in pagination number. Is that possible right now in some way?

**Comment by steveush** [comment]
Hi,

Could you be a bit more specific in what you're trying to achieve and could you provide a simplified code sample maybe? Also are you using V2 or V3 of FooTable? Basically anything in V3 can be overridden as it was written to be exceedingly extensible.

Thanks
