### ISSUE TITLE
update tags to v3.0.4

### ISSUE THREAD

**Issue by maruilian11** [fooplugins/FooTable#408]
hi, we host your libs on https://cdnjs.com, we use **npm auto-update** or **git auto-update**(depending on git tags) to add every released version, so could you please consider updating tags for every released version so that we can use **git auto-update** config.                                                 

thank you very much!

https://github.com/cdnjs/cdnjs/issues/7003

**Comment by steveush** [comment]
Hi,

I'll start to add tags for every new release going forward. This is something I have actually done in our other repos but seem to have left out of this one :(

Thanks for pointing this out!

**Comment by maruilian11** [comment]
thank you!

**Comment by steveush** [comment]
Hi,

I've pushed the latest version 3.0.6 and tagged it.

Thanks

**Comment by maruilian11** [comment]
https://cdnjs.com/libraries/jquery-footable
3.0.6 has been added! :grin:
