### ISSUE TITLE
click function of jquery does not work

### ISSUE THREAD

**Issue by keyrusmaurice** [fooplugins/FooTable#41]
hi, I have a link, that needs to be treated but the click event is never, when i put the link outside the footable the juery script work but not inside the footable below is a partial code 

$('.hotelDetails').click(function() {
        var hotelCode = $(this).attr("code");
        //alert(hotelCode)
        $.ajax({
          type: "POST",
          url: "/getHotelDetails",
          data: { hotelCode:hotelCode }
          }).done(function( msg ) {

```
      //$("#productDetails").html(msg)

    })
    return false;
  })
```

and the link is 

<a href="#" code="@h.hotelCode" class="hotelDetails" >Details</a>

help appreciated

**Comment by mleisher** [comment]
I'm assuming the click handler on the row is taking precedence. Try the following:

$('.hotelDetails').click(function(event){
  event.stopPropagation();
.......
});
