### ISSUE TITLE
Remember page number when back?

### ISSUE THREAD

**Issue by max-yu** [fooplugins/FooTable#411]
When I leave the table at a page, go to another page, and then hit "back" button of browser to come back, the page number was reset to "1". 

Is it possible to remember the page number?

**Comment by toybank** [comment]
You could try storing it in sessionStorage??

**Comment by steveush** [comment]
Hi,

An easy way to accomplish this is below but basically we hook into the "after.ft.paging" event and store the current page in localStorage or sessionStorage depending on your requirements. We then also set the [paging.current](http://fooplugins.github.io/FooTable/docs/components/paging.html#current) option to the value of the variable fetched from storage whenever the table is initialized.

``` javascript
$('#table-id').footable({
    paging: {
        current: !!window.localStorage ? localStorage.getItem('footable-page') : 1
    }
}).on('after.ft.paging', function(e, ftbl, pager){
    if (!!window.localStorage){
        localStorage.setItem('footable-page', pager.page);
    }
});
```

Thanks

**Comment by max-yu** [comment]
Thanks all! But the sample code does not work. Perhaps because I'm using Ajax loading data?

**Comment by max-yu** [comment]
it works now.
