### ISSUE TITLE
Change data-paging-size with a button?

### ISSUE THREAD

**Issue by itajackass** [fooplugins/FooTable#412]
how can i change data-paging-size with a button? in footable v2.x i used:

```
$("#table-id").attr("data-page-size",new-value);
$("#table-id").footable("footable_redraw");
```

but for versione 3.0.4 it doesn't work....

**Comment by steveush** [comment]
Hi,

To change the size of paging on the fly has changed, as has the entire underlying core of FooTable between V2 and V3. To be able to do what you were previously doing now you would use the below in your button click:

``` javascript
var ftbl = FooTable.get('#table-id');
ftbl.use(FooTable.Paging).size = NEW_VALUE;
ftbl.draw();
```

Thanks

**Comment by itajackass** [comment]
thanks. can you give me link with updated docs about those new methods (if exist)? thank you

**Comment by itajackass** [comment]
hi, i tried the code. It work but there is a problem:
for example if i set initial config to:

```
"paging": {
    "enabled": true,
    "size": 100,
    "countFormat": "{CP} di {TP}"
            }
```

then i send a search and i get for example of 20 results (smaller than 100 so pagination doesn't appear)....then i change the page-size with the code provide by you to a number smaller than 20 (for example 10)...page size of the table change ok, but paginatiion doesn't appear...so i can't navigate trough pages...i can only see page n.1

**Comment by steveush** [comment]
Hi,

I've pushed a new version (3.0.6) and made this task easier and fixed the bug you mentioned above. To change the page size from a button click you can now use the below code:

``` javascript
FooTable.get('#table-id').pageSize(NEW_VALUE);
```

This method can either get or set the value so if you need to find out what it currently is you can simply call it with no parameters. You can also find out more about the available functions by looking at the [JSDocs](http://fooplugins.github.io/FooTable/docs/jsdocs/index.html).

Thanks

**Comment by itajackass** [comment]
hi, i tried your code with:

```
$( document ).ready(function() {

        $('.tabella').footable({
            "sorting": {
                "enabled": true
            },
            "paging": {
                "enabled": true,
                "size": 100,
                "countFormat": "{CP} di {TP}"
            }
        });

        $("#bottone_risultati_per_pagina").on("click", function() {

            var risultati_per_pagina = $("#risultati_per_pagina").val();
            if ( risultati_per_pagina < 10 ) {
                risultati_per_pagina = 10;
                $("#risultati_per_pagina").val(10);
            }
            FooTable.get('.tabella').pageSize(risultati_per_pagina);

        });

    });
```

but nothing work...

**Comment by steveush** [comment]
Hi,

Not sure what you are doing then but I added an example using the same code provided to show it working. You can view the example [here](http://fooplugins.github.io/FooTable/docs/examples/advanced/change-pagesize.html).

Thanks

**Comment by itajackass** [comment]
in firebox consol i get this error:

TypeError: FooTable.get(...).pageSize is not a function

**Comment by steveush** [comment]
Hi,

Then you did not update to the latest version. As I said in my previous comment I pushed a new version (3.0.6) which added in the pageSize function. Please update the version you are using.
