### ISSUE TITLE
Bootstrap Downlaod Plus Filtering Plugin

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#413]
Hello,

I downloaded the Bootstrap Version (found on http://fooplugins.github.io/FooTable/docs/getting-started.html#download) to fit into our BSv3 theme and would like to now start using your filter option. Your main download page makes it sound like we can pick one of the three, and that the Standalone and BS Versions both contain all the plugins. But that does not seem to be the case. Because of this, I would like to ask a few questions..
- Do all three versions work independently? As in i can download any one of the three and just start using them? Standalone does not seem to have footable.js. Would someone just use footable.core.js instead?
- What makes the Boostrap Version different than the Standalone or Individual versions? Is footable.js different at all?
- Should I be downloading your project in GIT or downloading what you have on your site? I think most people are just grabbing their project files from GIT now... so what do you recommend?
- How do I include both your BS download and specific plugins like filtering? Can I just drop the Filter CSS/JS into my project as individual files?

These all may be silly questions, but i want to make sure I can keep up with your versions in my project, even when i am downloading different ZIPs.

Thanks.

**Comment by bradvin** [comment]
Hi,

The themes are purely CSS, so there is no difference in the JS files between BS or standalone themes.
I just checked http://fooplugins.github.io/FooTable/releases/footable-standalone.latest.zip and it def contains footable.js
The Bootstrap CSS has a much smaller css as it inherits most styling from BS itself.
Download direct from git to get latest changes, in case the zips are not built and deployed, but Steve usually pushes out the latest zips when he makes changes.

To customize the plugins you use, rather use the individual components zip and remove the files you do not need. You will probably need to build and minify the assets yourself then
