### ISSUE TITLE
Using Font Awesome Icons instead of Glyphicon (from Bootstrap)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#415]
I use Bootstrap V3x, but do not use the Glyphicon icons. Instead I use FontAwesome. There has been some other posts here about how to make sure either icon type shows up properly, but they do not show the full solution/workaround.

Within the BS CSS files provided on http://fooplugins.github.io/FooTable/docs/getting-started.html#download , the .fooicon class is defined with font-family: 'Glyphicons Halflings';, and defines all the Ggyph specific unicode for each class. If you make the following changes, FA should "work" with your BS/FA FooTable implementation...

```
.fooicon {
font-family: FontAwesome !important;
}
.fooicon-loader:before {
    /*Old Glyph - content: "\e030";*/
    content: "\f01e" !important;
}
.fooicon-plus:before {
    /*Old Glyph - content: "\2b";*/
    content: "\f067" !important;
}
.fooicon-minus:before {
    /*Old Glyph - content: "\2212";*/
    content: "\f068" !important;
}
.fooicon-search:before {
    /*Old Glyph - content: "\e003";*/
    content: "\f002" !important;
}
.fooicon-remove:before {
    /*Old Glyph - content: "\e014";*/
    content: "\f00d" !important;
}
.fooicon-sort:before {
    /*Old Glyph - content: "\e150";*/
    content: "\f0dc" !important;
}
.fooicon-sort-asc:before {
    /*Old Glyph - content: "\e155";*/
    content: "\f0de" !important;
}
.fooicon-sort-desc:before {
    /*Old Glyph - content: "\e156";*/
    content: "\f0dd" !important;
}
.fooicon-pencil:before {
    /*Old Glyph - content: "\270f";*/
    content: "\f040" !important;
}
.fooicon-trash:before {
    /*Old Glyph - content: "\e020";*/
    content: "\f1f8" !important;
}
.fooicon-eye-close:before {
    /*Old Glyph - content: "\e106";*/
    content: "\f070" !important;
}
.fooicon-flash:before {
    /*Old Glyph - content: "\e162";*/
    content: "\f0e7" !important;
}
.fooicon-cog:before {
    /*Old Glyph - content: "\e019";*/
    content: "\f013" !important;
}
```

I believe the better solution here would be to allow people to select what icon library they are using when initiating FT. But that means that the code maintainer also has to maintain the these libraries within the code. So I do not know the 100% perfect answer.

Also, if you ever need a quick place to find icons class names and search across multiple libraries, http://glyphsearch.com/ is VERY useful.

Hope this helps.

**Comment by steveush** [comment]
FYI - You can also [download the standalone version](http://fooplugins.github.io/FooTable/docs/getting-started.html#download) which is built using FontAwesome for the icons and use that however the standalone version does not use BootStrap for any of the table styling. If you want to keep BootStrap's table styling but use FontAwesome for the icons you can modify the BootStrap version as mentioned above, the source file containing the FontAwesome glyphs can be found [here](https://github.com/fooplugins/FooTable/blob/V3/src/css/FooTable.FontAwesome.css).
