### ISSUE TITLE
Back to last state (after search)?

### ISSUE THREAD

**Issue by max-yu** [fooplugins/FooTable#416]
I'm using a paged table. I searched for some items using the search input box. Each item represent a product in a company. I make the items clickable. When I click an item, the product details page for the item will be shown. But when I hit "back" button of the browser, it backs, but all items are shown now, while I just want it to show the filtered items.

**Comment by sccake03** [comment]
use footable filter, i can see thats what you need, but remember to set data-page-size="(desired number)".
hope it helps @max-yu :)

**Comment by steveush** [comment]
Hi,

Personally I would make the product display in a popup modal but if you are set on changing the page and making the user click the back button then you will need to store the current filter and reapply it when the page is reloaded. I take it you are using V3 so to get the current filters you can use the below:

``` javascript
var currentFilters = FooTable.get('#table').use(FooTable.Filtering).filters;
```

You could store that value in localStorage and then check it on page load. If there are filters in localStorage then you use them in the options when you initialize FooTable and it will apply them itself.

Thanks
