### ISSUE TITLE
Won't work in bootstrap collabable until page resized

### ISSUE THREAD

**Issue by gregisle** [fooplugins/FooTable#418]
Hi,

I can't seem to get the tables to work in either an accordion or a popup window. Bootstrap collapsible and modal). It will work but only after resizing the page. Is there anyway around this or have I missed something?

**Comment by steveush** [comment]
Hi,

I've added 3 examples showing FooTable in use in an [accordion](http://fooplugins.github.io/FooTable/docs/examples/bootstrap/accordion.html), [collapsible area](http://fooplugins.github.io/FooTable/docs/examples/bootstrap/collapse.html) and [modal popup](http://fooplugins.github.io/FooTable/docs/examples/bootstrap/modal.html). The only thing I can think of as to why it is not working as expected for you is that the breakpoints are working off the viewport width, your columns are configured as such and then the container that your table is actually in is a lot smaller than the viewport. You need to either configure the breakpoints on your columns correctly or you can try using the [useParentWidth](http://fooplugins.github.io/FooTable/docs/getting-started.html#useParentWidth) option as I did in the modal example.

Thanks

**Comment by gregisle** [comment]
Thanks steveush,
Your are most appreciated 
.Greg
