### ISSUE TITLE
Custom Filter Elements Beyond data-filtering=true (in Footable v3)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#419]
Hello All,

I like the filtering option in v3 (http://fooplugins.github.io/FooTable/docs/examples/component/filtering.html), but it does not seem to offer any flexibility to create our own elements, HTML, layout/look/feel. Placing the filter components into the THead does not work at all in my layout at all.

Filtering in pre-V3 versions offered the freedom to create your own layout and create the appropriate connections with FT..

http://fooplugins.com/footable/demos/filtering.htm

How can we do this when using V3? I am hoping there is already a solution for this that may not be documented yet. Or maybe I am just missing the solution inside the current docs. Either way, the automatically created search box just does not work for most of my layouts, but I do want to use filtering. How can I get this done?

Also, I don't "get" the specific filters option within v3 filtering ( http://fooplugins.github.io/FooTable/docs/components/filtering.html#filters ) "A filter is a simple object containing a name, a query and an array of columns." Is this used to filter rows on page load only? Can this be called dynamically once FT has already been instantiated for that table? I am missing something with how to actually use this in an example.

I have created a SO question about this with the hopes of opening up beyond this repo...
http://stackoverflow.com/questions/35922974/looking-for-more-flexible-filtering-in-footable-v3

Thanks.

**Comment by steveush** [comment]
Hi,

Please take a look at the following [example from the docs](http://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html). You can change the layout if you like, add custom elements or override anything really with V3. You could completely separate the filter component from the table, that is completely up to you and what methods you override/implement. The previously mentioned example shows the methods to use to add/remove custom filters programatically and how to get them to work with the default component.

Also the [filters option](http://fooplugins.github.io/FooTable/docs/components/filtering.html#filters) works the same as any other option, it is the initial state for the table (say loaded from user session/localStorage/whatever). It would be changed during runtime either through code or through user interaction with the component UI.

Thanks

**Comment by jeffconklin** [comment]
The example you provided, as is most of your documentation and examples, is overly complex and far from being intuitive. The amount of knowledge that one needs about your underlying code before they can implement some basic features can be tremendous at time. In this case, the example shows how to add a select box to the filter options that your system already displays. What about check boxes or buttons? How do we even instantiate the filter functionality and have the system NOT create the text area / search button / column select? And your example does not show how to "move" this functionality to a different location within my DOM. How can we have multiple tables on 1 page that have different custom filtering? Though I appreciate your link to the example, I still have to dig through your code to understand how to actually do what I want... which is why asked the question here.

As for your response about the filter option, it still does not show me how to use it after Footable takes over the table. 

I get that you know your code in and out, but your documentation needs to be written in a way that makes sense to people that do not have the depth of knowledge that you have.

**Comment by steveush** [comment]
> The example you provided, as is most of your documentation and examples, is overly complex and far from being intuitive.

Next time you ask for help try asking nicely. The docs provided @ http://fooplugins.github.io/FooTable/ are about as simple as I could make them. You click an option and it shows you what it does and how to use it, you click an example and you can copy/inspect the code...

> I get that you know your code in and out, but your documentation needs to be written in a way that makes sense to people that do not have the depth of knowledge that you have.

There's the [JSDocs](http://fooplugins.github.io/FooTable/docs/jsdocs/index.html) which documents every method, property and event of every object. Never mind that the entire source is available here on GitHub for you to look at. Everything you could possibly need to know is available here online.

> As for your response about the filter option, it still does not show me how to use it after FooTable takes over the table.

It's an option to set the initial state of the filters applied to the table. You don't use it in any way after FooTable takes over. The value provided by it is read into the [FooTable.Filtering#filters](http://fooplugins.github.io/FooTable/docs/jsdocs/FooTable.Filtering.html#filters) array and the plugin manages that array from there. As seen in the provided example if you want to modify it you can use the filter, clear, addFilter, removeFilter methods of the component but you do nothing with the option. Please look at the JSDocs for more info.

---

Now that's off my chest, I made an example showing how to add your own completely custom UI for filtering, separate from the table, using a method similar to the way the old V2 did it. You can find it [here](http://fooplugins.github.io/FooTable/docs/examples/advanced/custom-filter-ui.html).

**Comment by jeffconklin** [comment]
Thank you for the response, and for the second custom filter example. That example is much easier to understand, and actually helps me better understand the previous one.
