### ISSUE TITLE
Sorting: Excluding a column

### ISSUE THREAD

**Issue by ricardozea** [fooplugins/FooTable#42]
Hello,

Not if this is doable right now, but I read the documentation and couldn't find find anything related to this case.

My issue right now is that I would like to **exclude** a column from sorting.

The thing is that I have a column that holds thumbnails, just small preview images of the files they correspond to, so "sorting by thumbnail"... the sorting concept doesn't apply in this case.

Is there a `data-` attribute to "exclude" a column from sorting?

EDIT--

I used `data-ignore` on the `header` but it didn't work. 

I used it like this:

```
<thead>
  <tr>
    <th data-ignore="true">Thumbnail</th>
  </tr>
  <tr>
    <th>...</th>
  </tr>
<thead>
```

Thanks.

**Comment by bradvin** [comment]
rather use data-sort-ignore="true"

**Comment by ricardozea** [comment]
Ha! It worked great, thanks!

You think you could add this to the documentation in the [Data Attribute Configuration](https://github.com/bradvin/FooTable#data-attribute-configuration) section?

Just saying, since this feature is not documented yet and also thinking about others that may have the same issue.

Just [twitted this solution](https://twitter.com/ricardozea/status/319481864563871744) as well.

Thanks again!
