### ISSUE TITLE
Sorting off? How? 

### ISSUE THREAD

**Issue by adam-czop** [fooplugins/FooTable#420]
Hello,
I have a problem with the exception of the sort :)
Currently, it enabled filtering and sorting -> http://crm.mediahealth.pl/base/html/recepcja/ sorting but wanted to switch off and do not really are successful. Can someone help? Thank you and best regards
Adam

**Comment by steveush** [comment]
Hi,

Not exactly sure what you were wanting with this, either the sorting is enabled or not when the table is initialized. So if you want to not have sorting simply do not enable it. If you are wanting to prevent sorting please take a look at [this issue](https://github.com/fooplugins/FooTable/issues/443). The methods described in that issues response have been incorporated into the sorting component as of version 3.0.9 so you do not need all of the custom code, you can simply use them.

Thanks
