### ISSUE TITLE
Force re-draw of footable

### ISSUE THREAD

**Issue by angel-li** [fooplugins/FooTable#421]
How can one force a re-draw of a footable? I get the event after.ft.breakpoints but there is no resizing being trigerred.

**Comment by steveush** [comment]
Hi,

The below will force a redraw of the table, but when you write that there is no resizing happening could you be more specific? This sounds like the breakpoints are not setup correctly on your columns or you may be needing to use the [useParentWidth](http://fooplugins.github.io/FooTable/docs/getting-started.html#useParentWidth) option as by default the breakpoints work off of the viewport width.

``` javascript
FooTable.get('#table-id').draw();
```

Thanks

**Comment by angel-li** [comment]
Maybe "no resizing" is inaccurate. What I'm seeing is the following: if I start resizing a browser window, the table shrinks/expands until a breakpoint is reached and after that only the header is displayed  and the content of the tbody is gone.

I extracted the table code into a separate file and the table behaves as expected.

**Comment by steveush** [comment]
Hi,

Ok then, if the table is working as expected in a separate file I'll close this issue. It sounds like you have a conflict with either some CSS (if the tbody rows are in the page but not visible) or JS in your page and it's not an issue with FooTable itself.

Thanks
