### ISSUE TITLE
Footable to show selected column data only

### ISSUE THREAD

**Issue by rgoti** [fooplugins/FooTable#424]
Hi community,

I was wondering if there is a way in Footable to show only the data colmuns for the one you have selected and hide the others.

For example, let's say the below are the list of albums (rows in my footable)

> album-name-1
> album-name-2
> album-name-3

And if I select the album 1, it's data appears as follows:

> album-name-1
> - track1
> - track2
> - track3
> 
> album-name-2
> album-name-3

If I select album2, only those details appear and the previously expanded tracks from album 1 get collapsed as follows:

> album-name-1
> album-name-2
> - track1
> - track2
> - track3
> 
> album-name-3

I am using angularJS to use footable. Any suggestions on how to achieve this ?

**Comment by sccake03** [comment]
i think its best to use the jquery accordion in that scenarion :) hope it helps you.

**Comment by steveush** [comment]
Hi,

Sorry at present there is no option to only allow a single row to be expanded at a time. @sccake03 is correct, that does sound more like an accordion.

Thanks
