### ISSUE TITLE
Data-visible and filtering

### ISSUE THREAD

**Issue by itajackass** [fooplugins/FooTable#426]
Is it possible to hide an entire column but using this for filtering?
If i set data-visible=false, column disappear also in filtering.
If i set data-breakpoint="all" column is still selectable from filtering, but column is also visible clicking "+"...
i'd like to view column only in filtering....

**Comment by steveush** [comment]
Hi,

I've just checked in a new version, 3.0.7, which will allow you to set data-visible="false" while still allowing the column to appear in the filtering dropdown. To hide a column from the filtering UI is now solely dependent on the data-filterable="true|false" option.

Thanks
