### ISSUE TITLE
Toggle/Expand All Rows After Initial Load (v3)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#427]
Is there a quick way to toggle (display or hide) all the hidden columns for the entire table at one time? I see that I can include tr data-expanded="true" on page load, but I need a "show all" button that can be clicked on at any point in time by my users. In V2 I used the footable_expand_all and footable_collapse_all triggers, but I do not see the equivalent to this within V3.

Also, what is the best way to attach an onclick event to any element in the row to expand that 1 row? As a quick test I added the class "footable-toggle" to an element in my row and it does toggle that row properly. But that seems like a hack.

Thanks.

**Comment by ImTheDeveloper** [comment]
I use the following code on my tables:

```
$(document).on("click","#expand",function(){

  $("tr:not([data-expanded='true'])").trigger('click');

});

    $(document).on("click","#collapse",function(){

      $("tr[data-expanded='true']").trigger('click');

    });
```

**Comment by jeffconklin** [comment]
Thank you for the reply. I have a similar solution. The only difference is that I do not allow the default FT behavior that allows a user to click the full row. Instead I only allow for clicks on elements with .footable-toggle only. That means in my solution I need to find the first element with .footable-toggle and "click".

Though these solutions work, I have never liked the thought of firing a "fake" click like this. Instead, I would prefer a programmatic solution for this. But for now this will work.

Thank you again for the reply.

**Comment by steveush** [comment]
Added an [expandAll](http://fooplugins.github.io/FooTable/docs/getting-started.html#expandAll) option which will force the rows to be expanded by default. Will be included in the next release being pushed shortly.

**Comment by jeffconklin** [comment]
Thanks for the update, Steve. What you shared is good for initial load, but will it be available to be fired once the table has already been loaded? I need an "expand all" functionality that can be fired to expand or collapse on demand. That is the same thing that @Hardware-Hacks mentioned with his code too.

**Comment by steveush** [comment]
Ah, apologies, misunderstood what you were going for. I'll reopen this and see if I can put together the code today.

**Comment by ImTheDeveloper** [comment]
![image](https://cloud.githubusercontent.com/assets/1431348/17615256/e94fd5f8-6064-11e6-9c9f-64553d84bbb4.png)
I offer up the expand/collapse all buttons as shown in the attached. I use the code shown previously to do the actual changes.

**Comment by steveush** [comment]
@Hardware-Hacks thanks for the code :) The below is what I came up with but either will work. Firstly there is this little snippet of JS which just extends the original `FooTable.Rows` object with an `expand` and `collapse` methods, it just needs to be included in the page after FooTable has been.

``` javascript
(function(F){

    F.Rows.prototype.expand = function(){
        F.arr.each(this.array, function(row){
            row.expand();
        });
    };

    F.Rows.prototype.collapse = function(){
        F.arr.each(this.array, function(row){
            row.collapse();
        });
    };

})(FooTable);
```

Then to use it is as simple as calling the below:

``` javascript
FooTable.get('#table').rows.expand();
```

Or:

``` javascript
FooTable.get('#table').rows.collapse();
```

**Comment by steveush** [comment]
@jeffconklin I re-read your original issue message and no idea where I actually got the initial load option from lol. Anyway onto the second part of your issue, how to toggle a row from a child's click event, there are two ways to accomplish something like this. To start off let's say we want to toggle a row from a custom button element in an HTML column. So our table looks something like this:

``` html
<table id="example" class="footable table">
    <thead>
    <tr>
        <th data-type="number">ID</th>
        <th>Name</th>
        <th data-breakpoints="xs">Job Title</th>
        <th data-type="html"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1</td>
        <td>Steve</td>
        <td>Developer</td>
        <td>
            <button type="button" class="custom-toggle">Toggle Row</button>
        </td>
    </tr>
    </tbody>
</table>
```

The first way to get it work is by using the [toggleSelector](http://fooplugins.github.io/FooTable/docs/getting-started.html#toggleSelector) option and simply set the value to `.custom-toggle` so it targets only our button. That's it, clicking just the button will now toggle the row.

The second way is a bit longer but it gives you total control over how things are done. The basic idea is to bind a delegate event to the table that listens for our custom toggle buttons click event and in that handler we fetch the current row and manually toggle it.

``` javascript
$('.footable').on('click', '.custom-toggle', function(e){
    e.preventDefault();
    // to get the FooTable.Row object simply walk up the DOM, find the TR and grab the __FooTableRow__ data value
    var $row = $(this).closest('tr');
    // if this is a detail row get the previous row in the table to get the main TR element
    if ($row.hasClass('footable-detail-row')){
        $row = $row.prev();
    }
    // grab the row object
    var row = $row.data('__FooTableRow__');
    // toggle the row
    if (row instanceof FooTable.Row){
        if (row.expanded){
            row.collapse();
        } else {
            row.expand();
        }
    }
});
```

Thanks

**Comment by steveush** [comment]
I've included all these changes in 3.1.0. You can now use the `FooTable.Rows#expand()` and `FooTable.Rows#collapse()` methods without the custom code above. I have also included a handy utility method for retrieving the `FooTable.Row` object given a `TR` element or any of it's children called `FooTable.getRow()`. This new utility method would replace the custom toggle code above with the what's below:

``` javascript
$('.footable').on('click', '.custom-toggle', function(e){
    e.preventDefault();
    // grab the row object and toggle the row
    var row = FooTable.getRow(this);
    if (row instanceof FooTable.Row){
        if (row.expanded){
            row.collapse();
        } else {
            row.expand();
        }
    }
});
```

Thanks

**Comment by colleencater** [comment]
Hi there, I am reading through this issue and I have tried to get it to work with my table without any luck. I find it better when there is an example to go along with the code.  Is there a working example of the final code that @steveush provided in the last post?  Thanks again.

**Comment by dClark1967** [comment]
Hi there. Great plugin. Working well. I have a question about the edit and delete icons. Is there a way to disable or hide these for a particular row. I have rows given a class for rows I do not want the edit or delete to be available.
