### ISSUE TITLE
Off by one error with breakpoints?

### ISSUE THREAD

**Issue by MSeneadza** [fooplugins/FooTable#429]
First, I'm a big fan of FooTable & have been using v2 for a couple of years now.  Thanks for all the hard work...

I just upgraded my site from v2 to v3.  I noticed a strange issue on my iPad Air and in Chrome Dev Tools while emulating an ipad (768 x 1024).  On many of my tables I just wanted to hide some columns for phones.  So in the HTML for those columns I set the breakpoints to "x-small", which is set to 480.   For example: `%th{"data-breakpoints" => "x-small"} Note`

When I do that those columns are hidden/collapsed for both my iphone and ipad (and the ipad Chrome simulator).  I am able to get those columns to show for an iPad if I either change the definition of "small" to be 767 or if I modify a line (this one https://github.com/fooplugins/FooTable/blob/V3/src/js/components/internal/breakpoints/FooTable.Breakpoints.js#L139) in the calculate function.

Changing the less-than-or-equal-to to just less-than here `(prev instanceof F.Breakpoint ? width <= prev.width : true)` to `(prev instanceof F.Breakpoint ? width < prev.width : true)` seems to make it work.  

I went with the solution of changing my "small" breakpoint to being 767 instead of 768.

Have you seen anything like that before?  If it helps, here's one of the tables: http://swingtradebot.com/events -- the "Unfiltered Total" column is set to be hidden at 480 and, again, I've modified the "small" breakpoint to 767, so it should display correctly if you view it on an iPad now.

**Comment by steveush** [comment]
Hi,

Thanks for pointing this out, I've incorporated your change into the latest version (3.0.8) that I'll be pushing soon.

Thanks

**Comment by MSeneadza** [comment]
You're welcome
