### ISSUE TITLE
highlight expanded (toggled row) ?

### ISSUE THREAD

**Issue by XanderCam** [fooplugins/FooTable#431]
Is there an built-in way of highlighting toggled (expanded) rows ?
I'm writing a code where I rely heavily on nested tables inside the detail rows.
When several of the hidden rows are toggled it can sometimes be a difficult read.

So it would be a good thing to be able to hightlight the rows that are expanded.
I can always write a work-around code, but if there already is a function for it...

**Comment by steveush** [comment]
Hi,

At present there is no built in function for this but I've added in events in the next version (3.0.8) that you will be able to use to achieve the desired effect. The events are `expand.ft.row` and `collapse.ft.row`. Both of these events are passed the the following as parameters:

e - The jQuery.Event object
ft - The FooTable.Table object
row - The FooTable.Row object being expanded or collapsed

Example usage:

``` javascript
$('.table').on({
    'expand.ft.row': function(e, ft, row){
        row.$el.addClass('expanded');
    },
    'collapse.ft.row': function(e, ft, row){
        row.$el.removeClass('expanded');
    }
});
```

The new version should be pushed soon.

Thanks
