### ISSUE TITLE
postdraw.ft.table not firing

### ISSUE THREAD

**Issue by vanreus** [fooplugins/FooTable#432]
I have a footable with paging, filtering and sorting and loads my data using a $.getJSON. I am using the postdraw.ft.table event to add a row number to each row. It works perfectly when there are enough rows for multiple pages. However, if there is only enough data for a single page, the postdraw.ft.table event does not fire. Is this a bug?

**Comment by steveush** [comment]
Hi,

This is indeed a bug that has been squashed on my local repo and will be pushed live in the next version.

Thanks
