### ISSUE TITLE
[v3] Limit what is clicked to toggle a row... Or allow everything

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#433]
I have a few tables that contain cells with HTML content. When the HTML contains any block elements, you can not click those elements to toggle the row. This is frustrating to the user. Clicking one cell expands the hidden data and clicking some place else does not.

Here is an example to review:
https://output.jsbin.com/vozote

How can we either:
- Allow any inner HTML to also toggle the row without adding the footable-toggle to everything.
- Make it so nothing in the row is clickable, unless it has the .footable-toggle class.

Neither sound perfect here. Allowing "everything" to be clicked would be bad when you have elements within the cell that require a click... like a Bootstrap dropdown menu. Removing the row click also removes valuable functionality.  Adding the .footable-toggle class to elements seems like hack, but also seems to offer the most power. I say hack because I have not seen any documentation explaining that this is how we should handle these situations, and I do not like basing my projects on a guess.

I really love FT v3. Very powerful. But this is been a complaint with a few users already.

Thanks.

**Comment by jeffconklin** [comment]
Looks like there is a similar question about this already from Jan 2015:    https://github.com/fooplugins/FooTable/issues/309     They might be referencing v2 there though. Either way, at least a few people are looking for the proper solution for this. Any help would be great.

**Comment by jeffconklin** [comment]
Within the footable.js I see the following:

`_onToggle: function (e) {
    var self = e.data.self;
    // only execute the toggle if the event.target is one of the approved initiators
    if ($(e.target).is('tr,td,.footable-toggle')){
        self.toggle();
    }
}`

Would you consider making this configurable in the future? I still want to use .footable-toggle, but don't need TD or TR to ever be elements that fire off the toggle.

**Comment by steveush** [comment]
Hi @jeffconklin,

I'll create an option called toggleSelector that will let you set that .is selector value and check it in with the next round of fixes. It was actually made to be restrictive to prevent the row toggling when clicking a link in a row, or any interactive element, but it was definitely an oversight to not allow it to be changed.

Thanks

**Comment by jeffconklin** [comment]
Very nice. I will keep an eye out for an update. Thank you.

**Comment by jeffconklin** [comment]
Downloaded the latest version and tried it out... it is perfect. Thank you!
