### ISSUE TITLE
Footer (tfoot) columns not hiding along with the body columns

### ISSUE THREAD

**Issue by MSeneadza** [fooplugins/FooTable#434]
Does v3 not deal with hiding/showing columns in a table's footer?  I have a table with a footer where the body columns work as I expect but the footer never changes.  Any tips to get the footer's columns to hide along with the columns in the table's body?

**Comment by steveush** [comment]
Hi,

V3 does not handle custom tfoot rows. The footer is basically reserved space for the plugin at present for component UI like the paging component.

Thanks
