### ISSUE TITLE
FooTable Pagination in Bootstrap 4

### ISSUE THREAD

**Issue by CaptainBobby** [fooplugins/FooTable#436]
I just realized that pagination is no longer styled correctly with Bootstrap v4 so a quick fix is to add the following classes in footable.paginate.js:

to `<li>`:
class="page-item"

to `<a>`:
 class="page-link"

Looks like this:
`<li class="page-item footable-page-arrow"><a class="page-link" data-page="first" href="#first">`

Seems to work just fine for me. I'm still using v2 by the way. Why change when it still works?

**Comment by steveush** [comment]
Thanks, I'll be closing this as part of repo cleanup.
