### ISSUE TITLE
Checkbox issue in pagination (v3)

### ISSUE THREAD

**Issue by nafqureshi** [fooplugins/FooTable#437]
I have a column of checkbox in every row of the table. The issue is that after pagination when I select certain check-boxes from different pages and submit the form, the checkbox values of only the current page that I am on are forwarded. Any help would be highly appreciated.

**Comment by steveush** [comment]
Hi,

FooTable at present is made to show tabular data, and in doing so one of the biggest performance boosts is removing rows from the DOM when using paging to prevent browser slow downs on very large data sets. This is why you are only seeing the current page of data being submitted, the other pages no longer exist in the DOM and therefore no longer exist in your form. To achieve what you want I think the best bet would be to hook into your forms submit event and simply pull out the values you want to send to the server by parsing the rows.

To get an array of all rows being held in memory you can use something like the below:

``` javascript
var rows = FooTable.get('#table-id').rows.all; // var rows will be an array of FooTable.Row objects
for (var i = 0, len = rows.length; i < len; i++){
    var json = rows[i].value; // the json value of the row
    var jq = rows[i].$el; // the jQuery object for the row for custom parsing
}
```

Everything you need should be on the row object to be able to parse and submit the data.

Thanks

**Comment by nafqureshi** [comment]
is there any way that i could tweak the javascript of footable to have the complete list of rows?
