### ISSUE TITLE
Adding and removing row is not working  in V2.0.3 and V3

### ISSUE THREAD

**Issue by sahilchopra** [fooplugins/FooTable#439]
Hi

I am trying to add new row to footable. but seems like in latest version 
`var footable = $('table').data('footable');`
is undefined.

So http://fooplugins.com/footable/demos/add-delete-row.htm#docs is not working any more.

Do you know how we can fix that?

Thanks

**Comment by steveush** [comment]
Please have a look at the new editing component example in 3.0.8 to see how to make a table editable.
