### ISSUE TITLE
requirements/backward compatibility with jQuery 1.4.4

### ISSUE THREAD

**Issue by mvance** [fooplugins/FooTable#44]
Thanks a lot for writing the prior update to make footable work with jQuery 1.4.4. The [Drupal module integrating FooTable](https://drupal.org/project/footable) has gotten [relatively popular](https://drupal.org/project/usage/footable), as a result.

I'm writing to mention that backward compatibility with earlier versions of jQuery turns out to be an [ongoing issue](https://drupal.org/node/1927442). I managed to [track down](https://drupal.org/node/1927442#comment-7259592) the specific commit that appears to break backwards compatibility and I've [documented options for working around the issue in Drupal](https://drupal.org/node/1927442#comment-7259592) that don't require changes to the FooTable plugin.

If you'd prefer to just support "modern" versions of jQuery, just say the word. But if not, I'd be glad to relay backwards compatibility issues, if and when they come up.

**Comment by bradvin** [comment]
cool thanks for letting us know. One thing we do not really do when committing changes is check that is works on such older versions of jquery. Perhaps we should create a new branch that is specific to jquery 1.4.4 - if we do that will mean it might not have all the features that are in the main branch, but at least it will keep working going forward.

Please continue letting us know of issues you may find, and please, above all, push your fellow drupal users to upgrade their jquery to the latest versions - I know sometimes this is not always possible, but 1.4.4 is now almost 1.5 years old (was released in Nov 2011)

**Comment by EWB** [comment]
I just wanted to make a plea for supporting jQuery 1.4.4.  Our Drupal 7 projects will greatly benefit from Footable - and most of the options for moving to a higher/more up-to-date version of jQuery (as noted by mvance) are causing issues with other aspects of our deployments.  So, while completely understanding why this plea for supporting a now antique version of jQuery may not be feasible - it is important enough to a number of Drupalers that I thought it worth echoing.   Thank you

**Comment by bradvin** [comment]
I think creating a branch to cater for this type of backwards compatibility is the only way then.

**Comment by EWB** [comment]
That would be fabulous - and very much appreciated.
