### ISSUE TITLE
Paginating = true and breankpoints problems...

### ISSUE THREAD

**Issue by itajackass** [fooplugins/FooTable#440]
I've a table with paginating = true, size = 30.

If number of rows in table is >= 30, then all work propertly.
If number of rows in table is < 30, and I resize window, breakpoint doesn't work....i've to resize window, then update page with "F5"...only this time breakpoint works and i see correct layout....but if i resize again....breakpoint doesn't response......

**Comment by steveush** [comment]
Hi,

I found the issue and it has been fixed on my local repo. I will check in a new version once I've done a few more fixes.

As a temporary work around until I check in the commit you can also try out the below which should also resolve the problem. Just include the below JS in your page after you have included FooTable but before you call any plugin constructors.

``` javascript
FooTable.Paging.extend('draw', function(){
    if (this.total <= 1) return; // this is the fix
    this._super(); // call the original method
});
```

Thanks
