### ISSUE TITLE
Where is footable.core.css?

### ISSUE THREAD

**Issue by silverandrew** [fooplugins/FooTable#441]
http://fooplugins.com/plugins/footable-jquery/ mentions:

Include FooTable Core CSS
XHTML
<link href="path_to_your_css/footable.core.css" rel="stylesheet" type="text/css" />

but I don't see footable.core.css in the compiled folder. Did it get renamed to something else?

**Comment by steveush** [comment]
Hi,

That particular product page needs to be updated. It still has details up for V2. Please take a look at http://fooplugins.github.io/FooTable/docs/getting-started.html for the updated docs for V3.

Thanks
