### ISSUE TITLE
Maximum Call Stack Size Exceeded

### ISSUE THREAD

**Issue by silverandrew** [fooplugins/FooTable#442]
I tried importing rows from a large .JSON file using

"rows": $.get('output.json') 

and the data doesn't load. Safari says: "Maximum call stack size succeeded."

Workaround? I can import the json myself and display it in a normal HTML table. 

Is there a way to add the rows to the FooTable <table> one by one?

**Comment by steveush** [comment]
Hi,

You can always generate the table yourself and then initialize FooTable on it but you should not be seeing that error. How many rows are you trying to load? Do you have an example I could look at? As you can see from [the example page](http://fooplugins.github.io/FooTable/docs/examples/advanced/ajax.html) everything is working as it should when loading from a JSON source.

I'm guessing there is a configuration issue somewhere that just needs to be corrected.

Thanks

**Comment by silverandrew** [comment]
a little over 75,000. When I chop the json file down to 50,000 rows, it works fine. JQUERY.get() seems to be timing out after about 3 seconds. Is there no appendRow function in V3? Or, do you know how to make this .GET() call so that I can change the timeout, a la http://stackoverflow.com/questions/5225597/set-timeout-for-ajax-jquery ?

**Comment by steveush** [comment]
Hi,

Here is [the example](http://fooplugins.github.io/FooTable/docs/examples/basic/single-header.html) showing how to initialize it from a table element however with 75,000 rows I think you will run into issues with memory in browsers. Realistically I don't think FooTable is capable of handling what you are trying to load into it. In this situation with so many rows you need actual server side paging, filtering, sorting etc. which the current FooTable is not capable of doing. In our demos we handle 10,000 rows, this is around what we intended FooTable to be used for although I have tried up to around 25,000 rows without too much issue but this number could depend heavily on the device it was being run on.

There have been a few people asking for a purely ajax solution which loads only the current page rows and we are thinking about making one however it would then fall on the developer to create the server endpoints and database queries to handle the components such as filtering, sorting and paging. FooTable would basically just be providing the responsive layout and UI as all the heavy lifting and logic occurs server side.

Thanks

**Comment by silverandrew** [comment]
Thanks. Do you know of another project I could use instead?

**Comment by steveush** [comment]
Hi,

With such a large number of rows I believe https://datatables.net/ would be your best best. They have been around for a long time and have a solid solution for large complex tables.

Thanks
