### ISSUE TITLE
Event Fired After First (and only first) Time Rendering [v3]

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#444]
Hello,
I need to run a block of code after the table has loaded, taken over by Footable, and drawn completely for the first time. The closest thing that I see is 'postdraw.ft.table', but that is fired every time the table is drawn. meaning after filtering, sorting, etc. Currently, within my postdraw.ft.table code bock, I check to see if some arbitrary variable has some arbitrary value and firer my code appropriately. I would much rather have a dedicate "postinit" or "completed" event fired at the appropriate and predictable time for that table. Maybe I missed it? Or is creating a flag as I am doing now a better option?

Thanks.

**Comment by steveush** [comment]
Hey Jeff,

You can use the FooTable ready callback to do this. The first argument supplied to this callback and the `this` keyword within the callback are the FooTable instance itself.

Using the jQuery constructor:

``` javascript
$('#table-id').footable({/* Your Options*/}, function(ft){
    // this should be executed only once after init
});
```

Using the object constructor:

``` javascript
FooTable.init('#table-id', {/* Your Options*/}, function(ft){
    // this should be executed only once after init
});
```

Thanks

**Comment by jeffconklin** [comment]
Thank you for the quick reply. It led me in a good direction.

The one thing that I do want to mention is that including a "postinit.ft.table" type event would be just as powerful as being able to watch for the other events you already fire. With this included, I would instantiate FT, and on the "postinit.ft.table" event firing, perform whatever other tasks I need to perform. Listening for an event makes this more predictable and less intrusive than having to add something specific into the FT callback itself. Please review the following. They both show a simple way to add extra functionality after the table loads/renders:

A) Using JQuery constructor: [jsbin.com/wakuvi](http://jsbin.com/wakuvi)
B) Using a non-JQuery constructor flow: [jsbin.com/roxelez](http://jsbin.com/roxelez)

Though I was able to use the JQuery callback as you mentioned, I now have to include some non-FT code within my Footable specific code. Long term this is a bit messy and hard for multiple people to maintain.

Either way, thank you for the direction. I always appreciate your hard work on this great plugin.

**Comment by steveush** [comment]
I definitely see the value to adding in the event, it's the same reasoning for the callback existing in the first place. I'll add this into the next version but if you want to you can make a makeshift patch by doing the following which should allow you to separate your code and minimize the amount of changes that will be required when I add in the event to the plugin itself. Basically you would just need to remove the ready callback and everything should continue to function once the event is added.

``` javascript
$('#table-id').footable({/* Your Options*/}, function(ft){
    ft.raise('postinit.ft.table');
});
```

Using the above you would then be able to bind to the `postinit.ft.table` event the same way you would any other FooTable event.

On a side note you can pass in an array as the second parameter to the `FooTable.Table#raise(string, Array)` method and the values will be passed onto any bound event handlers as additional arguments after the event object and FooTable instance arguments. As an example using `ft.raise('my-event', ['param1', 'param2'])` the event handler would look something like the below:

``` javascript
function myEventHandler(e, ft, param1, param2){
}
```

Thanks

**Comment by jeffconklin** [comment]
Thank you again. I have updated my example above (B - jsbin.com/roxelez) to include the temp raise as you described. Works perfectly. I will certainly take this direction within our scripts.

You second example (ft.raise('my-event', ['param1', 'param2'])) is very creative, and very powerful. I do appreciate you sharing that. I can see how this would be useful in a few scenarios.

Thanks again.
