### ISSUE TITLE
data-sorted="true" Defaults to DESC, Backwards From Docs (v3)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#445]
Hello,

I have a table with a column labelled order. This column literally shows the order of the rows in that table ... 1 though X --- lowest to highest.

When I add data-sorted="true" to the Order column, the order switches to Highest to Lowest after initialization of FT.

As per your Docs, the default order should match the order of the table, which is ASC (lowest to highest). To allow this to work properly with the new Sort Check functionality ( #443 ) I am required to also add data-direction="ASC" to actually get the proper icon / sort to be used.

I made a JSBin example to show the issue:
[http://jsbin.com/qecaci](http://jsbin.com/qecaci)

You will see that I have data-Xdirection="ASC". Removing the "X" shows the ASC working properly.

Just for clarification, I am expecting (per your DOCS) to see ASC default, but I am seeing DESC instead.

-Jeff C

**Comment by steveush** [comment]
Fixed in 3.0.9
