### ISSUE TITLE
Footable 3.0.8 not work !!

### ISSUE THREAD

**Issue by Rgl88** [fooplugins/FooTable#446]
hello i can not use your plugin, i test and finally find old version of this plugin in this site
https://responsivedesign.is/resources/data-tables/footable
an it work correctly and easily
you use footable.core.css in demo but this file not exist in source?
i test all css and js files footable.core.standalone.css , ... but not work

**Comment by steveush** [comment]
I suggest reading the documentation on the [Getting Started](http://fooplugins.github.io/FooTable/docs/getting-started.html) page. It works, trust me...
