### ISSUE TITLE
pagination control shows only when reloading the page

### ISSUE THREAD

**Issue by pirat8** [fooplugins/FooTable#449]
I use V3.0.8 in a ruby on rails application with bootstrap(v3). My table looks like:
`<table class='table footable'`data-filtering='true'  data-paging-size='12' data-paging='true' data-sorting='true'>
`<thead>`
`...`
   `</table>`
`...`
`<script src='/assets/dr_bee_footable.self-f1d862b4d94c022985bb11ebfdeabfa7b73ef64db7a276559dd438adbb93c7a.js?body=1'></script>`
`<script>`
 `$( document ).ready(function() {
    $('.footable').footable();
  });
</script>
</body>
</html>`
The content of the table is not loaded by ajax but is plain html.

In the javascript I do some customized filtering.

The problem: The pagination control does not appear when I load the page. Only when I do a reload (Ctrl-R in the browser) I get it. On first load only 12 rows appear like in data-paging-size specified.

The problem seems independent from my customized filtering. The error appears too when I omit this part. After reload my page/table works as expected(sort/filter/pagination).
Sometimes it seems to work also on first load. What could be the problem?

**Comment by steveush** [comment]
Hi,

I really couldn't say what the issue might be, I haven't encountered this myself. Could you provide a link to a url or maybe a jsfiddle that I could see the issue live?

Thanks

**Comment by pirat8** [comment]
Hi,
I will come back to you later. For now just one observation. When I reboot my rails server it works for the first time I call the resource.  It shows the table with pagination control. 
When I then go back to the the dash board of my application and in the next step I call my resource again the pagination control does not appear. I have to press Ctrl-R for reload in the browser. Then it comes back. Do you have a idea what could be the background?

**Comment by pirat8** [comment]
I think the problem is related to turbolink which I use in my rails application. I use now version 5.0.0.beta2 of turbolink and the problem disappeared. Formerly I used version 2.5.3. Maybe someone can reproduce the effect.

**Comment by steveush** [comment]
Hi pirat8,

This sounds like a caching issue related to the turbolink which has since been resolved so I'll close this issue.

Thanks

**Comment by pirat8** [comment]
Ok.

**Comment by ArthurBrum** [comment]
Any update on this issue?
Can you confirm this was due to the turbolink,  @pirat8 ?
