### ISSUE TITLE
Custom filter usage with multiple tables on 1 page [V3]

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#451]
Hello,

I have implemented your custom filtering ( http://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html ) in multiple pages of my site. I now have a page with multiple tables. Both tables require filtering, with one of them requiring special (custom) drop down for filtering, the other one does not.

Within your demo you have provided:
FooTable.components.core.register('filtering', FooTable.MyFiltering);

This sets it up too add filtering to all tables and not just the one it actually relates to. How can I set up a custom filter for 1 specific table, and not all tables on the page with filtering enabled? maybe I missed something simple / specific?

I set up a stripped down demo of this here:
jsbin.com/coqeko

Thanks.

**Comment by steveush** [comment]
Hey Jeff,

I suggest having a look at [this custom filter UI example](http://fooplugins.github.io/FooTable/docs/examples/advanced/custom-filter-ui.html) from the docs. The way provided previously is indeed intended as an additional base component for the plugin and as such is available across all tables. If you want to provide custom filtering for multiple tables in the same page the above example shows how you can achieve that.

Thanks

**Comment by jeffconklin** [comment]
Wanted to add a follow up here. With the release of 3.1.0, custom filtering can now be set as table specific. I have updated my previously noted demo (http://output.jsbin.com/coqeko) to show this. 

Great work, @steveush !
