### ISSUE TITLE
Using with React

### ISSUE THREAD

**Issue by gelevanog** [fooplugins/FooTable#452]
Is there way to use this plugin with React? 

This pattern from [here](http://57f4dad48e7a4f7cd171c654226feb5a.proxysheep.com/questions/36576722/footable-with-reactjs-how-can-i-call-jquery-plugin-from-reactjs-component) is not working correctly 

``` javascript
componentDidUpdate: function(prevProps, prevState) {
    jQuery(ReactDOM.findDOMNode(this.refs.sampletable)).footable();
},

<table ref="sampletable">
```

It throws the following errors to console:

``` javascript
FooTable: unhandled error thrown during a draw operation. TypeError: Cannot read property 'toUpperCase' of undefined(…)

FooTable: unhandled error thrown during initialization. TypeError: Cannot read property 'toUpperCase' of undefined(…)
```

**Comment by steveush** [comment]
Hi,

Could you please show me your table configuration (either through options or the actual rows and cells etc.). The only place in the code that I see that could possibly be throwing that error is the `FooTable.str.toCamelCase` function which is used as part of a `css2json` method that converts a CSS text string like `display:none; color: red;` etc. to a JSON object. This parsing occurs when the `style` attribute or option is used on a column (TH), a cell (TD) or a row (TR) and the only way I can see it throwing this error would be if there is a mistake in the CSS text syntax or there is something I am not accounting for during the parsing which is leading to an undefined value being passed into the `toCamelCase` function.

Thanks

EDIT: Just wanted to add that I do not use React for anything myself so I'm just looking into the error.
EDIT2: If you could provide a jsfiddle showing the error that would be great so I can actually step through the JS and see where it's going wrong.

**Comment by gelevanog** [comment]
Unfortunately it is a huge project to start it up on jsFiddle.
But here is the pivotal code: 
product-table.js

``` javasript

import React, { Component, PropTypes } from 'react';
import ReactDOM from 'react-dom';
import { ProductItem } from './product-item';


export class ProductList extends Component {
  static propTypes = {
    filter: PropTypes.string,
    products: PropTypes.array.isRequired
  };

  renderProductItems() {
    const {
      filter,
      products
    } = this.props;

    return products
      .filter(product => {
        if (filter === 'enabled') return !product.disabled;
        if (filter === 'disabled') return product.disabled;
        return product;
      })
      .map((product, index) => {
        return (
          <ProductItem
            key={index}
            product={product} />
        );
      });
  }

  componentDidUpdate(prevProps, prevState) {
    // table initialization
    jQuery(ReactDOM.findDOMNode(this.refs.productstable)).footable();
  }

  render() {
    return (
      <div className="hpanel">
        <div className="panel-body">
          <table ref="productstable" className="table table-hover">
            <thead>
              <tr>
                <th></th>                
                <th>Title</th>
                <th data-breakpoints="xs">Description</th>
                <th data-breakpoints="xs sm">Quantity</th>
                <th data-breakpoints="xs sm">Price</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {this.renderProductItems()}
            </tbody>
          </table>
        </div>
      </div>
    );
  }
}

```

product-item,js

``` javascript
import classNames from 'classnames';
import React, { Component, PropTypes } from 'react';
import ProductFormEdit from './product-form-edit';

export class ProductItem extends Component {
  static propTypes = {
    product: PropTypes.object.isRequired
  };

  constructor(props, context) {
    super(props, context);
  }

  render() {
    const { editing } = this.state;
    const { product } = this.props;
    return (
      <tr>
        <td><button className="btn btn-success btn-circle" type="button"><i className="fa fa-check"></i></button></td>
        <td>{product.title}</td>
        <td>{product.description}</td>
        <td>{product.quantity}</td>
        <td>${product.price}</td>
        <td className="text-right">
         // never mind - that's not important component
          <ProductFormEdit />
        </td>
      </tr>
    );
  }
}

```

I hope it is enough to figure out how it's working. Thank you.

**Comment by steveush** [comment]
HI,

Since this issue was logged there has been numerous updates to FooTable including quite a few which added more parameter checks to some of the utility functions. With regards to this issue there was another one logged which did provide a simple method to replicate what was causing the `TypeError: Cannot read property 'toUpperCase' of undefined(…)` and so I believe this issue is resolved and so I'm closing this.

Thanks

**Comment by abasreal** [comment]
it still happen
