### ISSUE TITLE
Prevent line break

### ISSUE THREAD

**Issue by sturze** [fooplugins/FooTable#453]
Hey guys!
a question, maybe i am just to dumb...

is there a way to prevent a way to prevent a tablecell to break the line?

Maybe i have to give an example...
i have two cells, almost the same width but one of them breaks, the other dont...
like:

``` html
tel           |               fax                |             bla....
0800 400      |          0800 400 200 70 20      |              bla...
300 20        |                                  |              bla  ....
```

what defines which of them is bigger than the other?!
know what i mean?

**Comment by steveush** [comment]
Hi sturze,

How column width is calculated in various browsers is a bit of a pain as it was left completely up to vendors to come up with a solution, for more information and the w3 spec check out [this stackoverflow answer](http://stackoverflow.com/questions/17150154/how-is-column-width-determined-in-browser).

As for preventing line breaks you should be able to use 3 methods using FooTable to prevent this occurring, all make use of the CSS `white-space:nowrap;` value. That said some browsers may ignore the below on small screen sizes and either break the line or simply prevent the table from getting any smaller and so horizontal scroll bars may pop up.

1 - Using plain CSS and the `:nth-child(n)` selector. The `n` is the position of the column within the table, this is basically the index + 1. So the below would prevent line breaks in the second column.

``` css
#table-id tbody>tr>td:nth-child(2) {
  white-space:nowrap;
}
```

2 - Using the `classes` option of a column to apply a CSS class to each cell in a column.

``` css
.no-line-break {
  white-space: nowrap;
}
```

To apply the class to all cells within the column use the `data-classes` attribute to specify the CSS classes on the element itself or supply the `classes` value through the constructor like other column options.

``` markup
<table id="example">
  <thead>
    <tr>
      <th data-classes="no-line-break">ID</th>
```
1. Using the `style` option of a column to apply inline styles on each cell in a column. To apply the style to all cells within the column use the `data-style` attribute to specify the CSS text on the element itself or supply the `style` value through the constructor like other column options.

``` markup
<table id="example">
  <thead>
    <tr>
      <th data-style="white-space: nowrap;">ID</th>
```

Thanks
