### ISSUE TITLE
Problem with the ajax option

### ISSUE THREAD

**Issue by JujuPomme** [fooplugins/FooTable#455]
Hey,

I Hope everyone is fine.
First of all, thanks for this great plugin, it's awesome ! Very useful, easy to use... Very nice, congrats to the developers.
Second, sorry for my bad english, I'm french and i'm learning english every day :) 

I've one problem, it's to load some datas with an ajax request.

First, here's my code : 
``$(document).ready(function() {
    var $modal = $('#editor-modal'),
    $editor = $('#editor'),
    $editorTitle = $('#editor-title'),
    ft = FooTable.init('#editing-example', {
        ajaxEnabled: true,
        "sorting": { "enabled": true },
        columns: $.get('columns.json'),
        //rows: $.get('test.json'),
        "rows": $.get('server_side_interlocuteur.php'),
        editing: {
            "addText": "Ajouter un nouvel interlocuteur",
            enabled: true,
            addRow: function(){
                $modal.removeData('row');
                $editor[0].reset();
                $editorTitle.text('Ajouter un nouvel interlocuteur');
                $modal.modal('show');
            },
            editRow: function(row){
                var values = row.val();
                $editor.find('#nom').val(values.I_NOM);
                $editor.find('#prenom').val(values.I_PRENOM);
                $editor.find('#telephone').val(values.I_TEL1);
                $editor.find('#portable').val(values.I_TEL3);
                $editor.find('#email').val(values.I_EMAIL);
                $editor.find('#fonction').val(values.I_ADRESSE4);

```
            $modal.data('row', row);
            $editorTitle.text('Modifier ' + values.I_PRENOM + ' ' + values.I_NOM);
            $modal.modal('show');
        },
        deleteRow: function(row){
            var values = row.val();
            alert(values.I_PRENOM);
            // mettre I_EMAIL dans I_COMMENTAIRE
            if (confirm('Voulez-vous vraiment supprimer cet interlocuteur?')){
                row.delete();
            }
        }
    }
}),
uid = 10;
```

$editor.on('submit', function(e){
    if (this.checkValidity && !this.checkValidity()) return;
    e.preventDefault();
    var row = $modal.data('row'),
        values = {
            I_NOM: $editor.find('#nom').val(),
            I_PRENOM: $editor.find('#prenom').val(),
            I_TEL1: $editor.find('#telephone').val(),
            I_TEL3: $editor.find('#portable').val(),
            I_EMAIL: $editor.find('#email').val(),
            I_ADRESSE4: $editor.find('#fonction').val()
        };

```
if (row instanceof FooTable.Row){
// edit
    row.val(values);
} else {
    // add
    //ft.rows.add(values);
    $.ajax({
        url: 'insert_in_bdd.php',
        data: { nom: values['I_NOM'], prenom: values['I_PRENOM'], telephone: values['I_TEL1'], portable: values['I_TEL3'], email: values['I_EMAIL'], fonction: values['I_ADRESSE4'] }
    });
}
$modal.modal('hide');
```

});
});``

A very simple sample of code...
The thing is, when I want to load data from my php file (server_side_interlocuteur.php), it's not working and i'm not able to understand why. 

So, I try something : 
With Firebug, my PHP's file response is a valid JSON. So I put it in an another file name test.json, and when I call it with the "rows" option, it's working !

What I am doing wrong?

Thanks a lot, if I can have some help, it could be great.

Congrats again for your plugin !

**Comment by steveush** [comment]
Hi,

Everything looks correct and your English is very good, far better than my French :P The only thing I can think of is the mime type of the server response is set to something like plain text or HTML instead of `application/json` and so jQuery's `$.get` is not returning a JSON object. You should be able to see the returned mime type using the network tab of Firebug. If this is the reason then you have two options;
1. Correct the mime type on the server resource.
2. I think you might be able to just change `$.get('server_side_interlocuteur.php')` to use the more verbose `$.ajax` function below with an additional option which instructs jQuery to interpret the results as JSON.

``` javascript
$.ajax('server_side_interlocuteur.php', {dataType: 'json'})
```

Thanks

**Comment by JujuPomme** [comment]
Hi,

Thanks for your answer ! It's glad to have some support...

I'm sure that your french is not so bad :)

So you're correct, the content-type of my php file is text/html.

I tried to add header('Content-Type: application/json'); before return my data, but nothing change.

I tried also to use the $.ajax option like that : 

`ft = FooTable.init('#editing-example', {
        ajaxEnabled: true,
        "sorting": { "enabled": true },
        columns: $.get('columns.json'),
        //rows: $.get('test.json'),
        "rows": $.ajax('server_side_interlocuteur.php', {dataType: 'json'}),
        editing: {
            "addText": "Ajouter un nouvel interlocuteur",
            enabled: true,
            addRow: function(){
                $modal.removeData('row');
                $editor[0].reset();
                $editorTitle.text('Ajouter un nouvel interlocuteur');
                $modal.modal('show');
            },
            editRow: function(row){
                var values = row.val();
                $editor.find('#nom').val(values.I_NOM);
                $editor.find('#prenom').val(values.I_PRENOM);
                $editor.find('#telephone').val(values.I_TEL1);
                $editor.find('#portable').val(values.I_TEL3);
                $editor.find('#email').val(values.I_EMAIL);
                $editor.find('#fonction').val(values.I_ADRESSE4);

```
            $modal.data('row', row);
            $editorTitle.text('Modifier ' + values.I_PRENOM + ' ' + values.I_NOM);
            $modal.modal('show');
        },
        deleteRow: function(row){
            var values = row.val();
            alert(values.I_PRENOM);
            // mettre I_EMAIL dans I_COMMENTAIRE
            if (confirm('Voulez-vous vraiment supprimer cet interlocuteur?')){
                row.delete();
            }
        }
    }
}),`
```

The loading symbol disappear after 1 second, and nothing is displayed.

But nothing changes too... Have I to combine both solutions?

Thanks again, and thanks a lot !

**Comment by JujuPomme** [comment]
One more thing : When I change to the $.ajax option and I set the header to application/json, my php file is not called by the $.ajax option... A bit strange

**Comment by JujuPomme** [comment]
It's working well !!!

I change the $.ajax option to $.get, set the dataType to json, set the header in my php file and everything is working fine !

Thanks a lot to you.

(If u want some french lessons, I can give you some tips in return ;) )

Thanks, and one more time, congrats for this great plugin !

**Comment by steveush** [comment]
Glad to hear it's working, will close this issue then. Just remember to always set the mime type header for your endpoints, browsers and client side languages rely on it for quite a bit ;)
