### ISSUE TITLE
custom filter for specific column begin empty

### ISSUE THREAD

**Issue by sergeykk** [fooplugins/FooTable#456]
Hello,

I have started using FooTable v3 and like it a lot. I have created custom filters but now need to create filter to display rows with specific column being empty - is this possible?

Also does FooTable.query support other logical operators (such as NOT) besides OR and AND? 

Thanks,
Sergey

**Comment by steveush** [comment]
Hi Sergey,

There are some other logical operators, if you scroll down on the below page of the docs it lists them with some basic examples: http://fooplugins.github.io/FooTable/docs/components/filtering.html

As for filtering for an empty column, it's not something I have thought about really and will need to get back to you on that once I've tried some things on my local.

Thanks

**Comment by sergeykk** [comment]
Hi Steve,

Thank you!

For empty column may be something like "" or NULL to use as query string.

regards,
Sergey

**Comment by steveush** [comment]
Hi Sergey,

I've managed to implement this using `""` as the query string for an empty value. The one thing to take into account is the way FooTable performs it's checks to see if a row contains the supplied query string. Basically the way it works is the plugin combines all row values into a single string and this string is then used to perform the filter match. What this means is that if you had multiple columns and only one contained an empty value you must specify to search for an empty value only in that column.

As an example of what I mean above lets take the below table as an example:

| ID | Name | Title |
| --- | --- | --- |
| 1 | Steve | Developer |
| 2 | Sergey |  |

If I then search for an empty value using `""` across all columns it will not match anything as internally FooTable sees the rows as:

`"1 Steve Developer"`

and 

`"2 Sergey"`

So neither of the "row" strings are empty so they do not match. If you had to specify to only search the `Title` column then FooTable would see the rows as:

`"Developer"`

and 

`""`

As you can now see the second row matches our query string and so the second row would be returned in the results.

FYI The negate query string syntax also works for empty values so you could search for `-""` to pull all records where the value was not empty.

I'll be releasing a new version in the next day or two with these changes implemented.

Thanks

**Comment by sergeykk** [comment]
Hi Steve,

many thanks, that should do the trick

regards,
sergey

**Comment by steveush** [comment]
Hi, this should be available in 3.0.10
