### ISSUE TITLE
How to sort a html column

### ISSUE THREAD

**Issue by mqueirozcorreia** [fooplugins/FooTable#457]
I want to sort a html column using specif values. The visual effect what I want is this:
https://jsfiddle.net/mqueirozcorreia/z6d72jez/

But I want to sort the image column by red (value 1, top priority), yellow (value 2, middle priority), green (value 3, low priority). If I click in the above example, it cant order in the way...

When I set the cell(<TD>) data-value attribute, it ignore the image and use the value in the render:
https://jsfiddle.net/mqueirozcorreia/fsy8fgge/

I was able to set this behavior at the footable v2.

Can anybody help me?

**Comment by steveush** [comment]
Hi,

You can use `data-sort-value` for sorting as well as `data-filter-value` for filtering to provide specific values for these components to use.

http://fooplugins.github.io/FooTable/docs/components/sorting.html#cell-sortValue

Thanks

**Comment by mqueirozcorreia** [comment]
Thank you. It solved my problem
