### ISSUE TITLE
Reload data/ Footable

### ISSUE THREAD

**Issue by JujuPomme** [fooplugins/FooTable#458]
Hey all,

I've a problem to reload my footable.
I explain : When i add a customer in my table, first, I can't edit it, I have to reload the full page... >First thing.
Second, I have several tabs in my page, and for example, if I leave my tab where my footable is, and I was at the third page, when I come back on this tab, with a new company, I'm always on the third page with the old company. So it's not refresh with new data...

How can I fix it?

Thanks, and congrats again for this great plugin !
(Sorry again, I'm always french, and I'm always improving my english ! )

**Comment by JujuPomme** [comment]
I add one thing :
When I click several time on my tab (where I can see my table), it display one footable more each time and of course, you guess something like that : https://gyazo.com/c0c36830ceee605ab2da87e6c91ebbf2

**Comment by steveush** [comment]
Hi, this should be fixed in 3.0.10
