### ISSUE TITLE
SORTING: Type Number removes special chars

### ISSUE THREAD

**Issue by chrys1110** [fooplugins/FooTable#459]
When I set the data-type to Number. All the special chars like . and , are getting removed.

More Info:
I tested it multiple times. It's only after it's sorted. Before it stays the correct value (i.e. "12.34").

**Comment by steveush** [comment]
Hi,

This seems to be an incorrect default value for the thousand separator option for number columns. Please can you try adding `data-thousand-separator=","` to your number column (the `TH` you specified with `data-type="number"`) and let me know if it resolves your issue. I'll need to update the default value in the next release.

Thanks

EDIT: You can also use `data-decimal-separator` to specify that value as well.

**Comment by chrys1110** [comment]
Thanks. It works with this workaround

**Comment by steveush** [comment]
Hi, this should be fixed in 3.0.10
