### ISSUE TITLE
Filtering feature: "Reset" button?

### ISSUE THREAD

**Issue by ricardozea** [fooplugins/FooTable#46]
Hello,

Although not an issue per se, is there a way to have/add/create a "Reset" button for the filtering feature?

**Use case**

While working on a demo page for a client, I kept testing the filter feature (which worked very well). The issue I noticed was that every time I wanted to try a new keyword I had to press back space or select+delete. 

My thought is that maybe users could very well go through the same experience of "trying" different keywords to see the different results the table could offer, but to do so they have to press back space or select+delete every single time in order to 'clear' the input field.

When using the filtering feature I think that it's very likely that a user wouldn't necessarily know off the bat which keyword to type, but instead try several.

So maybe adding a Reset button or a keyboard combination (or simply press ESC) to clear the input field could improve the usability of the filtering feature.

Just throwing out ideas for this awesome project.

What do you think?

Thanks.

OFFTOPIC: BTW, there's a typo in the page http://themergency.com/footable/ -  it says _"Fitlering"_ instead of "Filtering".

**Comment by mleisher** [comment]
In http://github.com/mleisher/Horton (very similar to FooTable), the Escape key clears the filter input field.

**Comment by bradvin** [comment]
check out the changes made to the filtering extension

It now takes into account the escape key and I also allow you to clear the filter from your own custom event. So in the filtering demo, I added a "x" link next to the filter which clears the filter. So you can do something similar to do your reset button

```
  $('.clear-filter').click(function(e) {
    e.preventDefault();

    $('table').trigger('footable_clear_filter');
  });
```

**Comment by bradvin** [comment]
@rzea thanks for the heads up about the typo on my page - it is corrected now

**Comment by ricardozea** [comment]
Sorry for my late reply.

I checked your filtering demo but I don't see the "x" link you mentioned: http://themergency.com/footable-demo/demo-filtering.htm

Did I miss something?

Thanks.

**Comment by bradvin** [comment]
@rzea I have not updated the live demos on my site yet - check out the latest code, it is in there

**Comment by ricardozea** [comment]
Got it, will check. Thanks again.

EDIT--

@bradvin Resetting the input field with the `ESC` key works great man, thanks a million for implementing.

EDIT 2--

OFFTOPIC: Your Encoder/Decoder extension for Chrome is a godsend, thanks for that as well. [Twitted about it.](https://twitter.com/ricardozea/status/323840683964260352)

**Comment by bradvin** [comment]
@rzea cool - glad you like the chrome extension too - I was sick of having to visit websites to decode/encode URLs and HTML
