### ISSUE TITLE
sortable and icon

### ISSUE THREAD

**Issue by dmaglio** [fooplugins/FooTable#460]
i have installed footable and made sortable my table, but the icons are different between demo and local. for example, the double arrow in demo is displayed by "TM" mark. the content are the same "\e150"

**Comment by dmaglio** [comment]
![schermata3](https://cloud.githubusercontent.com/assets/446573/15398564/5fb06e74-1de4-11e6-89d7-2da1e683a4e0.png)

**Comment by steveush** [comment]
Hi,

The icons used by FooTable are either FontAwesome in the standalone version or if using the Bootstrap version it uses the Glyphicons icon set. It sounds as if you have another font being loaded in your page which is incompatible with which ever version you are using. Unfortunately this is not a plugin issue to resolve as we make use of the before mentioned widely available icon sets but rather an implementation one that you will need to figure out.

Thanks
