### ISSUE TITLE
i18n for defaults 'Search' an 'No results'

### ISSUE THREAD

**Issue by pirat8** [fooplugins/FooTable#465]
I use footable in my application together with i18n-js. 
What is the best way to internationalize the strings "Search" from footable.filtering.js 
and "No results" in footable.core.js in my application?
Here is a [screenshot](http://www.randspringer.de/missing_i18n_footable.png) .
For my customized written filter I used i18n-js (green) but the hard coded is red.

What should work is to patch the footable*js files but may be there is a better way.

Thomas

**Comment by steveush** [comment]
As per the documentation, for the "Search" string use the http://fooplugins.github.io/FooTable/docs/components/filtering.html#placeholder option. For the "No Results" string use the http://fooplugins.github.io/FooTable/docs/getting-started.html#empty option.

Thanks

**Comment by pirat8** [comment]
Cool, thanks.
