### ISSUE TITLE
documentation incorrect

### ISSUE THREAD

**Issue by anddyson** [fooplugins/FooTable#466]
Hi

Not sure if an issue is the right way to highlight this but I can't see any other contact details.

The documentation at https://fooplugins.github.io/FooTable/docs/columns/date.html appears to be incorrect. it states that "data-formatString" is the attribute to use to set a date format, but this doesn't work. I discovered by trial and error that "data-format-string" is correct. I later discovered (by accident) that the example at https://fooplugins.github.io/FooTable/docs/examples/component/sorting.html confirms this.

This minor typo caused me a great deal of frustration and wasted time, so I just wanted to highlight this for anyone else who comes across it, and hopefully the documentation can be corrected.

Thanks

**Comment by steveush** [comment]
Ah, sorry about that, and yes this is the best place to bring it up. It seems I made a copy paste mistake there when I copied the JavaScript option name to make the attribute name. I've corrected it and updated the docs.

Thanks
