### ISSUE TITLE
Show more than 10 results

### ISSUE THREAD

**Issue by ashleya** [fooplugins/FooTable#467]
Hi, i'd like to show more than 10 results. For example, shopping cart has 13 items in it, but Footable is only displaying 10: https://www.soundexchangetampabay.com/index.php/view-cart/?on=87035 

Checked docs on footable website, but I don't see how to do this. 

Please help :) 

Thank you.

**Comment by steveush** [comment]
Hi,

You will need to make use of the [paging components size option](http://fooplugins.github.io/FooTable/docs/components/paging.html#size), just click on the option and it will show you how to use it ;)

Thanks

**Comment by steveush** [comment]
It also just occurred to me that for your type of table you may just simply want to disable paging all together which may be a simpler option to do.

Thanks

**Comment by ashleya** [comment]
Thank you!!

On Wed, Jun 1, 2016 at 3:58 AM, steveush notifications@github.com wrote:

> It also just occurred to me that for your type of table you may just
> simply want to disable paging all together which may be a simpler option to
> do.
> 
> Thanks
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/fooplugins/FooTable/issues/467#issuecomment-222920188,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADD9-g_Tk7aadpOKoaQm6s3cHD9hIdGXks5qHTuVgaJpZM4IqsM9
> .

## 

Ashley Sica / (813) 777-7350 / ashley@marketinggrouptampa.com
