### ISSUE TITLE
Data-Name not showing at toggle

### ISSUE THREAD

**Issue by mqueirozcorreia** [fooplugins/FooTable#469]
At footable v2, you could set the data-name attribute and that was showed at the toggled content:
https://jsfiddle.net/mqueirozcorreia/m5uzfgon/

You can see this behavior on the link above, when you click in the first column (First Name). The content "DOB (hidden)" is replaced by "Data of Birth"

However, at footable v3, the same behavior doesn't occur:
https://jsfiddle.net/mqueirozcorreia/d94z2ye7/

Have anyone faced this situation? Is this an problem or the behavior has definitively changed?

**Comment by steveush** [comment]
Hi,

Please check out the [name](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-name) and [title](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-title) column options.

In summary the `name` option specifies the property name the column binds to on the underlying data source while the `title` option allows you to specify a friendly name that is displayed.

Thanks
