### ISSUE TITLE
FooTables with jQuery 3.0 causes lots of repaints

### ISSUE THREAD

**Issue by jleider** [fooplugins/FooTable#472]
Attempting to use FooTables with jQuery 3.0 causes lots of repaints as the form is initialized. Since jQuery finally started using requestAnimationFrames in 3.0 for its DOM manipulation I would venture a guess that all the state setting DOM manipulations made by FooTables which had gone unnoticed and unpainted are now being surfaced by jQuery's more efficient interaction with the browser.

**Comment by steveush** [comment]
Hi,

I haven't had a chance to test FooTable yet with jQuery 3.0, if you could provide more details and how you tested that would help me out a lot. Also FooTable 3 was built to work with Bootstrap 3 which currently will throw out an an error when using jQuery 3.0. The error is quite simply `Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`. So at present I am not surprised that there may be some issues that need to be worked through.

Thanks

**Comment by jleider** [comment]
Fixed by #556
