### ISSUE TITLE
Help me please :)

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#476]
Good day, there is some way to keep the state of the grid to make a postback? .NET to perform a postback inside an UpdatePanel, the page number is lost ..

**Comment by steveush** [comment]
Hi,

You can use the [paging.current](http://fooplugins.github.io/FooTable/docs/components/paging.html#current) option to set which page FooTable loads up first. So after your post back initialize FooTable with the correct page number and it should do what you need. As for how to get the current page number before you perform the post back you can use the below JS snippet to get it.

``` javascript
var currentPage = FooTable.get("#table-id").use(FooTable.Paging).current;
```

Thanks
