### ISSUE TITLE
Footable initialization after clicking on bootstrap collapsible link

### ISSUE THREAD

**Issue by zaibazhar** [fooplugins/FooTable#477]
After clicking on bootstrap collapsible link footable is not working. My table is inside the targeted div. after showing the targeted div footable is not working until i re-size the browser.

**Comment by steveush** [comment]
Hi,

Can you provide a jsfiddle demo'ing the issue? This sounds like a problem with the table being completely hidden when initialized and needing to be redrawn when shown. If you like you should be able to resolve this by calling `FooTable.get('#table').breakpoints.check()` when the collapsible link target is shown.

Thanks

**Comment by jeffconklin** [comment]
@zaibazhar I was able to set up what I think you mentioned within my dev environment. I  wrapped one of my Footable tables inside a basic BS Collapse setup. Something like this:

```
<button data-toggle="collapse" data-target="#demo123123123">Collapsible</button>
<div id="demo123123123" class="collapse">
    // table here
</div>
```

Later in my flow, Bootstrap is loaded/instantiated, followed by Footable being instantiate on the table. Footable is working properly for me. I tried using both class="collapse" (hidden on load) and class="collapse in" (displayed on load) and they both worked.

Next I tried to placed the table into a div with "display:none;" on load. Once I call .show() on the div, the table is displayed and Footable is working properly.

I was hoping to help find the issue, but I can not reproduce it. As Steve mentioned, creating a demo to be reviewed will help here.

Edited to add question: What version of Footable and Bootstrap are you using?

**Comment by steveush** [comment]
No response and no example so closing this issue.

**Comment by rramal** [comment]
To initialize footable in Angularjs datatable using bootstrap ,

1.Add plugin in config.js,
  *files: ['../Content/css/plugins/dataTables/footable.core.css', '../Content/js/plugins/dataTables/footable.js']*

2. In controller,
 register the footable in withOption like below code,
  
self.dtdata = DTOptionsBuilder.newOptions()
            .withDOM('<"html5buttons"B>lTfgitp')
            .withOption('lengthChange', false)
            .withOption('ordering', false)
            .withOption('paging', false)
            .withOption('searching', false)
            .withOption('columns', [
            { "width": "5%" },
            { "width": "5%" },
            { "width": "5%" },])
            setTimeout(function () {
              $('table').footable();
            },4000);
