### ISSUE TITLE
Create Pagination

### ISSUE THREAD

**Issue by hyomba-pratik** [fooplugins/FooTable#478]
How can I create the pagination without loading all the rows initially??

Actually i am trying to generate pagination without loading all rows. While changing the pagination index, the app will send request to server and new data will be populated in the table. Can any one explain how to generate pagination by passing total number of rows and current page number.

**Comment by steveush** [comment]
Hi,

This is not supported, please read my response to #402 for reasoning, but if it is absolutely required (i.e. your database has a large number of rows 100,000+) then I suggest using something like https://datatables.net/. FooTable was made to supply a decent table experience with minimal setup required and filled the gap between rolling your own and going with something as comprehensive as DataTables.

Thanks
