### ISSUE TITLE
Table changes to Mobile Layout when the table is inside one of Twitter Bootstrap tabs

### ISSUE THREAD

**Issue by fizerkhan** [fooplugins/FooTable#48]
My application has multiple Twitter bootstrap tabs where i have my tables(which are enabled by Footable). Footable changes the layout of Table to Mobile Layout even if it is in the Desktop.

**Comment by ricardozea** [comment]
You might want to post your issue in Stackoverflow.com since you may need to post your code in order to get help.

I don't think your problem is really an issue **_of**_ the FooTable script but in your implementation instead.

**Comment by fizerkhan** [comment]
@rzea Thanks for the reply. I used simple Bootstrab tabs with tables

``` html
<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#table1">Leads</a></li>
  <li><a href="#table2">Contacts</a></li>
  <li><a href="#table3">Messages</a></li>
  <li><a href="#table4">Settings</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="table1">.
        <table><thead></thead><tbody></tbody>
 </div>
  <div class="tab-pane" id="table2">
          <table><thead></thead><tbody></tbody>
  </div>
  <div class="tab-pane" id="table3">
        <table><thead></thead><tbody></tbody>
  </div>
  <div class="tab-pane" id="table4">...</div>
</div>
```

``` javascript
<script>
  $(function () {
    $('table').footable();
  })
</script>
```

The active tab(table1) works correctly. But all other tab tables changed to Mobile Layout i.e some of fields are hided.

**Comment by mleisher** [comment]
Try https://github.com/mleisher/Horton/ (very similar to FooTable). It should work, but if it doesn't it will as soon as I can set up a test.

**Comment by bradvin** [comment]
@fizerkhan can you setup a codepen example reproducing the issue so I can see what is going on - i think it may be because the other tabs are hidden so the table width is being calculated to be 0 so FooTable thinks it needs the smallest breakpoint

**Comment by bradvin** [comment]
@mleisher are you going to hijack every thread here telling everyone to rather use Horton?

**Comment by mleisher** [comment]
Nope. All done now.

**Comment by bradvin** [comment]
get the latest code and check out the new demo-with-bootstrap.htm

it does exactly what you trying to do and the resizing issue is now also solved

**Comment by fizerkhan** [comment]
@bradvin Thanks. It works great.

**Comment by fizerkhan** [comment]
@bradvin When will be this feature be released or tagged?

Now  I uses bower frontend package manager to install packages including FooTable. But Bower could not install the master branch, it works only on Tags. Your changes for this mobile layout is available in master and not yet released or taged. So every time i put **bower install**, code breaks. Now i coping latest code of **footable** manually. I will be helpful if you could release or tag this feature soon.

**Comment by bradvin** [comment]
v0.5 tag created

**Comment by fizerkhan** [comment]
Thanks mate.

**Comment by fizerkhan** [comment]
@bradvin Unfortunately the version v0.5 is not semver standard. So bower is failed to fetch the recent tag.

https://github.com/bower/bower/issues/449#issuecomment-17323983

Can you change from v0.5 to v0.5.0?

**Comment by bradvin** [comment]
deleted v0.5 and added 0.5.0

**Comment by fizerkhan** [comment]
Thanks.
