### ISSUE TITLE
Combine classes options with ajax

### ISSUE THREAD

**Issue by JujuPomme** [fooplugins/FooTable#481]
Hey, 

How can I add the classes options (to add some style) with the ajax option?

> rows: $.ajax({
>             url: 'modules_specifiques/affaire_table/server_side_affaire.php',
>             dataType: 'json',
>             success: function(data) {
>             },
>             error: function() {
>             }
>         }),

Something like that...

**Comment by steveush** [comment]
Hi,

Please take a look at the JavaScript example of the [rows](http://fooplugins.github.io/FooTable/docs/getting-started.html#rows) option. It shows how you can include options for rows or cells in the JSON object. If you want to merge the classes options you need to integrate it into your JSON object containing the row data either on the server or in your success callback.

The rows option itself simply accepts a jQuery promise that resolves with an array of objects so you don't have to use $.ajax as the value, you can create your own function that returns a promise that returns the results, for example the below would be completely valid.

``` javascript
function getRows(){
    return $.Deferred(function(d){
        try {
            // do whatever you need to to get your rows array and then call
            var rows = ...;
            // do additional processing on your rows if required
            d.resolve(rows);
        } catch (err) {
            d.reject(err)
        }
    });
}
```

And you could then use it like normal:

``` javascript
$('#table').footable({
    rows: getRows()
});
```

Thanks
