### ISSUE TITLE
Get record on click of pagination using ajax call.

### ISSUE THREAD

**Issue by rahul8sharma** [fooplugins/FooTable#483]
Hi All
First of all thanks for making a beautiful plugin.
I am new in web development and I am using footable to create a table.
I want 5 records on page load and whenever I clicked on pagination then it will do ajax call and show next 5 records. It means I don't want all records at the time of page load. I want to record when I clicked on pagination.
Thanks in advance :)

**Comment by steveush** [comment]
Hi,

This has actually been asked before and you can read my response in #402 but basically this is not supported. If you absolutely require this feature then something along the lines of https://datatables.net/ fulls that roll.

Thanks
