### ISSUE TITLE
Unable to toggle pagination on page

### ISSUE THREAD

**Issue by Ketzalkotal** [fooplugins/FooTable#485]
I'm currently using footable V2.
I'm able to choose whether to paginate or not paginate a footable on the initial page load, but I can't toggle pagination afterwards.

If I run the following
$('.footable').footable({paginate: true});
$('table tbody').trigger('footable_initialized');
I get an error from the sort plugin
Uncaught TypeError: Cannot read property 'sort' of undefined

**Comment by steveush** [comment]
Hi,

I suggest updating to V3 as V2 is no longer supported, I haven't actually looked at the code base in a couple years now. V3 I can help you out with but there were a lot of issues in V2 that were never addressed and won't be, the branch is actually going to be removed soon.

Thanks
