### ISSUE TITLE
V3 data-class

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#489]
Hi,
Does data-class available to use in V3?

**Comment by steveush** [comment]
Hi,

You should be able to apply the `data-classes` attribute on a `TH` for a column and that value will be applied to every cell in the column. I just checked the docs and it seems I did not include this option by accident but it does exist in the code. I've fixed the docs in the next update that I'll be pushing soon.

Thanks

EDIT: Fixed typo in attribute name
