### ISSUE TITLE
Header names are empty

### ISSUE THREAD

**Issue by mwalus** [fooplugins/FooTable#49]
I was integrating FooTable with DataTable. Everything was ok, but in hidden content (this one which shows in small sizes) column names was empty. I found out that array columns.names is empty. So I changed script to:

``` javascript
      $row.find('> td:hidden').each(function () {
        var index = $(this).index(), column = ft.getColumnFromTdIndex(index), name = column.name;
        if (column.ignore == true) return true;

        if (index in column.names) name = column.name;
        values.push({ 'name': name, 'value': ft.parse(this, column), 'display': $.trim($(this).html()), 'group': column.group, 'groupName': column.groupName });
        return true;
      });
```

this orginial line:

``` javascript
if (index in column.names) name = column.names[index];
```

to this line:

``` javascript
name = column.name;
```

And it seems it works. Dunno if it's a bug or i can't use FooTable properly. :)

**Comment by bradvin** [comment]
thanks for letting me know - I think this is a bug

**Comment by mwalus** [comment]
btw great plugin :) Works with datatables perfectly. I did some changes to make it work. Redraw function will be very useful feature. I've commented some code to force initialization on element which already have footable instance.. not a nice way but it work and makes redraw for datatable redraw callback :P

**Comment by bradvin** [comment]
can you get the latest code and test the blank column names please - I tried to reproduce the issue with the latest code and all seems to be working fine
