### ISSUE TITLE
sorting float number

### ISSUE THREAD

**Issue by takkus** [fooplugins/FooTable#491]
Hi there

I've a problem with sorting float number. 

Some part of my code as follows. But, sorting doesn't work correctly.

```
<table class="footable table table-stripped toggle-arrow-tiny" data-sorting="true">
  <thead>
    <tr>
      <th data-name="storeName" data-title="Store Name" data-breakpoints="xs">Store Name</th>
      <th data-name="totalSalesAmount" data-title="Total Sales Amount" data-type="number">Total Sales Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Store 1</td>
      <td data-sort-value="9.9900" class="font-bold text-info">
        $ 9,99
      </td>
    </tr>
    <tr>
      <td>Store 2</td>
      <td data-sort-value="1150.9900" class="font-bold text-info">
        $ 1.150,99
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by steveush** [comment]
Hi,

Ok, you have a problem, could you tell me what it is? At the moment you have provided me a sample but what exactly do you want to achieve? I can see you are losing your currency format but sorting seems to be working correctly.

Thanks

**Comment by steveush** [comment]
Looking at your example a bit more the below is the changes required to get the result I think you are after.
1. Change the `data-sort-value` attribute on the cells to be `data-value` instead.
2. Create a format function for the column. In the code below it is called `dollarFormat` and is applied using the `data-formatter` attribute on the column.

``` html
<script type="text/javascript">
    function dollarFormat(val){
        return '$ ' + val.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,');
    }
</script>
<table class="footable table table-stripped toggle-arrow-tiny" data-sorting="true">
    <thead>
    <tr>
        <th data-name="storeName" data-title="Store Name" data-breakpoints="xs">Store Name</th>
        <th data-name="totalSalesAmount" data-title="Total Sales Amount" data-type="number" data-formatter="dollarFormat">Total Sales Amount</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Store 1</td>
        <td data-value="9.9900" class="font-bold text-info">
            $ 9,99
        </td>
    </tr>
    <tr>
        <td>Store 2</td>
        <td data-value="1150.9900" class="font-bold text-info">
            $ 1.150,99
        </td>
    </tr>
    </tbody>
</table>
```

Thanks

**Comment by takkus** [comment]
Hi, 

Thanks for your reply. It's working in this way. But, I want to use the custom text(actually html content) in the cell of "Total Sales Amount". 
As follows ; 
`1.150,72 <i class="fa fa-try"></i>`

But, footable is converting to number my custom text. Then, It's show like -> `1.150,72`
Deleting my font-awesome icon.

I tried to explain the problem I had.
I'm sorry for my bad English. 

Thanks.

**Comment by steveush** [comment]
Hi,

You can just create a different format function or alter my previously supplied 'dollarFormat' example to simply include the icon if you want to. The formatter function can return a string (including HTML), an HTMLElement or a jQuery object as the return value. That function let's you format the value and create the content for a cell. As a quick example you can create a new `iconFormat` function and set the `data-formatter` attribute to use the new function:

``` javascript
function iconFormat(val){
    return val.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,') + ' <i class="fa fa-try"></i>';
}
```

And that would create a string like `1,150.72 <i class="fa fa-try"></i>`

Thanks
