### ISSUE TITLE
filters do not appear to be case sensitive.

### ISSUE THREAD

**Issue by redrockzee** [fooplugins/FooTable#492]
filters do not appear to be case sensitive.  Is there a way to make them case sensitive?  I tried quotes already.

**Comment by steveush** [comment]
Hi,

I've added in an option into 3.0.11 for the filtering component and simply called it [ignoreCase](http://fooplugins.github.io/FooTable/docs/components/filtering.html#ignoreCase). Please check out the docs for usage.

Thanks
