### ISSUE TITLE
if have link 

### ISSUE THREAD

**Issue by guxin0123** [fooplugins/FooTable#498]
footable.js   version 3.0.11    at line 1309

`if (F.is.element(valueOrElement) || F.is.jq(valueOrElement)) return $(valueOrElement).data('value') || $(valueOrElement).text(); // use jQuery to get the value
`

`if (F.is.element(valueOrElement) || F.is.jq(valueOrElement)) return $(valueOrElement).data('value') || $(valueOrElement).html(); // use jQuery to get the value
`

**Comment by steveush** [comment]
No need to change the code, you just need to set the [column type](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-type) to HTML.
