### ISSUE TITLE
jQueryMobile

### ISSUE THREAD

**Issue by noahpke** [fooplugins/FooTable#50]
Hello,

Any suggestions on getting footable to work with jQueryMobile?

Here is the head of demo.htm file modified with jQueryMobile.  

   title FooTable - jQuery plugin for responsive HTML tables /title 
   meta name="viewport" content = "width = device-width, initial-scale = 1.0, minimum-scale = 1.0, maximum-scale = 1.0, user-scalable = no" / 

   link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" / 
   link href="css/footable-0.1.css" rel="stylesheet" type="text/css" / 

   script src="js/data-generator.js" type="text/javascript"  /script 
   script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"  /script 
   script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"  /script 
   script src="js/footable-0.1.js" type="text/javascript"  /script 
   script type="text/javascript" 
    $(function() {
      $('table').footable();
    });
   /script 

Thanks
-Noah

**Comment by mleisher** [comment]
jQuery Mobile does it's own version of table management. FooTable won't work as far as I can tell. For jQuery Mobile, you have to wrap tables like this:

``` html
<div data-role='page'>
  <div data-role='content'>
    <div data-role='table'>
      <table>
       ...
      </table>
   </div>
  </div>
</div>
```

**Comment by valos** [comment]
FooTable works perfectly well with jQuery Mobile.
You need just to reorder the header declarations and bind your code to the pageshow event.

``` html
...
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
<link href="css/footable.css" rel="stylesheet" type="text/css" />

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>

<script>
$(document).bind("mobileinit", function () {
  $(document).on('pageshow', function() {
    $('table').footable();
  });
});
</script>

<script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
...
```

**Comment by bradvin** [comment]
@valos thanks for posting this solution
