### ISSUE TITLE
Dynamic update rows

### ISSUE THREAD

**Issue by stavrianosy** [fooplugins/FooTable#500]
I use footable V3 Bootstrap with Aurelia and its is really handy! 

On the page I have a list of categories that the user can choos to populate the footable with the appropriate data. The data are populated with an ajax call based on the users selection and every time the users chooses a different option from the list, I must repopulate the table with the new rows from server. 

Currently I do:
`$(".myFooTable > tbody").empty();`

and then re initialize the whole table again:

`$('.myFooTable').footable({
            "rows": this.ftResult,
            "paging": {"limit": 10,"enabled":true, "size":15, "current":1, "position": "right"},
            "filtering": {
                "enabled":true,
            }
        });`

Is there a better, more optimized way of doing of updating datasource of the table?

Thanks for the great plugin.

**Comment by steveush** [comment]
Hi,

If you are using the latest version I've recently added in a [`FooTable.Rows.load(Array.<object> rows, bool append=false)`](https://github.com/fooplugins/FooTable/blob/V3/src/js/components/internal/rows/FooTable.Rows.js#L211) method to make this a bit cleaner. As an example:

``` javascript
// the full path to the function
FooTable.get('.myFooTable').rows.load([{id: 1, ...},{id: 2, ...}]);

// or using the shorthand method
FooTable.get('.myFooTable').loadRows([{id: 1, ...},{id: 2, ...}]);
```

You can supply a second bool parameter after the rows array that tells the plugin whether to append the rows or overwrite them, by default it overwrites all rows with the new ones supplied.

Thanks

**Comment by stavrianosy** [comment]
Works like a charm!

Thanks
