### ISSUE TITLE
Add class (conditionally) on row after ajax call

### ISSUE THREAD

**Issue by stavrianosy** [fooplugins/FooTable#504]
Can i add a class on the row after the data are retreived from ajax?

I tried the similar events with the below with no luck.

$('.table').on({
    'init.ft.rows"': function(e, ft, row){
        row.$el.addClass('redRow');
    },
});

Please advise.

**Comment by steveush** [comment]
Hi,

The `init.ft.rows` event supplies all rows, not just one. So you can change it to be something like:

``` javascript
$('.table').on({
    'init.ft.rows"': function(e, ft, rows){
        F.arr.each(rows, function(row){
            row.$el.addClass('redRow');
        });
    },
});
```

Otherwise you can make use of embedding the row options into the JSON object used to create them. Take a look at the documentation for the [rows option](http://fooplugins.github.io/FooTable/docs/getting-started.html#rows), specifically the JavaScript examples.

Thanks

**Comment by stavrianosy** [comment]
For some reason these events are not triggered.
This is how i have it:

`$('.myTable').footable({
                "rows": result,
                "paging": {"limit": 10,"enabled":true, "size":15, "current":1,"position": "right" },
                "filtering": {
                    "enabled":true,
                }
            });`

```
        `$('.myTable').on({
            'init.ft.rows': function(e, ft, rows){
                console('rows init event');
                F.arr.each(rows, function(row){
                    row.$el.addClass('redRow');
                });
            },});`
```

I would expect to get the log into the console, but nothing!
Any ideas why?

**Comment by steveush** [comment]
Hi,

If the above is the order that the snippets of JS are in the page I think the `init.ft.rows` event has already fired by the time you bind the event. Calling `.footable()` would raise the event and then you are only listening for it once it has been raised. So you have two options, use the [on option](http://fooplugins.github.io/FooTable/docs/getting-started.html#on) which was made to avoid this exact issue or reorder your scripts so you bind the event before you call the constructor, either will work.

Thanks

**Comment by stavrianosy** [comment]
It seemed that i was referencing more than one version of footable in my aurelia project which was causing this strange behavior.
I resetup a clean aurelia project and tried the above which worked. The only problem was that it couldnt find F so I looped through the rows list instead, which did the trick.

Thanks
