### ISSUE TITLE
I upgraded from footable 2 to 3 and I found the data-sorting has problem

### ISSUE THREAD

**Issue by hungchai** [fooplugins/FooTable#508]
As the column in footable is a number with colored label, e.g 
`<td data-sort-value="1987">
   <span class="label label-primary">1987</span>
</td>`
I found that 
if I set the data-type column header as number , the class style will be disable
`<th data-type="number">OBV</th>`

if I set the data-type to be "html", the sorting result will be wrong, how to fix it?
`<th data-type="html">OBV</th>`

**Comment by steveush** [comment]
Hi,

Could you explain a bit further on what is incorrect when setting the column to `data-type="html"`? I created a small test table that looks like the below:

``` html
<table id="example" class="footable table" data-sorting="true">
    <thead>
    <tr>
        <th>Name</th>
        <th data-type="html">DOB</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Steve</td>
        <td data-sort-value="1984">
            <span class="label label-primary">1984</span>
        </td>
    </tr>
    <tr>
        <td>Brad</td>
        <td data-sort-value="1982">
            <span class="label label-primary">1982</span>
        </td>
    </tr>
    <tr>
        <td>Jen</td>
        <td data-sort-value="2001">
            <span class="label label-primary">2001</span>
        </td>
    </tr>
    </tbody>
</table>
```

The sorting seems correct to me but with such a small example I'm sure I am missing something.

Also if you want HTML to appear in the cells for a `data-type="number"` column you need to supply a [custom formatter](http://fooplugins.github.io/FooTable/docs/getting-started.html#formatter) for the column. The plugin will use this formatter to generate the cell contents for all cells in the column. As an example you could do the below:

``` html
<script>
    function custom_formatter(value){
        return '<span class="label label-primary">'+value+'</span>';
    }
</script>
<table id="example" class="footable table" data-sorting="true">
    <thead>
    <tr>
        <th>Name</th>
        <th data-type="number" data-formatter="custom_formatter">DOB</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Steve</td>
        <td>1984</td>
    </tr>
    <tr>
        <td>Brad</td>
        <td>1982</td>
    </tr>
    <tr>
        <td>Jen</td>
        <td>2001</td>
    </tr>
    </tbody>
</table>
```

NOTE: In the above we don't have to set any `data-sort-value` attributes and the original markup doesn't require the HTML either.

Thanks

**Comment by hungchai** [comment]
Thanks for your answer. But if I set the header to be data-type="html", could footable  recognize the data type of data-sort-value ? such as number / text / date.

**Comment by steveush** [comment]
Hi,

It won't recognize a date but it will handle strings, numbers, objects, booleans and even arrays just fine. The reason being that it uses [`jQuery.data()`](https://api.jquery.com/data/#data-html5) under the hood to retrieve the attribute value and jQuery automatically attempts to convert the value into what it believes to be the correct type. The dates used by FooTable are moment.js objects which jQuery has no knowledge about so it can't perform an automatic conversion. That said for date values I would just use the date's tick value instead as sorting will still work exactly as expected and users will not be seeing it. Once retrieved the values are then simply passed into the generic sorting function and the browser takes over from there to perform the actual sort.

Thanks

**Comment by hungchai** [comment]
Thanks
