### ISSUE TITLE
Currency display

### ISSUE THREAD

**Issue by Retiixx** [fooplugins/FooTable#510]
Hi, first thanks for your plugin, it's awesome.
Have an issue to display the prices with the currency sign, and making that sorting still works. If I put the column type to number, sorting works but currency sign gets deleted, and if I put no data-type, currency sign is there but sorting doesn't work anymore, even if I specify the sorting value to be without currency sign.

EDIT: kind of solve it by putting the currency sign in the pseudo ::after, but would be awesome to have a currency type, or that the parser accepts the sign

**Comment by steveush** [comment]
Hi,

The easiest way to accomplish this is by using the [column formatter](http://fooplugins.github.io/FooTable/docs/getting-started.html#formatter) option. The below example shows how to add in the `R` symbol for the South African Rand using this option but you can see that it's fairly simple to change to what ever you might need.

``` html
<script>
    function currency_format(value){
        return 'R ' + value;
    }
</script>
<table id="example" class="footable table" data-sorting="true">
    <thead>
    <tr>
        <th>Name</th>
        <th data-type="number" data-formatter="currency_format">Cost</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Chips</td>
        <td>5.99</td>
    </tr>
    <tr>
        <td>Bread</td>
        <td>14.99</td>
    </tr>
    <tr>
        <td>Milk</td>
        <td>13.99</td>
    </tr>
    </tbody>
</table>
```

Thanks
