### ISSUE TITLE
V3 Request add "breakpoint" class when only footable-toggle is visible

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#514]
Hi,
Please add "breakpoint" when footable-toggle is visible, else no. Example:

When no hidden row:
`<table class="footable breakpoint-lg">`

When have hidden row / footable-toggle is visible:
`<table class="footable breakpoint-sm breakpoint">`

This is very useful for layout styling.

**Comment by steveush** [comment]
Hi,

You can achieve this by overriding the `FooTable.Columns#predraw` method using the snippet below, just include it after you have included FooTable in your page but before you initialize the plugin.

``` javascript
(function($, F){

    // override the base method with our own to toggle the breakpoint class
    F.Columns.extend('predraw', function(){
        this._super(); // call original method
        this.ft.$el.toggleClass('breakpoint', this.hasHidden); // if there are hidden columns add the class otherwise remove it
    });

})(jQuery, FooTable);
```

Thanks

**Comment by claudchan** [comment]
Thanks,
BTW, will this be include/merge into master instead?

**Comment by steveush** [comment]
I have added it to the develop branch and will include it in the next version release. Until then you can either use the above snippet or clone the develop branch and run the default Grunt task to build the project.

Thanks
