### ISSUE TITLE
How to replace row data with HTML in ajax bind?

### ISSUE THREAD

**Issue by hfishere** [fooplugins/FooTable#515]
Hi, i love this plugin..

But i have some question, i cant explained as well, so let see the code..

``` javascript
editRow: function(row){
                        var values = row.val();
                        console.log(values.id); // this will get the id for sure
                    }
```

I want to get the id, and replace the cells data with html.
ex:
current cell data is `<td>1</td>
`replace with `<img src="../img/" + 1 + />`

Sorry i hope you can accept my question and give me some explanation. Thanks.

**Comment by steveush** [comment]
Hi,

I think we can work something out but I'm a little unclear on what you are trying to do? The title is about ajax binding, the first snippet is about editing and the last one shows the same value for the current cell data and what you want to replace it: `"1"`

Thanks

**Comment by hfishere** [comment]
Hi @steveush 

Im updated my question, sorry for that, forget to markdown it.. 

Why i'm mention the ajax binding for this question?
Because in looping method, it work as well..
I just give attribute data-type: "html" to thead, and change the row data with `<img src="~/Images/ + selectedrow +" alt="pic" width="100" />`

I want do the same way in ajax binding. But how it works?

Thanks..

**Comment by steveush** [comment]
Ah ok, now I get it :) The easiest thing to do in this case would be to use the [column formatter](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-formatter) option. Using this option the plugin will use the formatter whenever it needs to convert the base numeric ID into the HTML for the cell contents. This way you don't have to do it manually or worry about it at all, it should all be handled for you. As a small example:

``` html
<script>
    function idToIMG(value){
        return '<img src="../img/'+ value +'"/>';
    }
</script>
<table>
    <thead>
        <tr>
            <th data-type="number" data-formatter="idToIMG">ID</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Steve</td>
        </tr>
    </tbody>
</table>
```

When FooTable parses the table it will pass all values found in the `ID` column to the `data-formatter` function to create that columns' cell contents. In this case we simply make up the HTML for the `IMG` element using the custom `idToIMG` function. When the table is redrawn by the plugin the `TBODY` row would look like the below:

``` html
...
<tbody>
    <tr>
        <td><img src="../img/1"/></td>
        <td>Steve</td>
    </tr>
</tbody>
...
```

Doing it this way means that when you get or set a row or cells value you only have to deal with the actual value, in this case a number. So when getting the values in `editRow` as you showed above it will still be the actual numeric ID you get returned. This also means that if you update the ID when submitting your editor form you again only use the numeric ID value, the plugin will generate the HTML for the cell from the formatter function.

Thanks

**Comment by hfishere** [comment]
Oh  my god, it works!!! 
Sorry i should improve my skill..

Thanks @steveush ..
I will close this question.. :)
