### ISSUE TITLE
JSON initialisation issue?

### ISSUE THREAD

**Issue by whoisdis** [fooplugins/FooTable#516]
Appears initialising a Footable using columns and rows json data is adding the rows data one field per line.

eg.
Col1     Col2     Col3
Data1
            Data2
                         Data3

JS Fiddle showing the issue: https://jsfiddle.net/whoisdis/8wLpf6z3/5/

**Comment by steveush** [comment]
Hi,

In your fiddle you supplied the rows array as the following string `"[ {\"Id\":1}, {\"Name\":\"My Name\"}, {\"Email\":\"My Email\"} ]"`. Once parsed this creates an array with three rows in it. The first row contains just an Id, the second just the Name and the third just the Email.

As an example this is what your JSON string looks like when parsed compared to what it should look like.

``` javascript
// currently it looks like this, each object is a new row.
var rows = [
    {"Id": 1},
    {"Name": "My Name"},
    {"Email": "My Email"}
];

// it should look like this
var rows = [
    {"Id": 1, "Name": "My Name", "Email": "My Email"}
];
```

Thanks
