### ISSUE TITLE
How / Should i use redraw in my case?

### ISSUE THREAD

**Issue by hfishere** [fooplugins/FooTable#517]
See in code below :

`function getDept(str) {
            var xhttp;
            if (str == "") {
                document.getElementById("ajax-example-1").innerHTML = "";
                return;
            }
            xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function (e) {
                e.preventDefault();  
                if (this.readyState == 4 && this.status == 200) {                    

```
                $(function ($) {
                   $('#ajax-example-1').footable({
                        //"columns": $.Deferred(function (d) {
                        //    setTimeout(function () {
                        //        $.get('../Json/columnjobs.json').then(d.resolve, d.reject);
                        //    }, 1000);
                        //})
                        "columns": $.get('/Job/GetColumns'),
                        //"rows": $.get('/Job/GetJobs'),
                        "rows": $.ajax({
                            type: "GET",
                            url: "/Job/GetJobs",
                            data: "dept=" + str,
                            contentType: "application/json; charset=utf-8",
                            dataType: "json",
                            success: function () { }
                        }),
                        "editing": {
                            "enabled": true,
                            "alwaysShow": true,
                            "allowDelete": false,
                            "allowView": true,
                            "allowAdd": false,
                            "editRow": function (row) {
                                var values = row.val();
                                //$('#ajax-example-1').find('#iJob').val(values.iJob);
                                $(location).attr('href', '/Database/Job/Edit/' + values.iJob);
                            },
                            "viewRow": function (row) {
                                var values = row.val();
                                //$('#ajax-example-1').find('#iJob').val(values.iJob);
                                //$(location).attr('href', '/Database/Job/Details/' + values.iJob);
                                alert(values.iJob);
                            }
                        }
                    });
                });
            }
        };
        xhttp.open("GET", "/Job/GetJobs?dept=" + str, true);
        xhttp.send();
    }
```

`

I combine this method  [http://www.w3schools.com/ajax/tryit.asp?filename=tryajax_database](url) with ajax in footable..
And it works but i think this is not a perfect method, cause i got many errors, like the 'row' value in editing options getting 'null' value and after change the dropdown which have no value in row and back to row which have value is blank in table..
Dont worry if you dont understand me, cz i recorded my case.. 😆 

http://sendvid.com/16sdub2a

**Comment by hfishere** [comment]
I hope you can give me some reference @steveush :)

**Comment by steveush** [comment]
HI,

Apologies for the delay, I've been working on another project full time. Please take a look at one of the new examples I've added to the docs showing how you [can load rows into the table](http://fooplugins.github.io/FooTable/docs/examples/advanced/loading-rows.html). I think this example covers your scenario pretty well and you should be able to get things working as expected from them.

Thanks

**Comment by hfishere** [comment]
Its okay @steveush , and thanks for response.. Now i have an idea because that guide.. :)
