### ISSUE TITLE
data-sorted="true" Defaults to ICON to DESC (v3)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#519]
Within issue #445 , there was an issue with the default sorting of a column. This has been addressed since that time. But the icon within the header to show the order (on initial load) is showing descending (biggest to smallest)...

![2016-09-08-scripts](https://cloud.githubusercontent.com/assets/6152325/18364314/e9fce964-75db-11e6-80be-3c57b549f4af.png)

Once you click around it is displaying the proper icon.

As a test, after adding data-direction="ASC" to the column, the appropriate icon (ascending, smallest to biggest) is used onload...

![2016-09-08-scripts-v2](https://cloud.githubusercontent.com/assets/6152325/18364447/525774de-75dc-11e6-8771-947b008e93c8.png)

My original example (http://output.jsbin.com/qecaci) shows this issue.

**Comment by steveush** [comment]
This has been fixed in version 3.1.1
