### ISSUE TITLE
bug?!

### ISSUE THREAD

**Issue by alsd** [fooplugins/FooTable#52]
When table is placed in a floated div, it shows only the columns without tablet and phone.
Please see the test page. Remove    .f {float:left}  everything works.

Also, in the test page, the last column data-hide is "phone" only and it shows at first for tablet and full width views, however after resize to narrow then resize back to full width, it's still hidden.
http://jsbin.com/uyegih/2

**Comment by bradvin** [comment]
thanks for letting us know and posting an example - that is some strange behavior indeed

we will look into a fix for using with floats

**Comment by OliverRC** [comment]
You can set a width on the containing element to stop this behavior.
.f {
   float: left;
   width: 50%;
}

**Comment by bradvin** [comment]
yes that should do it - setting something to float without specifying a width can lead to strange behaviour

Setting the width in the above jsbin solved the problem
