### ISSUE TITLE
Footable how to use under webpack

### ISSUE THREAD

**Issue by zhangfisher** [fooplugins/FooTable#520]
Footable how to use under webpack?

**Comment by steveush** [comment]
Hi,

Sorry but I don't use webpack or plan to use it so I'm not sure how you would go about doing this. This repo contains all the source code for FooTable and it is just a jQuery plugin so I'm sure there must be a tutorial you can follow which may not be FooTable specific but does cover how to make use of jQuery plugins and webpack.

Thanks
