### ISSUE TITLE
Disable pagination Version : 2.0.3

### ISSUE THREAD

**Issue by lukgru** [fooplugins/FooTable#521]
Hi, i use footable 2.0.3. I must include footable.paginate.js, but i want disable pagination in some tables on page. How i can do this?

**Comment by jeffconklin** [comment]
Hello,

I do not have v2 installed, but I looked at the pagination.js file and see that you might be able to pass an option to footable during initialization for that one table, telling Footable not to include pagination. 

Example:
`$('#footable-without-pag').footable({
  paginate:false
});`

I have not tested to see if this works... but it seems like it should.

Have you considered upgrading to v3? V2 has not had any active development in a long time.

**Comment by steveush** [comment]
Jeff's comment is 100% correct on both how to disable the pagination and also that you should take a look at the V3 version of the plugin so I am closing this.

Thanks
