### ISSUE TITLE
How can I unable sorting for a column?

### ISSUE THREAD

**Issue by YBM100Pt** [fooplugins/FooTable#523]
Hi! I'm using FooTable in my SpringMVC project. Thanks for the great work by the way.
I want to add a number-of-row column to my footable, and I do not want to sort this column.
I use <c:forEach> for the data.
I've tried using 
`<table>
    <thead>
        <tr>
            <th data-sortable="false">Number</th>
            ...
        </tr>
    </thead>
    ...
</table>`
But it's not working.

**Comment by steveush** [comment]
Hi,

I've just tested this now and setting the `data-sortable` attribute to `false` works as expected for me. The column becomes unsortable and hovering over the header does not reveal the sort icon. Can you make sure you're using the latest version of the plugin and if the problem persists can you provide a small fiddle replicating the issue?

Thanks

**Comment by YBM100Pt** [comment]
I've downloaded V3 Individual Components. But I couldn't find the `footable.core.bootstrap.min.css` or `footable.core.standalone.min.css` files as required.
The unzipped files that I've downloaded are shown below.
![image](https://cloud.githubusercontent.com/assets/22232657/18622031/080d0930-7e55-11e6-82d6-82fb97e72a5f.png)
