### ISSUE TITLE
Clicking the search button with no text and default option is not correct in Custom Filtering (v3)

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#524]
Hello,

When using Custom Filtering, there seems to be a case where the filtering disregards what is in the other fields provided. Please review the following example:

On the filter dropdown example, http://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html, click the Search button (without changing anything). All the results are removed, and the Search/Cancel button now shows the X to clear. The filtering system seems to disregard the "Any Status" selection since it is the default.

Also, once it is in this "No results" state, changing the dropdown to anything else will not return any results.

The only way to get out of this incorrect state is to type something in the text search box or to clear the filtering.

Is there anything I can do to stop this from happening? To the user this is very confusing.

Thanks.

**Comment by steveush** [comment]
This has been fixed in 3.1.2, the issue was that the filtering component was ignoring the `min` option.
