### ISSUE TITLE
V3: Sorting only in one direction

### ISSUE THREAD

**Issue by PixelZombie** [fooplugins/FooTable#526]
Hey guys,

do you have any solution for sorting the columns in just one direction when the table header is clicked? I want to prevent the sorting from low to high. V2 made it possible (see the docs) to sort with a custom click handler. I allready tried the .sort() function from V3, but I was unable to get it working.

Thanks a million in advance!

**Comment by steveush** [comment]
Hi,

You can accomplish this using the `before.ft.sorting` event as seen below:

``` javascript
$('#table').footable({
    on: {
        'before.ft.sorting': function(e, ft, sorter){
            if (sorter.column.name == 'col1' && sorter.direction == 'ASC'){
                sorter.direction = 'DESC';
            }
        }
    }
});
```

Thanks
