### ISSUE TITLE
Array of filtered rows 

### ISSUE THREAD

**Issue by kondloa** [fooplugins/FooTable#527]
Hi 

I would like to know if there is a way to get the list of filtered rows from my footable. I need the footable.rows.array object after the filter has been applied and before the paging has occurred. 

Can I get this list without re-writing the filtering.predraw function.
Thank you.

**Comment by steveush** [comment]
Hi,

Unfortunately you will need to modify the predraw function of either the Filtering or the Paging components. Luckily this is quite easy as can be seen below:

``` javascript
FooTable.Filtering.extend('predraw', function(){
    this._super(); // call the original function
    console.log('after filter applied', this.ft.rows.array);
});
```

or

``` javascript
FooTable.Paging.extend('predraw', function(){
    console.log('after filter applied but before paging', this.ft.rows.array);
    this._super(); // call the original function
});
```

Thanks

**Comment by olivia-chen** [comment]
That really helps! Thanks very much!
