### ISSUE TITLE
Pasting does not trigger filtering

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#528]
Hello,

Please review the following:
- Visit: http://fooplugins.github.io/FooTable/docs/examples/component/filtering.html
- Paste anything into the search/text box
- Filtering is not triggered.

This is rather frustrating when using FT on a table. Many times I will have found text somewhere, copied it, and came to the table to find that text, paste it in and nothing happens. I have to click the search or add/remove text. Would be better if pasting also triggered the filter functionality.

Thanks.

**Comment by steveush** [comment]
Hi,

I've added this to the develop branch, pasting into the default search input will now trigger a filter operation. Please grab the files from the compiled folder for testing. If everything is working as expected I'll include it in the next release.

Thanks

**Comment by jeffconklin** [comment]
Using compiled files, pasting now works as expected.

Thanks.

**Comment by steveush** [comment]
This is now released in 3.1.2
