### ISSUE TITLE
Unable to load ajax data

### ISSUE THREAD

**Issue by juanfcocontreras** [fooplugins/FooTable#533]
If download any version of Footable V3 and upload to my web server, I can't run the ajax example. I always have the same error:

`FooTable: unhandled error thrown during initialization. – Error: No columns supplied.
`

If I add a function to get the results of $.get method, I actually get them:

```
Data Loaded: [
  {"name":"id","title":"ID","breakpoints":"xs sm","type":"number","style":{"width":80,"maxWidth":80}},
  {"name":"firstName","title":"First Name"},
  {"name":"lastName","title":"Last Name"},
  {"name":"something","title":"Never seen but always around","visible":false,"filterable":false},
  {"name":"jobTitle","title":"Job Title","breakpoints":"xs sm","style":{"maxWidth":200,"overflow":"hidden","textOverflow":"ellipsis","wordBreak":"keep-all","whiteSpace":"nowrap"}},
  {"name":"started","title":"Started On","type":"date","breakpoints":"xs sm md","formatString":"MMM YYYY"},
  {"name":"dob","title":"Date of Birth","type":"date","breakpoints":"xs sm md","formatString":"DD MMM YYYY"},
  {"name":"status","title":"Status"}
]
```

What am I doing wrong?

**Comment by juanfcocontreras** [comment]
This is something very weird.

If I change urls, it works:

"columns": $.get('https://fooplugins.github.io/FooTable/docs/content/columns.json'),
"rows": $.get('https://fooplugins.github.io/FooTable/docs/content/rows.json')

But if I upload those files to my web server, they don't. They are exactly the same files, and $.get actually got the data. The same happens locally (I double checked I'd disabled local restrictions in the browser).

Any idea of what is going on?

**Comment by steveush** [comment]
Hi,

This sounds like a `Content-Type` header issue. I'm not sure but from what you have wrote it seems like your server is not serving `.json` files with the correct header. Please take a look at my response to #455 as I think you have the same problem.

Thanks

**Comment by juanfcocontreras** [comment]
Hello!

You were right. I simply change $.get to $.ajax plus {dataType: 'json'} argument and it is working great.

Thank you so much!!

Please, close this issue.
