### ISSUE TITLE
How to use "postdraw.ft.table" event?

### ISSUE THREAD

**Issue by alatebloomer** [fooplugins/FooTable#534]
Here is my code...

```
jQuery(function($){
    $('.table').footable({
        "paging": { "size": 15 },
        "showToggle": false,
        "columns": $.get('/footable/js/columns.json'),
        "rows": $.get('/footable/js/rows.json')
    })
}); 
```

I want to do something after the table is finished initialize and I found there is an event called "postdraw.ft.table", but I don't know how to use it ?

Can any one tell me?

I try like below but nothing happened

```
 jQuery(function($){
    $('.table').footable({
        "paging": { "size": 15 },
        "showToggle": false,
        "columns": $.get('/footable/js/columns.json'),
        "rows": $.get('/footable/js/rows.json'),
        "postdraw.ft.table" : function() {
            alert('test'); 
        }
    })
}); 
```

**Comment by steveush** [comment]
Hi,

You are looking for the `on` option or you can simply use jQuery's `.on()` like any other event. Here is a link to the [on docs](http://fooplugins.github.io/FooTable/docs/getting-started.html#on).

Thanks

**Comment by alatebloomer** [comment]
@steveush Really appreciated. You help me a lot.

**Comment by pdalvi1893** [comment]
thanks
