### ISSUE TITLE
Filter always on exact match (entire phrase)

### ISSUE THREAD

**Issue by KingCrows** [fooplugins/FooTable#536]
First things first, i love the Footable Plugin!! Works great in many ways and projects.
For a new project i'm having some problems with getting my filters values right. 

Is it possible to always filter on the entire phrase, so "my filter" with the quotes included? The website i'm developing has many row with the same name in them, lets call them "MyTeam 1"). When i want to filter on "MyTeam 11", i also get filter results for "MyTeam 1", "MyTeam 12" etc. When i put quotes around them i get just my team! What is exactly what i want :-) How can i make i possible to always filter on the enitre phrases? And where do i alter this code?

Thanks for you time and help!!

**Comment by steveush** [comment]
Hi,

I quite liked this idea so I've checked in some code to the [develop branch](https://github.com/fooplugins/FooTable/tree/develop) that addresses this. Basically I've added in an option called `exactMatch` for the filtering component which then treats all search queries as phrases. You can grab the already compiled files that you might need from the [compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled) in that branch and then test out this option by using it like below.

``` html
<table class="table" data-filter-exact-match="true">
    ...
</table>
```

or

``` javascript
jQuery(function($){
    $('.table').footable({
        "filtering": {
            "exactMatch": true
        }
    });
});
```

This will be included in the next release.

Thanks

**Comment by KingCrows** [comment]
Wow, this is awesome @steveush!! Works like a charm, thank you a lot :-)
I'm alse using the sorting plugin at the same time and with changing the footable.core and footable.filtering file i now get an error on the sorting script:

`footable.sorting.min.js:8 Uncaught TypeError: Cannot read property 'register' of undefined`

**Comment by steveush** [comment]
Hi,

I think you are then on a previous 3.0.X version, there was quite a few changes to the underlying plugin with the release of 3.1.X so I suggest updating all of your files to the newer versions found in the compiled folder. Check out the README in the develop branch for the changelog but there have been quite a few fixes and updates as well.

Thanks

**Comment by KingCrows** [comment]
Yes, that was it. Haha sorry, my bad! This is so cool, thanks so much again @steveush!!

**Comment by KingCrows** [comment]
On touch devices i now have an issue that the results only show when the users clicks the "return" button (on iPhone / iPad). It only auto-refreshs / shows results until a certain point. When the users clicks "return" and the keyboard hides again, the results show properly. Is this also something that can be build in, that the results always auto-refreshs / shows without pushing the "results" key?

Thanks for your time!!

**Comment by steveush** [comment]
Hi,

I would need to look into this a bit more but the auto-refresh is already bound to the `keyup`, `change` and `paste` events for the input, this may just be one of those iOS quirks.

Thanks

**Comment by KingCrows** [comment]
Uhm, that indeed sounds like a iOS quirk. If you could take a look a this issue that would be great :-)

Thanks allot!!

**Comment by KingCrows** [comment]
Did you perhaps made any progress regarding this issue? 🙈
