### ISSUE TITLE
Filtering bug "No results" when pressing Delete or Backspace in empty Search box

### ISSUE THREAD

**Issue by gitoffme** [fooplugins/FooTable#538]
To replicate:
Go to [Filtering rows](http://fooplugins.github.io/FooTable/docs/examples/component/filtering.html) example page and in the Search box, press _Delete_ or _Backspace_ and **No results** will appear in the table body. Pressing either key again will bring back the contents of the table.

**Comment by bucketpress** [comment]
I believe this does not have to do with only delete or backspace keys. The function searches whenever keys are pressed. so even when we press arrow keys insde the search input, the search is triggered and returns a 'No results' - because it searched for an empty string.

**Comment by gitoffme** [comment]
Yeah, just confirmed it is affected by other keys as well - I initially noticed it when I hit backspace or delete one too many times when clearing the search field (which led me to test trying it in an empty search field).

**Comment by bucketpress** [comment]
@gitoffme but just to let you know that on my live site implementing code based off the develop branch https://github.com/fooplugins/FooTable/tree/develop, I can't replicate the issue.

**Comment by gitoffme** [comment]
I will check that branch then, thanks!

**Comment by steveush** [comment]
Hi,

@bucketpress is correct, this issue is fixed in the develop branch, once I have a few more changes I'll release a new version with it in.

Thanks

**Comment by gitoffme** [comment]
Confirming it seems resolved from develop branch. Sorry I didn't check the latest development branch prior to opening an issue - new to github and didn't know how to get there.

**Comment by steveush** [comment]
The fix for this issue is now included in version 3.1.3.
