### ISSUE TITLE
Toggle Column Visibility

### ISSUE THREAD

**Issue by bucketpress** [fooplugins/FooTable#539]
Is it possible to do something like this to toggle columns' visibility after footable has been init:

```
ft = $el.footable({
  ...
}).data("__FooTable__");

ft.columns.get('col1Name').visible = true;
ft.columns.get('col2Name').hidden = false;
ft.draw(); // redraw table to render
```

Tried the above - but doesn't seem to be working.

**Comment by steveush** [comment]
Hi,

The `hidden` property is set in the `FooTable.Columns#predraw` method and should be treated as a read-only property, I need to go through and redo the jsdoc's as there are quite a few mistakes that have crept in as changes have been made but the comments not updated in the code. The `hidden` value is determined by calling the `FooTable.Breakpoints#visible` method passing in the current column's `breakpoints` property.

That said are you trying to make a column disappear entirely from view or appear in the details row for hidden columns?

If you want to make it disappear entirely then do exactly what you did above except set `visible = false` and leave out the `hidden` property. I tried the below on the demo pages and it works as expected.

``` javascript
ft.columns.get('col1Name').visible = false; // hides the column entirely from view
ft.draw(); // redraw table to render
```

If you are trying to toggle a column between normal layout and the details row then I will need to play around a little to figure it out. I think you will need to update the `breakpoint` property of the column to include the current breakpoint (`sm`, `md`, `lg`, etc.) and then redraw the table.

Thanks

**Comment by bucketpress** [comment]
@steveush My intention was to hide a column entirely - so this should suffice. Let me try what we have discussed here so far. Update: it works.
