### ISSUE TITLE
Using dynamic Data and Re-initializing footable - Duplicate Data and Instances

### ISSUE THREAD

**Issue by TomasJerrySebo** [fooplugins/FooTable#540]
Hi, 
I would like to some for some assistance with one problem.
I have an AJAX call which returns some date used to populate a table which then gets initialized with Footable.

I'm using this code to initialize the Footable plugin with Editing properties. 

`var ft = FooTable.init('#collection-edit-table', {
                        editing: {
                            enabled: true,
                            debug: true,
                            addRow: function(){
                                $modal.removeData('row');
                                $editor[0].reset();
                                $editorTitle.text('Add a new row');
                                $.fancybox({
                                    href: '#collection-edit-lightbox',
                                    closeBtn: true,
                                    closeClick: false,
                                    maxWidth:'571',
                                    minHeight: 'auto',
                                    height: 'auto',
                                    padding: 10,
                                    margin: 10,
                                    leftRatio: 0.5,
                                    topRatio: 0.25,
                                    autoResize : true,
                                    autoCenter: true,
                                    autoSize: false,
                                    helpers     : {
                                        overlay : {closeClick: false, locked: true }
                                    },
                                    keys : {
                                        close  : null
                                    },
                                    afterClose  : function() {

```
                                    $('.footable-up')
                                            .unbind()
                                            .click(function(){
                                                var currentRow = $(this).parents('tr');
                                                var siblingRow = $(this).parents('tr').prev();
                                                if(siblingRow.length > 0) { currentRow.insertBefore(siblingRow); }

                                            });
                                    $('.footable-down')
                                            .unbind().
                                            click(function(){
                                                var currentRow = $(this).parents('tr');
                                                var siblingRow = $(this).parents('tr').next();
                                                if(siblingRow.length > 0) { currentRow.insertAfter(siblingRow); }

                                            });

                                }
                            });
                        },
                        editRow: function(row){
                            var values = row.val();
                            $editor.find('#id').val(values.id);
                            $editor.find('#collection_id').val(values.collection_id);
                            $editor.find('#content_type').val(values.content_type);
                            $editor.find('#collection_title').val(values.collection_title);
                            $editor.find('#collection_img').val(values.collection_img);
                            $editor.find('#collection_url').val(values.collection_url);
                            $editor.find('#collection_content').val(values.collection_content);
                            $modal.data('row', row);
                            $editorTitle.text('Edit row #' + values.id);
                            $.fancybox({
                                href: '#collection-edit-lightbox',
                                closeBtn: true,
                                closeClick: false,
                                maxWidth:'571',
                                minHeight: 'auto',
                                height: 'auto',
                                padding: 10,
                                margin: 10,
                                leftRatio: 0.5,
                                topRatio: 0.25,
                                autoResize : true,
                                autoCenter: true,
                                autoSize: false,
                                helpers     : {
                                    overlay : {closeClick: false, locked: true }
                                },
                                keys : {
                                    close  : null
                                },
                                afterClose  : function() {

                                    $('.footable-up')
                                            .unbind()
                                            .click(function(){
                                                var currentRow = $(this).parents('tr');
                                                var siblingRow = $(this).parents('tr').prev();
                                                if(siblingRow.length > 0) { currentRow.insertBefore(siblingRow); }

                                            });
                                    $('.footable-down')
                                            .unbind().
                                            click(function(){
                                                var currentRow = $(this).parents('tr');
                                                var siblingRow = $(this).parents('tr').next();
                                                if(siblingRow.length > 0) { currentRow.insertAfter(siblingRow); }

                                            });


                                }
                            });
                        },
                        deleteRow: function(row){
                            if (confirm('Are you sure you want to delete the row?')){
                                row.delete();
                            }
                        }
                    },
                    "breakpoints": {
                        "x-small": 480,
                        "small": 768,
                        "medium": 992,
                        "large": 1200,
                        "x-large": 1400
                    },
                            debug: true
                }),`
```

It works perfectly fine but when I change the API data, let's say I call a different version of the file I call this function again. The core Footable Init fires the Destroy function but the instance isn't deleted when I check the DOM FooTable.instances .... Also the html table keeps all the "footable" classes, all the data attributes everything. The table looks fine at first glance because the re-initialization  replaces the old data with the new all the editing works, but when I resize the table and it reaches a breakpoint then the <tbody> gets appanded with the <tr> data from the previous FooTable instance as well. Can you assist me with this ? 

I tried almost everything like before hitting the above function I ran this code trying to clear everything `delete FooTable.instances[8];
                        $('#collection-edit-table').find('*').unbind().removeClass();
                         $ft.unbind().removeClass().addClass('admin-class').removeData('__FooTable__');
                        $('#collection-edit-table tbody').unbind().removeClass().addClass('body');
                        $('#collection-edit-table tbody tr').each(function(){$(this).unbind().removeData('__FooTableRow__'); });
                        $('#collection-edit-table .footable-header th').each(function(){$(this).unbind().removeData('$el'); });`

But it's still appending the data on resizing the browser. I have more FooTables on the page some just simple without editing properties and it's happening with all of them which load dynamic data and gets resized after.

Any advice would be really appreciated

Thank you

**Comment by steveush** [comment]
Hi,

Rather than destroy and recreate the entire plugin each time you load a different array of rows take a look at the [loading rows example](http://fooplugins.github.io/FooTable/docs/examples/advanced/loading-rows.html) and try loading your rows that way. The advantage to this is that the plugin and it's options only ever have to be created once and the underlying rows are simply swapped out.

If you are still having issues after trying the above please put together a small jsfiddle that contains just the code to replicate the issue. I often find when I do this I figure out the problem, also it will help me out as what you pasted above doesn't show me any input data, actually see the problem or let me debug it with dev tools.

Thanks

**Comment by TomasJerrySebo** [comment]
Ok great I will try that. Thanks for the quick response. I will let you know

**Comment by steveush** [comment]
Hi,

Something I just noticed I didn't cover in that example is you can supply an initial `rows` option when you initialize FooTable along with the rest of the options like usual and then load more rows later using `FooTable.Rows#load` method, in the example I only showed tables with no initial rows supplied.

``` javascript
var ft = FooTable.init("#table", {
    "columns": $.get("my-columns.json"),
    "rows": $.get("my-rows.json"),
    // ...other options
});

// ... some time later
$.get("my-new-rows.json").then(function(rows){
    ft.rows.load(rows);
});
```

Thanks

**Comment by TomasJerrySebo** [comment]
Hi, 
so I tried the     ft.rows.load(rows) by fetching the instance based on it's id and then inserting the rows. 
It works. It's just it's so easier for us to append the JSON data we get from the API to the table body and then initialize the footable again other than loading it with the     ft.rows.load(rows) because the JSON we get from the API is so much different in structure than what needs to be supplied for the load function.

Isn't there a way to call the     ft.rows.load(rows) but tell it to take the html data from the `<tbody></tbody>` and load those rows instead of supplying it with the JSON. 

Thanks

**Comment by steveush** [comment]
Hi,

Not at the moment no. From here if you could provide me a url where I could take a look at the original issue encountered when re-initializing the plugin again, as you shouldn't have encountered that issue. Or if you could provide me with a jsfiddle that replicates the problem along with some simple steps to reproduce it like:
1. Resize browser to 400px
2. Click on load new data
3. etc. etc. etc.

It would help me a lot to resolve this, I'm still not 100% sure I understand the initial issue you were having and it would help me a lot to actually see it or be able to reproduce it locally.

Thanks

**Comment by bucketpress** [comment]
@TomasJerrySebo Maybe you can show an instance of what your JSON response looks like, and which part of the JSON data you want to load into footable. Because it seems that parsing to html and then making footable read from that html again is really making a big detour then coming back again. Most probably we can solve the JSON issue by parsing it using underscorejs functions (or something similar) in a more straightforward manner.

**Comment by hozefask** [comment]
Hi...
i'm Creating dynamic table in this table i just add table id and addclass in that class iam using table footable in this id not accepting  footable.js what reson ..................

**Comment by simamote15** [comment]
HI. 
I have added one row below header to add filters for specific columns (text box below column). Its working fine. But in responsive mode , my layout is totally changing ...Pls heflp

![image](https://user-images.githubusercontent.com/87744904/135470555-03ca28e4-6240-4005-be85-73899f41272b.png)
![image](https://user-images.githubusercontent.com/87744904/135470711-08ab0ce0-68c9-4bf8-a081-6d5fde6a782e.png)
