### ISSUE TITLE
Footable Paging information on the basis of records

### ISSUE THREAD

**Issue by aamirshahzad** [fooplugins/FooTable#541]
In footable currently we have paging on the basis of page number like;

```
Page: 1 of 5, 
Page: 2 of 5 like this. 
```

But I want to have it like on the basis of records like;

```
Showing 1 to 10 of 57 entries;
Showing 11 to 20 of 57 entries;
Showing 51 to 57 of 57 entries;
```

I have tried to implement a function myself but that's too time consuming and its hard for me cover all scenarios specially when we add search along.

Any insight/help on if there is already any implementation of it? Or any guidance for implementing it myself?

Thanks
Aamir Shahzad

**Comment by steveush** [comment]
Hi,

You need to take a look at the [countFormat](http://fooplugins.github.io/FooTable/docs/components/paging.html#countFormat) option for the paging component. Your particular example should be: `Showing {PF} to {PL} of {TR} entries`

Please be sure to be using at least version 3.1.2 as it contained a fix for the `{TR}` placeholder as it was not calculating filtered rows correctly.

Thanks
