### ISSUE TITLE
Get request to null address with pagination

### ISSUE THREAD

**Issue by yahyaerturan** [fooplugins/FooTable#542]
Hi,

I have applied footable (and I love the way of working) with ajax and client pagination. It loads nicely. Pagination links works. But when I clicked to pagination links it tries to send a `GET` request to `http://domain.com/null` address. But it works normally. However, I am the brutal nemesis for Chrome Console Errors :smile How can I get rid of it? Or maybe simply I am misapplying the code.

Ajax requests collects all data from the source without a limit.

```
$('#product_table').footable({
    "rows": $.get(BaseURL+'web/store/xhr_store_products'),
    "showToggle": true,
    "empty": "Ürün Bulunamadı",
    "paging": {
      "enabled": true,
      "size": 5
    },

    "columns": [
      { "formatter":function(value){return '<img src="'+value+'">'}},
      { "name": "title", "title": "Ürün Adı","formatter":function(value){var given,title,id_secured;given=value.split('|');title=given[0];id_secured=given[1];return '<a href="javascript:void(0);">'+title+'</a>'}},
      { "name": "id_product", "title": "Ürün Kimliği", "classes":"text-center" },
      { "name": "stock_code", "title": "Stok Kodu", "classes":"text-center","breakpoints": "xs" },
      { "name": "operations", "title": "İşlemler", "breakpoints": "all", "formatter":function(value){
        return '<a href="'+'<?=site_url(Route::get('store_product_manage'));?>/'+value+'">Düzenle</a>'
      } },
      { "name": "add_colour", "title": "Renk Ekle", "breakpoints": "all", "formatter":function(value){
          if(value) {
            return '<a href="#" class="jq-create-sub-item" data-ids="'+value+'" data-prnt="'+value+'">Renk Ekle</a>';
          } else {
            return '-';
          }
      } },
      { "name": "delete-product", "title": "Renk Ekle", "breakpoints": "all" },
      { "name": "enhance-properties", "title": "Özellik Ekle", "breakpoints": "all" }
    ],
    "filtering": {
      "enabled": true
    },
    "sorting": {
      "enabled": true
    },
    'on': {
      'postinit.ft.table': function(e, ft) {
        $('#product_table').css('visibility', 'visible');
      }
    }
  });
```

**Comment by steveush** [comment]
Hi,

Your code looks correct but I also don't think the issue lies with FooTable. It doesn't make any ajax requests itself, you fetch the rows when you set the options so it doesn't need to. I suggest checking other scripts loaded into the page and see if one of them is binding to the pagination anchor elements. I would guess it's an analytics script or something seeing as it's trying to make an external call to track an anchor click. 

The easiest way to test is to make a test page, or better yet a jsfiddle so I could see it as well, with just FooTable and see if you can replicate the error.

The [example ajax load demo](http://fooplugins.github.io/FooTable/docs/examples/advanced/ajax.html) does not suffer from this issue either so this also leads me to believe it's another script in your page.

Thanks

**Comment by yahyaerturan** [comment]
I believe i spotted the problem finally. As you already guess, it's on me, nothing related to FooTable. It's because unsuccessful image request.

Still have a question.. Is row data accessible like this?

```
...
  {"formatter":function(value, row) { return row.title + ' Stock Code: ' + row.stock_code;}
...
```

Sorry to bothering but this is critical to move on.

**Comment by steveush** [comment]
Hi,

At present you can't access the row data within the formatter as depending on how the table is initialized the row object might not be populated yet. If rows were supplied through the options the row object would be known and I could do something like in your example. However if the rows were supplied through HTML then at the point the formatter is called the full row object is yet to be determined as the plugin is still looping through the cells building it.

If you want you can try using the below modification that should allow you to do what you want.

``` javascript
FooTable.Cell.prototype.format = function(value){
    return this.column.formatter.call(this.column, value, this.ft.o, this.row.value);
};
```

I haven't tested the above but it should add the current cell's row object to the arguments for the formatter. The second argument is already the options for the plugin so I've added it in as a third argument. You should be able to use it something like this.

``` javascript
function myFormatter(value, options, row){
    // return your value
}
```

Thanks
