### ISSUE TITLE
onWindowResize still fired after table destroyed

### ISSUE THREAD

**Issue by JRMaitre** [fooplugins/FooTable#543]
Hi,

I'm using 3.0.9 for now.

In my project I re-create a footable on the same container every time a user clicks on a button. The previous tables are "destroyed" properly with FooTable. However I found 2 things that I think are "bugs" but I might not understand it fully :)

First, after checking the code I see that we bind an event whenever the window is resized on the init function of a table. But that event is never removed. I would expect a window.off event to be added to the destroy method.

> $(window).off('resize.ft'+self.id, self._onWindowResize)
>           .on('resize.ft'+self.id, { self: self }, self._onWindowResize);

If I add in the destroy method (after self.initialized = false)

> $(window).off('resize.ft'+self.id, self._onWindowResize)

then the event stops being fired and it removes the issues I'm having in my project. But I'm just curious how that works for other people?

Second, not really an issue for me but I noticed that, the footable-2 footable-3 footable-4 etc... classes are never removed, so when I'm using the same container for a table, it always keeps all these classes and it doesn't look very clean.

Thanks for your help, and thank you for this awesome project :)

EDIT: After reviewing the existing issues, I believe #540  is very similar to my issue. I need to add to the body to repaint as I don't have an easy access to the FooTable objects which is why I'm re-initializing the table every time. But even though it's not the cleanest way to do things, I still think the onWindowResize event should be unbound from the window when we destroy a table!

**Comment by steveush** [comment]
Hi,

Thanks for pointing out the resize event issue, I've just pushed the fix to the develop branch so it will be resolved in the next release which should be 3.1.3.

As for the old class names not being removed that was fixed in release 3.0.10 and is in the changelog ;)

Thanks

**Comment by JRMaitre** [comment]
OK I'll upgrade to 3.0.10 for the time being and keep my customization until 3.1.3. Glad I could help and thanks for such a quick response :)

**Comment by steveush** [comment]
Hi,

Version 3.1.3 is now pushed which contains the fixes for this plus quite a few others, check out the changelog for details.

Thanks

**Comment by JRMaitre** [comment]
Awesome, thank you!
