### ISSUE TITLE
Pager not rendering

### ISSUE THREAD

**Issue by caschbre** [fooplugins/FooTable#545]
I'm using FooTable 3.1.1 currently and am trying to get the pager to work.  I have a simple table setup with thead and tbody rendering more than 10 results.  When I add data-paging="true" to the table tag the first page is correctly limited to 10 results, however there is no pager.  I see that and empty tfoot has been added to the table but nothing inside of it.

**Comment by steveush** [comment]
Hi,

I can't reproduce this issue. With the below table using either the current develop branch or the files from the 3.1.1 release I see the expected behavior of the pagination being rendered on the bottom of the table showing pages 1 and 2 (6 items total and a page size of 5).

``` html
<table class="table" data-paging="true" data-paging-size="5">
    <thead>
        <tr>
            <th data-name="id" data-breakpoints="xs" data-type="number">ID</th>
            <th data-name="firstName">First Name</th>
            <th data-name="lastName">Last Name</th>
            <th data-name="jobTitle" data-breakpoints="xs">Job Title</th>
            <th data-name="startedOn" data-breakpoints="xs sm" data-type="date" data-format-string="MMMM Do YYYY">Started On</th>
            <th data-name="dob" data-breakpoints="xs sm md" data-type="date" data-format-string="MMMM Do YYYY">Date of Birth</th>
        </tr>
    </thead>
    <tbody>
        <tr data-expanded="true">
            <td>1</td>
            <td>Dennise</td>
            <td>Fuhrman</td>
            <td>High School History Teacher</td>
            <td>November 8th 2011</td>
            <td>July 25th 1960</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Elodia</td>
            <td>Weisz</td>
            <td>Wallpaperer Helper</td>
            <td>October 15th 2010</td>
            <td>March 30th 1982</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Raeann</td>
            <td>Haner</td>
            <td>Internal Medicine Nurse Practitioner</td>
            <td>November 28th 2013</td>
            <td>February 26th 1966</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Junie</td>
            <td>Landa</td>
            <td>Offbearer</td>
            <td>October 31st 2010</td>
            <td>March 29th 1966</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Solomon</td>
            <td>Bittinger</td>
            <td>Roller Skater</td>
            <td>December 29th 2011</td>
            <td>September 22nd 1964</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Bar</td>
            <td>Lewis</td>
            <td>Clown</td>
            <td>November 12th 2012</td>
            <td>August 4th 1991</td>
        </tr>
    </tbody>
</table>
```

Could you create a jsfiddle to reproduce the issue you are seeing?

Thanks

**Comment by caschbre** [comment]
@steveush Well I added my table to jsfiddle (https://jsfiddle.net/tbad3enz/) and it does appear to be working there.  So it must be something going on within the site I'm building.  There are no errors in the console.  Any suggestions on how to track down why I'm only getting an empty tfoot tag?

**Comment by steveush** [comment]
@caschbre it's tough to say without being able to see and alter the page as it could quite literally be any other JavaScript you're loading. You're going to need to do some debugging to resolve the issue. I would simply start removing other included scripts to narrow down which one is causing the issue. Then take a look through the source of whichever script it is and see if it does anything using the Bootstrap pagination selector `.pagination` as that is the class that FooTable uses to create it's pagination. I'm guessing there is another script that is supposed to remove it's own pagination but it is also removing FooTable's as well but it could be a lot of different reasons.

**Comment by caschbre** [comment]
Thanks @steveush. Right now this is part of a Drupal site so unfortunately there are other libraries being loaded, though none that I can think of that would delete the .pagination selector.  Also, I'm using the standalone version of FooTable if that makes any difference.

Any recommendations on where to add a breakpoint in footable.js when it builds the pager so I can follow where it goes afterwards and eventually eats it up?

**Comment by caschbre** [comment]
@steveush And I've figured it out. So what was happening was my .footable() call was getting called twice for some reason.  Adding a bit of logic to make sure it was only fired once corrected the issue.

Sorry about raising the flag too early!  :)  And thanks for the quick responses!!!

**Comment by JhoanSteve** [comment]
helo in laravel 5.3 not found  . this error is (No results)

**Comment by steveush** [comment]
Hi,

Version 3.1.3 is now pushed which contains a fix for the paging dissappearing when FooTable is initialized on the same table multiple times.

Thanks
