### ISSUE TITLE
Enhancement: Add last-column classes on the last td:visible

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#547]
Hi,
Possible to have a class that specific the last cell that visible in the row?
`<th data-breakpoints="xs" style="display: table-cell;">Item 1</th>`
`<th data-breakpoints="xs" style="display: table-cell;">Item 2</th>`
`<th data-breakpoints="xs" style="display: table-cell;" class="last-column">Item 3</th>`
`<th data-breakpoints="xs" style="display: none;">Item 4</th>`

Better if could also have first-column class at the first visible cell
`<th data-breakpoints="xs" style="display: table-cell;" class="first-column">Item 1</th>`

**Comment by steveush** [comment]
Hi,

The above commit is included in version 3.1.3

Thanks
