### ISSUE TITLE
How to find the old version docs?

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [fooplugins/FooTable#548]

**Comment by steveush** [comment]
Hi,

They are no longer available online as they were hosted on our external site and not by this repo like the current V3 version. As V3 has been out for over a year and V2 support and active development has ceased the old docs were removed and instead redirected to the new V3 documentation to encourage users to upgrade.

You can still get a copy though by downloading the [V2 branch](https://github.com/fooplugins/FooTable/tree/V2) which includes the demos and online docs that were hosted.
