### ISSUE TITLE
Issue with search and load rows method

### ISSUE THREAD

**Issue by juanfcocontreras** [fooplugins/FooTable#551]
I'm building a dynamic table (content changes continuously) with FooTable. I use `FooTable.Rows#load(array, bool)` method (I have the same behaviour with `FooTable.Table#loadRows(array, bool)`) to update the table content. I have set the content is refreshed each 3 seconds.

The problem I have is if I'm writing in the search box and the table is refreshed at that moment, the letters I write are lost. I attach a screencast refreshing each second to illustrate the issue:

![issue](https://cloud.githubusercontent.com/assets/4047415/20098521/951462de-a5b4-11e6-8129-71c7701c658f.gif)

Any idea to solve it?

The following is the relevant code within the main jQuery function:

```
load_rows(); // this will run on page load
setInterval(function(){
  load_rows() // this will run after every x seconds
}, 3000);

function load_rows() {
// ajax fetch the rows
$.ajax(url, {dataType: 'json'}).then(function (rows) {
  // and then load them using either
  ft.rows.load(rows);
  // or
  // ft.loadRows(rows);
  });
};
```

**Comment by steveush** [comment]
Hi,

I've looked at this and am leaning towards not fixing it within FooTable. By default FooTable does remember any filters applied across loads but in this case there isn't any actual filter yet, the user hasn't stopped typing or hit the search button, to actually work around this I would need to create/update the filter on every keydown which is not particularly efficient. You can try to capture the search input's current value prior to calling `ft.rows.load` and then set it again after.

e.g.

```javascript
var filtering = ft.use(FooTable.Filtering);
var current = filtering.$input.val();
ft.rows.load(rows);
filtering.$input.val(current);
```

Thanks

**Comment by juanfcocontreras** [comment]
Hello @steveush,

I think that could be great! I'll try and keep you posted. Thanks a lot!

Regards,
Pedro

**Comment by juanfcocontreras** [comment]
It seems to be working great.

Thanks again @steveush!
