### ISSUE TITLE
Enhancement: Set option classes inside footable-details (td)

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#552]
Hi,
First of all, I couldn't find this feature in the document, if have, please point me to that page.

Basically is the UI/"look and feel" enhancement.
I understand that, the "footable-details" second column (td), the class will 'mimic' what the we have set from original table td cell. Example, I declared data-classes="text-center" / class="text-center". Everything looks neat and mice on desktop viewport.

When comes to breakpoint inside "footable-detail-row" > "footable-details". 
The issue is, on breakpoint (mobile view), I would like the second column (td) class to be set back to class="text-left".

From breakpoint (mobile view) text align to center looks awkward because it do not align with the title above the cell.

I know that, I can use css to fix it by set back the class "text-center" to text-align to left. But it doesn't sounds really right.

I hope fooTable to have second option to apply the inner cell classes, perhaps.

Thanks.

**Comment by steveush** [comment]
Hi,

This is something that is so specific that I don't think I will provide any built in functionality to FooTable for it. As you said it can be fixed through CSS alone and I think that is how it should be handled and not through the JS. From my point of view FooTable provides a way to distinguish the detail row cells from the normal display cells as you have already pointed out by using the parent `.footable-detail-row` class, this is how I would recommend to anyone using the table to change any specific styles of the details rows cells.

Thanks
