### ISSUE TITLE
columns - classes "hidden-print" affects cells but not column header.

### ISSUE THREAD

**Issue by kvcomeaux** [fooplugins/FooTable#555]
Added class to column in the column definitions "hidden-print" to hide options column when printing.
Seems all of the data cells in the column below in each row are hidden in the print/print preview process, but the column header is still displayed.
...
$('.footable-xyzzy').footable(
{
      'columns': [
...
{ "name" : "row-options",  "title" : "Options",  "type" : "html" , 'breakpoints': 'xs', 'classes' : "hidden-print" },
       ], 
        'rows' :

**Comment by steveush** [comment]
Hi,

Can you try including the below snippet in your page just after you include the main FooTable JS file.

``` html
<script>
    FooTable.Column.extend('$create', function(){
        this._super();
        this.$el.addClass(this.classes.join(' '));
    });
</script>
```

I haven't had a chance to test this but it should override the default method that creates the jQuery TH object and then simply adds the the parsed classes array to the element. This should resolve the issue and if it does I'll push a fix to the develop branch for the next release.

Thanks

**Comment by kvcomeaux** [comment]
Thank you for the info!  It seems to work.  The header &lt;th&gt;&lt;td&gt; column is also hidden from the print as well as the &lt;tr&gt;&lt;td&gt;.
