### ISSUE TITLE
How can I filter the data by a date range?

### ISSUE THREAD

**Issue by demorales13** [fooplugins/FooTable#557]
Hi,

I need to filter the data of a table using a range of dates, is there any option to do this?

Thanks

**Comment by steveush** [comment]
Hi @demorales13 

This is something that would need to be custom implemented at present. I've been meaning to add it as an enhancement to the filtering component, so you can search using less than and greater than symbols like I suggested in my reply to #454 but I just haven't got a chance to sit down and do it.

Thanks

**Comment by demorales13** [comment]
Thanks for the answer, 

I'll try to deploy it by filtering the collection, thanks again.

**Comment by demorales13** [comment]
Thanks for the answer, 

I'll try to implement it by filtering the collection, thanks again.

**Comment by webselect** [comment]
If have put this on my code (no need to replace the one from footable.js)
```javascript
(function(F){
    /**
     * Checks if the row is filtered using the supplied filters.
     * @this FooTable.Row
     * @param {Array.<FooTable.Filter>} filters - The filters to apply.
     * @returns {boolean}
     */
    F.Row.prototype.filtered = function(filters){
        var result = true, self = this;
        F.arr.each(filters, function(f){
            if (result){ //check if its already flag to false;
                if (f.query._original.charAt(0) == ">"){
                    result = self.value[f.columns["0"].name] >= moment(f.query._original.substring(1));
                    return (self.value[f.columns["0"].name] >= moment(f.query._original.substring(1)));
                }else{
                    if (f.query._original.charAt(0) == "<"){
                        result = self.value[f.columns["0"].name] <= moment(f.query._original.substring(1)).add(1,'days');
                        return (self.value[f.columns["0"].name] <= moment(f.query._original.substring(1)).add(1,'days'));
                    }else {
                        if ((result = f.matchRow(self)) == false) return false;
                    }
                }
            }
        });
        return result;
    };
})(FooTable);
```




Work with many filters but i am prety sure it wont work with "AND" and "OR". Thats good enought for what i need.
To filter juste put "<" or ">" before the date you whant to filter.
