### ISSUE TITLE
HTML Tags inside a cell are not properly parsed

### ISSUE THREAD

**Issue by jjimenezroda** [fooplugins/FooTable#558]
So my problem is that I'm using KnockoutJS together with footable. The value of one of the binded cells is a set of html tags, but when footable renders it, it renders as a single string. This column has the data-type property set to "html" so I would expect that it renders it accordingly (column Details in the code snipet below).

Here the code:

`<table id="eventsOnPeriodTable" class="table footable" data-show-toggle="true" data-page-navigation=".paginate" data-page-size="50" data-toggle-column="first" data-paging="true" data-sorting="true" data-filtering="true">
                        <thead>
                            <tr>
                                <th data-type="date" data-sortable="true">DateTime of the Event</th>
                                <th data-sortable="true">Event Name</th>
                                <th data-sortable="true">Stream Id</th>
                                <th data-type="number" data-sortable="true">Checkpoint number</th>
                                <th data-breakpoints="all" data-type="html">Details</th>
                            </tr>
                        </thead>
                        <tbody data-bind="foreach: listOfSelectedEvents">
                            <tr>
                                <td data-bind="text: TimeOfTheEvent"></td>
                                <td data-bind="text: EventName"></td>
                                <td data-bind="text: StreamId"></td>
                                <td data-bind="text: CheckpointNumber"></td>
                                <td data-bind="text: EventPayLoad"></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr class="hide-if-no-paging">
                                <td colspan="100" class="text-center">
                                    <div class="paginate">
                                        <ul class="pagination"></ul>
                                    </div>
                                </td>
                            </tr>
                        </tfoot>
                    </table>`

See also attached image for the result of the current code.

![capture](https://cloud.githubusercontent.com/assets/12435936/20367149/934a6c28-ac4e-11e6-9bc0-9846c63df89b.PNG)

Do you know what am I doing wrong?

**Comment by steveush** [comment]
Hi @jjimenezroda,

I don't use KnockoutJS myself but I think it is because you are binding the result using text. I think you should be using the html binding http://knockoutjs.com/documentation/html-binding.html.

PS. To get nicely formatted code here in GitHub use three back ticks to maintain white-space and then add in the language for the code block.

e.g.

<pre>&#96;&#96;&#96;html
&lt;html&gt;&lt;/html&gt;
&#96;&#96;&#96;</pre>

Thanks

**Comment by jjimenezroda** [comment]
True...silly me...Thanks I close the issue.
