### ISSUE TITLE
Footable is not working with jquery steps

### ISSUE THREAD

**Issue by vrushalip** [fooplugins/FooTable#559]
FooTable pagination is not working with jquery steps. Pagination is visible but page numbers are not working.

**Comment by steveush** [comment]
This is an issue with the Steps plugin and how it initializes it's content. Take a look at this [SO question](http://stackoverflow.com/questions/38076480/ken-wheelers-slick-carousel-down-start-normally-with-jquery-steps) and log an issue on the plugins repo.

**Comment by vrushalip** [comment]
Issue is not with initializing footable. I am able to see pagination but page numbers are not working

**Comment by steveush** [comment]
Hi,

Sorry, was the first thing in the morning here and hadn't quite woken up yet. Are you using the latest version of FooTable? There were a few fixes in the last couple of versions that addressed issues with pagination. If you are using the latest version can you please create a jsfiddle the replicates the issue so I can see it live and debug it.

Thanks

**Comment by steveush** [comment]
Hi,

Any update to this?

Thanks
