### ISSUE TITLE
Ignore javascript when clicking link

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#56]
Can I somehow ignore the dropdown if I click a link in a row? It triggers the javascript before updating the page.

**Comment by bradvin** [comment]
This was fixed quite a while ago. Do you have an online example on codepen or JSFiddle where the link is still expanding the detail row? Perhaps it is still using an older version?

Cause the row should only expand if the cell is clicked. If you click elements inside the cell it should not trigger the expand. Check out demo2.htm which has links in the cells

**Comment by ghost** [comment]
If I click the first last name in http://themergency.com/footable-demo/demo2.htm when width is small, it opens a new tab, but it expands the row.

**Comment by bradvin** [comment]
that is old and outdated. I need to update the demos at some point.
Download the code and look at demo2.htm and you will see it is fixed

**Comment by ghost** [comment]
I see. Thank you :-)
