### ISSUE TITLE
Text box for used for filtering 

### ISSUE THREAD

**Issue by a-naslund** [fooplugins/FooTable#561]
Hi, is there any way to intercept the text box used for filtering?
I would like to change the json data source using ft.loadRows(...) when doing search and use the value from the field to create a search URL

No text in the search box should use:
url: '.rows.json?OpenView'

with text in the search box
url: '.rows.json?SearchView&Query=<textbox.value>'

**Comment by steveush** [comment]
Hi,

If you want to try doing something like what you describe there are two ways I can think of to accomplish it. 

The first would be to bind a listener to the `before.ft.filtering` event and then call `e.preventDefault()` on the event handler to stop any actual filtering taking place. The second parameter supplied to this event is the instance of FooTable raising the event and the third parameter is an array of all filters to apply, so you can use that to determine the url to load the new data from.

e.g.

```javascript
$('table').footable({
	on: {
		"before.ft.filtering": function(e, ft, filters){
			e.preventDefault(); // stop the default filtering taking place
			// use the filters array to figure out the url to load
			var url = ...;
			// once you have the url ajax load the rows and push them into the table
			$.get(url).then(function(rows){
				ft.loadRows(rows);
			});
		}
	}
});
```

The other way you can do this is to override the default `FooTable.Filtering#filter` function. Seeing as you have created your own custom filtering implementation (from the other issue logged) you can override the default `filter` function seeing as you don't actually need it's logic and then perform the required actions in there.

e.g.

```javascript
FooTable.MyFiltering = FooTable.Filtering.extend({
	// ... other implementation logic
	filter: function(){
		// this goes through all filters and ensures they are actually filters setting default properties etc.
		this.filters = this.ensure(this.filters);
		// use the filters array to figure out the url to load
		var url = ...;
		// once you have the url ajax load the rows and push them into the table
		var self = this;
		$.get(url).then(function(rows){
			self.ft.loadRows(rows);
		});
	}
});
```

I haven't tested the above but either way should get you headed in the right direction.

Thanks

**Comment by a-naslund** [comment]
Hi, thank you for a quick response. I've tried using the "before.ft.filtering" first but found that the actual value of the search string was not so easy to retrieve since I'm also using additional dropdown filters but the following code solved it.
```javascript
e.preventDefault(); // stop the default filtering taking place
// use the filters array to figure out the url to load
var searchText = "";
var filterNames = filters.map(function(item) { return item.name });
var filterQuery = filters.map(function(item) { return item.query });
for (i=0; i<filterNames.length; i++) {
	if (filterNames[i]=="search") {
		var tmpValue = [filterQuery[i]];
		searchText= tmpValue.map(function(item) { return item._value });
	}
};
// once you have the url ajax load the rows and push them into the table
```
What if I want to remove the text box and it's values from the actual filterarray but still use the filtering function and my dropdown values?

In the mean while I'll make a try using the override filtering way.

**Comment by steveush** [comment]
Hi @a-naslund,

I missed your question in your previous comment and re-reading it now I'm not quite sure what you are asking? To remove the default search textbox would require you to basically look through the default `FooTable.Filtering` class and then in your custom `FooTable.MyFiltering` override all functions that use the `$input` property which is the jQuery object for the search input.

Overall it's easier to just hide the search input's `form-group` or the entire row using some CSS. Have a look at the [custom filter UI example](http://fooplugins.github.io/FooTable/docs/examples/advanced/custom-filter-ui.html) which covers the scenario of hiding the default UI and replacing it entirely with your own implementation which could be anything.

Thanks

**Comment by a-naslund** [comment]
Hi, I've decided to go with the custom `FooTable.MyFiltering` and created a new `$input` which I could manage my self and since I also still wanted to use the footable-filtering row I had to hide the original `$input` and it's toggle and buttons. Since I didn't want to edit the js files it wasn't so easy to get a hold of that object but `.footable-filtering .form-inline div.form-group:last-child { display: none; }` did the trick.

This also meant that I needed to create my own remove filter button and are using the sample and removing one filter after another but is there some shortcut available to remove all filters like `self.removeFilter('ALL');` ?

**Comment by steveush** [comment]
Quickest way to remove all is to just set the `this.filters` property to an empty array (`[]`). The `removeFilter` is just a convenience method that looks up the filter using it's name and then removes it from the array, if you want to clear the whole lot then just set it to an empty array prior to calling `filter`.
