### ISSUE TITLE
IE11 64bits troubles

### ISSUE THREAD

**Issue by sbsrouteur** [fooplugins/FooTable#563]
Hi, 

I seem to have trouble using footables with IE11. Upon browser start when website loads first, I get the following console log error : 
![image](https://cloud.githubusercontent.com/assets/11095871/20657779/eaeca5d4-b538-11e6-9295-50c34fb880b3.png)

With Win10, reloading the page "fixes" the problem, for win7 users, it's no show.

Is there some settings required to use footables (current version with IE11?).

Regards,

**Comment by ChrisCatta** [comment]
Tu cherche la compatibilité jusqu a quel IE 11 10 9 8 7 ???

**Comment by steveush** [comment]
Hi,

I've just double checked and FooTable should be working as expected in IE9-11 & Edge (it does not support IE8). Are you running the site in a lower compatibility mode?

Thanks

**Comment by sbsrouteur** [comment]
Hi, 

Running IE11 on Win10 & Win7. You get the above message on Win10 IE11. Reloading "fixes" the problem. On Win7, it's a no go.

If you could give it a shot @ : http://v-l-m.org/jvlm. Maybe you'll see something we did obviously wrong in our html header that messes IE. Edge runs here fine, as well as FF, Chrome, Opera.

Thanks,

**Comment by steveush** [comment]
Hi,

Directly below your title you are forcing the page to render in IE8 mode by using the following:

```
<meta http-equiv="X-UA-Compatible" content="IE=8">
```

FooTable will not work in IE8 or IE8 compatibility mode.

Thanks

**Comment by sbsrouteur** [comment]
Arrghh, shame on us.
Changed to content="IE=11", since removing the line make IE go to an even lower compatibility mode.

Sorry for the inconvenience, and thank you for pointing our the error.
