### ISSUE TITLE
Table striping (different class for odd/even rows)

### ISSUE THREAD

**Issue by stevevg** [fooplugins/FooTable#564]
In v2 there was the possibility to set a different background for odd/even rows. Is it possibile to do the same in v3?

**Comment by steveush** [comment]
Hi,

FooTable uses all of Bootstrap's table styling which you can see at http://getbootstrap.com/css/#tables. The [main example](http://fooplugins.github.io/FooTable/) makes use of Bootstrap's `table-striped` class to provide this functionality. If you want to provide your own colors you should need to just make your own classes targeting the rows using the `:nth-child` selector.

Thanks

**Comment by stevevg** [comment]
Cool, I didn't realize I mistyped the class name `table-stripped` instead of `table-striped`.

**Comment by x10** [comment]
The problem with using the BS3 `table-striped` class with collapsed rows, is the striping is mathematically applied to visible rows so it doesn't work when one is expanded. Are there "even/odd" styles for Footable 3?
