### ISSUE TITLE
FooTable dynamic page sizing is not working with React

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#565]
Hi,
I am using react for my website and for responsive table i have utilized FooTable.I have a table with pagination,View All and View Less button. Initially the table page size would be 10 and when i hit on View All button it should show all records of table without paging and when i hit on View Less it should resume pagination with page size to 10.
I have initialized FooTable in componentDidMount() and on componentDidUpdate() i am changing the pageSize.When state variable is passed to pageSize method <tfoot> elements are getting removed and pagination numbering is not being displayed.I have mentioned code below,please let me know what mistake i am doing and how to resolve this issue.

**JSX Declarationfor table**
`<table id='sampleTable' className='footable table' data-show-toggle='true' data-paging='true' data-sorting="true" data-filtering="true" data-page-size={this.state.pageSizeLength}>`

**JS Declarations**
```
state={
       pageSizeLength:10
}
 componentDidMount(){	
              $('#sampleTable').footable({  
                    "columns": tableColNames,
		                    "rows": tableRows
            }); 
     }
    componentDidUpdate(){      
            FooTable.get('#sampleTable').pageSize(this.state.pageSizeLength);
    }

```

**Comment by steveush** [comment]
Hi,

Apologies, I don't use React for any of my projects and have absolutely no idea why it is not working for you. All I can say is the same thing I say to the Angular developers, I'll leave this issue open and see if anyone that uses React can help you out however everything I have seen would lean towards not trying to mix frameworks such as React and jQuery and only if absolutely neccessary do it so I'm not sure how much help you might get.

Thanks

**Comment by ghost** [comment]
Hi,

I had made some modification before calling pageSize() and it works as expected and following is the solution

 componentDidUpdate(prevState,prevProps){   
           if(prevState.pageSizeLength!=this.state.pageSizeLength)
            FooTable.get('#sampleTable').pageSize(this.state.pageSizeLength);
    }

This basically checks if the pageSize is same as before,if there is change in pageSize then it calls for pageSize method to dynamically change the pageSize of the table

Thanks for answering me steveush

**Comment by jinog268** [comment]
Dear ghost,
Can you please show how the footable is implemented in your react project?Am always getting " footable() is not a function" error
