### ISSUE TITLE
Explicitely show/hide loader on table

### ISSUE THREAD

**Issue by stavrianosy** [fooplugins/FooTable#569]
When the page load, I initialize the table with no records and then, when the user click on the fetch data button, I explicitly call the rows.load to fetch the data with ajax. 

```
attached(){
this.fooTable = FooTable.init('.myTable',{
                'on': {
                    'draw.ft.table': function(e, ft) {
                        tooltip();
                    },
                    'postinit.ft.table':function(e,ft){
                        _self.loadRows();
                    }
                },
                "columns": ...
)};
}

loadRows(){
  **show loader / spinner**

  var result = _fetch data from server_
  ...
  this.fooTable.rows.load(result);

  **hide loader / spinner**
}
```

Can I show the loader (spinner) and hide it when the data are retrieved?

**Comment by steveush** [comment]
Hi @stavrianosy,

With the changes that are on the develop branch I think this is possible as the loader is now stored as a property on the table, e.g. `this.fooTable.$loader` so you could just append it yourself. That said I think I will add in a utility method for this to make life a little simpler, e.g. `this.fooTable.loader( state = false )` where the state parameter is just a bool value indicating whether to add or remove the loader.

If you want to implement this yourself right now with the current release version of FooTable you could just use the following snippet and insert in your page just after the FooTable scripts.

```javascript
(function($, F){

	F.Table.extend('loader', function(state){
		state = F.is.boolean(state) ? state : false;
		if (state){
			var $loader = $('<div/>', { 'class': 'footable-loader' }).append($('<span/>', {'class': 'fooicon fooicon-loader'}));
			this.$el.hide().after($loader);
		} else {
			$('.footable-loader').remove();
			this.$el.show();
		}
	});

})(jQuery, FooTable);
```

And then in your case call it using `this.fooTable.loader( true )` to show the loader and `this.fooTable.loader( false )` to hide it.

Thanks

**Comment by stavrianosy** [comment]
Thanks it worked.
When my datasource is relatively big, >1000 records it will show the loader until the data are fetched, then display the "No Results" message for a moment, then the loder and finally the results.

I tried to use the `this.fooTable.loader( true ) `and `this.fooTable.loader( false )` in the events draw and predraw, but still getting this behaviour.
```
'draw.ft.table': function(e, ft) {
                        _self.fooTable.loader( false )
                    },
'predraw.ft.table': function(e, ft) {
                        _self.fooTable.loader( true )
                    },

```
Is there anything else I can do to fix this?

**Comment by steveush** [comment]
Hi @stavrianosy,

Can you try hiding the loader in the `postdraw.ft.table` event? I'll play around with this later today and see if I can replicate what you're seeing.

Thanks

**Comment by stavrianosy** [comment]
Its perfect now.
Thanks!
