### ISSUE TITLE
Totals

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#57]
It would be a great feature to add totals in the bottom of the table which acts correctly according to the filter.

**Comment by bradvin** [comment]
This is a great idea for a footable extension. check out the plugin template to see how easy it is to create an extension : https://github.com/bradvin/FooTable/blob/master/js/footable.plugin.template.js

**Comment by hpatoio** [comment]
Only with the template is very hard! Would be nice to have documentation to know how get cells values, format and etc.
