### ISSUE TITLE
what  problem  declare </br> for  &lt;/br&gt;    in <td>

### ISSUE THREAD

**Issue by JhoanSteve** [fooplugins/FooTable#570]
example php 

<tr>
  <td><?php echo  $array['sku']  ?></td>
</tr>
-- is change 

&lt;tr&gt;
  &lt;td&gt;<?php echo  $array['sku']  ?>&lt;/td&gt;
&lt;/tr&gt;

-- for footable change sintaxis for html

**Comment by steveush** [comment]
Hi,

Sorry, but I have no idea what this issue is about. Please provide more information or I'll just be closing this.

Thanks
