### ISSUE TITLE
FooTable not loading new data when pagination is set

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#571]
Hi,

I am using FooTable to render my tables,i have also added pagination,sorting and filtering functionalities.On first load of table all these features works properly without any issue.In my scenario i have a drop down and as and when dropdown value changes,table will be loaded with new data.
The issue i am facing is on drop down value change only the first 10 records of table is getting updated and all other rows that are hidden due to pagination are not being updated and reminds will old row values.Because of this even sort and filtering is not working correctly.
Please let me know ways to dynamically refresh the table row thereby showing all table rows with updated data and sort/filtering should work with new data

**Comment by steveush** [comment]
Hi,

Please take a look at the load rows example (http://fooplugins.github.io/FooTable/docs/examples/advanced/loading-rows.html) to see how to switch out the underlying rows with a new data set or append to the current.

Thanks

**Comment by ghost** [comment]
Hi,

I have to display a table that has 2 of its column with html elements and have to bind click events to it..I am able to render the html elements but unaware on how to bind the click events

**Comment by steveush** [comment]
Hi,

Seems I missed your follow up so before I close I'll respond to it. The easiest way is to use delegate event handlers, so you bind your events to the `<table>` element using [jQuery's `.on()`](http://api.jquery.com/on/) method. This has two main advantages;

1. You only have to bind one handler.
2. You don't have to worry about the tables content changing.

Thanks
