### ISSUE TITLE
Dynamically append <th> and <td> for expanding toggle 

### ISSUE THREAD

**Issue by neorana** [fooplugins/FooTable#572]
Hi guys,
I need to load dynamically the details for toggling of footable.
Need to pull records from api then maybe append it on toggle of the table.
Example:
     1st Record:
              Header1: <td>details1</td>
              Header2: <td>details2</td>
     2nd Record:
              Header1: <td>details1</td>
     3rd Record:
              Header1: <td>details1</td>
              Header3: <td>details3</td>

The objective is to load the details on toggle dynamically..
Hope it was clear...
Need your help.. thanks in advance..

**Comment by steveush** [comment]
Hi,

Apologies but I don't think FooTable is the right plugin to use for this. You might be able to get it to work but it is a customization that you would need to implement on your own, I can't think of an easy way to accomplish this as it was simply never designed to accommodate it.

Thanks
