### ISSUE TITLE
Issue with limiting paging

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#573]
I have a table that returns thousands of rows, so naturally, I want to have paging. The paging is working great, except I can't get the limit to work. If I have 25000 rows, and limit the page size to 100, I have 250 paging buttons. I want to limit that to 10 buttons. currently, this is my code initializing the table
```var ft = FooTable.init("#mailingData", {
	"columns": [
		{ "name": "example1", "title": "example 1" },
		{ "name": "example2", "title": "example 2" },
		{ "name": "example3", "title": "example 3" }
	],
	"paging":
		{ "size": 100, "position": "right", "limit": 10 }
		})
```
Everything else is working fine, but the limit isn't. Please help

**Comment by steveush** [comment]
Hi,

I suggest checking for CSS conflicts in your page as this is working correctly in all the examples (http://fooplugins.github.io/FooTable/docs/examples/component/paging.html). All pagination links always exist in the DOM and are simply shown/hidden depending on what number page you are on so it sounds like you have some CSS that is forcing all of the links to always be displayed.

Thanks

**Comment by ghost** [comment]
Thank you so much, that was exactly it. Apparently the css file that contained the "visible" class had not been added to my project. I never would have caught that, thank you!
