### ISSUE TITLE
Possible to concatenate columns?

### ISSUE THREAD

**Issue by EggrollOfDestruction** [fooplugins/FooTable#576]
I have columns that break up a part number. and I'd like to concatenate them into one column. I tried looking at the formatter and the parser but didn't understand how to go about doing it. I tried something like the following but it didn't work. What am I missing? Thanks. 

```
$(document).ready(function() {
            jQuery(function($){
	           $('.table').footable({
                "expandFirst": false,
                "columns": [
                    { "name": "PartID", "title":"PartID", "visible":false },
                    { formatter: function(value){
                        //formatted like ##.###.##
                        return value.PartCategory +"."+ value.PartNumber1 +"." + value.PartNumber2; 
                    }},
                    { "name": "PartCategory", "title": "PC" },
                    { "name": "PartNumber1", "title": "PN1" },
                    { "name": "PartNumber2", "title": "PN2",  },
                    { "name": "PartName", "title": "Name",  },
                    { "name": "DescShort", "title": "Description",  },
                    { "name": "SupplierName", "title": "Supplier", },
                    { "name": "SupplierPartNumber", "title": "Supplier Part #",  }
                ],
                "rows": $.getJSON("../dist/scripts/testGetParts.php")
               });
            });
        });
```

**Comment by steveush** [comment]
Hi,

At the moment there is no way by default to access the full row data during cell creation. Please take a look at my final response to #542 for the reasoning and a possible work around.

Thanks

**Comment by steveush** [comment]
Hi @EggrollOfDestruction,

I've implemented this type of functionality into the develop branch and it will be included in the next release. Basically the formatter function is now supplied three parameters; `value`, `options` and `rowData`. The `rowData` is just a JS object containing all parsed values for the row.

Thanks
