### ISSUE TITLE
HTML elements inside table being removed after .footable();

### ISSUE THREAD

**Issue by SimStm** [fooplugins/FooTable#578]
Ok, so I have a table who contains some links and HTML tags inside each row.

Without Footable everything looks good, but when I do the ".footable()" thing, any HTML tag inside my table is just removed. I haven't this issue in previous Footable version (v2) so I think this is something related to the V3 version.

Before running the footable() method:
![chrome_2017-01-05_17-14-48](https://cloud.githubusercontent.com/assets/7052502/21696956/5927c630-d377-11e6-8e96-9205efa86c23.png)

HTML code before footable() method:
![chrome_2017-01-05_17-15-24](https://cloud.githubusercontent.com/assets/7052502/21697023/a1a8aaa0-d377-11e6-9630-bed7c60ae85a.png)

After running footable() method:
![chrome_2017-01-05_17-14-48 - copia](https://cloud.githubusercontent.com/assets/7052502/21697035/a9c9eb54-d377-11e6-99a8-0a1251773814.png)

HTML code after footable() method:
![chrome_2017-01-05_17-15-49](https://cloud.githubusercontent.com/assets/7052502/21697044/b2bbb3aa-d377-11e6-9736-8fa9eab3fc87.png)

Tried some changes inside .js file but without success. 
I'm using only the footable.core.js with the core.bootstrap css

Any solution about this?

**Comment by jeffconklin** [comment]
Please review the options listed on the Getting Started guide. There is a "[type](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-type)" column option that, by default, treats everything as text. You will need to use the HTML type fr your cells that contain HTML.

**Comment by steveush** [comment]
Hi @SimStm,

@jeffconklin is correct, please try using the HTML column type, this should prevent any custom HTML being stripped from the column.

Thanks
