### ISSUE TITLE
Sortable disable not working

### ISSUE THREAD

**Issue by CallumWalterWhite** [fooplugins/FooTable#582]
Hi!

Working on project atm which requires HTML tables that need sorting, but one of these table have a column which has select checkbox's to select the row, so I wanted to disable the TH column which has all the select checkbox's because that TH has a checkbox which select all the checkbox's for the rows.

I first tried passing "columns": [{"sortable": false }] within the param but nothing occurred, next i tried the attribute data-sortable="false" on the TH with the that passing param but still nothing occurred.
I don't know what version using as Im using template monster product so it has it within there, any help would be most appreciated!

**Comment by steveush** [comment]
Hi,

I've just tested both the data attribute and passing the option directly in the constructor and it works as expected. Unfortunately I'm not sure who the author is for your template but you would need to contact them and ask for it to be updated. The plugin as it is now, available on this repo, works and you can disable sorting on specific columns.

Thanks

**Comment by CallumWalterWhite** [comment]
Hi,

Basically the version that Template monster implemented was 2.0.3 of Footable so is there anyway in that version to disable columns sorting? Because when I try to implement I new updated version of Footable alot of stuff needs to change on mutiple pages so Im just asking now

**Comment by steveush** [comment]
Hi,

That version is not maintained or supported anymore but at the time it was decommissioned you could disable sorting on a specific column by adding the `data-sort-ignore="true"` attribute to the column header.

There is a [V2 branch](https://github.com/fooplugins/FooTable/tree/V2) available on this repo which contains the 2.0.3 version and it's docs and demos so you can download that to view the documentation but it is no longer hosted online.

Thanks

**Comment by CallumWalterWhite** [comment]
Hi,

That worked perfectly cheers!
