### ISSUE TITLE
Ajax table won't sort numeric column

### ISSUE THREAD

**Issue by bwburch** [fooplugins/FooTable#583]
I'm using the ajax table / column below, and it's not sorting the numeric column correctly.  The column is actually a decimal.  Any idea how I can get this to work?

The table sorts like this.

9500.00
9400.00
940.00
9300.00
930.00
9200.00

String columns = "["+
			  "{\"name\":\"Details\",\"title\":\"Actions\",\"type\":\"html\",\"breakpoints\":\"xs sm md\"},"+
			  "{\"name\":\"Invoice\",\"title\":\"Invoice\"},"+
			  "{\"name\":\"Customer\",\"title\":\"Customer\"},"+
			  "{\"name\":\"Amount\",\"title\":\"Amount\",\"data-type\":\"numeric\",\"breakpoints\":\"xs sm md\"},"+
			  "{\"name\":\"Status\",\"title\":\"Status\",\"breakpoints\":\"xs sm md\"},"+
			  "{\"name\":\"Date\",\"title\":\"Invoice Date\",\"type\":\"date\",\"formatString\":\"MM/DD/YYYY\",\"breakpoints\":\"xs sm md\"},"+
			  "{\"name\":\"Contact\",\"title\":\"Contact\",\"breakpoints\":\"xs sm md\"}]";

Thanks,
Brett

**Comment by steveush** [comment]
Hi,

Looking at your sample code the options are incorrectly set for the "Amount" column. The name should be `"type"` instead of `"data-type"` and the value should be `"number"` instead of `"numeric"`.

Thanks

**Comment by bwburch** [comment]
Thanks for the feedback, I've made the changes and still not sorting as expected.

If I change the type to number it doesn't display the decimal for whole dollar amounts, but numeric does.

css in page.
/footable/css/footable.bootstrap.css
javascript in page.
/footable/js/footable.js

This is displayed with:
"{\"name\":\"Amount\",\"title\":\"Amount\",\"breakpoints\":\"xs sm md\",\"type\":\"numeric\"},
![image](https://cloud.githubusercontent.com/assets/6172731/21957562/8678c88a-da5e-11e6-985e-571bccdaad09.png)

This is displayed with:
{\"name\":\"Amount\",\"title\":\"Amount\",\"breakpoints\":\"xs sm md\",\"type\":\"number\"}
![image](https://cloud.githubusercontent.com/assets/6172731/21957598/46ccb132-da5f-11e6-8d3c-db3d25d47573.png)

**Comment by steveush** [comment]
Hi,

The type `numeric` does not exist, the plugin supports `number`. So setting it to `numeric` is basically the same as setting it to `text` which is the default column type and is why the sorting is not correct.

You must set the column type to `number` and then take a look at the [column formatter option](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-formatter). You can use this to format the values to include the two decimal places. At present it is simply using the default `.toString()` value of the decimal which does not include decimal places if they are zero.

You could use something as simple as:

```javascript
function myFormatter(value){
	return value.toFixed(2);
}
```

Or get it to return whatever you might need like including the currency symbol as an example:

```javascript
function myFormatter(value){
	return "$" + value.toFixed(2);
}
```

Thanks

**Comment by steveush** [comment]
Hi,

Just wanted to add, seeing as you are building up a string of options you can supply the formatter function as a string as well so the function can exist in the page and you don't need to output it within the options itself. To supply it as a string it must be a named function accessible from the global scope. As an example:

```html
<script>
	function myFormatter(value){
		return "$" + value.toFixed(2);
	}
	
	jQuery(function($){
		$(".table").footable({
			columns: [
				{"name":"Amount","formatter":"myFormatter"}
			]
		});
	});
</script>
```

The function can also be a namespaced function:

```html
<script>
	window.myAPI = {
		formatter: function(value){
			return "$" + value.toFixed(2);
		}
	};
	
	jQuery(function($){
		$(".table").footable({
			columns: [
				{"name":"Amount","formatter":"myAPI.formatter"}
			]
		});
	});
</script>
```

Thanks

**Comment by bwburch** [comment]
I really appreciate all your help, I've tried the formatter option and it will display with the $ but sorting by the Amount column still sorts like this.

$9980.00
$998.91  -- This shouldn't be here.
$9967.00

I'm sure it's something I'm doing wrong but not sure how to proceed.

Thanks again,
Brett

**Comment by steveush** [comment]
Hi @bwburch,

Did you change the column type to `number`? The sorting should be working as expected once the column type is set correctly. I've tested it here locally and it sorts as expected using your example figures. You can test it using the below:

```html
<table class="table" data-sorting="true">
</table>

<script>

	function myFormatter(value){
		return "$" + value.toFixed(2);
	}

	jQuery(function($){
		$('.table').footable({
			"columns": [{"name":"Amount","title":"Amount","type":"number","formatter": "myFormatter"}],
			"rows": [
				{"Amount": 9980.00},
				{"Amount": 9500.5},
				{"Amount": 998.91},
				{"Amount": 9967.00},
				{"Amount": 9300},
				{"Amount": 9300.5}
			]
		});
	});

</script>
```

Thanks

**Comment by bwburch** [comment]
Here's my code.  Looking at your code should I use static columns instead?

<script type="text/javascript">
$(document).ready(function() { //document
	jQuery(function($){
		$('#invoiceHistory').footable({
			"columns": $.ajax('/rest/api/invoice/list/columns'),
			"rows": $.ajax('/rest/api/invoice/list')
		});
	});
});
</script>

<script>
function formatTotal(value){
	return "$" + value.toFixed(2);
}
</script>


ajax call to /rest/api/invoice/list/columns
public class InvoiceHistoryColumns {

	String columns = "["+
			  "{\"name\":\"Details\",\"title\":\"Actions\",\"type\":\"html\",\"breakpoints\":\"xs sm md\"},"+
			  "{\"name\":\"Invoice\",\"title\":\"Invoice\"},"+
			  "{\"name\":\"Customer\",\"title\":\"Customer\"},"+
			  "{\"name\":\"Amount\",\"title\":\"Amount\",\"breakpoints\":\"xs sm md\",\"formatter\":\"formatTotal\",\"type\":\"number\"},"+
			  "{\"name\":\"Status\",\"title\":\"Status\",\"breakpoints\":\"xs sm md\"},"+
			  "{\"name\":\"Date\",\"title\":\"Invoice Date\",\"type\":\"date\",\"formatString\":\"MM/DD/YYYY\",\"breakpoints\":\"xs sm md\"},"+
			  "{\"name\":\"Contact\",\"title\":\"Contact\",\"breakpoints\":\"xs sm md\",\"style\":{\"maxWidth\":50,\"overflow\":\"hidden\",\"textOverflow\":\"ellipsis\",\"wordBreak\":\"keep-all\",\"whiteSpace\":\"nowrap\"}}]";
	
		
	public String getColumns() {
		return columns;
	}

	public void setColumns(String columns) {
		this.columns = columns;
	}
	
																																																																																							
}

ajax call to /rest/api/invoice/list  -- Just a sample returns many rows.
[
  {
    "Invoice": "67876",
    "CustomerID": "4550",
    "Customer": "customer name",
    "CreatorID": "7253",
    "Contact": "contact name",
    "Date": "1483250400000",
    "Amount": "175.00",
    "Modified": "2017-01-01 04:11:54",
    "Status": "Open",
    "Details": "<span class=\"btn-group\"><button class=\"btn dropdown-toggle\" data-toggle=\"dropdown\"><strong>More</strong>&nbsp;&nbsp;<i class=\"caret\"></i></button><ul class=\"dropdown-menu pull-right\"><li id=\"Invoice_detailView_moreAction_Print\"><a href=\"/rest/api/invoice/print?invoiceID=67876\">Print / Export PDF</a></li><li id=\"Invoice_detailView_moreAction_Details\"><a href=\"/invoice/invoice-details.jsp?invoiceID=67876\">View Details</a></li></ul></span>"
  }
]

**Comment by steveush** [comment]
Hi @bwburch,

I believe this may be related to issue #595 which I have now resolved on the develop branch. Basically if a number was supplied as a string the sorting component was still treating it as a string instead of performing a numeric sort. This is the difference between our examples above I never noticed but it stands out now. You were supplying your values as strings (`"123"`) while I was supplying it as an actual number (`123`).

Thanks
