### ISSUE TITLE
How to do preventDefault on sortable column

### ISSUE THREAD

**Issue by sekharvemuri** [fooplugins/FooTable#585]
I would like to preventDefault when I click on a Footable column header upon checking a condition. If my condition fails, I would like to stop sorting otherwise it should sort.

I tried adding a click event listener on header but it is getting invoked only after listener in source executes. Can I get some help in this regard?

**Comment by steveush** [comment]
Hi,

Please try using the ["before.ft.sorting"](http://fooplugins.github.io/FooTable/docs/jsdocs/FooTable.html#.event:Sorting%2522before.ft.sorting%2522) event and then you can call `e.preventDefault()` on that to conditionally stop the sorting behavior.

Example:

```javascript
$(".table").footable({
	on: {
		/**
		 * Handle the before sort event to check any conditions and stop sorting.
		 * @param {jQuery.Event} e - The jQuery.Event object.
		 * @param {FooTable.Table} ft - The current instance of the plugin.
		 * @param {FooTable.Sorter} sorter - A small object detailing the column and direction of the sort.
		 */
		"before.ft.sorting": function(e, ft, sorter){
			if ( some_condition === true ){
				e.preventDefault();
			}
		}
	}
});
```

Thanks
