### ISSUE TITLE
Initializer ignores paging limit option

### ISSUE THREAD

**Issue by askuratovsky** [fooplugins/FooTable#586]
`* @version 3.1.4`
downloaded from:
http://fooplugins.github.io/FooTable/docs/getting-started.html#download
Bootstrap Version

initializer coffee:

```coffee
$ ->
  $('.footable').footable 'paging':
    enabled: true
    size: 20
    limit: 5
```

Table has 1323 rows

Result:
<img width="809" alt="screen shot 2017-01-23 at 14 59 00" src="https://cloud.githubusercontent.com/assets/2787325/22203120/83ba9ad6-e17c-11e6-83f6-2712bd3b37fb.png">

**Comment by steveush** [comment]
Hi,

Please take a look at my response to #573 and check if you have a CSS conflict in your page which is forcing all pagination buttons to be displayed. Or as in the case of 573 make sure all the CSS files are correctly included in the page.

Thanks

**Comment by askuratovsky** [comment]
Thanks, the problem was in css.
