### ISSUE TITLE
How to set background of a cell by json

### ISSUE THREAD

**Issue by kvcomeaux** [fooplugins/FooTable#587]
I was looking for an example of how to set the json being returned to color a cell.
If I were writing html I could set a class on the "<TD" tag, but not sure how to do this in javascript JSON.
I have an ajax call that sets the data to the rows.   Just not sure how to set the background color of a particular cell depending on the data in that cell.  For example if a Status is "Critical", it should be bg-warning.
Any thoughts on this would be appreciated.

Thanks

**Comment by steveush** [comment]
Hi,

The JSON method of supplying rows supports providing individual row or cell options, take a look at the second to last example for the [rows option](http://fooplugins.github.io/FooTable/docs/getting-started.html#rows) to see how to provide options for individual cells. It basically boils down to the below:

```javascript
jQuery(function($){
	$('.table').footable({
		"rows": [{
			// supply options for the row
			"options": {
				"expanded": true,
				"classes": "your-css-class"
			},
			"value": {
				"id": {
					// supply options for the id cell
					"options": {
						"classes": "your-css-class"
					},
					"value": 1
				},
				"firstName": "Dennise",
				"lastName": "Fuhrman",
				"jobTitle": "High School History Teacher",
				"started": "November 8th 2011",
				"dob": "July 25th 1960"
			}
		},{
			...
		}]
	});
});
```

If you can't alter the endpoint you can always create a custom column type to handle this for you, something like the below should do what you need.

```javascript
(function($, F){

	// create a new cell class that will be used by the new column when creating cells
	F.StatusCell = F.Cell.extend({
		// override the original $create method and update it with one that applies the CSS class based on the current value
		$create: function(){
			this._super();
			if (this.created){
				switch(this.value){
					case "Critical":
						this.$el.addClass("bg-warning");
						break;
				}
			}
		}
	});

	// create a new column type called "status" that will use our custom cell class when creating cells
	F.StatusColumn = F.Column.extend({
		// override the base constructor so we can specify the type as "status"
		construct: function(instance, definition){
			// call the base constructor
			this._super(instance, definition, "status");
		},
		// override the base createCell method and make it use our new cell class when creating cells
		createCell: function(row){
			var element = F.is.jq(row.$el) ? row.$el.children('td,th').get(this.index) : null,
				data = F.is.hash(row.value) ? row.value[this.name] : null;
			// the above is required and the only change to this method is to return a new StatusCell instead of just a Cell
			return new F.StatusCell(this.ft, row, this, element || data);
		}
	});

	// register the "status" column so we can use it in our tables
	F.columns.register('status', F.StatusColumn);

})(jQuery, FooTable);
```

Once you have included the above in the page after the FooTable scripts you can then specify the column type as `"status"`, just like you would do for `"number"` or `"date"` columns at the moment.

Example:

```javascript
jQuery(function($){
	$('.table').footable({
		"columns": [{
			"type": "status",
			...
		},{
			...
		}]
	});
});
```

Or you can provide it using the `data-type` attribute on a column header element.

Thanks

**Comment by kvcomeaux** [comment]
Thank you for the quick response.  Found the problem.   I was able to set
the td class, but having the table-striped was causing the problem.
Removed that and it started working.
Regards, Kerry

What I did in the javascript:

            $('.footable-merchant-list').each(function(index)
            {
                $cells = $(this).find("td");
                $cells.each(function(cellIndex)
                {
                    //$status = "<span class='data-status'
bg-type='bg-info'>$status</span>";
                    var cellHtml = $(this).html();
                    if (cellHtml.indexOf("data-status") >= 0)
                    {
                        if (cellHtml.indexOf('bg-danger') >= 0)
                        {
                            $(this).addClass("bg-danger");
                        }

...
