### ISSUE TITLE
Filtering rows on FooTable

### ISSUE THREAD

**Issue by erminido** [fooplugins/FooTable#589]
Dear all,

I'm new posting on GitHub so really sorry for my lack of experience and skill. Obviously, I have a question for you guys, I've first looked for similar questions, but with no successful answer. Here I go with my question: http://fooplugins.github.io/FooTable/docs/examples/component/filtering.html
Such filtering example displayed, with Search text-box, and lens and dopdown list with checkboxes corresponding to the table columns, how can I implement an example like this? I mean, what kind of jquery I have to call for reproducing the same behaviour as the example? I exactly need the same behaviour, with the possibility to exclude the checked table columns from filtering the word written in Search text-box.

I hope I properly explained my question... Thank you in advance for your time, kindness and help.

**Comment by steveush** [comment]
Hi @erminido,

The required JS and HTML markup for the example you linked is provided directly below the example itself. The behavior you described is the default for the filtering component.

Thanks

**Comment by erminido** [comment]
Hi Steve,
thank you very much you answered my seally question, at finally I got it.. the plug-in did exaclty what I wanted.. and it's ok.

I have another problem using the plug-in I try to explain. I have table headings like this:

```
<table id="footableProgrammi" class="table footable footable-filtering footable-paging footable-paging-right footable-filtering-left table-bordered table-hover toggle-circle" data-paging-size="@Utils.CONST._ELEMENTIPERPAGINA" data-filtering="true" data-filter="#filter" data-sorting="true">
   <thead>
       <tr class="footable-header">
            <th class="col-xs-1 colonna_ordinamento" data-type="number">
                @Localizer.Stringify("Ordinamento")
                <a class="fa fa-info-circle info-block fa-lg fa-fw unselectable add-tooltip nascondi-tooltip" data-original-title="@Localizer.Stringify("Trascina_programma")"></a>
            </th>
       </tr>
   </thead>
</table>
```

The problem is that items inside the dropdown (representing the heading colums of the table) also  visualizes (shows) the HTML anchor tag <a ....... ></a> like it would be simple text. Therefore, I suppose the plug-in gets all things inside <th> tag and displays them like plain text. So my question: it is possible to say the plug-in what showing inside the dropdown? My goal is to show only a string, for esample, @Localizer.Stringify("Ordinamento") inside the dropdown, is it possible?

Thank you so much for your help.
Donna

**Comment by steveush** [comment]
Hi,

You're looking for the [column title](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-title) option.

Thanks

**Comment by erminido** [comment]
Ok, thank you very much for your help, I tried, but if I set data-title as column title, the anchor code inside <th> is ignored and then not visualised at all in the head column of the table. 

The problem is that I need to show the anchor inside the head column in the table (because it is an info icon explained something about the column), but I don't want to visualize the anchor inside the dropdown..  

If I specify the column title as data-title, the anchor disappears completely from the head column in the table.. I mean, no html is visualized..

Thanks for your help,
Donna

**Comment by steveush** [comment]
Ah, I see what you mean now. I've made a small modification to the way the dropdown is created so that it strips out child elements (in your case the `a`) and leaves just the text. The modification basically just inherits from the original filtering component and then overrides the `$create` method, it then registers itself with the plugin replacing the original filtering component. To use the below script just include it in your page after the FooTable scripts but before you initialize the plugin.

```javascript
(function ($, F) {

	F.MyFiltering = F.Filtering.extend({
		$create: function () {
			var self = this;
			self._super();
			self.$dropdown.empty();
			if (!F.is.emptyString(self.dropdownTitle)){
				self.$dropdown.append($('<li/>', {'class': 'dropdown-header','text': self.dropdownTitle}));
			}
			var $tmp = $('<div/>');
			self.$dropdown.append(
				F.arr.map(self.ft.columns.array, function (col) {
					return col.filterable ? $('<li/>').append(
						$('<a/>', {'class': 'checkbox'}).append(
							$('<label/>', {text: $tmp.html(col.title).children().remove().end().text()}).prepend(
								$('<input/>', {type: 'checkbox', checked: true}).data('__FooTableColumn__', col)
							)
						)
					) : null;
				})
			);
		}
	});

	F.components.register("filtering", F.MyFiltering);

})(jQuery, FooTable);
```

The main line of code that you may need to change to suit your needs is:

```javascript
$tmp.html(col.title).children().remove().end().text()
```

This line basically inserts the column title into a temporary `div` and then removes all child elements and then fetches just the remaining text.

Thanks

**Comment by erminido** [comment]
Thanks a lot, you're great! I did it and it works well, as I want! I appreciate your help, really thanks!

**Comment by erminido** [comment]
Ok, in case you still have a little patient, I have a problem with column sorting... it seems to be a kind of the previous one, but with sorting.. I'm going to explain..

My table has a <td> containing an image (<img>) and also a string which is the title (@item.s_titleLong), I mean, there are both between <td> and </td>, like the following:

```
<td>
        <img src='@Images.GetProxedUrlListCMS(Request.IsSecureConnection, Request.ServerVariables["HTTP_HOST"],100,60,item.s_logoImage)' class="hidden-xs imageLogoList" />
         @item.s_titleLong                                      
</td>
```
Ok, when I click over <th> for column sorting, I see the sorting function getting the following "value" (I set data-formatter="OnlyTitleNoImgFormat" function to see that): 
```
<img src="........../xxx.png" ............ />
Hello world!
```
So, it seems the sorting function also sorts the image.. or something like this.. On the contrary, I would sort only the text in the table (Hello world), the image is only a surplus info...

I hope I explained myself, I think the problem is similar to the previous one, but I don't know how the sorting function works.. so I appreciate any help you would give to me..

Thanks in advance

**Comment by steveush** [comment]
Hi,

You can output a different value to sort by using the `data-sort-value` attribute on the `td`. e.g.:

```html
<td data-sort-value="@item.s_titleLong">
        <img src='@Images.GetProxedUrlListCMS(Request.IsSecureConnection, Request.ServerVariables["HTTP_HOST"],100,60,item.s_logoImage)' class="hidden-xs imageLogoList" />
         @item.s_titleLong                                      
</td>
```

There is also a `data-filter-value` attribute to specify the value used during filtering operations that can be supplied the same way.

Thanks

**Comment by erminido** [comment]
Great! It works! Really thanks for your help and kindness!
