### ISSUE TITLE
Static data-value and formatter VS ajax load rows

### ISSUE THREAD

**Issue by poulnike** [fooplugins/FooTable#591]
If static table, I use

table cell
```
...
<td (data-value='{ "name": "Tom Smith", "id":"123123123" }')><td>
...
```

colums.json
```
...
{"name": "UF_NAME", "title": Name", "type":"html", "formatter":"footable3__formater_user"}
...
```

footable3__formater_user
```
function footable3__formater_user(value) {
     return '<a id=' + value.id + '>' + value.name + '</a>';
}
```
 That's work.

But, if load rows from json

cell in row
```
"UF_NAME": {
      "options" : {
        "classes": "class1 class2"
      },
      "value": {
         "name": "Tom Smith", 
         "id":"123123123"
      }
    }
```
not work.
And this not work
```
"UF_NAME": {
      "options" : {
        "classes": "class1 class2"
      },
      "value":  "Tom Smith"  
    }
```

Work, if formater in colums like this
```
"formatter": function (value) { ... }
```
But now, no access to value.id and value.name 

Maybe I can call to value from other colum in row?

**Comment by steveush** [comment]
Hi @poulnike,

Please take a look at my final response to #542 for why this is not allowed by default but can be added in quite easily if you are supplying rows through the options/ajax.

Thanks

**Comment by poulnike** [comment]
Thanks @steveush. Understood

**Comment by mamashin** [comment]
@poulnike can you show simple example with formatter and load rows, I can't understand how to do it in #542 :(

**Comment by poulnike** [comment]
@mamashin 
Default, from docs https://jsfiddle.net/poulnike/bes48y93/

from #542 (and if you wont get value from ather column) https://jsfiddle.net/poulnike/bes48y93/3/
(on "jsfiddle.net" This example does not work. I do not know why. Maybe some other version of the plugin. But on my site it works.)

**Comment by mamashin** [comment]
@poulnike Got it ! Its work :) 
Thanks a lot !
