### ISSUE TITLE
Trigger Sort Component

### ISSUE THREAD

**Issue by CallumWalterWhite** [fooplugins/FooTable#592]
Hi,

Working on a project which requires filters on the table. So I'm putting data-sort-ignore on the th which has a filter, when I click the filter and click the ascending button, what I do is rid the attribute from the th then try both $('tablename').trigger('footable_redraw'); and $('tablename').trigger('footable_initialize'); to reload the table to allow it to filter, but it doesn't work.

So i was wondering if there any method with footable which i could trigger a sort component upon the table by parse?

**Comment by steveush** [comment]
Hi @CallumWalterWhite,

Unfortunately the version of FooTable (V2) you are using is no longer supported or maintained. The documentation is not even available anymore online, if this is a new project I would suggest using V3. If you want to continue using V2 you can grab the documentation that was available at the time that version was decommissioned from the [V2 branch](https://github.com/fooplugins/FooTable/tree/V2) of this repository, they are in the demos folder.

Thanks
