### ISSUE TITLE
"Uncaught ReferenceError: FooTable is not defined"

### ISSUE THREAD

**Issue by michellechild** [fooplugins/FooTable#594]
Hi all,

I am relatively new to jQuery so I apologize if this is a newbie question, but I've spent the better part of the day working to get this right. I am building a site with Foundation (zurb) and would love to use FooTable - it provides the exact functionality I had in mind. However, I'm having a tough time getting it to work in my project. 
Here is my workflow so far:

- I installed footable via bower
- I added "bower_components/footable/compiled/footable.js" to my config.yml file
- I called the function in my main js file (app.js to anyone who's familiar with Foundation) like so: 

`$(function(){
	$('.footable').footable();
});`

I'm consistently getting an "Uncaught ReferenceError: FooTable is not defined" error message. I can see that the dist folder is compiling the footable.js folder, but references this line `FooTable = window.FooTable || {}` as the error.

I tried adding FooTable without bower - adding a script to my main index.html file, to no avail. 

Foundation has jQuery built in, and it's loaded before footable.js. Any help/thoughts as to why this is happening?

**Comment by steveush** [comment]
Hi @michellechild,

Unfortunately the bower package is not controlled by me, I'm not sure who created it or what version it is on so for now I would recommend just using the plugin from this repo to get the latest version.

As for the error, what browser are you seeing this in? Older browsers like IE8, which the plugin does not support, may throw an error like you have described when declaring the FooTable namespace/object.

Thanks

**Comment by michellechild** [comment]
Hi @steveush, 
Thank you for the quick reply. I'm seeing this in the latest version of Chrome and Safari, even when using the plugin from this repo (and not bower :/ ).

Thanks

**Comment by steveush** [comment]
Hi,

Could you show me the code snippet of how you are including the scripts into the actual page? The only thing I can think of is they are being included in the incorrect order or something is being left out as I've just tested now using the examples from the docs and everything works as expected in Chrome, I don't have access to Safari at the moment so can't test that yet.

Thanks

**Comment by michellechild** [comment]
Hi Steve,

Sure thing. So, in Foundation all external js files are set up to compile into the app.js folder upon build. I have the footable.js file referenced in my config.yml file like so: 

`    # Paths to your own project code are here

    - "src/assets/js/vendor/footable.js"

    - "src/assets/js/!(app).js"

    - "src/assets/js/app.js"
`

And in inspect, you can see the error: 

<img width="1217" alt="screen shot 2017-02-08 at 10 15 25 am" src="https://cloud.githubusercontent.com/assets/9676840/22743218/8e7b4a2a-ede7-11e6-97b7-5efd0d28feb8.png">

 and the section it's references
<img width="431" alt="screen shot 2017-02-08 at 10 16 10 am" src="https://cloud.githubusercontent.com/assets/9676840/22743242/a46e5110-ede7-11e6-83a2-4df8c6143ee6.png">

The footable.js file is compiled at the very bottom of the file, just before the jquery call:
<img width="256" alt="screen shot 2017-02-08 at 10 17 38 am" src="https://cloud.githubusercontent.com/assets/9676840/22743330/e246799a-ede7-11e6-83d4-6734ea22bd75.png">

Hope this helps. Thank you for your help!

**Comment by michellechild** [comment]
I added a post on the foundation forum as well - if it helps to see my process a little more detailed: http://foundation.zurb.com/forum/posts/50798-adding-a-jquery-plugin-to-foundation

**Comment by michellechild** [comment]
Hi @steveush,

I wanted to give you an update - I've determined the problem is in the Gulp compilation. If I bring the file in from an external server, it works. I can't figure out what Gulp doesn't like about the plugin code yet.

Thanks again,
Michelle
