### ISSUE TITLE
 Is there any option to add more buttons in a row?

### ISSUE THREAD

**Issue by demorales13** [fooplugins/FooTable#598]
Hi,

I need to add two new buttons (up and down) in each row to add a sort behavior in a news table, Is there any option to do that?

Thanks in advance.

**Comment by poulnike** [comment]
@demorales13 

Hi, maybe it help you https://jsfiddle.net/poulnike/ek0ag7ma/1/

**Comment by demorales13** [comment]
Thanks a lot, 

That's what I was looking for...
