### ISSUE TITLE
Sorting File Conflicting with Details View Click

### ISSUE THREAD

**Issue by ChadRepoManager** [fooplugins/FooTable#6]
Hello, 
for some reason the sorting code is conflicting with the details views. I am testing this on Chrome and Firefox on ubuntu and on my iPhone default browser. Your demo version works on these browsers so I thought it might be the downloaded versions. I copied all files and html from your demo version and it still doesn't work on my side. I am totally confused. Any help/Suggestions or Bug? 

I have stopped investigating at the moment but have weeded down what sections this happens.
#1: With the following code commented out of the sorting file the details view will work UNTIL you sort then it will not work anymore.

for(var c in e.ft.columns) {
                var column = e.ft.columns[c];
                if (column.sort.initial) {
                    p.sort(e.ft, $tbody, column);

```
                var $th = $table.find('thead th:eq(' + c + ')');

                if (column.sort.initial == "descending") {
                    p.reverse(e.ft, $tbody);
                    $th.addClass(cls.descending);
                } else {
                    $th.addClass(cls.sorted);
                }
                break;
            } else if (column.sort.ignore != true) {

            }
        }
```
#2: And this is the code in the sorting file that keeps it from working after you sort.

$(e.ft.table).find('tr th.' + cls.sortable).click(function (ec) {
            console.log("clicked");
            var $th = $(this), index = $th.index();
            var column = e.ft.columns[index];
            if (column.sort.ignore == true) return true;
            ec.preventDefault();
            $table.find('> thead > tr > th').not($th).removeClass(cls.sorted + ' ' + cls.descending); 
            }
            if ($th.hasClass(cls.sorted)) {
                p.reverse(e.ft, $tbody);
                $th.removeClass(cls.sorted).addClass(cls.descending);
            } else if ($th.hasClass(cls.descending)) {
                p.reverse(e.ft, $tbody);
                $th.removeClass(cls.descending).addClass(cls.sorted);
            } else {
                p.sort(e.ft, $tbody, column);
                $th.removeClass(cls.descending).addClass(cls.sorted);
            }
                return false;
            });

**Comment by flazcano** [comment]
download and replace this files in js directory:

http://themergency.com/footable-demo/js/footable-0.1.js
http://themergency.com/footable-demo/js/footable.sortable.js
http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js

and this solve this issue :)

**Comment by bradvin** [comment]
hi there

Yes I think it is because the demo on my server has not been updated to use the latest versions yet :)
