### ISSUE TITLE
How can I draw the parameter of a object?

### ISSUE THREAD

**Issue by demorales13** [fooplugins/FooTable#601]
Hi,

I have the following collection:
`var collection = [
    {
       item: {name: 'item1', id: 1}
       comment: 'comment item 1'
    },
   {
       item: {name: 'item2', id: 2}
       comment:'comment item 2'
    }
]`

How can I draw the parameter 'name' of the object 'item' in a column?

I've try that but not work.

`var ft= FooTable.init('.table', {
            columns: [{
                name: '_id',
                visible: false
            }, {
                name: 'item',
                title: 'Item',
                formatter: function (value) {
                    if (value) {
                        return value.name;
                    }
                },
            }])
`

Thanks in advance.

**Comment by steveush** [comment]
Hi @demorales13,

The reason why the above is not working is that the default text column parser forces the value passed to the formatter function to be a string or null. In this case the object comes through as a string literal `"[Object object]"`. To get around this you can override the default columns parser function but the better option would be to create a column that handles this a bit better. The below code creates such a column and should be included after the original FooTable files but before you initialize any tables.

```javascript
(function($, F){

	F.ObjectColumn = F.Column.extend({
		construct: function(instance, definition) {
			this._super(instance, definition, 'object');
		},
		parser: function(valueOrElement){
			if (F.is.element(valueOrElement) || F.is.jq(valueOrElement)){ // use jQuery to get the value
				var data = $(valueOrElement).data('value'); // .data() will automatically convert a JSON string to an object
				return F.is.object(data) ? data : null; // if we have an object return it
			}
			if (F.is.object(valueOrElement)) return valueOrElement; // if we have an object return it
			return null; // otherwise we have no value so return null
		},
		formatter: function(value){
			return F.is.object(value) ? JSON.stringify(value) : '';
		}
	});

	F.columns.register('object', F.ObjectColumn);

})(jQuery, FooTable);
```

At the moment the above formatter function simply does a `JSON.stringify` on the value as the default action however your current code will overwrite that and return the `value.name` property. The only change that would need to be made is that you must include `type: "object"` for the column.

```javascript
$('.table').footable({
	columns: [{
		name: '_id',
		visible: false
	},{
		name: 'item',
		title: 'Item',
		type: 'object',
		formatter: function (value) {
			return FooTable.is.object(value) && FooTable.is.string(value.name) ? value.name : '';
		}
	}],
	rows: [{
		item: {name: 'item1', id: 1},
		comment: 'comment item 1'
	},{
		item: {name: 'item2', id: 2},
		comment:'comment item 2'
	}]
});
```

Thanks

**Comment by demorales13** [comment]
Works fine, this behavior should be a default option... Thanks a lot.
