### ISSUE TITLE
Placing the filter form outside table

### ISSUE THREAD

**Issue by jeffconklin** [fooplugins/FooTable#604]
Hello,

I use custom dropdown filtering (ex: http://fooplugins.github.io/FooTable/docs/examples/advanced/filter-dropdown.html) throughout my tables. We have started to change our layout and would like to "move" this built in filtering outside the table, without having to recreate anything.

Since this is all Javascript that creates the filter form, would you ever consider allowing us to specify a target element instead of automatically creating the header row? Looking through the code quickly I see that you add the new row within the thead (.prependTo(self.ft.$el.children('thead'));), add the th/colspan, and do some more magic to get it all functioning. Maybe instead of adding a row to the thead, you just add it to another element of our choice?

I know it would help me since without this I need to recreate your logic to accomplish the same thing.

Thanks.

**Comment by steveush** [comment]
Hey @jeffconklin,

There's a bit more to it than just the `$create` method to alter but I'll look into it to see if I can make the target an option.

Thanks

**Comment by steveush** [comment]
Hi @jeffconklin,

I've updated the develop branch with this feature by adding a new option to the filtering component called simply `container`. You can supply a CSS selector as the value and the plugin will output the filtering form in the first matched element and not in the table as it currently does.

```javascript
$(".table").footable({
	filtering: {
		...
		container: "#filter-container"
		...
	}
});
```

The attribute for this option is `data-filter-container` and must be applied on the `<table>` element.

Thanks

**Comment by ghost** [comment]
Has this made it to the stable branch?  I'm trying to use it and it's not working.

**Comment by joshco** [comment]
Can you do this for the paging control too?

**Comment by jeffconklin** [comment]
@ThreeWest ... I do not believe this has been released yet. Current version is 3.1.4, which was released before this post started.

@joshco ... great idea... would be very helpful. 

Also, @steveush, will providing a class allow this to be placed in multiple locations? We have filtering on the top, but also include it at the bottom of the table when not using Footables.
