### ISSUE TITLE
Column formatter extra parameter

### ISSUE THREAD

**Issue by DrunkenMoose** [fooplugins/FooTable#605]
Hey everybody,

I have a request for perhaps a handy extension. The formatter function is very handy to have more control between the moment the data is added and showed to the user. I have an example where I think the formatter falls a little bit short. 

I have a table which shows some contracts. I want to have a link to the detail page of the contract in the table. I think i can make this link functionality with the formatter. So you have a column with a contract ID and I added a formatter function which wraps the <a> tag around it.

But what I would like to see is to have more control which values are accessible in the formatter function. So I would like to have two values: the contract ID for the link itself and a contract nummer as string as the text showed in the link. So is it perhaps an idea to have a data-formatter-attribute(s) where you can link some values. 

While I'am typing this I think i can do a workaround where every row in the table has it's unique ID and this is the value given to the formatter. In the formatter is it then possible to find the row and then the attribute you want. 

But if you want to take a look then I would be thankful.

Greetings, 

Roland M

**Comment by poulnike** [comment]
@DrunkenMoose 
#591 #601

**Comment by DrunkenMoose** [comment]
Thank you for the response, I would take a look at it.

**Comment by steveush** [comment]
Hi,

Just commenting that I've updated the column formatter option as described in @poulnike's comment on the develop branch and the change will be included in the next release. If you like you can checkout and build the [develop branch](https://github.com/fooplugins/FooTable/tree/develop) to test the updated version now or simply use the files found in the [compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled).

Thanks

**Comment by steveush** [comment]
The above mentioned changes are now available in 3.1.5.

Thanks
