### ISSUE TITLE
Filter and showing related rows

### ISSUE THREAD

**Issue by yonihbc** [fooplugins/FooTable#606]
Hi,

I have a table that some of the rows are sub-row for it's parents
lets say i have only 2 rows
id|name|desc|number|phone|email
1|a         |a     | 1          | 0004 | email@email.com 
1|b         |bb  | 2          | 0005 | email@email.com 

both rows has same groupid as data attribute for the <tr>

if i search for "bb" i want the parent row to show as well
if i search for "0004" i want the sub/child row to show as well

how can i do that?

**Comment by steveush** [comment]
Hi,

It looks like some of your text got cut off but if I'm understanding you correctly there's no built in functionality to accomplish this. You would need to override some of the default methods and implement you own custom lookup for associated rows. Something like the below is what I would do:

```javascript
(function($, F){

	// Extend the Row object with a new property called groupId by overriding the define method
	F.Row.extend("define", function(dataOrElement){
		// call the original method
		this._super(dataOrElement);

		// check if the row was supplied as an object and check if it has options
		var isObj = F.is.hash(dataOrElement),
			hasOptions = isObj && F.is.hash(dataOrElement.options) && F.is.hash(dataOrElement.value);

		// get the groupId from either the element data or if supplied from the options.
		this.groupId = F.is.jq(this.$el) ? this.$el.data("groupid") : (hasOptions && dataOrElement.options.groupid ? dataOrElement.options.groupid : null);
	});

	// Extend the Filtering component to handle the new groupId property on the rows 
	F.Filtering.extend("predraw", function(){
		// if we have no filters just exit
		if (F.is.emptyArray(this.filters))
			return;

		var self = this;
		// first find all the rows that match the filters
		var filtered = $.grep(self.ft.rows.array, function(r){
			return r.filtered(self.filters);
		});
		// then get an array of groupId's from the filtered rows
		var groups = $.map(filtered, function(r){
			return r.groupId;
		});
		// finally get all rows that belong to the matched groups or exist in the filtered array
		self.ft.rows.array = $.grep(self.ft.rows.array, function(r){
			return !!($.inArray(r.groupId, groups) !== -1 || $.inArray(r, filtered) !== -1);
		});
	});

})(jQuery, FooTable);
```

The above assumes your rows contain a `data-groupid` attribute which is what I think was cut off previously, e.g.:

```html
<tr data-groupid="1">
	<td>1</td>
	<td>Dennise</td>
	<td>Fuhrman</td>
	<td>High School History Teacher</td>
	<td>November 8th 2011</td>
	<td>July 25th 1960</td>
</tr>
```

Thanks

EDIT: Forgot to add that you would need to include the above code snippet in your page after you have included the FooTable files but before you initialize the plugin.

**Comment by yonihbc** [comment]
can you give some explanation to the code because it might be partial to what i need.

**Comment by steveush** [comment]
Hi,

Can you tell me what you need explained? My explanation is in the code comments which outlines basically what each line does.

Thanks

**Comment by yonihbc** [comment]
i will try to work with it and write back if needed

is it possible to call that code as function at specific pages?

**Comment by steveush** [comment]
Could you explain a bit further and give me some context on what you are trying to do? I'm not 100% sure I understand what you're asking for. If you want this functionality on only a few specific pages then only include the script on those pages. If you want to call this specific code as a function what are you wanting the function to return/do?
