### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined     at footable.js:139

### ISSUE THREAD

**Issue by Genna17ruos** [fooplugins/FooTable#607]
I downloaded the version without bootstrap.
I tried to create tables that have no header row (basic examples).
I have create a page html with this code: 
...
<script type="text/javascript" src="js/footable.js"></script>
...
<link rel="stylesheet" href="css/footable.standalone.css" rel="stylesheet" type="text/css">
...
<body>
<div class="example">
...
<table class="table">
	<tr>
		<td data-title="ID" data-breakpoints="xs">1</td>
		<td>Dennise</td>
		<td>Fuhrman</td>
		<td data-title="Job Title" data-breakpoints="xs">High School History Teacher</td>
		<td data-title="Started On" data-breakpoints="xs sm">November 8th 2011</td>
		<td data-title="Date of Birth" data-breakpoints="xs sm md">July 25th 1960</td>
	</tr>
...

but I have this error : Uncaught ReferenceError: jQuery is not defined     at footable.js:139

Can you help me?

**Comment by jeffconklin** [comment]
Hello,

It sounds like you are not including JQuery on on your page, or are not including it before the footable.js file is referenced within your HTML.  For example:

- Please view the source of: http://fooplugins.github.io/FooTable/index.html
- Just above the closing HTML tag, you will see jquery.min.js is included before the footable.js file.

If you include footable.js before jquery.min.js, or do not include jquery.min.js at all, Footable will not function.
