### ISSUE TITLE
Footable and remember last search

### ISSUE THREAD

**Issue by yonihbc** [fooplugins/FooTable#608]
Hi,

If the user type something in the search box.
than in the table he click on the row to go edit that row.
when he gets back to the table. i need the filter to reapply.

is that possible?

**Comment by yonihbc** [comment]
I have found this and modified it
is that the right way?

var filtering = FooTable.get('table').use(FooTable.Filtering), // get the filtering component for the table
		filter = "home"; // get the value to filter by
	if (filter === 'none'){ // if the value is "none" remove the filter
		filtering.removeFilter('status');
	} else { // otherwise add/update the filter.
		filtering.addFilter('search',filter);
	}
	filtering.filter();

i will run it on window.load and if cookie has value i will filter by that

any better idea?

**Comment by steveush** [comment]
Hi,

You should be able to just enable the [state component](http://fooplugins.github.io/FooTable/docs/components/state.html) for the plugin. You can do so using the below:

```javascript
$(".table").footable({
	state: {
		enabled: true
	}
});
```

Thanks
