### ISSUE TITLE
Expandable Columns Only Showing First and Last

### ISSUE THREAD

**Issue by leaguecrawler** [fooplugins/FooTable#610]
Hello - I am having trouble getting started using this module.  I have installed the 7.2 version from the Drupal site, enabled it and am trying to use it on an existing view instead of the regular Table view I was using.  My problem is I cannot get the expansion settings to work.  I have watched every video I can find and read as much as I can and everything is pointing to the module having a drop down selection to pick the Expandable Column.  The only selection mine has is "First" and "Last".  Any help is greatly appreciated!

![footable](https://cloud.githubusercontent.com/assets/26130377/23492279/7420ae90-fed1-11e6-8e77-22b13e91cee0.png)

**Comment by steveush** [comment]
Hi,

Unfortunately I'm not sure which module you're talking about as I have not made any specifically for Drupal, I've never seen the screen displayed in your attachment so this was created by another developer.

That said the options available in the drop down do seem correct, you can only select to display the toggle for expanding rows in either the first or last visible column of a table.

Thanks
