### ISSUE TITLE
Footable with jQuery v3.1.1

### ISSUE THREAD

**Issue by demorales13** [fooplugins/FooTable#611]
When I have tried to run footable with jQuery v3.1.1 dont work, it only works with version v2.2.4, Is there an incompatibility with the latest version of jQuery?

**Comment by steveush** [comment]
Hi,

I've just tested now and everything seems to work as expected using 3.1.1. If you are using Bootstrap 3.3.6 or lower it will throw an error warning jQuery 3+ is not supported however updating to Bootstrap 3.3.7 resolves that issue.

Thanks

**Comment by demorales13** [comment]
Please, take a look to this project.

Thanks in advance.

[js-err.zip](https://github.com/fooplugins/FooTable/files/829284/js-err.zip)

**Comment by steveush** [comment]
Hi @demorales13.

The issue here is that in your app.js you are calling `ft.rows.load()` before the plugin is initialized which is then leading to the error being thrown as a breakpoint has not yet been set. I'm not sure if you intend to use the `find()` function anywhere else but to resolve the issue I simply moved the logic within FooTable's ready callback to avoid any errors. I changed your `StoreController` implementation starting on line 21 of the app.js file to the following and everything seems to work as expected (I left in the old code but it's just commented out).

```javascript
function StoreController($scope, $timeout, $uibModal, DataService, $window) {

	$scope.title = "Usuarios";
	$scope.collection = [];

	var ft = FooTable.init('.table', {
		columns: [{
			name: 'id',
			title: 'Id'
		}, {
			name: 'firstName',
			title: 'Nombre'
		}, {
			name: 'jobTitle',
			title: 'Trabajo',
		}, {
			name: 'something',
			title: 'Identificación',
			breakpoints: 'xs'
		}, {
			name: 'started',
			title: 'Fecha',
			breakpoints: 'xs'
		}, {
			name: 'status',
			title: 'Estado',
			breakpoints: 'all'
		}]
	}, function(){
		DataService.get()
			.then(function (response) {
				$scope.collection = response;
				ft.rows.load($scope.collection);
				$timeout(function () {
					$scope.showTable = true
				}, 300);
			})
	});
	
	//find = function() {
	//    DataService.get()
	//        .then(function (response) {
	//            $scope.collection = response;
	//            ft.rows.load($scope.collection);
	//            $timeout(function () {
	//                $scope.showTable = true
	//            }, 300);
	//        })
	//}
	//
	//find();
	
}
```

Thanks

**Comment by steveush** [comment]
Hi @demorales13, further testing with your example seems to show there is some issue with the Editing component and jQuery 3+. I'll be looking into it today to see what's gone wrong there.

EDIT: Scrap that, I just realized you don't provide callbacks for the editing so it's not doing anything ;) Everything in the Editing component seems to be fine.

**Comment by demorales13** [comment]
Hi steveush, thanks a lot for your support.

I need to use the find function after editing and creating new items, for that reason I have it after the initialization. I will try to call the find function where you move it and tell you how it goes.

Yes, the editing component is not implemented, the project I did to show you the jQuery error :D ... If you change the version of jQuery by 2.4.4 it works fine.

**Comment by demorales13** [comment]
Works fine, thanks again.
