### ISSUE TITLE
redraw table after successful ajax call

### ISSUE THREAD

**Issue by anasred** [fooplugins/FooTable#612]
I'm not using the built in Editing component. I'm inserting custom button to each row and using data-* bootstrap to get the record id to do edit or delete action.

my code is look like this:

```javascript
$('#delete').click(function(){
    $.ajax({
	type: "delete",
	url: "/contact/" + id,
	data: { 'id': id},
	success: function(message){
		modal.modal('hide');
	},
	error: function(){
		alert("Error");
	}
    });
});
```

deleting the record is working fine, but how should I delete the current row from page DOM.

I tried this
```javascript
$('#contacts').footable(); //the table id is 'contacts'
```
but it reloads the table again with the deleted row record!

**Comment by steveush** [comment]
Hi @anasred,

Are you using the single main footable.min.js file or are you including each component separately? The reason I ask is that while you are not using the built in editing component it does add useful methods to various objects within the plugin like `FooTable.Row#delete( bool redraw )` so including it is recommended even if building your own UI.

That said I would just like to point out a possible issue in your above code that you may have missed, your selector for the button `"#delete"` implies that every row has a button with an ID of `delete` which may lead to issues. Rather use jQuery's event delegation and bind a single handler to the `<table>` element and then provide a class selector that matches your button, as seen in the following:

```javascript
$("#contacts").on("click", ".delete-btn", function(e){
	e.preventDefault();
	var row = FooTable.getRow(this);
	if (row instanceof FooTable.Row){
		row.delete(true);
	}
});
```

And then your delete button in each row would look something like:

```html
<button type="button" class="delete-btn">Delete</button>
```

Thanks

EDIT: I just wanted to add that after using just the above code the table should redraw itself minus the deleted row so there is no need to perform an additional call to `$('#contacts').footable()`.

**Comment by anasred** [comment]
oops my bad. there is a part from code missing. But any way I really thank you for your patience and explicit reply.

now the complete code look like this. and it worked like a charm ;)


```javascript
                //the table id is contacts
                //when click on the button with delete-btn class it will show the modal directly using bootstrap data-toggle="modal" and data-target="#delete" 
		$("#contacts").on("click", ".delete-btn", function(event){
			var row = FooTable.getRow(this);
                        
                       //call bootstrap event to handle the data-id attribute
			$('#delete').on('show.bs.modal', function (event) {
				var button = $(event.relatedTarget);
				var id = button.data('id');
				$("button#delete").click(function(){
					$.ajax({
						type: "delete",
						url: "/contact/" + id,
						data: { 'id': id},
						success: function(message){
							if (row instanceof FooTable.Row){
								row.delete(true);
							}
							$('#delete').modal('hide');
						},
						error: function(){
							alert("Error")
						}
					});
				});
			});
		});
```

the button that firing the modal
```html
<button type="button" class="btn btn-danger delete-btn" data-toggle="modal" data-target="#delete" data-id="2">Delete</button>

```

After firing the modal there will be another DELETE button to confirm the deletion process which has the id of "delete"

You're awesome

**Comment by anasred** [comment]
btw, i'm using the main footable.min.js which holds all core code and components code as well.

**Comment by steveush** [comment]
Glad to hear it's all working for you ;) I'll close the issue then.

**Comment by peter-brennan** [comment]
Hi, i'm hoping this thread is still being watched. I have added checkboxes to the rows and I am trying to create a multiple delete function. 

If I select a single checkbox and click the delete button it removes that row correctly, but my problem is as soon as I select more than 1 checkbox (row) and then click the delete button it wipes out the whole table. It removes the whole table from the DOM.

Im not getting any errors on the console.

```
$(document).on("click", ".trigger-bulk-action", function() {
    
    $(".select-row:checked").each(function() {

	var tr = $(this).closest("tr");
	var row = FooTable.getRow(tr);

	if (row instanceof FooTable.Row) {
	    row.delete();
	}

    });

});
```
