### ISSUE TITLE
How to bind with static actions like buttons, dropdowns, inputs with FooTable V3?

### ISSUE THREAD

**Issue by claudchan** [fooplugins/FooTable#613]
Hi,
Someone can guide how to solve this?

[how-to-bind-with-static-actions-like-buttons-dropdowns-inputs-with-footable-v3](http://stackoverflow.com/questions/42692281/how-to-bind-with-static-actions-like-buttons-dropdowns-inputs-with-footable-v3)

--
FooTable V3 comes with pagination, filtering and sorting controls within it self. I have "Custom dropdown" and "Custom search" that required but out of the FooTable controls. I am new to FooTable V3. Can someone guide me how to bind it. Here is my test demo:

[jsfiddle](https://jsfiddle.net/claudchan/gup20y3v/2/)

Thanks in advance!

**Comment by steveush** [comment]
Hi,

Please take a look at the [updated version of your jsfiddle](https://jsfiddle.net/gup20y3v/4/). It shows the basics of how to use the plugin API to sort and filter the table.

Thanks

**Comment by claudchan** [comment]
Thanks @steveush ,
This helps a lot!
