### ISSUE TITLE
Attributes (Id, title, data- and etc.)

### ISSUE THREAD

**Issue by poulnike** [fooplugins/FooTable#617]
Hi, @steveush.

Initially, I had a need to make a tooltip (http://getbootstrap.com/javascript/#tooltips) on the column header `<th>`. For convenience, since often the name of the column is shortened. To do this, I need to arrange the attributes. Even to make a simple "title" you need an attribute. Or, for example, the formatter for `<th>`

Then, I realized that it would be useful to have the id of the row `<tr>`, since the data in row can change and it is useful to know what it the row in init. And to have exact access to row from outside the table.

Perhaps I overlooked something and there are such opportunities?

**Comment by steveush** [comment]
Hi @poulnike,

There are no default options to allow this behavior but it is quite simple to quickly add into the plugin.

To be able to add attributes to a column header `<th>` you need to override the `FooTable.Column#$create` method which creates the `<th>` for each column and then use FooTable's ready callback to initialize them. Here is an example adding in the tooltips:

```javascript
(function($, F){

	// Extend the Columns $create method to add attributes for tooltips.
	F.Column.extend("$create", function(){
		// call the original method
		this._super();
		// then do what you need to do with the tooltip attributes
		this.$el.attr({
			"title": this.title,
			"data-toggle": "tooltip",
			"data-placement": "top"
		});
	});

})(jQuery, FooTable);

jQuery(function($) {
	// use the ready callback of FooTable to initialize the tooltips
	$(".table").footable({ /* options */ }, function (ft) {
		ft.$el.find('[data-toggle="tooltip"]').tooltip();
	});
});
```

That said there is an issue using this approach, Bootstraps tooltips are inserted into the DOM directly after the hovered element. This causes layout issues within a table as it inserts a `<div>` which is then treated like another `<th>` in some browsers like Chrome. This then forces all the remaining column headers to be pushed over by one making them not line up with there actual values. This is not an issue with FooTable but just a general layout issue between Bootstraps tooltips and tables.

The second request to add a row ID to each `<tr>` can be accomplished in a similar way by overriding the `FooTable.Row#$create` method and adding in your attributes as required. This assumes the ID you are wanting to add to each row was supplied with the rest of your column data.

```javascript
(function($, F){

	// Extend the Row.$create method to add an id attribute to each <tr>.
	F.Row.extend("$create", function(){
		// call the original method
		this._super();
		// get the current row values
		var values = this.val();
		// then add whatever attributes are required
		this.$el.attr("id", values["your-id-column-name"]);
	});

})(jQuery, FooTable);
```

The other way to access a row externally is using the `FooTable.getRow` method. This method takes a jQuery object, selector or a HTMLElement that is either the `<tr>` itself or one of its children and returns you the `FooTable.Row` object associated with it. Using that object you can then get the cell values by calling `.val()`. For example given a basic table as seen below:

```html
<table id="my-table">
	<thead>
		<tr>
			<th data-name="id" data-type="number">ID</th>
			<th data-name="name">Name</th>
			<th data-name="custom_html">Custom HTML</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>steveush</td>
			<td>
				<button class="some-button">Some Button</button>
			</td>
		</tr>
		<tr>
			<td>2</td>
			<td>poulnike</td>
			<td>
				<button class="some-button">Some Button</button>
			</td>
		</tr>
	</tbody>
</table>
```

You could do something like the below to get the first rows value:

```javascript
var row = FooTable.getRow("#my-table tbody tr:nth-child(1)");
var value = row.val();
console.log(value); // => {"id":1,"name":"steveush","custom_html":/*The jQuery object containing the cell contents.*/}
```

But as I stated previously the `FooTable.getRow` method also accepts any of the rows child elements as well. This makes binding custom event handlers where you need access to the row object nice and easy. For example the `.some-button` in each of our rows can have it's `click` event bound like below:

```javascript
$("#my-table").on("click", ".some-button", function(e){
	e.preventDefault();
	var row = FooTable.getRow(this); // 'this' is the actual <button> element
	var value = row.val();
});
```

Thanks

**Comment by poulnike** [comment]
Hi @steveush 
Many thanks. A lot of useful except answers to my questions.
