### ISSUE TITLE
How to access all the rows of table and send it back to server?

### ISSUE THREAD

**Issue by prashant-pokhriyal** [fooplugins/FooTable#618]
Hi, @steveush 

I'm using footable with modal. So when user add a row into the table using modal I'm just populating it on the table.  And there is a submit button which sends all the table data to server. I'm not able to find a way how to access all the rows  in json format and send it back to server

**Comment by steveush** [comment]
Hi,

You should be able to use something like the below:

```javascript
var ft = FooTable.get("#my-table"),
	rows = [];
	
$.each(ft.rows.all, function(i, row){
	rows.push(row.val());
});

/*
rows == [{
	id: 1,
	...
},{
	id: 2,
	...
}];
*/
```

Thanks

**Comment by prashant-pokhriyal** [comment]
wow! Thank you so much @steveush. This solution saved a hell lot of line of codes.

**Comment by prashant-pokhriyal** [comment]
@steveush Just one more issue. `row.val()` contains one more field **editing**. For now I'm deleting that field. Is there any way that row.val() only contain user defined field and not internal ones.

**Comment by jai-singhal** [comment]
hey @steveush, I am not able to send the rows data back to the server via ajax. Is this is making JSON object? When I try to print the data, it is printing the empty string. Please help me out.
