### ISSUE TITLE
Append HTML ements to  cells

### ISSUE THREAD

**Issue by ErnstSchiener** [fooplugins/FooTable#619]
I simply want to add some jQuery elements to a cell. Within the init.ft.rows event I have the following code:

"init.ft.rows": function(e, ft, rows) {

	FooTable.arr.each(rows, function(row, index) {

		FooTable.arr.each(row.cells, function(cell, index) {

			if (cell.column.name == 'plant') {

				var $cell = $(cell);

				$cell.css('color', 'red');
				$cell.append('<div>Test</div>');
			}
		});
	});
}

Changing the CSS and making the cell red works, butt appending the div-element does not work. Do I have to redraw the table? What is the correct place to do some kind of changes. I can't use the formatter function because I need other row values and within formatter I don't have access to that values.

Regards
Ernst

**Comment by steveush** [comment]
Hi Ernst,

If you grab the files you need from the [compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled) on the develop branch the `formatter` function is now supplied 3 parameters; `value`, `options` and `rowData`. The first two parameters have always been available, the first being the cell value and the second being the current options for the plugin. The new third parameter is pretty much what you said you needed, a plain JavaScript object containing the cell values for the entire row.

As for changing the color of a particular column you can use either plain CSS and the `nth-child(n)` selector:

```javascript
.table tr th:nth-child(3),
.table tr td:nth-child(3) {
	background-color: red;
}
```

Or use the column [classes](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-classes) or [style](http://fooplugins.github.io/FooTable/docs/getting-started.html#column-style) options to apply CSS to all cells in a column.

Thanks

**Comment by ErnstSchiener** [comment]
Thank you four your quick reply. It helped me a lot but does NOT solve my problem at all. In my FooTable I want to insert a slider via the follopwing code within every row:

        <div id="mySlider" class="dragdealer">
            <div class="handle red-bar">
                <span class="value"></span>%
            </div>
        </div>

I can do this in the formatter function. But the slider is a jQuery plugin and I have to initialize it via:

        new Dragdealer('mySlider');

The width of the slider handle depends on some row data, e.g. start and end. Also each slider must have a unique id, so I want to use:

        $('mySlider').uniqueId();

The problem is that I can't find the right place of initializing the slider. Where do I have to put?

        $('mySlider').uniqueId();
        new Dragdealer('mySlider');

When I drag the slider the according update function of the slider has to modify the current row data and write it back to the server.

Please can you help me?

Regards
Ernst

**Comment by ErnstSchiener** [comment]
To complete my question. How do I recognize when the table has completely drawn. I suppose that my issue has to deal with asynchronous Ajax-calls. The only thing I need is an event when the table is ready to manipulate the DOM tree.

Regards

**Comment by steveush** [comment]
Hi @ErnstSchiener,

I've tried for the better part of the day today to get the Dragdealer plugin working with FooTable. Unfortunately the sliders lose all state whenever the DOM element or one of it's parents is attached/reattached. FooTable does this extensively as it adds/removes rows from the DOM and recreates the cell contents if it is ever required (normally this is only done once). Dragdealer requires its' `reflow` method to be called after every DOM operation and it can only be called once the slider element is actually in the page and visible.

While I can get it sort of working it is not working well, not well enough that I would use it in production for anything. I would not suggest using this plugin with FooTable at the moment.

Thanks
