### ISSUE TITLE
Change the background color for a particular row

### ISSUE THREAD

**Issue by faisalshah1** [fooplugins/FooTable#620]
Hello,
Hope you are doing well.

I am using ft.loadrows  function to get the rows dynamically, I need to change the background color of particular rows, Can you please guide me

**Comment by poulnike** [comment]
@faisalshah1 
Perhaps this issue will help you #617

**Comment by steveush** [comment]
Hi @faisalshah1,

Please also take a look at the [row classes option](http://fooplugins.github.io/FooTable/docs/getting-started.html#row-classes). Basically instead of supplying a row like the following:

```javascript
{
  "id": 1,
  "name": "Steve"
}
```

You would supply it like the below:

```javascript
{
  "options": {
    "classes": "some-css-class"
  },
  "value": {
    "id": 1,
    "name": "Steve"
  }
}
```

Thanks
