### ISSUE TITLE
Where's the master branch?

### ISSUE THREAD

**Issue by jasonkarns** [fooplugins/FooTable#622]
Quite difficult for contributors to figure out what's going on with the branches when there's no master branch.

**Comment by steveush** [comment]
Hi @jasonkarns,

As per the [readme section for contributors](https://github.com/fooplugins/FooTable#contributors), "Pull requests need to be made against the develop branch as a new feature."

Regard develop as the master that you make changes to and submit. The V3 branch only contains the latest version, no development work.

Thanks

**Comment by jasonkarns** [comment]
Cool. That's obviously your prerogative. I'll just point out the workflow for a contributor for documentation, so you realize the cost of this decision...

1. notice typos/mistakes in documentation on http://fooplugins.github.io/FooTable/docs/getting-started.html
2. cmd+click github icon to get to source on github in new tab
3. paste typo string into search box to find where it is in the docs
4. select first search result, confirm result is the intended mistake
5. scroll to top to switch from sha to master branch (because github search results jump to the exact sha, not a branch head)
6. see a branch selector that doesn't include master:
![image](https://cloud.githubusercontent.com/assets/119972/24011628/b45bf97a-0a51-11e7-87a2-fec7abaeafd7.png)

7. open this issue noting that this repo violates git and github convention

As a drive by user and contributor aiming to help with documentation _as it is encountered_, any amount of friction makes the effort not worthwhile. Frequent contributors that are actually cloning, building and running tests will more likely (but still not completely) read the readme to get up to speed on each repo's idiosyncrasies. Drive-bys that are submitting patches solely through github UI most certainly will not.

(FWIW, it's pretty trivial to follow github flow and still follow git/github convention. Name git-flow's `develop` branch as `master` and git-flow's `master` branch as `release` or `stable`. Everyone wins and you lower barrier to contributions.)
