### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by poulnike** [fooplugins/FooTable#629]
Hi.
I saw that the search had the opportunity to take it to the right block.
"Added a new container option to the filtering component."

How can I do the same for the paging component?

I want to do a scrolling of the table, fixing the first column, but then it will move and `<tfoot>`

**Comment by steveush** [comment]
Hi @poulnike,

This is something I want to build into the paging component by default so you can move it where ever you like. It's the main reason I haven't pushed the new version yet, I just haven't had time to do it the past few weeks. The basic idea would be the same as the changes made to the filtering component in [this commit](https://github.com/fooplugins/FooTable/commit/9de734f05d35b30a55c879496b783779ca525aec). But obviously adapted for the paging component where necessary.

Thanks

**Comment by poulnike** [comment]
@steveush 
Yeah, it would be great.

**Comment by steveush** [comment]
@poulnike, working on it at the moment so hopefully will have a working version today that I can test out and release the new version over the weekend.

Thanks

**Comment by steveush** [comment]
@poulnike the above commit adds in the functionality as discussed, you can now use the `container` option to provide a CSS selector and the plugin will render the paging UI in the first matched element. As per usual this can be supplied through JS options:

```javascript
$(".table").footable({
	paging: {
		container: "#my-selector"
	}
});
```

Or via data attributes on the `<table/>`:

```html
<table class="table" data-paging-container="#my-selector">
	...
</table>
```

Please give it a go and let me know if you find any issues, so far it seems to work in the tests I've done my side.

Thanks

**Comment by poulnike** [comment]
@steveush 
Super.
Working. Errors have not yet noticed
