### ISSUE TITLE
Negative numbers don't work

### ISSUE THREAD

**Issue by wrodie** [fooplugins/FooTable#630]
If you define a column with a data-type of number then some of the numbers are negative, it strips off the '-' sign.

I think this is to do with the 
this.cleanRegex = new RegExp('[^0-9' + F.str.escapeRegExp(this.decimalSeparator) + ']', 'g');

where it only allows 0-9 as valid characters.
It should allow '-' and '+' as well

**Comment by steveush** [comment]
Hi,

Please take a look at issue #621.

Thanks
