### ISSUE TITLE
Formater function of all column

### ISSUE THREAD

**Issue by poulnike** [fooplugins/FooTable#631]
Hi @steveush.

This not work if table static? Only if load json?

> Updated the .formatter() function of all column types to now accept three parameters; value, options and rowData.

**Comment by steveush** [comment]
Hey @poulnike, it should work for both.

Thanks

**Comment by poulnike** [comment]
Hi @steveush.
```
function formatter (value, options, row){
    console.log(row);
}
```
undefined

if load data from json it work

**Comment by steveush** [comment]
Hi @poulnike,

Sorry for the delay, been extremely busy these past couple of weeks. I finally got around to testing this morning and I can't replicate what you're seeing, in every case I get the full `rowData` object back. If you are using the individual components did you update all of them to the new versions in the develop branch? This is the only thing I can think of for why it's not working as expected.

Thanks

**Comment by poulnike** [comment]
hi @steveush.
Thanks for the answer
Maybe I'm confused in the versions. Now once again I downloaded the plug-in from the development branch and it all worked.

**Comment by steveush** [comment]
@poulnike, glad to hear it, I thought I may have over looked something. Also I plan on releasing the new version this weekend some time so hopefully the confusion between live and develop will go away shortly ;)
