### ISSUE TITLE
Do not hide all raw. Possible?

### ISSUE THREAD

**Issue by CCvinc** [fooplugins/FooTable#632]
Hello,
First of all : thank you for this nice "Footable". I installed it in my website.

I only have one question : it is possible to do not hide all raw? I mean to keep some "hidden" raw displayed.

**Example :** 
1/
![capturqsdqsde3 copie](https://cloud.githubusercontent.com/assets/25612636/24361186/8af0f73c-1309-11e7-8d35-5cb1e4d88f74.jpg)

2/
![captuqsdqsdre2](https://cloud.githubusercontent.com/assets/25612636/24361255/b6c4b3a8-1309-11e7-9fb6-5263cbadbd89.png)

On this example 2 columns are always displayed in raw. If the user clicks on "+" the 2 other columns are displayed in raw

Thank you.

Best regards,
Vincent.

**Comment by steveush** [comment]
Hi @CCvinc,

I'm not 100% sure I know what you are asking for here, I think it was lost in translation :) If you could give me a bit more details to try help me understand what you are wanting to do that would be great.

Thanks

**Comment by CCvinc** [comment]
hello steveush,
I'm gonna try to explain again :
Footable is responsive. So,
if the window is big, all columns can be displayed in the table.
If the window is small, some columns become hidden rows and a "+" button appear (allowing to display hidden rows).

What i'm looking for is : to do not hide all rows. Be able to display at least 1 or 2 rows. And then the "+" button allow the user to display all rows (like on my first image example).

Do you better understand?

Best regards,
Vincent.

**Comment by steveush** [comment]
Ah OK, now I understand what you are asking for, unfortunately this is not possible at the moment with how the hidden row details are created. They exist purely in a single `tr` element which is then appended or removed from the DOM when the user clicks the +. To do what you ask would require the details row to always be appended and then clicking the + shows/hides certain columns within that details row. Sorry but the plugin does not have an option or an easy way to cater for this, it would require rewriting a lot of the `FooTable.Row` objects methods to cater for it.

Thanks
