### ISSUE TITLE
`No results` in search when any characters after _ or @

### ISSUE THREAD

**Issue by dehnli** [fooplugins/FooTable#633]
What can be the reason such search behaviour and what should I check to get proper results?

![footable-search-issue](https://cloud.githubusercontent.com/assets/14199981/24491892/5d5f07fe-153a-11e7-8ae8-eb49b2ea1e34.png)

Search returns `No results` if string looks like `ywyavlq@hebraica.eu`.
Though `ywyavlq@` gives results. The same with `@hebraica.eu` - no results. `@hebraica` gives results.

![footable-search-issue2](https://cloud.githubusercontent.com/assets/14199981/24491898/6246494e-153a-11e7-9311-182724d25c99.png)

**Comment by steveush** [comment]
Hi,

Please try setting the filtering components [connectors option](http://fooplugins.github.io/FooTable/docs/components/filtering.html#connectors) to false.

Thanks

**Comment by dehnli** [comment]
@steveush thanks for prompt reply. It works now as expected
