### ISSUE TITLE
Footables does not sort columns of URL properly despite data-type = html being set

### ISSUE THREAD

**Issue by wakatara** [fooplugins/FooTable#635]
I'm looking at Footables as a replacement for dataTables at the moment for a project I am updating. Kinda lurving it. However, I've run into a problem which I'm not sure how to resolve. I have a number of rendered html links in in the table. When I go to sort these, even with html set as the data-type on the header-column, the sorting appears to be following the URL which is set by species_id.

```
eg.  <td class='list-column'><a href="/admin/species/show/5662">Ambystoma laterale</a></td>
```

which sorts incorrectly, at least when paged. My assumption is it is sorting by the href of the URL, rather than by the text within the URL (ie. Ambrystoma laterale) while most people are after having the alphabetical name of the species sorted in descencing or ascending order. 

I looked in the Github issues on the project for this one and googled a bit, but did not seem to find an easy way around this, so just thought I'd ask directly. 

let me know if there is an easy fix on this, and I'm just being dense.

thanks!

**Comment by poulnike** [comment]
hi @wakatara 

```
<th data-sort-value="Ambystoma laterale">
   <a href="/admin/species/show/5662">Ambystoma laterale</a>
</th>
```
http://fooplugins.github.io/FooTable/docs/components/sorting.html

**Comment by steveush** [comment]
Hi @wakatara,

Apart from @poulnike's response which will work, the HTML column type also supports the option `sortUse` which can be supplied a value of either `"html"` (the default) or `"text"`. I think setting this value to `"text"` will work in your case. You can either set it using a data attribute on the TH itself `data-sort-use="text"` or by supplying it as one of the columns options:

```javascript
$(".table").footable({
	columns: [{
		type: "html",
		sortUse: "text",
		...
	}]
});
```

Thanks
