### ISSUE TITLE
filter.addFilter documentation error

### ISSUE THREAD

**Issue by raytri** [fooplugins/FooTable#636]
There is a documentation error in your JSDocs that cost me a fair bit of time.

I was trying to build a checkbox-based filter, using your "Custom Filter UI" as a starting point:
https://fooplugins.github.io/FooTable/docs/examples/advanced/custom-filter-ui.html

Specifically, I was looking at this line of code:
`filtering.addFilter('status', filter, ['status']);`

I built a space-separated query string, and then needed to change the "space" parameter from "AND" to "OR".

Here is the JSDocs page on that object:
https://fooplugins.github.io/FooTable/docs/jsdocs/FooTable.Filter.html

According to that page, the order of parameters is this:
`filter(filtername,query,columns,space,connectors,ignoreCase,hidden)`

But my query wasn't working. A whole bunch of troubleshooting later, it turns out the problem is that the real order of parameters is this:
`filter(filtername,query,columns,ignoreCase,connectors,space,hidden)`

Please update your JSDocs to reflect the actual order of the parameters in cases like this.

**Comment by steveush** [comment]
Hi,

Sorry about that. At the moment I'm not happy with the JSDocs at all, I couldn't find a template I liked so I spent some time [writing my own](https://github.com/steveush/foodoc) which I intend to use on this project however I have not had the time to bring it across. When I do bring it across I'll be going through and updating all code comments in the entire project.

That said I'll rerun the JSDocs to make sure everything is up to date. I think the current JSDocs are a version behind what is actually available.

Thanks

**Comment by raytri** [comment]
Thanks! I figured there was a lot of leftover housekeeping from the switch to V3 and ongoing development.
