### ISSUE TITLE
How do I get rid of the search column selector button on the filter?

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#639]
Hi. I don't need the little drop down in the search/filter bar at the top of the table. So far I have been able to hide the pop out that lets you select which columns to search with this CSS override:

.footable-filtering .dropdown-menu {
	display:none;
}

But I'm not sure how to get rid of the actual button that you can click on to get the pop out because it appears to be using the bootstrap button css and if I override it, it will override all my buttons using that code unless I'm missing something in the CSS for the filter....

Thanks.

**Comment by poulnike** [comment]
@ThreeWest 
If I understand correctly
```
.form-group.footable-filtering-search .input-group-btn {
    display: none;
}
```

**Comment by ThreeWest** [comment]
Thanks @poulnike  It does remove the drop down button but also the search button but the search box still works. Now I think I might be able to find what to look for and override to have one button hidden but not the other. Thanks again. :D

**Comment by ThreeWest** [comment]
Update: I have done why I needed by creating this CSS:

.bhide {
    display: none;
}

Then just adding it to the class list like so in the footable.filtering.js file.

$dropdown_toggle = $('<button/>', {type: 'button', 'class': 'btn btn-default dropdown-toggle bhide'})

**Comment by poulnike** [comment]
@ThreeWest 
Why is it so difficult?
```
.footable-filtering-search .btn.dropdown-toggle {
    display: none;
}
```
