### ISSUE TITLE
How to dynamically cancel ' data-sorting="true" ' setting in js

### ISSUE THREAD

**Issue by hzhaohenry** [fooplugins/FooTable#642]
My initial code as following:

`<table data-sorting="true">
    code
</table>`

it supports sorting for all columns, but I want to cancel sorting function after I click a button.

I try like this:

$("#element id").attr('data-sorting', "false");
$("#element id").footable();

but it does not worked for me.

Can anyone help me ?

Thanks,
Henry

**Comment by poulnike** [comment]
@hzhaohenry 

http://fooplugins.github.io/FooTable/docs/components/sorting.html

```
$("#element id").footable({
	"sorting": {
		"enabled": false
	}
});
```
or
```
<table data-sorting="false">
	...
</table>
```

**Comment by steveush** [comment]
Hi,

You should be able to disable sorting using something like the below, `#toggle-sort` is the ID of the button and `#your-table` is the ID of the table you want to toggle sorting on.

```javascript
$("#toggle-sort").on("click", function(e){
	e.preventDefault();
	var sorting = FooTable.get("#your-table").use(FooTable.Sorting);
	sorting.toggleAllowed();
});
```

Thanks
