### ISSUE TITLE
Bootstrap JS Question

### ISSUE THREAD

**Issue by ghost** [fooplugins/FooTable#645]
Hey! Quick question here:
Is the js collected in the `releases/footable-bootstrap.latest.zip` the same as the compiled js in `compiled/footable.js`?

Thanks for all your hard work!

**Comment by steveush** [comment]
Hi,

Yes, it is. The compiled folder simply has all the files used in each of the 3 packages; Bootstrap, Stand Alone and Component. The ZIP's are the bundled files for each version so you don't have to mix and match yourself.

Thanks

**Comment by ghost** [comment]
Got it, thanks!
