### ISSUE TITLE
Reject filter matches both reject and soft reject actions

### ISSUE THREAD

**Issue by dehnli** [fooplugins/FooTable#648]
What could be done to exclude such search behaviour and get only `reject` results but not both ` reject` and `soft reject `?

![footable-filter-issue](https://cloud.githubusercontent.com/assets/14199981/25483031/347f7472-2b65-11e7-8bbd-7d9ba456bcd7.png)

**Comment by poulnike** [comment]
@dehnli 
http://fooplugins.github.io/FooTable/docs/components/filtering.html
Queries
