### ISSUE TITLE
FooTable Data vanishes after a row expanded, Why is that?

### ISSUE THREAD

**Issue by dinukshi** [fooplugins/FooTable#650]
My code works fine in asp.net web forms, but once added to a asp.net mvc application, hidden data only displaced once. When i expand again data is gone. Can this be solve? 

    <div class="row">
    <div class="col-md-12 col-lg-12 col-xs-12">
        <div class="panel-body">
            <table id="table2" class="table"></table>
        </div>
    </div>
</div> 

 
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/3.1.4/footable.min.js"></script>

    <script type="text/javascript">

    $('#table1').footable({ 
        "expandFirst": true,
        "columns": [{
            "name": "id",
            "visible": false
        },
          {
              "name": "firstName",
              "title": "First Name"
          },
          {
              "name": "lastName",
              "title": "Last Name"
          },
          {
              "name": "jobTitle",
              "title": "Job Title",
              "breakpoints": "xs"
          },
          {
              "name": "started",
              "title": "Started On",
              "breakpoints": "all"
          },
          {
              "name": "dob",
              "title": "Date of Birth",
              "breakpoints": "all"
          }
        ],
        "rows": [
            {
                "id": 1,
                "firstName": "Dennise",
                "lastName": "Fuhrman",
                "jobTitle": "High School History Teacher",
                "started": "November 8th 2011",
                "dob": "July 25th 1960"
            },
            {
                "id": 2,
                "firstName": "Maxh",
                "lastName": "Fuhrman",
                "jobTitle": "High School History Teacher",
                "started": "November 8th 2011",
                "dob": "July 25th 1960"
            }
        ]
    });
     </script>

**Comment by steveush** [comment]
This has been resolved in the 3.1.5 version.
