### ISSUE TITLE
single components for table collapse only

### ISSUE THREAD

**Issue by neuropass** [fooplugins/FooTable#652]
Hi,

what would I need to use the collapse functionality only?
will shows +/- icon to collapse the row etc.

is that the footable.core.js only?

**Comment by steveush** [comment]
Hi,

Sorry, for the long delay. I know you must have figured it out already but just for anyone searching this in the future. Yes, you should just need the `footable.core.js` file and then either the `footable.core.bootstrap.css` or `footable.core.standalone.css` files depending on the version you are including.

Thanks
