### ISSUE TITLE
Footable Sorting : the foo icon is displayed near to next column heading 

### ISSUE THREAD

**Issue by sjosh13** [fooplugins/FooTable#655]
While using footable sorting, the sorting icon is visible near to next column instead of the column which it is suppose to sort. Can someone help?

**Comment by jeffconklin** [comment]
I agree, the sorting icons being displayed on the right is rather confusing. When hovering, the icon is "ok". But once you click or if you define sort direction onload, the icon showing up on the right certainly looks like it is for the wrong column altogether...
![20170508-whichcol](https://cloud.githubusercontent.com/assets/6152325/25821641/ecf7b75c-3403-11e7-94ee-18fccc62679b.png)

Within my CSS I override the default behavior with the following:

`td.footable-sortable > span.fooicon, th.footable-sortable > span.fooicon {
  right: auto !important;
  padding-left: 5px;
}`

I do wish there was a cleaner solution already available in FT. If anyone knows one, please share.

Edit: Added padding-left: 5px; to the code above

**Comment by sjosh13** [comment]
Hey Jeff Thank you very much... It worked for me :)
