### ISSUE TITLE
How to add link inside a cell with param that is described in another cell

### ISSUE THREAD

**Issue by jpranskaitis** [fooplugins/FooTable#656]
Need to build a table with links with same href in all cells. With formatter im able to form a link in the cell that has the value, but in other cells not able to do that.

Is there a way of accessing rows from the formatter function so link can be added to all cels ?

**Comment by poulnike** [comment]
only in develop branch

`Updated the .formatter() function of all column types to now accept three parameters; value, options and rowData. value and options have always been available, the new addition is the rowData parameter which is an object containing the current rows' parsed values, the properties of this object match `
