### ISSUE TITLE
How to add html elements to the rows?

### ISSUE THREAD

**Issue by prashant-pokhriyal** [fooplugins/FooTable#657]
@barchard 
I want to add a checkbox to every row of the footable so that user can select it and after selecting I should be able to parse the selected one. How to achieve this functionality using footable

**Comment by poulnike** [comment]
formatter function
http://fooplugins.github.io/FooTable/docs/getting-started.html#column-formatter

**Comment by prashant-pokhriyal** [comment]
@poulnike 
Thank You for quick response. Now I'm able to create checkbox to each row. But how will I get to know which row user selected. And I'm also having a global checkbox which is going to select  or deselect all checkbox.
How will I achieve this global checkbox functionality. And I'm also using pagination from server so If new data is loading it's checkbox should be selected if user selects global search.

**Comment by poulnike** [comment]
@prashant-pokhriyal 
It's difficult for me to suggest something so I do not know the logic. What happens when a user selects a row? It will be some form? etc.

And I did not use the ability to load rows, so I can not help with the pages.

**Comment by prashant-pokhriyal** [comment]
This comment helped me --> https://github.com/fooplugins/FooTable/issues/503#issue-171827462
