### ISSUE TITLE
Table resizes to tablet instead of phone when first loaded

### ISSUE THREAD

**Issue by lilith712** [fooplugins/FooTable#66]
Hi,

first of all I want to thank you for the amazing plug-in. It makes like much easier!

Yesterday I bumped into an issue and I cannot figure put how to solve it. I have a responsive template based on bootstrap and the page is divided in 3 columns. In the second and third column I have 2 tables. When I first load the page, the first table resizes (to phone breakpoint) but the second doesn't. 
I have tried to solve the issue with css, as I thought that the reason why this happens is that the first field of the table is filled with urls (so not short text). But if I resize the page and put it back as it was, the plug-in behaves perfectly and the table is phone-size. Do you know what it could be?
I have inverted the two tables but it's still that one causing trouble. The plug-in detects it as tablet-size (table footable footable-loaded tablet) and not phone.

Thanks a lot!
Elisa

**Comment by bradvin** [comment]
Hi Elisa - do you have a public URL? Or can you create a jsfiddle or codepen duplicating your problem so I can check it out?

**Comment by lilith712** [comment]
Hi, thanks for your quick reply.

Unfortunately I don't have it online as it is a jsp webapp and we are working locally.

I have created a jsfiddle but there the footable doesn't work at all.
The link is http://jsfiddle.net/4RpE8/4/
In my page the column 2 works perfectly, while column 3 gets to tablet-size instead of phone.

**Comment by lilith712** [comment]
Sorry, stupid me. I didn't add the jquery call to start footable. Here you have the correct link to look at.
http://jsfiddle.net/4RpE8/6/
in jsfiddle it works, but not in my page.
(Although the breakpoint when resising the window in jsfiddle as a bit different - Here you have the linnk to the screenshot I took https://docs.google.com/file/d/0Bzf6gZm6FES0WDAxSVZ6LWk0cjQ/edit )

**Comment by bradvin** [comment]
check out http://jsfiddle.net/4RpE8/7/

I had to override the footable function for calculating widths by looking at the table's parent width

The data in the table was causing it to act weirdly

**Comment by lilith712** [comment]
hi, thanks a lot! that is great!
