### ISSUE TITLE
Footable Editing and Sorting : Delete and Sorting Icons not visible in Firefox

### ISSUE THREAD

**Issue by sjosh13** [fooplugins/FooTable#660]
While working on footables in Firefox I am facing following issues with the sorting and editing components:
1. Sorting : Sorting Icons are not visible. instead a box appears
2. Editing : Delete Icon on each row is not visible. Only a box is visible.

Everything works fine in IE and Chrome. But fails in Firefox.
Can someone help me?

**Comment by steveush** [comment]
Hi,

I've just checked the demo pages now and everything seems correct and the icons are displaying in Firefox. Have you checked the console for any errors? Only thing I can think of is that the font file is being blocked due to some issue like a CORS error or something.

Thanks
