### ISSUE TITLE
Filtering with multiple values

### ISSUE THREAD

**Issue by jheyjheyjhey** [fooplugins/FooTable#664]
Hello, 

Is it possible to filter a row containing multiple values? Like for instance, I have this row containing multiple values:

_`<td class="category" style="display: none;">,4,5,6,9</td>`_

I also have a list of checkboxes. If the checked value exists in the row data, it must be on the result after the filter. I hope I explained it enough for anyone to understand.

I am currently upgrading from FooTable v2 to v3  when I encountered this problem.

Thanks!

**Comment by steveush** [comment]
Hi,

Sorry for the late response I've been busy on another project lately and have not had as much time as I would like to devote to FooTable. Please take a look at the bottom of the Filtering Component page, specifically at the [Queries section](http://fooplugins.github.io/FooTable/docs/components/filtering.html#queries). You can specify `AND` and `OR` queries plus a few more. If you have a selection of checkboxes then you would just need to concatenate the values together with the correct operator separating them.

Thanks
