### ISSUE TITLE
Memory Leak - FooTable.Table.destroy()

### ISSUE THREAD

**Issue by BlueWater86** [fooplugins/FooTable#665]
Reinitializing the footable plugin causes memory to leak. This is very noticeable on large data sets inside SPAs.

Reinitialising is needed to change the columns provided to FooTable... user chooses a different set of data within the SPA.

Calling FooTable.Table.destroy() inside the init method does not decrease the memory footprint that was created by FooTable.Rows.load(). As a workaround, calling FooTable.Rows.load([]) will cause garbage collection on detached DOM elements.

Suggest cleaning up detached elements on FooTable.Table.destroy().

https://jsfiddle.net/a2fzuy62/33/

**Comment by steveush** [comment]
Hi,

Thanks for this, I'll implement it in the develop branch and push it out with the next release once I get a chance to sit down and work on FooTable again.

Thanks
