### ISSUE TITLE
Show/Hide columns 

### ISSUE THREAD

**Issue by publicischris** [fooplugins/FooTable#667]
Hi,

is it possible to show/hide columns after the table is loaded? My idea is that the user can choose what column he or she want to see. 

Thank you in advance,
Chris

**Comment by steveush** [comment]
Hi,

Sorry for the late response I've been busy on another project the last couple of months and we are in the final push stage so I've been devoting all my time to that at the moment. As for you request it is possible, you can simply set the `visible` property of a column to `false` and then call the `draw` method of the table.

As an example you can open up the docs page here http://fooplugins.github.io/FooTable/ and then open the developer console and execute the following two commands to hide the ID column.

```javascript
FooTable.get(".table").columns.get("id").visible = false;
FooTable.get(".table").draw();
```

If you were to use this in a button click event to toggle the visibility of the ID column you could write it something like:

```javascript
$(".toggle-id-column").on("click", function(e){
	e.preventDefault();
	var ft = FooTable.get(".table"), idColumn = ft.columns.get("id");
	idColumn.visible = !idColumn.visible;
	ft.draw();
});
```

Thanks
