### ISSUE TITLE
Edit Row when Expanded = Empty Values in Expanded section.

### ISSUE THREAD

**Issue by AppliedEllipsis** [fooplugins/FooTable#668]
If you perform an update on a row, while it's expanded, the resulting expanded row will be have empty values.
If you perform an update on a row, while it's NOT expanded, the resulting expanded row will be filled with the correct info.
Expanding/Shrinking does not fix it.

>                     if (editing_row instanceof FooTable.Row){
>                         editing_row.val(values);
>                     } else {
>                         ft.rows.add(values);
>                     }

The original data is populated via JSON.

Bug can be duplicated using:
`http://fooplugins.github.io/FooTable/docs/examples/component/editing.html`
Scaling your browser so it hides columns and you have to click to expand. (responsive editor ctrl+shift+m, 768×1024)
Hit edit rows.
Have the row you want to edit expanded and click edit, just press submit, it will have empty values in the expanded area.

**Comment by higujral** [comment]
+1

**Comment by higujral** [comment]
@AppliedEllipsis Did you find any workaround for this issue?

**Comment by steveush** [comment]
Hi,

Please can you try the develop branch version. Simply grab the files you need from the [compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled) and let me know if that resolves your issue.

Thanks

**Comment by AppliedEllipsis** [comment]
Hey steveush,
The development branch files solved the problem.

**Comment by steveush** [comment]
Hi,

The new 3.1.5 version contains the fix for this issue.

Thanks
