### ISSUE TITLE
Sorting Date Columns

### ISSUE THREAD

**Issue by ashwinkumarvarma** [fooplugins/FooTable#67]
Hello,

Can I sort Date Columns using Footable sortable plugin?

It doesn't work for me. Any suggestions ?

![DateSortIssue Footable](https://f.cloud.github.com/assets/4245656/419982/1e9aba22-ace3-11e2-897c-4e95a8b09900.JPG)

Date Column
cells[2].Attributes.Add("data-type", "numeric");
cells[2].Attributes.Add("data-sort-initial", "true")

**Comment by bradvin** [comment]
when using dates your need to supply the date's timestamp value in the data-value attribute

From the demo : 

&lt;td data-value=&quot;303892481155&quot;&gt;19 Aug 1979&lt;/td&gt;

**Comment by ashwinkumarvarma** [comment]
Thanks bradvin. It works now. Footable is really great !! It's probably the best responsive grid I have come across recently

**Comment by bradvin** [comment]
glad you like it - spread the word :)

**Comment by raghuveerweb** [comment]
Hi Bradvin,

Once I keep the time stamp date sort is working by clicking on the header but  data-sort-initial="true" is not working. Can you help me with this

Thanks in Advance

**Comment by gilcrespo** [comment]
@raghuveerweb  Have you tried using data-sorted="true" ?
