### ISSUE TITLE
row.val() function does not update footableDetailRow values

### ISSUE THREAD

**Issue by higujral** [fooplugins/FooTable#670]
When updating data in a row using row.val({}) function, it empties the data inside column marked with footableDetailRow instead of updating it. Columns other than footable detail row get updated properly.

**Comment by steveush** [comment]
Hi,

Please can you try the develop branch version. Simply grab the files you need from the [compiled folder](https://github.com/fooplugins/FooTable/tree/develop/compiled) and let me know if that resolves your issue.

Thanks

**Comment by higujral** [comment]
Hi Steven,

The issue seems to be resolved in the develop branch version. When can we get the release version of this ? Thanks for looking into the issue.

Thanks.

**Comment by steveush** [comment]
Hi,

Version 3.1.5 is now released which includes the fix for this issue.

Thanks
