### ISSUE TITLE
How to use Scroller instead of Pagination

### ISSUE THREAD

**Issue by jai-singhal** [fooplugins/FooTable#674]
Hi,
I am using footable for my project, and In my project, I need footable for adding, editing, deleting, for few table rows only (6-12). So I need the footable, of fixed height and width, and a scroller which can scroll the table rows when data is exceeded by a limit.

```
var my_row = []
$(document).ready(function(){
jQuery(function($){
	var $modal = $('#editor-modal'),
		$editor = $('#editor'),
		$editorTitle = $('#editor-title'),
		ft = FooTable.init('#table', {
			columns: my_col,
			rows:  my_row,	
			editing: {
                                     ...
                                     ...
				},
				editRow: function(row){
					...
                                        ...
				},
				deleteRow: function(row){
                                         ...
				}
			},
		}), //end of ft
      })
})
```

I am initializing footable which is shown above.
And I thankful to all the developers who made this amazing thing for free, this is surely a better alternative to DataTable.
Please help as soon as possible

**Comment by steveush** [comment]
Hi,

Sorry for the delay in response but this is not possible out of the box and any solution would need to be custom created.

With FooTable we wanted to avoid scrollbars all together as having a scrolling table within a scrolling page often translates to a strange user experience. Instead we provided pagination, filtering, sorting and the ability to hide less important columns at various breakpoints allowing you to display only what's really required. Now these may not be the specific features you are using FooTable for but they are the core of what FooTable is and scrolling is not something I will be implementing into the base plugin unless there is an overwhelming demand for it.

Thanks

**Comment by jai-singhal** [comment]
Thanks for the reply.

It's okay for me to use this plugin with the pagination but is it possible to make this of fixed height. In the times when the rows are empty, and when I try to add rows to it, its height grows and when I delete it's height shrinks if the number of the rows is less than the limit of pagination size.
I want this to be of fixed size. If the rows are empty, it may show the empty rows. Is there is any way to do this?
