### ISSUE TITLE
Predetermined filtering?

### ISSUE THREAD

**Issue by angeliquejw** [fooplugins/FooTable#68]
I'm using FooTable (awesome, btw!) with a site I'm creating and would like to know if it's possible to create links (e.g., http://domain.com/mytable.html?search=query ) that prepopulate the filter input and present pre-filtered tables to my visitors. I've tried a few ways of passing the search/filter term from the URL to the input box provided by the filtering plugin, but none have worked yet.

**Comment by bradvin** [comment]
This is something I want to add - the easiest way would be to raise an event on the table and pass the filter you want to the footable, e.g.:

$footable.raise('footable_filter', 'filter text here');

I will add this soon and let you know

**Comment by angeliquejw** [comment]
That's outstanding. Thanks so much for the head's up, Brad.

**Comment by CoolLinuxGuy** [comment]
Brad, have you added this ability yet to footable?
We need to be able to set a particular filter based on the <select> options, after the page loads, similar to this:

<script>
window.onload = showSelection;
function showSelection()
    {
    $footable.raise('footable_filter', 'filter text here');
    }
</script>

Any help here would be great.

**Comment by CoolLinuxGuy** [comment]
oops, in my above post, it stripped my sample javascript code :|
