### ISSUE TITLE
How to get data in a column?

### ISSUE THREAD

**Issue by under-project** [fooplugins/FooTable#681]
Please help me, i want to get the value of a column. But I can not find a way yet.
Can anyone help me?

**Comment by steveush** [comment]
Hi,

When you say get a value of a column to you want all cell values for that entire column or just a single specific cell value from a single row?

Thanks

**Comment by NashBridgesAT** [comment]
as far as i have found out, you can do following:

```
var ft = FooTable.get("#selector");
$.each(ft.rows.all, function(i, row){
//get all row values by row.val() or
//access a specific colmn by row.value.columnname and
//do some code
//and write it back to update the table by
// row.val(newvalues);
	});
```
I am not sure if this is the right way, i found it in stackoverflow, but for me another problem occurs, see #710

**Comment by ivandjava** [comment]
Thanks all

**Comment by under-project** [comment]
Thanks all
