### ISSUE TITLE
Footable Pagination: Is there any way to change number of records per page

### ISSUE THREAD

**Issue by sjosh13** [fooplugins/FooTable#683]
I need to add control to allow user chnage number of records displayed on each page. Is there any way to achieve that?

**Comment by steveush** [comment]
Hi,

I think you want this - http://fooplugins.github.io/FooTable/docs/examples/advanced/change-pagesize.html.

Thanks

**Comment by sjosh13** [comment]
Thank you steve.. It worked for me :)

**Comment by Shubhamnandwana18** [comment]
Hi @steveush ,
I am using foo-table with angular.
* FooTable - Awesome Responsive Tables
 * Version : 2.0.3
But I am unable to add - 'Change no of records' control. While using - http://fooplugins.github.io/FooTable/docs/examples/advanced/change-pagesize.html.
I am receiving an error that FooTable is not defined.
What is the way to add such controls in older versions?
