### ISSUE TITLE
Export?

### ISSUE THREAD

**Issue by MikhailKlemin** [fooplugins/FooTable#684]
Hi, if there a way to add at last simple export to CSV feature?  I tried various plugins but they export whole table regardless of filters/sorting which was quite expecting honestly...

**Comment by steveush** [comment]
Hi,

I've made some changes locally that I'll check in today that will expose two new methods on the `FooTable.Table` class; `.toJSON()` and `.toCSV()`. Both of these methods accept only a single parameter called `filtered` which determines whether or not to exclude filtered rows from the result, it defaults to `false` so you would want to pass in `true` instead to achieve what you want.

As an example it could be used like the below:

```javascript
var csv = FooTable.get("#table").toCSV(true);
```

Thanks
