### ISSUE TITLE
prototype undefined error

### ISSUE THREAD

**Issue by sandip-darwade** [fooplugins/FooTable#687]
footable.js:7331 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at footable.js:7331
    at footable.js:7345

In js file i found this one

**Comment by steveush** [comment]
Hi,

Thanks for pointing this out. This was definitely a bug and was caused by the new export component as the  DateColumn was not being created if Moment.js was not included in the page. I've released a new version 3.1.6 containing just a fix for this as it was critical.

Thanks

**Comment by carcus88** [comment]
@steveush The stand alone latest version linked from the website still includes 3.1.5

**Comment by HaRii66666** [comment]
@steveush The bootstrap version from the website is also on 3.1.5

**Comment by Alaa84kh** [comment]
Simply replace function in line 7331:
```javascript
// override the base method for DateColumns
F.DateColumn.prototype.stringify = function (value, options, rowData) {
    return F.is.object(value) && F.is.boolean(value._isAMomentObject) && value.isValid() ? value.format(this.formatString) : '';
};
```
with this code:
```javascript
// override the base method for DateColumns
if (F.DateColumn != undefined) {
    F.DateColumn.prototype.stringify = function (value, options, rowData) {
        return F.is.object(value) && F.is.boolean(value._isAMomentObject) && value.isValid() ? value.format(this.formatString) : '';
    };
}
```

**Comment by nfriend21** [comment]
I get this error right out of the box, with the standalone version, and with moment.js installed.

**Comment by rodrigokiller** [comment]
I dont get it. The stantalone is not beeing updated?

**Comment by mranisz** [comment]
You have to download version 3.1.6 directly from github page:
https://github.com/fooplugins/FooTable/releases/tag/3.1.6

**Comment by rodrigokiller** [comment]
Thank you.
