### ISSUE TITLE
Initialise the table on click event

### ISSUE THREAD

**Issue by lilith712** [fooplugins/FooTable#69]
Hi,

I cannot find a way to initialise my table on click event. I load an external file into a div with jquery load function and after that, I would like to initialise the table. Any suggestions?

The function is

$('.loadData').click(function() {
    $('#loadedData').load('example.htm);
    $('#loadedData .footable').footable();
});

and the table .footable is in example.htm.

Thanks
Elisa

**Comment by bradvin** [comment]
use the load function's complete callback:

$('.loadData').click(function() {
$('#loadedData').load('example.htm', function() {
    $('#loadedData .footable').footable();
});
});
