### ISSUE TITLE
Reinitialize Pagination

### ISSUE THREAD

**Issue by Tekanewa** [fooplugins/FooTable#70]
Hi, I'm trying to combine this plugin with with <a href="https://github.com/rbayliss/Dropdown-Table-Filter" target="_blank">Dropdown-Table-Filter</a> and while the filtering works, it breaks the pagination. Is there a way to reinitialize the pagination of footable?

**Comment by alonextou** [comment]
Yes, this is currently in issue

**Comment by bradvin** [comment]
in the V2 branch, if you trigger the footable_setup_paging event it will redo the paging:

$('table').trigger('footable_setup_paging');

**Comment by shubhi-gupta** [comment]
Hi brad, I have tried using 'footable_setup_paging' to reinitialize the pagination as I need to change the data-page-size dynamically as per user selection and then do the ajax call. But its not working for me. Even I am not able to find where you have defined the above mentioned event. Can you please add some demo for the same ??

**Comment by Sushil-Dhiver** [comment]
Hi Bradvin, I tried triggering the footable_setup_paging event but still it doesnt work. I am setting the page size dynamically based on the screen resolution. i even tried triggering a redraw but it doesn't work.
