### ISSUE TITLE
Cannot search for items with a hyphen

### ISSUE THREAD

**Issue by ericlangeDH** [fooplugins/FooTable#737]
If there is a text cell that contains a hyphen, e.g. "my-searchable-item", using the search box to find "my-searchable-item" will yield no results.

**Comment by nightmode** [comment]
You might want to try setting the "connectors" option to false since it defaults to true.

```
$('.table').footable({
    "filtering": {
        "connectors": false
    }
});
```

More into at http://fooplugins.github.io/FooTable/docs/components/filtering.html#connectors

**Comment by ericlangeDH** [comment]
@ForestMist Thanks.  That works!
