### ISSUE TITLE
Hiding columns and expanding a row to show hidden columns doesn't seem to be working in Google Chrome

### ISSUE THREAD

**Issue by brettboylen** [fooplugins/FooTable#74]
Example: http://www.boyleninc.com/pv/camps/camps_table.php

Log in with the user: dualfragment 
(no password required as this system will be going into a separate codebase that already has auth)

It works fine in IE/Firefox but in Chrome it does not hide the headers with data-hide="default" and does not work when data-class="expand" is set, either.  Again, this bug is only in Chrome.

**Comment by bradvin** [comment]
you are using the data-hide="default" but I think you should be using data-hide="all" so those columns are always hidden on all screen sizes.

**Comment by brettboylen** [comment]
hah, thank you.  I think this shows my ignorance when it comes to jquery and such.  It is really odd however that it worked fine in IE/Firefox but Chrome didn't like the default.

Very sorry for wasting your time on this and appreciate that tip that fixed it.

**Comment by bradvin** [comment]
cool :) Your demo actually revealed a bug in the footable code that I had not noticed before. I will making some changes shortly to fix it. 

thanks
