### ISSUE TITLE
Search/filter plugin for footable (jquery plugin) doesn't expand a result if the searched data is in the hidden portion

### ISSUE THREAD

**Issue by brettboylen** [fooplugins/FooTable#75]
If you have data hidden but it shows within the expandable section set when you click the + after setting a column with data-class="expand", and then search via the filter for text that appears only within the hidden columns, it does not auto-expand them.

Example: I have a hidden column and one of the rows has the text "example" in that hidden column.  These hidden columns only show on rows if you click the + to expand.  Now, if I search for "example" in the filter box, the single row is correctly returned, but it does not auto-expand as it should, since the text is inside a hidden field.  

If necessary, I can submit two screenshots showing the issue.

**Comment by bradvin** [comment]
The filtering does not auto-expand the row-detail when the search string is found within a hidden column. This functionality was never built in, and I do not think it should be built in, as this is a requirement for your specific project. 

Please don't get me wrong, I am not saying it is not useful in this instance, but I think this should be done with custom coding for your project.

You can bind to the "footable_filtered" event and expand the rows

**Comment by brettboylen** [comment]
My apologies if I sound like I'm demanding features here.  I'm a PHP developer and my jQuery experience is limited.  I just thought this may be a feature that some others would find useful as an option.  

Thanks for the response.  I'll see if my go-to jQuery guy knows the best way to do this.
