### ISSUE TITLE
Issue with search button face

### ISSUE THREAD

**Issue by matthewdu92** [fooplugins/FooTable#750]
Hi

Can you help me fixing this issue ?
The seauch button has not the face it should have
I use  bootstrap css

Thanks a lot 

<img width="116" alt="capture d ecran 2017-11-25 a 18 05 31" src="https://user-images.githubusercontent.com/33986156/33232767-fa1b213e-d20b-11e7-81f2-1489f999c36e.png">

**Comment by vnoris** [comment]
Same problem...
Is it a version conflict ?

I'm using bootstrap 3.3.7 + jquery 3.2.1

Many thanks in advance !
Regards,
Vnorsi

**Comment by vnoris** [comment]
Hello matthewdu92,
I had the same issue and checked my html code with online validator ...

My `<!DOCTYPE html>` was misspelled...

Now everything is ok...

I hope this will help ....

Best regards !
vnoris

**Comment by matthewdu92** [comment]
Hi vnoris
Did not get : what was misspelled ??

Thanks a lot !

Mathieu

**Comment by vnoris** [comment]
Are you French ?

**Comment by matthewdu92** [comment]
Oui, vous aussi ?

**Comment by vnoris** [comment]
Non mais francophone en tout cas, ca sera plus facile... 
Je ne suis pas développeur mais j'ai eu le même problème...
j'ai cherché partout dans mon code ... et je ne comprenais pas pq cela fonctionnait dans un petit fichier test  mais pas sur mon projet de site...
J'ai repassé mon html et j'avais simplement fait une erreur dans mon DOCTYPE...
en html5 il doit être de la forme `<!DOCTYPE html>` ... si tu ne commences pas avec ca ta page, footable déconne... pas le reste mais le plugin le vit assez mal....

ta page commence bien par un DOCTYPE valide ?

BàT,
Vnoris

**Comment by matthewdu92** [comment]
Bravo ! c’etait bien cela !

Merci beaucoup ! ☺

**Comment by vnoris** [comment]
Nickel ... Tu peux passer le Ticket à Closed/Solved...
