### ISSUE TITLE
Javascript Accion in  hidden column

### ISSUE THREAD

**Issue by carlinchisart** [fooplugins/FooTable#76]
Hi all,

I have to implemente a javascript accion in a colum that i have hidden, i put the javascript code but when the colum is hiden (default) an try to use the javascript functionality the javascript no work.

If i put the colum visible, the javascript code work perfect. 

example:

$(document).ready(function(){

```
 $('#lista_productos').footable();
 $("[data-toggle=popover]").popover().click(function(e) {
    e.stopPropagation();
    e.preventDefault();
    alert('click');
  });
});
```

i have one colum call "acciones" if i put visible the colum the alert('click') work, and the popover function work, but if i hiden the colum for example with data-hide="default,phone,tablet" the javascript no work.

I don't know if is posible, ejecute javascript code?

**Comment by bradvin** [comment]
You should rather use delegation to bind your events. Footable "clones" the cell contents into the detail row, so the events are not carried across with the elements. We looked at doing an actual jQuery clone, but it was a messy affair. The best way to bind events is by using the .on function. Take a look at the demo https://github.com/bradvin/FooTable/blob/master/demo-events.htm

**Comment by carlinchisart** [comment]
Thanks!!!! and sorry for the question.
