### ISSUE TITLE
Move demo files into subfolder

### ISSUE THREAD

**Issue by dboune** [fooplugins/FooTable#77]
A suggestion from the field.

Move the demo files into a subfolder of their own. This will help those who need to use a build process or repackage.

In my case, my build process alerts me to new files, causing me to need to go take a look and let my build system know what to do with them. If the demo files were in a single folder, it would be easy to just toss out or ignore that entire folder during the build process.

Thanks! :)

**Comment by bradvin** [comment]
@dboune I agree completely! Check out the V2 branch - where there is now a demos folder - and all demo related js and css files have been moved in there - much cleaner

The V2 branch will be merged into master soon, after some more testing has been done

**Comment by dboune** [comment]
Ha! I completely missed that. That's what I get for being in a hurry. :)
