### ISSUE TITLE
Add package manager project definitions

### ISSUE THREAD

**Issue by dboune** [fooplugins/FooTable#78]
Suggestion to add package manager project definitions.

NPM
https://npmjs.org/doc/json.html

Bower
http://bower.io/

There is another called Component, which I admit to never having used. 
https://github.com/component/component

If I can find a bit more time later I'll file a PR for NPM and Bower at least.

Thanks!

**Comment by bradvin** [comment]
@dboune great suggestion. I have never used these tools before, so if you could help me out that would be great. I reckon make these changes in V2 branch

**Comment by dboune** [comment]
I've added several of these in a fork, but haven't tested them yet. I'm especially iffy about the component.js. Once I do I'll submit a PR. If you see anything glaring, let me know.

For NPM
dboune@e55d56db6a88e4a996e1fd990fc462ab4ebf9348

For Bower
dboune@fb4749f391ecc36945e0029b60f59c48d30617e0

For Composer (Primarily a PHP package tool, but can do pretty much anything)
dboune@ca822e5a06da4b12158a88e72b612b5cc9255141

For Component
dboune@186a7acaa1338421460b04824421c2ff7c1d98e9

**Comment by bradvin** [comment]
@dboune thanks for these Damian - I also need to gett the travis CI builds working - have you done something similar before?

**Comment by seriema** [comment]
I can get Travis to work if we use GruntJS for building the JS. I've done that for other projects, like [Raphaël](https://github.com/DmitryBaranovskiy/raphael).

**Comment by bradvin** [comment]
@seriema that would be great! If you can help me to get this working I would really appreciate it. I tried to set it up using grunt a couple days ago, but it kept failing. I am new to grunt and node etc so this is all a learning curve for me :)

**Comment by seriema** [comment]
Cool! I have a team-dinner tonight but I'll have a look at it tomorrow then.

**Comment by dboune** [comment]
@bradvin no problem! I'm glad @seriema spoke up. I've never set up travis myself.

I've added a basic grunt configuration and added/updated the needed files. The jshint task fails for the moment which is something to be dealt with in the source files, but the uglify task completes. I haven't tested the resulting minified files.

dboune@99fd5a88f4085c089e7f8dc4dc8a2fe8fcd6a033

Also found a stray comma at the end of package.json.

To test all this check out the dboune@package-managers branch and run the following commands from the project root (this assumes you already have npm installed)

```
npm install
grunt
```

npm will download all the dev dependencies into the `node_modules` folder, which I've added to .gitignore. You will then see all of the errors/warnings from jshint after running `grunt`.

If you want to just test uglify alone use `grunt uglify`. This will create a dist folder and place the minified files there. I've added the dist folder to .gitignore.

To remove the dist folder, use `grunt clean`. Normally this would be done automatically prior to the uglify task, just after a successful run of jshint.

You can also use `grunt watch` to get notifications from jshint each time you save a source file, including the Gruntfile.js.

There is quite a bit more work to be done here, but this may help get it rolling.

**Comment by seriema** [comment]
Sorry got struck with a stomach bug. I wasn't able to Fork @dboune code, but since he already included Grunt then the only thing left is to add this to `package.json`:
    "scripts": {
        "test": "grunt test"
    },
or whatever `grunt xxx` command you want to run.

Basically Travis-CI runs `npm test` so all you need to do is support that command.

**Comment by dboune** [comment]
@seriema, just curious, why weren't you able to fork?

I will gladly add that right now.

Since qunit or similar is not set up here, it could be a dummy target for test, or it could run jshint. The code would need some cleanup for jshint, but at least then travis would report something useful for the moment?

**Comment by seriema** [comment]
@dboune I think it's because I already forked this project, and GitHub (at least through the web interface and client app) don't allow multiple forks.

I had created a separate task `grunt test` that just runs jshint. I think it's fine for it to fail on the initial commit. Red-green-refactor ;)

**Comment by dboune** [comment]
Oh I see.. I guess you would have to instead bring it in another way, like adding a remote to your local. So, something like this:

```
git remote add dboune https://github.com/dboune/FooTable.git
git checkout dboune package-managers
... make your changes, and commit ...
git push origin package-managers
```

I've added the grunt test task which will run jshint.

**Comment by dboune** [comment]
@bradvin let me know if you would like me to make this a PR.

**Comment by bradvin** [comment]
@dboune @seriema thanks for the help with this. @steveush was telling me that to pass jshint, footable would need a rewrite, so if the CI build just checks to make sure the code compiles and can run without errors, that is all I want for the time being

@dboune please make a PR

**Comment by dboune** [comment]
@bradvin I believe that in order to do any testing something like qunit would need to be used. At least, I am unaware of any way to tell grunt or travis to test the ability to compile/run otherwise.

I will add the PR, and then commits can be added to it to support qunit, or fix the jshint errors, or however you want to solve getting travis to work.

As far as passing jshint, there are a number of changes that need to be made, but I wouldn't consider it a rewrite. A fairly wide distribution of changes, I admit, but nothing that should break anything.

Just for interest, here is a list of the errors jshint throws. All very easily fixable. I would be willing to smash these out for progress.

Expected '{' and instead saw 'groups'.
  This just means that one should never do if (test) do_something();

Instead do:

```
if (test) {
  do_something();
}
```

Expected '!==' and instead saw '!='.
  This means that the != test may have unintended side effects. Instead use !== so that javascript can't do strange string things to the values being tested.

Unnecessary semicolon.
  No big deal.. just doesn't need to be there.

Missing radix parameter.
  Yeah, well, fair enough, it can lead to confusion otherwise.

A constructor name should start with an uppercase letter.
  Sure.. it's a convention that should probably be followed. Minor refactor.

'ec' is defined but never used.
  Ok. Add it back if it ever needs to be used.

Mixed spaces and tabs.
  Easy fix. Spaces tend to be the preference these days for most stuff. Just need to pick one way and stick to it.

**Comment by bradvin** [comment]
@dboune cool I think we make these changes in the V2 branch

**Comment by seriema** [comment]
You can configure jshint so that it doesn't warn on the stuff you fail, so you start with a passing jshint test. =) Incrementally you can turn things on and fix them.

**Comment by seriema** [comment]
I think we can close this now?

**Comment by vs0uz4** [comment]
This project is included in npm? If so on what name?
