### ISSUE TITLE
Table display change notification needs a standardized convention

### ISSUE THREAD

**Issue by dboune** [fooplugins/FooTable#79]
I put together a little plugin for zebra row formatting (odd/even class needed for <= IE8), but there is no event raised for page changes from footable.paginate.

Adding the following to footable.paginate worked nicely, but thinking about this also brought up a larger issue. Every plugin that needs to perform an action after the visible data has changed would need to track events for every plugin it wishes to be compatible with.

``` javascript
ft.raise('footable_page_changed', { currentPage : info.currentPage });
```

I think that instead of each plugin defining it's own event there needs to be a standardized event, or some other way, to inform interested plugins that the data or visible data has changed.

``` javascript
ft.raise('footable_display_changed', { plugin : p.name, data : { foo : bar }});
```

Or something with a similar generic effect.

**Comment by dboune** [comment]
The same thing could also be said for a notification that changes are about to begin.

**Comment by bradvin** [comment]
I have added better events to paging, sorting and filtering events in the V2 branch

But I really like this idea of creating a single event name and passing in the "action" ( I propose action, as a single plugin might have multiple actions)

something like:

<code>ft.raise('footable_changing', { action : 'sort', data : { foo : bar }});</code>

and for after-the-fact:

<code>ft.raise('footable_changed', { action : 'sort', data : { foo : bar }});</code>

**Comment by dboune** [comment]
Sounds good to me!

For the purpose of consistency, it might be helpful to standardize "data" being passed as `{ data: { foo : bar }` in all events. This way you could always expect data (whatever it is) to be in the data 'bucket'. Obviously this is just a documentation issue, since anything can be put into the event data and will not be parsed by `ft.raise`.

`ft.raise(event [,{description}])`

```
event
Type: String
A string containing the event name to be raised

description
Type: PlainObject
A set of key/value pairs that describe the event. All elements are optional.
See below for a list of standard keys.

    action
    Type: string
    A string providing an action name. For use with generic events like 'footable_changed'.

    data
    Type: PlainObject
    A set of arbitrary key/value pairs to be passed to event listeners.
```
