### ISSUE TITLE
Filtering: How to disable the dropdown menu?

### ISSUE THREAD

**Issue by leonirlopes** [fooplugins/FooTable#791]
I did not find in https://fooplugins.github.io/FooTable/docs/components/filtering.html how to disable this.

![image](https://user-images.githubusercontent.com/1014419/39051641-a857a58e-447f-11e8-8c5b-260a221a9e8a.png)

Can I hide or disable it?

**Comment by vladciulley** [comment]
I guess you should hide it with CSS. At least this is what the docs recommend if you want to build your own custom filters UI: https://fooplugins.github.io/FooTable/docs/examples/advanced/custom-filter-ui.html
