### ISSUE TITLE
Integration Plugin for Responsive DataTables.net

### ISSUE THREAD

**Issue by oller** [fooplugins/FooTable#8]
Hi guys, a great resource you're putting together here.

I've a project, which relies heavily on the great datatables.net and from initial playing around, FooTable isn't far away from seemlessly integrating into it.

If I've time I'll try and write the plugin to this, but figure I should share my thoughts if I'm unable to to.

On each draw of the datatable, you need to re-initialise footable:

``` javascript
$('.dataTable').dataTable( {
   "fnDrawCallback": function() {
        $('.dataTable').footable();
    }
});
```

The only problem I've found is cells moving all over the place when sorting a column using the datatables sort, once footable has hit a breakpoint and started hiding columns.

JSFiddle :  http://jsfiddle.net/pxDb6/1/

The gist of the plugin I'd be looking to create would be to try and use the dataTables function `fnSetColumnVis()` on the fooTable breakpoint snapping event to hide the columns, so the sort should then behave.

http://www.datatables.net/release-datatables/examples/api/show_hide.html

How does that sound to you guys?  Shall post these thoughts over at DataTables too....

**Comment by bradvin** [comment]
what parts of datatables.net do you rely on? We actually built footable to replace datatables.net on a couple of smaller projects we were working on, but we realise that there are certain things we have not done yet in FooTable. 

So.... let's build a few add-ons to get it there :)

Having said that - there are a few things that we believe should only be done on the server side. For example, loading of the data and also pagination.

**Comment by mscdex** [comment]
FWIW I managed to get the two working without rendering bugs (so far) with this:

``` javascript
var $table = $('#example'), initialDraw = true, drawtmr, dt;
function refreshTable() {
  var isBreakpointed = $table.is('.breakpoint');
  if (initialDraw) {
    initialDraw = false;
    $table.footable();
  } else if (dt && !isBreakpointed)
    $table.find('tr td:hidden').show();
  else if (isBreakpointed)
    $table.removeClass('footable-loaded').footable();
}
dt = $table.dataTable({
  'fnDrawCallback': function() {
    // coalesce multiple redraws within same or next tick into one
    // redraw to increase performance
    clearTimeout(drawtmr);
    drawtmr = setTimeout(refreshTable, 2);
  }
});
dt.on('sort', refreshTable);
$table.on('footable_breakpoint_phone', refreshTable);
$table.on('footable_breakpoint_default footable_breakpoint_tablet', function() {
  $('.footable-row-detail').hide()
                           .removeClass('footable-row-detail')
                           .prev()
                           .removeClass('footable-detail-show');
  $table.removeClass('footable-loaded');
});
```

My particular setup is only the first column is shown for phone users and tablet/desktop users see all columns, so YMMV.
