### ISSUE TITLE
Add pagination page size control

### ISSUE THREAD

**Issue by dboune** [fooplugins/FooTable#81]
An enhancement request to add a pagination page size control.
### Function

To allow the user to select a number of rows that will be displayed per page. The user will click a control which will present a number of options to the user which they may select from. Selecting an option will cause the number of rows displayed per page to change.
### Options

Enable the developer to add a list of page sizes to offer the viewer (e.g. `[10, 25, 100]`).

If the default `pageSize` is not one of these options, then it should be added in numeric order.

``` javascript
{
    pageSize: 5
    pageSizeOptions: [10, 25, 100]
}
```

The resulting page size option list would then be `[5, 10, 25, 100]`.

If no `pageSizeOptions` are specified, no page size control will be displayed.
### Display

While Bootstrap provides a nice way of displaying button menus which is preferable to a Select box aesthetically speaking, I feel that using a Select is necessary to keep the plugin agnostic. The developer could then progressively enhance the Select into a Bootstrap style button menu.

This leaves the question of how to introduce a Select into the navigation without sacrificing default appearance of the nav when used with Bootstrap or any configuration which styles the nav.
- A separate element could be required to be in place prior to initialization
  I'm not a fan of this option except as an optional feature. The plugin should know how to draw a full nav.
- A select could be added after the nav

![select-after](https://f.cloud.github.com/assets/68863/570174/66dbb76c-c734-11e2-8e5a-9849bfff916c.png)

The only problem I see with this is that then this portion of the nav would not necessarily be contained inside `.pagination`
- A select could be added into an LI at the end of the nav

![select-in-li](https://f.cloud.github.com/assets/68863/570185/970bd63c-c735-11e2-9817-0a0e983ae93d.png)

This method doesn't create a kind visual effect with the default Bootstrap theming, as it interrupts the border radius. While it is possible to theme a select element to match the theme, it does not work very well cross browser.

**Comment by bradvin** [comment]
what about being able to specify what the page size control is. In the filtering plugin, you specify the filter control with a data attr on the table. Perhaps something similar for the page size? Then the dev has full control over where it is and how it looks, we just hook into the change event of that control.

thoughts?

**Comment by dboune** [comment]
I'm of two minds. On one hand I think the developer should be able to have full control over where and how controls are displayed, and how they interact with core functionality. On the other, it is really helpful to be able to build out the minimum framework and be presented with a sensible default behavior for any given feature.

+1 for both methods, but if I had to choose just one, then developer control wins.

I believe one issue with using the changed event is that not all custom controls fire a changed event, nor can you be certain of how to get the updated value when it does.

For html select it would be fine since the api is well defined, and as a default functionality it would be serviceable.

For full control I think it would be necessary to provide a public getter/setter for the value, and let the developer call them when needed.

**Comment by bfj05021** [comment]
Has this already been implemented?
I am trying to change the page size by changing the attribute data-page-size in the .footable  element and then trigger the footable_redraw but it doesn't seem to do anything.

**Comment by steveush** [comment]
I have checked in a fix allowing you to change the data-page-size attribute and call redraw to get it to properly use the new options.
