### ISSUE TITLE
Columns not hiding

### ISSUE THREAD

**Issue by martinconnelly** [fooplugins/FooTable#82]
Everything loads correctly, but columns are getting hidden.

Sure it's on me, but I'm not sure how.

jquery and footable loading find. no errors in the inspector. 

Possible key:  classes change with window size, but .breakpoint never shows up.  As smallest I've got:  class="footable footable-loaded phone"

More info -- seems like the data-\* attributes might not be working, as "expand" isn't loading anything either. 

Current chrome and FF, jquery from google. 

Many many thanks,

m

**Comment by bradvin** [comment]
Hi there,

Do you have an online example I can check out? Perhaps in codepen or jsfiddle?

**Comment by martinconnelly** [comment]
Columns _aren't_ getting hidden.  Ooof.  

Tossed it into codepen, where it works, obviously -- Must have been a conflict with something else -- but thought it was very odd that some classes were loading when others did not.  

Was for a shopify theme that's live now, but if you're really curious I can recreate with flat files. If you're not, that's cool too.
