### ISSUE TITLE
IE11 Footable slow to load table

### ISSUE THREAD

**Issue by emmielewis** [fooplugins/FooTable#831]
Footable is slow to render in IE11.  Even if I visit the showcase.html page, it lags in IE11 for a little bit before displaying.  Any advice on how to speed this up?

![image](https://user-images.githubusercontent.com/4294995/46922069-92095600-cfd1-11e8-88d6-c5d8cfd5b8ab.png)

**Comment by emmielewis** [comment]
I am using the ajax loading for columns and rows and my slowness is gone.  I am closing this.

**Comment by drummerik** [comment]
Hi Emmie,
How many rows is your data?
Grtz
