### ISSUE TITLE
Columns hidden in big screen / pc

### ISSUE THREAD

**Issue by octa7th** [fooplugins/FooTable#84]
Well, i have tabs in my web page. Table is hidden by default in tab 2. When i opened tab 2 footable is displaying table like in the phone. I'm wondering there is function to reset size of footable, because when i resize my screen the table is display correctly.

I create a fiddle if you want to see. http://jsfiddle.net/5Ntye/8/embedded/result/

ps. sorry bad english

**Comment by bradvin** [comment]
You can trigger an event on the table to force FooTable to resize itself:

$('.footable').trigger('footable_resize');

But it will not work with your JSFiddle, as you are using an outdated version (0.1). Update to the latest please
