### ISSUE TITLE
postdraw event not working to change rows css

### ISSUE THREAD

**Issue by albu77** [fooplugins/FooTable#840]
I want to add a css class which value is derived from a column value. Either with draw or postdraw event I can see th css apply by code but as soon as the code exit from the event listeners the css class is removed:
![image](https://user-images.githubusercontent.com/624802/51806274-6fe1ce00-2278-11e9-8ad6-e8e39d157dbe.png)
But after the code is out of the breakpoint
![image](https://user-images.githubusercontent.com/624802/51806286-8d169c80-2278-11e9-982e-9b608619b31b.png)
Code with draw event but samething happen with postdraw
```
on: {
          "draw.ft.table": function(e, ft){
            var table1 = document.getElementById('table-stocks-vins');
            var tbody1 = table1.getElementsByTagName('tbody')[0];
            var rows1 = tbody1.getElementsByTagName('tr');    
            
            for (var i=0, len=rows1.length; i<len; i++){
               $(rows1[i]).addClass(rows1[i].cells[1].innerHTML );        
            }
          }
        },
        columns: [
```

**Comment by muthu3107** [comment]
Were you able to fix the issue?

Am facing same issue for different use case!

@albu77
