### ISSUE TITLE
How to hide sort icon?

### ISSUE THREAD

**Issue by nd3w** [fooplugins/FooTable#862]
I have table with four columns. How do I hide the  sort icon from a column that doesn't have head title?

**Comment by nd3w** [comment]
From https://stackoverflow.com/questions/16117490/show-hide-element-with-jquery I use code below. First I use attribute data-sortable and set it to false.

    $(document).ready(function() {
        $('.footable').footable();
        $(".footable-sortable[data-sortable='false']").hide();
    });

**Comment by tlorens** [comment]
You're supposed to be able to set <th data-sortable="false"></th>. but that doesn't seem to work either.  I think documentation is out-dated.
