### ISSUE TITLE
Make it work without table headers

### ISSUE THREAD

**Issue by Agamennon** [fooplugins/FooTable#9]
First, thank you, i am enjoying fooTable a lot! 

My request here is to make fooTables also work on tables that does not declare headers, those are useful to display data and sometimes it is not necessary to add headers and having them be responsive would just be awesome

**Comment by bradvin** [comment]
thanks for the awesome suggestion - I agree with you - sometimes you do not need table headers.
I will build in a way to setup the columns just by using the options when you initialise the plugin

**Comment by kenzik** [comment]
+1

**Comment by steveush** [comment]
Just wanted to add in here I think we should still provide a way configure the table using data- attributes as this was one of the main features of the initial plugin. Possibly doing it via the html col tags? This way you could still configure your columns via data- attributes but not have any headers visible. Just a thought, will try it out and see how it goes.

**Comment by fizerkhan** [comment]
+1
