### ISSUE TITLE
Unable to work with new JQuery versions

### ISSUE THREAD

**Issue by graystevens** [fooplugins/FooTable#94]
Hi All,

I've just tried out Footables (V2) with my website, and I figured I had better report that it doesn't work with anything above version 1.8.3.

Thanks,

Graham

**Comment by bradvin** [comment]
Hey Graham,

The V2 showcase demo uses 1.9.1 and is working fine: https://github.com/bradvin/FooTable/blob/V2/demos/showcase.htm#L11
