### ISSUE TITLE
Looking for a way to hide data-name :  in expand view when using group only

### ISSUE THREAD

**Issue by lenamtl** [fooplugins/FooTable#95]
Hi,
Looking for a way to hide 
data-name : 
in + - expand view (small view) when using group only.

Group 1
title : column info1
title : column info2

What I need is
column info1
column info2

For data-name I'm using & n b s p ;
But I don't know how to remove : only for groups in small view

**Comment by bradvin** [comment]
you need to override the createDetail function using the footable options when you init your table : https://github.com/bradvin/FooTable/blob/master/js/footable.js#L64

something like:

$('table').footable({ createDetail : function(element, data) {
  //do my own stuff here
}});

**Comment by lenamtl** [comment]
I need it only for groups, I want to keep it for other column type
