### ISSUE TITLE
How can i set the first row to "expand" mode at mobile size?

### ISSUE THREAD

**Issue by emage** [fooplugins/FooTable#96]
Instead of collapsing, is it possible to expand the first one by default?  Not a guru at script so I was just wondering,

Thanks

**Comment by alexisletrotteur** [comment]
Would be interested in that feature too.

**Comment by bradvin** [comment]
@emage @alexisletrotteur this feature is built into V2 branch now - check out the demo : auto-expand-first-row-on-breakpoint.htm
