### ISSUE TITLE
callback functions and adding a row help needed.

### ISSUE THREAD

**Issue by solumac-sdb** [fooplugins/FooTable#97]
I need a callback function so that I can total the displayed values, when I run $('table').footable(); I need to count only the tr:visible row totals. 

Also I need to add a row to the footable and have it work with it when paging. After I have appended a tr and page away it disappears until I reload the table from scratch.

Would be grateful for any help, thanks.

**Comment by liquidvisual** [comment]
Would like to know this too. I want to hide the table while the JS runs - to prevent the flash of unstyled content.
