### ISSUE TITLE
data-hide="all" and data-ignore="true" messes up detail row resize

### ISSUE THREAD

**Issue by jakemdrew** [fooplugins/FooTable#98]
To recreate using demo 1:
1. Add <th data-ignore="true" data-hide="all"> to any column.
2. Shrink window until all fields are hidden.
3. Expand any detail row 
4. Maximize window to full size.
5. detail row does not take up full row width.

I experienced this bug when trying to hide a field completely that I use for row level hidden data.

![image](https://f.cloud.github.com/assets/2107763/776940/023aa010-e990-11e2-9f61-09e786219232.png)

**Comment by bradvin** [comment]
please can you test this with the V2 branch and let me know if the issue is solved

**Comment by jakemdrew** [comment]
Almost, but still having one issue.  When the window is expanded, the
detail row fills the entire width. However, it does not hide the last
remaining fields when they are showing on the main record. Notice in the
image below that Job, DOB, and Status are showing on both rows.

To Reproduce Behavior:
1. Using footable.js, and footable-0.1.css from V2.
2. Change the demo4 Last Name column to: <th data-ignore="true"
   data-hide="all">Last Name</th>
3. Change all columns below last name to data-hide="phone,tablet"
4. Shrink window to phone width and expand first record.
5. Maximize window.

[image: Inline image 1]

**Comment by jakemdrew** [comment]
just fyi, it also appears in V2 that data-class="expand" only works on the
first column.  In cases where the first column is hidden, (data-hide="all")
the expand icon is not showing up.  The column still expands when clicked
though.

**Comment by bradvin** [comment]
I managed to reproduce your issue, but I am trying to understand your requirement : why would you want to hide the column AND set it to ignore. This means you will never see that column in the table. Are you using that column for  filtering?

**Comment by bradvin** [comment]
also in V2, I dont rely on the data-class to add the toggle button anymore.
This is now done by adding data-toggle="true" to the column

**Comment by jakemdrew** [comment]
Sorry, I guess I should have mentioned that. I wrote a footable.editable plugin. It's finally working. I am using the hidden column(s) in cases where the field is auto-increment / primary key and only used to identify the record on the server during Ajax calls.

**Comment by bradvin** [comment]
ok cool - I have made some changes to the V2 branch (https://github.com/bradvin/FooTable/commit/adb887c346ce40a58366a04e39cd1476a8fa19c4) which now caters for these types of hidden columns. Your scenario should now just work. Also check out the hidden-columns.htm demo

**Comment by jakemdrew** [comment]
Thanks!  Do you know of a editable plugin for Footable yet?  If I put it on
git hub would you be interested in checking it out / consider including it
in the package?

**Comment by bradvin** [comment]
@jakemdrew oh hell yes I would :) please put it up

**Comment by bradvin** [comment]
@jakemdrew and no - I do not know of one

**Comment by jakemdrew** [comment]
I will make a few of your demo examples editable today and post to git hub.
 I followed your plug in architecture, but I am sure the code could be
cleaned up.  I will send post a link later.  Thanks!

**Comment by bradvin** [comment]
looking forward to it

**Comment by jakemdrew** [comment]
Ok, I have published the FooTable.Editable code and some demos, including
an ASP.net project with a generic handler example included.  I will write
up some docs when I have time over the weekend.  This is def an "Alpha"
release.  I am sure there are plenty of bugs.  I also exposed some of the
internal functions in a little ftEditable API function of sorts to produce
a few of the demos.  I did this last minute.  I am sure there is probably a
better approach for that part.  The docs will be very helpful whenever I
can get the README.md updated.  Until then, you can download and take a
look around!

https://github.com/jakemdrew/FooTable.Editable

Thanks,
Jake Drew
www.jakemdrew.com

**Comment by jakemdrew** [comment]
I finished documenting the API which covers most of the functions in the source code.  This should be very helpful when going through the code.  If you have any thoughts or questions, feel free to drop me a line.

https://github.com/jakemdrew/FooTable.Editable

jakemdrew@gmail.com
