### ISSUE TITLE
Tables are always minimized on first load

### ISSUE THREAD

**Issue by bluebrat** [fooplugins/FooTable#99]
Hi, I'm having an issue where the tables on a wide screen layout are already being minimized. However, they revert un-minimized as soon as the browser window is resized in the slightest. 

Any idea why this could be happening? 

Thanks!

**Comment by bradvin** [comment]
Can you give me a URL of your site? Or put up a demo of this on jsfiddle please?

**Comment by aphidesign** [comment]
I'm experiencing the same problem. Here's an example page… intent is that all columns show when window width > 768px, and only First Name & Last Name show when window width < 768px. But right now it always loads in 'collapsed' mode, even with the window is > 768px. A slight resize of the browser window in any direction seems to wake it up, so to speak, and show all columns.

**Comment by aphidesign** [comment]
Looking through comments on other issues, I saw

```
$('.footable').trigger('footable_resize');
```

adding it seems to have done the trick… all the proper columns are displaying on load. Thanks!

**Comment by bradvin** [comment]
This sometimes happens when footable is initialized on a table that is hidden (could be in another tab etc) and the width coming back for the table is zero. Then it applies the smallest breakpoint and hides all the columns it can.

Triggering the resize event will force a recalculation
